### ISSUE TITLE
requestDrawing

### ISSUE THREAD

**Issue by 4drik** [opentibiabr/otclient#1]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Jump function is not smooth, probably we need to requestDrawing like in walking case.

### Expected behaviour
Smooth jump animation

### Actual behaviour
Not a very smooth jump animation

### Environment
The newest commit.

### Solution
In void Creature::updateJump() we can add:
            g_map.requestDrawing(true, self->isLocalPlayer() || self->hasLight());
under:
            self->updateJump();

**Comment by mehah** [comment]
Thx
