### ISSUE TITLE
Creature start to walking too fast and on loop when trying to walk without speed

### ISSUE THREAD

**Issue by Ryan050** [opentibiabr/otclient#10]
Found out a bug just now when you are without speed it'll try to walk on the same square too fast (you can try it yourself removing player total speed) on normal otc it just stop on the square without walking at all.

**Comment by mehah** [comment]
Could you provide me with information to reproduce this problem?

**Comment by Ryan050** [comment]
Remove speed with creature:changeSpeed(-2000) and try to walk.
