### ISSUE TITLE
VS solution, can't compile

### ISSUE THREAD

**Issue by tomasz1337** [opentibiabr/otclient#1008]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

![image](https://github.com/user-attachments/assets/05f0e382-005b-4faa-8534-97c01dd45496)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SkullzOTS** [comment]
@tomasz1337 added BOT_PROTECTION as exclusion?

**Comment by tomasz1337** [comment]
Removed it 

![image](https://github.com/user-attachments/assets/dd499442-48b9-4a87-9bf8-b8811deb94d8)

**Comment by SkullzOTS** [comment]
Does compilation work with BOT_PROTECTION?

**Comment by tomasz1337** [comment]
![image](https://github.com/user-attachments/assets/5a37951e-31e9-4e71-bdda-568dc6561f35)

**Comment by SkullzOTS** [comment]
call me on discord (skullzots)

**Comment by SkullzOTS** [comment]
the error occurred when using SHOW_CHARACTER_LEVEL_RPC == 1

solved with: https://github.com/mehah/otclient/pull/1009
