### ISSUE TITLE
1.1.1b: Render stack quantity bug

### ISSUE THREAD

**Issue by Znote** [opentibiabr/otclient#104]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Equip some spears in weapon slot
2. Have some gold in your bag/backpack slot
3. Toggle backpack container

### Expected behaviour

Display stack quantity values: (mehah/1.0.1)
![renderQuantityNumber2](https://user-images.githubusercontent.com/1552144/126788199-659d57f6-8660-4eb0-83ef-1c652f2dc815.gif)

### Actual behaviour

Only the last item with a quantity value displays its value:
![renderQuantityNumber](https://user-images.githubusercontent.com/1552144/126787853-57f12670-0c7d-40cc-9a26-ff69dd7fc22a.gif)

Appears to only work on the last "UI rendered item". 
![renderQuantityNumber3](https://user-images.githubusercontent.com/1552144/126788630-b9c13eae-d4ab-44ae-9d07-c1b1c2d1c08b.gif)

### Environment

W10, 8.6, OTClient mehah/1.1.1b

**Comment by mehah** [comment]
fixed: https://github.com/mehah/otclient/releases/tag/1.1.1
