### ISSUE TITLE
Text select is ugly, CTRL + A (select all) doesnt show selected text in send message box

### ISSUE THREAD

**Issue by Znote** [opentibiabr/otclient#108]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Select any text from a text channel
2. write text in send message
3. click CTRL + A to highlight everything
4. click delete to delete all text

### Expected behaviour

When you select text in a text channel, you should still be able to easily see and read the text you selected.
When you click CTRL + A after writing a message before you send it, it should be visibly highlighted. 

### Actual behaviour

Selected text is ugly.
When you click CTRL + A, the text is being selected, you just don't see it.

![textselect1](https://user-images.githubusercontent.com/1552144/126864936-c7f9a07f-4664-4273-befc-2e2dcab5693f.gif)

![textselect2](https://user-images.githubusercontent.com/1552144/126864939-36b4973c-178e-4497-81d7-105949a1bad9.gif)

**Edit:** This also happens with show text boxes:
![textselect3](https://user-images.githubusercontent.com/1552144/126865146-edb11697-4c6e-4216-adb0-757cc9801425.gif)

**Edit2**:
Also notice in text boxes when you scroll down (etc big text boxes like Spellbook) and try to select text, you will jump to the top of the text:
![textselect4](https://user-images.githubusercontent.com/1552144/126865236-143f7de6-f42a-471f-bbd7-d6eeef81a09e.gif)

### Environment

W10, 8.6, Mehah/1.1.1

**Comment by mehah** [comment]
this has already been fixed, however i haven't released a release yet, just compiling the newest revision, i will wait a while to release, as soon as other bugs are fixed.

I'm going to close this report since it's not in the current reviews.

thx.

**Comment by Znote** [comment]
> this has already been fixed, however i haven't released a release yet, just compiling the newest revision, i will wait a while to release, as soon as other bugs are fixed.
> 
> I'm going to close this report since it's not in the current reviews.
> 
> thx.

Great! 🥰  Looking forward to the next tagged release. This repo is becoming extremely good, and will most likely be the client of my server (launch in about 10 days).
