### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by kungen32** [opentibiabr/otclient#11]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Download Otclient here
2. Compile it
3. Add a line at final on init.php ? EnterGame.setUniqueServer("127.0.0.1", 7171, 1264) 
4. But is on client_entergame 
 serverConfig = {
  ip = "127.0.0.1",
  port = 7171
}
4. doesnt connect with @god / god, but god / god yes
5. On login chracters it says : wrong account or password
6. Console: Error Account not found

FIX METHOD:

Change your Account name as Email, how to proceed to change this on Otclient ? Because it enters with Name ( on name phpmyadmin database instead of email ) ?

Ps: Also Change Outfits and use mount doesnt work

### Environment
Last from this repository

![client](https://user-images.githubusercontent.com/77188623/118283907-26acfb00-b4d0-11eb-8eaf-b754a505310b.png)

Happens: Wrong account & password

using god/god:
![2](https://user-images.githubusercontent.com/77188623/118283940-31679000-b4d0-11eb-9ed3-e4869a386361.png)

Then try to enter on a character:
![3](https://user-images.githubusercontent.com/77188623/118283960-36c4da80-b4d0-11eb-8fd5-8ae2703db662.png)

Console: 
![4](https://user-images.githubusercontent.com/77188623/118283968-39bfcb00-b4d0-11eb-9bad-ba15393306a5.png)

**Comment by MajestyOTBR** [comment]
Use updated server to login with email.

**Comment by mehah** [comment]
the project is still adapting to the new protocols.

**Comment by dudantas** [comment]
The email problem has already been fixed, you need to update the server and the client.

About the outfit and mount: the project is still under reformulation, some problems can be found, try to report in a separate issue to make it easier.

**Comment by kungen32** [comment]
Thanks, ya i see is new, but just you guys are awesome with this release! 
ok @MajestyOTBR  im going download again the server , 
@dudantas yeah i found opening TIbia normal, change outfit, save, then relog on Otclient it show outfit and you can mount /dismount if you have saved a mount on client normal!

Thanks guys i was just want to inform about this if was not fixed!

**Comment by iiCornwallis** [comment]
> 
> 
> The email problem has already been fixed, you need to update the server and the client.
> 
> Canary: [opentibiabr/canary@244fe4a](https://github.com/opentibiabr/canary/commit/244fe4a11030b76c0470d24ef121c6b6c25314f4)
> OTServBR-Global: [opentibiabr/otservbr-global@db41b78](https://github.com/opentibiabr/otservbr-global/commit/db41b7862e2e4ed4a20923f7feb0c2f173bcf703)
> 
> About the outfit and mount: the project is still under reformulation, some problems can be found, try to report in a separate issue to make it easier.

Are those changes incompatible with the 10/12 branch?

As a side note, since idk where else to post it, I'm really glad this team is forking this client, I think you guys will do great things with it, I'd like to help where I can.

**Comment by dudantas** [comment]
> > The email problem has already been fixed, you need to update the server and the client.
> > Canary: [opentibiabr/canary@244fe4a](https://github.com/opentibiabr/canary/commit/244fe4a11030b76c0470d24ef121c6b6c25314f4)
> > OTServBR-Global: [opentibiabr/otservbr-global@db41b78](https://github.com/opentibiabr/otservbr-global/commit/db41b7862e2e4ed4a20923f7feb0c2f173bcf703)
> > About the outfit and mount: the project is still under reformulation, some problems can be found, try to report in a separate issue to make it easier.
> 
> Are those changes incompatible with the 10/12 branch?
> 
> As a side note, since idk where else to post it, I'm really glad this team is forking this client, I think you guys will do great things with it, I'd like to help where I can.

Only compatible with otservbr-global's develop branch and canary
