### ISSUE TITLE
Error Boost Compiling OTClient

### ISSUE THREAD

**Issue by CatDealers** [opentibiabr/otclient#111]
OTClient Mehah Version 1.1 new
Screen print: https://prnt.sc/1fds2da

It's giving several erros boost vcpkg current & current visual studio.
Thanks you. report a error.

**Comment by mehah** [comment]
apparently your project is not recognizing c++ 17, are you sure you are compiling with otclient 1.0 VS Project, if so, make sure your visual studio is up to date.

**Comment by CatDealers** [comment]
Worked 1.1.2 OTClient. Thank you <3
