### ISSUE TITLE
Walk issue when updating tile below localplayer

### ISSUE THREAD

**Issue by oarsc** [opentibiabr/otclient#112]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Just let someone attack you while walking
2. Leave blood beneath you
1b. Also happens when stepping depot tile

### Expected behaviour
We expect that the animation continues as usual

### Actual behaviour
This is what happens:
https://i.imgur.com/nszYUBO.mp4
https://i.imgur.com/RGpKtwo.mp4

### Environment
Ubuntu Linux 18.04
OtHire with OT version 7.72

### Information
As far as I could see, the problem happens when receiving the opcode 105 (GameServerUpdateTile)
The creature::onAppear thinks it's a teleport and executes stopWalk, which causes the animation to stop

Stacktrace:
```
0# Creature::stopWalk() in otclient
1# LocalPlayer::stopWalk() in otclient
2# Creature::onAppear() in otclient
3# Tile::addThing(stdext::shared_object_ptr<Thing> const&, int) in otclient
4# Map::addThing(stdext::shared_object_ptr<Thing> const&, Position const&, short) in otclient
5# ProtocolGame::setTileDescription(stdext::shared_object_ptr<InputMessage> const&, Position) in otclient
6# ProtocolGame::parseUpdateTile(stdext::shared_object_ptr<InputMessage> const&) in otclient
7# ProtocolGame::parseMessage(stdext::shared_object_ptr<InputMessage> const&) in otclient
8# ProtocolGame::onRecv(stdext::shared_object_ptr<InputMessage> const&) in otclient
9# Protocol::internalRecvData(unsigned char*, unsigned short) in otclient
```

**Comment by mehah** [comment]
I downloaded this server and tested it, everything is working normally, I don't know if it was some change I made recently in the hiking system, something else, I see it's using GM, I tested it with normal Player at high speed and it's ok.

**Comment by oarsc** [comment]
Even though you're seeing a GM character, I disabled the gamemaster flag, and it's just a normal Player in those videos.
It's easier to see with slow speed.

I digged into this issue a little more...

I did compare the code between this and edubart's client.
The problem here is that the m_oldPosition doesn't update to the tile with the depot's button.
```c++
Creature::onAppear
...
    if(m_removed) {
        stopWalk();
        m_removed = false;
        callLuaField("onAppear");
    } // walk
    else if(m_oldPosition != m_position && m_oldPosition.isInRange(m_position, 1, 1) && m_allowAppearWalk) { // ALLOWAPPEARWALK IS NOT SET TO TRUE, WHICH IS OK IN THIS CASE
        m_allowAppearWalk = false;
        walk(m_oldPosition, m_position);
        callLuaField("onWalk", m_oldPosition, m_position);
    } // teleport
    else if(m_oldPosition != m_position) {
        stopWalk();   // <-- EXECUTES THIS LINE
        callLuaField("onDisappear");
        callLuaField("onAppear");
    } // else turn
```

In edubart's client, the m_oldPosition is updated to be equals to m_position, because the Creature::onDisappear is being called here:
```c++
0# Creature::onDisappear() in otclient
1# Tile::removeThing(stdext::shared_object_ptr<Thing>) in otclient
2# Tile::clean() in otclient
3# Map::cleanTile(Position const&) in otclient
4# ProtocolGame::setTileDescription(stdext::shared_object_ptr<InputMessage> const&, Position) in otclient
5# ProtocolGame::parseUpdateTile(stdext::shared_object_ptr<InputMessage> const&) in otclient
6# ProtocolGame::parseMessage(stdext::shared_object_ptr<InputMessage> const&) in otclient
7# ProtocolGame::onRecv(stdext::shared_object_ptr<InputMessage> const&) in otclient
8# Protocol::internalRecvData(unsigned char*, unsigned short) in otclient
```

The Tile::clean implementation of the current code doesn't execute anything, just clears a vector.
Modifying the clean method to be the same as edubart's seems to work:
```c++
void Tile::clean()
{
    while(!m_things.empty())
        removeThing(m_things.front());
}
```

HOWEVER...
There is an animation reset in this process, and this happened in all my attempts to equal the m_oldPosition and m_position:
https://i.imgur.com/w2jfBSP.mp4 (It's hard to see it, but it's not fluid)
https://i.imgur.com/Ivtbd37.mp4 (easier to see with the "powered hunters" attacking (there are also some crazy weird movements at the end). Its not a GM, it's a normal player level 1 with more HP than he should, I only used the GM powers to spawn the hunters)

For the moment, I'm not applying this change, because I'd like to see a clean version of OTHire to check it, according to your last comment.

**Comment by mehah** [comment]
that's right, it was my mistake, thanks for the debugging.

**Comment by oarsc** [comment]
This last commit (55a3421) is made to prevent this behavior:

https://user-images.githubusercontent.com/5507777/131008847-c4fdf00a-8026-41f6-b0db-c0c61d1db016.mp4

**Comment by oarsc** [comment]
If I was the only with this problem, I could try to fix my server and revert this commit...
If anyone can check it out, I'll appreciate it
