### ISSUE TITLE
Black box with lights disabled

### ISSUE THREAD

**Issue by Sifl46** [opentibiabr/otclient#115]
Hey, got a strange issue with having lights disabled.
If I disable lights in options, close and re-launch the client, and log back in, I get this strange black box on the left of the screen. I can temporarily get rid of it by re-enabling lights, and disabling them again.

This is with latest revision, on both Windows and Mac OS. Also confirmed it happens with latest prebuilt release.
7.72 Protocol.
![image](https://user-images.githubusercontent.com/77085292/126898199-344d265f-23a7-4146-8b4f-b4898753da82.png)

**Comment by oarsc** [comment]
Same with Linux and 7.72
