### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by ivopr** [opentibiabr/otclient#117]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Follow the instructions to compile at edubart/otclient (a.k.a. link in the README)

### Expected behaviour
It should compile

### Actual behaviour
It doesn't compile

### Environment

ArchLinux, gcc 11.1.

Also, including `atomic` seems to have fixed the problem.
Not sure if it occurs in other systems, or gcc versions.

**Comment by oarsc** [comment]
Could you give more details?
Which error message do you receive?

**Comment by mehah** [comment]
well, since we haven't received any feedback, i'll close.
