### ISSUE TITLE
Illumination in upper floors

### ISSUE THREAD

**Issue by oarsc** [opentibiabr/otclient#119]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Wait until night
2. Set ambient lights to a low value

### Expected behaviour
I don't actually have pictures, but illumination should somehow affect upper floors too

### Actual behaviour
![Image 1](https://i.imgur.com/d9U3ssU.png)
![Image 2](https://i.imgur.com/Sf9R5wF.png)

### Environment
OTHire 7.72 server
Ubuntu 18.04

**Comment by oarsc** [comment]
Another thing that is worth mentioning is that, just when starting to get dark, looks like some illumination have less illumination than the natural one and looks like it darken the global illumination instead of brightening it:
![Screenshot at 2021-07-31 20-34-55](https://user-images.githubusercontent.com/5507777/127751519-43a90211-3621-4736-805a-d7a4e0f446f6.jpg)

**Comment by mehah** [comment]
I'm abandoning for now this new lighting system and branch on which it is updated is this: 
https://github.com/mehah/otclient/tree/new-lighting-system
