### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by Hiquezerah** [opentibiabr/otclient#123]
Hi mehah, I just compiled your client, and I went to test the transparency and I'm having some problems with it.
screenshot in game https://prnt.sc/1gp76nh

**Comment by mehah** [comment]
see if it's not the shadow floor system

**Comment by Hiquezerah** [comment]
Sorry, but what would this floor system be?
I don't think so, just channelalpha

**Comment by mehah** [comment]
floor shadowing system, darkens the floor below, from what I saw in the image it looks like it does, as it is showing everything transparent, but dark.

**Comment by Hiquezerah** [comment]
every place where the water is transparent is on the same floor. In the print I sent you above, only a small part of the transparency worked, everything else went dark. I believe it is not the shading as they are the same item.
https://prnt.sc/1gsnjmr using another client, look at the transparency throughout the site, they are the same items.
https://prnt.sc/1gspmb4 using the version otclient-1.1.3

**Comment by Hiquezerah** [comment]
https://prnt.sc/1gsqqt3

**Comment by mehah** [comment]
![image](https://user-images.githubusercontent.com/2267386/127239334-60133705-f99b-46c6-ac61-c5f8615d6b12.png)
Did you try setting it to 100% to disable floor shadowing?

**Comment by Hiquezerah** [comment]
https://prnt.sc/1gt7v00

**Comment by Hiquezerah** [comment]
worked not transparency, is system floor.

**Comment by mehah** [comment]
blz, assim que eu conseguir arrumar um tempo, verei, preciso também montar um ambiente com transparência. :wink:

**Comment by SkullzOTS** [comment]
Estou utilizando TFS 0.3.6 (854) e acontece o mesmo, desenha as criaturas as vezes sim ou não, que estão no andar abaixo, porém não desenha o mapa, itens, etc... não lembro se você se lembra @mehah mais eu até tinha te chamado no otland pra informar sobre este problema!

como deveria ficar:
https://i.imgur.com/L1L8k0S.png

como fica:
https://i.imgur.com/uyRSSAs.png

**Comment by mehah** [comment]
provavelmente o cliente está removendo os objetos, já que ele está sendo desenhando abaixo de um item opaco, mas não está levando consideração que ele está com transparência.

**Comment by mehah** [comment]
podem testar?

**Comment by SkullzOTS** [comment]
> podem testar?

@mehah 
acabei de testar aqui e ainda não resolveu, tipo... nos cantos onde mostraria uma parede embaixo daí ele funciona, mais nos demais pisos em volta não! vou tentar demonstrar aqui

**Comment by SkullzOTS** [comment]
@mehah 

olha... no andar de cima:  (parece que só funciona quando está desenhando alguma parede nos cantos)
https://i.imgur.com/nYa0BI3.png

e no andar o qual estou olhando da print acima:
https://i.imgur.com/AZu6jdN.png

**Comment by mehah** [comment]
faz um teste entao, em map.cpp

substituir os métodos isCovered, isCompletelyCovered, por isso e vê e resolve:

```cpp
bool Map::isCovered(const Position& pos, int firstFloor)
{
    // check for tiles on top of the postion
    Position tilePos = pos;
    while(tilePos.coveredUp() && tilePos.z >= firstFloor) {
        TilePtr tile = getTile(tilePos);
        // the below tile is covered when the above tile has a full ground
        if(tile && tile->isFullGround())
            return true;
    }
    return false;
}

bool Map::isCompletelyCovered(const Position& pos, int firstFloor)
{
    const TilePtr& checkTile = getTile(pos);
    Position tilePos = pos;
    while(tilePos.coveredUp() && tilePos.z >= firstFloor) {
        bool covered = true;
        bool done = false;
        // check in 2x2 range tiles that has no transparent pixels
        for(int x=0;x<2 && !done;++x) {
            for(int y=0;y<2 && !done;++y) {
                const TilePtr& tile = getTile(tilePos.translated(-x, -y));
                if(!tile || !tile->isFullyOpaque()) {
                    covered = false;
                    done = true;
                } else if(x==0 && y==0 && (!checkTile || checkTile->isSingleDimension())) {
                    done = true;
                }
            }
        }
        if(covered)
            return true;
    }
    return false;
}
````

**Comment by SkullzOTS** [comment]
> faz um teste entao, em map.cpp
> 
> substituir os métodos isCovered, isCompletelyCovered, por isso e vê e resolve:
> 
> ```c++
> bool Map::isCovered(const Position& pos, int firstFloor)
> {
>     // check for tiles on top of the postion
>     Position tilePos = pos;
>     while(tilePos.coveredUp() && tilePos.z >= firstFloor) {
>         TilePtr tile = getTile(tilePos);
>         // the below tile is covered when the above tile has a full ground
>         if(tile && tile->isFullGround())
>             return true;
>     }
>     return false;
> }
> 
> bool Map::isCompletelyCovered(const Position& pos, int firstFloor)
> {
>     const TilePtr& checkTile = getTile(pos);
>     Position tilePos = pos;
>     while(tilePos.coveredUp() && tilePos.z >= firstFloor) {
>         bool covered = true;
>         bool done = false;
>         // check in 2x2 range tiles that has no transparent pixels
>         for(int x=0;x<2 && !done;++x) {
>             for(int y=0;y<2 && !done;++y) {
>                 const TilePtr& tile = getTile(tilePos.translated(-x, -y));
>                 if(!tile || !tile->isFullyOpaque()) {
>                     covered = false;
>                     done = true;
>                 } else if(x==0 && y==0 && (!checkTile || checkTile->isSingleDimension())) {
>                     done = true;
>                 }
>             }
>         }
>         if(covered)
>             return true;
>     }
>     return false;
> }
> ```

vou testar...

**Comment by SkullzOTS** [comment]
> faz um teste entao, em map.cpp
> 
> substituir os métodos isCovered, isCompletelyCovered, por isso e vê e resolve:
> 
> ```c++
> bool Map::isCovered(const Position& pos, int firstFloor)
> {
>     // check for tiles on top of the postion
>     Position tilePos = pos;
>     while(tilePos.coveredUp() && tilePos.z >= firstFloor) {
>         TilePtr tile = getTile(tilePos);
>         // the below tile is covered when the above tile has a full ground
>         if(tile && tile->isFullGround())
>             return true;
>     }
>     return false;
> }
> 
> bool Map::isCompletelyCovered(const Position& pos, int firstFloor)
> {
>     const TilePtr& checkTile = getTile(pos);
>     Position tilePos = pos;
>     while(tilePos.coveredUp() && tilePos.z >= firstFloor) {
>         bool covered = true;
>         bool done = false;
>         // check in 2x2 range tiles that has no transparent pixels
>         for(int x=0;x<2 && !done;++x) {
>             for(int y=0;y<2 && !done;++y) {
>                 const TilePtr& tile = getTile(tilePos.translated(-x, -y));
>                 if(!tile || !tile->isFullyOpaque()) {
>                     covered = false;
>                     done = true;
>                 } else if(x==0 && y==0 && (!checkTile || checkTile->isSingleDimension())) {
>                     done = true;
>                 }
>             }
>         }
>         if(covered)
>             return true;
>     }
>     return false;
> }
> ```

@mehah compilei, porém ainda não resolveu!

**Comment by mehah** [comment]
faz o seguinte, me da um exemplo de mapa q esteja dando esse problema, pois estou testando aqui e está funcionando normal.

pode recortar esse ai e me mandar

**Comment by mehah** [comment]
o seu cliente é limpo, sem nenhuma modificação, preciso saber disso, pois talvez você tenha esquecido de aplicar algo.

aqui está mostrando tudo, já fui em vários lugares e está de boa.
![image](https://user-images.githubusercontent.com/2267386/127585811-4e4e8ead-147d-4f9d-8ba6-5b43b44f09f5.png)
.
exemplo do meu otml:
```css
items
  1152
    opacity: 0.5
    full-ground: false
```

**Comment by SkullzOTS** [comment]
ah sim, tipo... to usando uma compilação limpa mesmo porém estava setando a transparência direto na sprite e não usando o otml! vou testar utilizando o otml

**Comment by mehah** [comment]
é porque eu estou setando como full-ground: false, eu posso tirar a verificação do fullground, pois agora eu vejo se é totalmente opaco por pixel, sem precisar de flag.

veja se é isso, se for, irei tirar a verificação de fullground e vc testa sem otml

**Comment by SkullzOTS** [comment]
@mehah não consegue vir em call no dc pra você poder entender melhor? qlqr coisa manda convite SkullZ#1900 q dai compartilho tela e te mostro oq to fazendo exatamente!

**Comment by mehah** [comment]
não dá, estou corrigindo outros problemas.
faz o seguinte,

troque
https://github.com/mehah/otclient/blob/65e73948fe1134edcd0027090ce0caf1b7ba6a9b/src/client/thingtype.h#L217
por
```cpp
    bool isOpaque() { return m_opaque; }
```
