### ISSUE TITLE
Alt key not working in MacOS

### ISSUE THREAD

**Issue by Sifl46** [opentibiabr/otclient#124]
When the client is compiled natively under MacOS, the game runs perfectly, except for the alt key not being functional whatsoever.
Running a windows build under wine will map Alt to Command on a mac keyboard, however, running it natively will not.

While it's easy to work around this issue by rebinding attack creature/player to another key in game_interface, it would of course be ideal to have it work as intended.

Note: Command key under mac is "Meta". a possible solution would be to re-assign Alt as Meta if running on mac

**Comment by mehah** [comment]
sorry but i don't have mac to be able to solve this problem and test.

**Comment by Sifl46** [comment]
Commonly, in multi platform applications, what would be Alt in windows would be bound to the Command key in MacOS. The Command key on a Mac keyboard shares the same keycode as the Windows key on Windows.
On the windows side of things, it would be basically programming your application to use the windows key instead of the Alt key if it detects MacOS.

Currently, the client does indeed recognise the Command key in the hotkeys menu. It detects it as the "Meta" key, which is what the windows key is detected as under Windows.

**Comment by mehah** [comment]
I honestly don't know how I could help you without a MAC to test, but since you have a basic notion, you can use this command ``` if(g_app.getOs() == "mac")```, to detect if the client is using macOS and change the behavior of the keys.

**Comment by mehah** [comment]
fixed #131
