### ISSUE TITLE
Pixelation when resizing some item drawn on the client

### ISSUE THREAD

**Issue by SkullzOTS** [opentibiabr/otclient#126]
### Expected behaviour
https://i.imgur.com/K0yJ2f6.png

### Actual behaviour
https://i.imgur.com/UwsKzQI.png

### Environment
when an item is drawn larger than the size given in the sprite, it becomes pixelated, in this example these items are 32x32 and are being resized to 40x40 through the module which is being set in .otui

**Comment by mehah** [comment]
give me an example, what are you drawing, is it a creature?

**Comment by SkullzOTS** [comment]
> give me an example, what are you drawing, is it a creature?

no, it's an item...

**Comment by SkullzOTS** [comment]
@mehah  this is what i'm using in the images i posted, in the .otui of a certain module:

UIItem
    id: slot1
    width: 40
    height: 40
    image-size: 40 40
    item-id: 3228
    focusable: false
    anchors.top: parent.top
    anchors.left: parent.left
    margin-top: 36
    margin-left: 12
    draggable: false
    
here I resize it to 40x40, and in .SPR it is defined as 32x32

and in other modules the same happens, whenever I define an itemID to be drawn and resize it ends up getting pixelated in both UIItem and UIWidget according to what I saw happening here, I don't know if it happens on other occasions!
