### ISSUE TITLE
Draw borders (Transparent)

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#130]
There is something strange about drawing borders (Perhaps Transparent Bug?). 
Almost like they draws in the wrong order. 
I did not have this problem with commit [fix #87 #86](https://github.com/mehah/otclient/commit/3d9bdfa8611903a11cb9836597669388a43f77a7) before the drawpool system.

This is what it looked like **(before drawpool)** when it worked: [Video](https://dl.dropboxusercontent.com/s/h465o9blabd7goa/pe3KJeUY8G.mp4)
Here is what it looks like now **(Bugged)** with latest commit and drawpool system: [Video](https://dl.dropboxusercontent.com/s/tjmwcqgdutiruq4/MYDDo3uq3f.mp4)

Use latest TFS and your client cache-for-all

**Comment by mehah** [comment]
take a look in your map editor if these borders are not below, as now have an algorithm to avoid unnecessary renderings and that is why this bug may have occurred.

**Comment by Klonoa88** [comment]
It looks like this in the map editor [Video](https://dl.dropboxusercontent.com/s/sgpmp98ylt92m6i/s031Gvs8G8.mp4)
And it has worked before :S ?

All tiles I moved in the video has different opacity.

**Comment by mehah** [comment]
from what I'm seeing, most of the tiles, are all identical

> It looks like this in the map editor [Video](https://dl.dropboxusercontent.com/s/sgpmp98ylt92m6i/s031Gvs8G8.mp4)
> And it has worked before :S ?
> 
> All tiles I moved in the video has different opacity.

I talked about in my first post.

**Comment by Klonoa88** [comment]
> from what I'm seeing, most of the tiles, are all identical

I checked now and they are the same. 
Why I have more in one stack is because the more I put, the darker the tile becomes.

So you should not be able to have 6 or more borders/tiles in a stack anymore if they are identical?

**Comment by mehah** [comment]
sorry but this workaround is bad, you has put to render the same block multiple times, you better take one and edit the opacity as you wish.

**Comment by mehah** [comment]
sorry but this workaround is bad, you has put to render the same block multiple times, you better take one and edit the opacity as you wish.

**that's why it looks like this, the algorithm removes identical tiles in the same position, for example, if you have two fire swords in the same position, it won't render the same object twice.**

**Comment by mehah** [comment]
if you don't want it to do that, remove this condition, whole block.

https://github.com/mehah/otclient/blob/b25f27f4eb74513892f09ea08cb8847b9c776f0c/src/framework/graphics/drawpool.cpp#L87

but I don't advise, the way you're doing it, it's totally wrong, it will impact the performance of weaker graphics cards.

**Comment by Klonoa88** [comment]
Okay I understand what you mean :) I make a new border in the color and transparency I want

**Comment by mehah** [comment]
if everything is ok, close the issue or let me know that I close.

**Comment by Klonoa88** [comment]
Yes, it's okay. Closing
