### ISSUE TITLE
Assigning hotkey to Tab key does not work on Windows

### ISSUE THREAD

**Issue by Sifl46** [opentibiabr/otclient#132]
The hotkey menu will detect the Tab key, and enable you to assign it as a hotkey. However, actually trying to use the hotkey has no effect on Windows. Strangely, this doesn't seem to affect MacOS, and works correctly on there.
I had assumed it may have been related to game_console binding Tab to switch between chat tabs, however removing the bind in console.lua didn't fix the issue.

**Comment by oarsc** [comment]
Does it work with WASD mode active?

There are some keys that are disabled in chat mode, such as words or numbers, because you should use them to type...
Probably the condition is not 100% accurate yet. You can find this at the end of hotkeys_manager.lua

**Comment by Sifl46** [comment]
WASD mode did not make a difference on Windows. (Though iirc it required to be on for MacOS)

**Comment by Sifl46** [comment]
Seems to have been an issue with my keyboard. That was embarassing.
