### ISSUE TITLE
ERROR: MODULES OTClient 1.1.4 Lastet NOW

### ISSUE THREAD

**Issue by CatDealers** [opentibiabr/otclient#133]
Server Source: OTX 2 / Version Client: 860
OTClient Source Version: 1.1.4
I went to compile otclient update and open otclient and see terminal an error appeared. can solve the solution?
https://prnt.sc/1kt3zjf

**Comment by mehah** [comment]
what is your video card, are your drivers up to date?

**Comment by mehah** [comment]
well, so far I haven't got an answer, and this problem is probably related to your video card driver or your video card doesn't support shaders feature.
