### ISSUE TITLE
Invisible outfit when changes outfit while walking

### ISSUE THREAD

**Issue by gaamelu** [opentibiabr/otclient#134]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Crie qualquer evento que altere imediatamente sua outfit (talkaction, action, tanto faz)
2. Ande com o personagem vários steps sem parar
3. Enquanto o personagem anda, execute o evento que troca a outfit.

### Expected behaviour
O personagem trocar de outfit normalmente enquanto anda sem nenhum problema

### Actual behaviour
O personagem fica invisível enquanto anda, no exato instante que para de andar, a outfit é trocada.

### Environment
OTClient mehah com os últimos commits 8.54

### Comments
Eu acredito que isso esteja relacionado com o drawpool que reduz a quantidade de vezes que o visual de uma criatura é atualizado.

**Comment by mehah** [comment]
O seu cliente é modificado? Isso corre muito em clientes de pokemon.

O cliente já foi testado em várias versões e isso não ocorre.

**Comment by gaamelu** [comment]
Sim, tem várias modificações na minha versão desse repositório, mas são basicamente as mesmas modificações que tinham no meu otclient antigo (baseado na versão do Edubart mesmo) que não tinha esse problema.

Por desencarno de consciência, vou fazer mais testes já que você relatou que isso acontece em clientes de pokémon. Quando terminar dou retorno por aqui. Valeu pela atenção.

**Comment by mehah** [comment]
todo o sistema de walking foi reescrito, teve uma galera que corrigiu o "problema" no próprio objectbuilder, da uma olhada nele, vê se tem algo de anormal.

mas de qualquer forma, olhe esses três métodos.

https://github.com/mehah/otclient/blob/dc01981bb9c8797ea467633c9dae0818351fc675/src/client/thingtype.cpp#L668
https://github.com/mehah/otclient/blob/dc01981bb9c8797ea467633c9dae0818351fc675/src/client/creature.cpp#L501
https://github.com/mehah/otclient/blob/dc01981bb9c8797ea467633c9dae0818351fc675/src/client/creature.cpp#L985

-------------------------------------------------------------

a solução provavelmente é colocar -1 em:
https://github.com/mehah/otclient/blob/dc01981bb9c8797ea467633c9dae0818351fc675/src/client/creature.cpp#L506

mas o ideal é você corrigir no Object Builder.

**Comment by SkullzOTS** [comment]
@mehah estou tendo o mesmo problema, explique como seria essa correção pelo ObjectBuilder... eu testei tentando colocar const int footAnimPhases = getTotalAnimationPhase()-1; porém, sem sucesso!

**Comment by SkullzOTS** [comment]
@scopz

**Comment by oarsc** [comment]
Is this what doesn't work for you?
I don't speak Portuguese, sorry

https://user-images.githubusercontent.com/5507777/130842825-e9688c69-ef82-4024-98ce-fd59f7170804.mp4

**Comment by gaamelu** [comment]
I just tried what mehah suggested about changing footAnimPhases, but it didn't worked. About the idea of fixing and rebuilding the object builder, I don't know ActionScript at all to know how to fix it :/

Sorry for speaking portuguese instead of English, @scopz. 

It is something similar to that, but it seems it didn't happened in your test.

https://imgur.com/a/oHviQ3F

**Comment by SkullzOTS** [comment]
happens exactly the same way with me, make an action script to change the outfit, and keep changing it while moving, to see if it happens @scopz

**Comment by mehah** [comment]
se o problema é quando anda, então tenta resetar a animação quando for trocar de outfit.

add
```lua
m_walkAnimationPhase = 0
```
in
https://github.com/mehah/otclient/blob/4f8fa3e87d0b4f489989f04d1946e6419d686a5c/src/client/creature.cpp#L699

me avise se resolver.

**Comment by SkullzOTS** [comment]
@mehah de acordo com os testes aqui, aparentemente está funcional! obrigado...

**Comment by gaamelu** [comment]
Perfeito, funcionou para mim também!

**Comment by oarsc** [comment]
Commit added,
This line was removed for #112.
I will try to find why I made that change and try for something else.
