### ISSUE TITLE
Issues with UIMiniWindow changes

### ISSUE THREAD

**Issue by LeandroPerrotta** [opentibiabr/otclient#135]
I found two bugs in the new UIMiniWindow refactored code to allow save Window state for each character individually.

**Reload modules (Ctrl+Shift+R)**

First, of you reload interface (Ctrl+Shift+R) the MiniWindow modules will not be usable anymore. They will be in tray on top but not opening.

After debuging a little I could understand the problem: When OTClient reload modules seems the modules are trying to be ordered by **setupOnStart** just in real time and seems the problem happens when old previous index MiniWindow module is still not loaded.

When client starts it seems to not happens the problems because for some reason, setupOnStart is only called after all modules are already loaded (what not happens when reloading).

Anyways, I could not be able to fix it (tried do some hacks but... not worked). Also it not affect most of players.. Usually only devs will use the reload modules function.

**Opening multiple instances of game**

Another bug similar to the first, is if you open multiple instances of the game at same time, in different characters, and then you quit game in them all, and open again. One of the characters will have one or multiple MiniWindow that will not work.

I did not debug a lot this issue, but seems to be something bad happenning when multiple instances try to write to config.otml at same time and seems it may somehow corrupt the node CharMiniWindows (when it happens the only way I found to back all mini windows opening again is deleting config.otml).

Maybe storing CharMiniWindows in different .otml files for different characters may fix the problem.

But... To fix the problems I just reverted the changes from uiminiwindow.lua to default OTClient/Edubart and everthing back work properly, what is not really a fix ofc.

**Comment by oarsc** [comment]
Didn't know about this Ctrl+Shift+R thing 😱 
I'll take a look at this

**Comment by oarsc** [comment]
Reloading modules (Ctrl+Shift+R) should be fixed with dc01981.
Please, verify it's working fine.

About the multiple instances thing, I will try to take a look at what can we do. This is not the only thing not working with multi-clients, I also found some weird things with hotkeys not saving or stuff like that

**Comment by oarsc** [comment]
Well, as I didn't get any answer, I guess its working fine then.
If you can reproduce the problem opening multiple clients, please, open another issue (or reopen this one)
