### ISSUE TITLE
Possible another drawing bug

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#136]
If you watch this [video](https://dl.dropboxusercontent.com/s/6ezk8clrcyxnzrw/14WBT1Au68.mp4) I have an elevator you can ride in. 
Everything draws right in the beginning when I look at the elevator when it goes up/down. 
It also draws right when I go with it. 
But after I went with it up/down and use the elevator again, no tiles on the z floors below me draws.
It just turns black.

Using latest TFS and your latest otclient

**Comment by mehah** [comment]
does this only happen with the light system enabled?

**Comment by Klonoa88** [comment]
Idk. I have put in my client that the lights system should always be on and removed options to change it

**Comment by mehah** [comment]
I need you to test without the light system, because, this is your customization, I will not create an identical system just to reproduce the problem and fix it.

**Comment by Klonoa88** [comment]
okay i'm going to put it back so i can turn it off. Will update here again in a while

**Comment by Klonoa88** [comment]
Have turned lightsystem **off** now and it is the same as **on**
[Video](https://dl.dropboxusercontent.com/s/zff0xvli30wd8q4/ofcFXJNDkN.mp4)

**Comment by Klonoa88** [comment]
And I have Shadow floor intensity at 100%. So that's not the problem either

**Comment by mehah** [comment]
probably for me to fix this bug, I'll have to have access to your server, I don't want the server itself, just ip and port, and if I can't enter your server with otclient 1.0, only with yours, then there's no way, I will need your client's source code, this bug is very punctual, as it is your customization.

**Comment by Klonoa88** [comment]
I do not have to send all my files. You can easily test this on your server.

Use this action script: [Here](https://pastebin.com/X4xkCace).
Set actionid on the lever and change floor position and item ids.
And try it on Z floor 8.

Watch this [Video](https://dl.dropboxusercontent.com/s/s12db09ub509lfl/bIw6Ll12Zd.mp4).

**Comment by Klonoa88** [comment]
Could the problem have something to do with this [#120 ](https://github.com/mehah/otclient/issues/120)? It feels like it is the same with tiles as creatures?

**Comment by mehah** [comment]
maybe, i need to analyze it, i'm on vacation... :)

**Comment by Klonoa88** [comment]
@mehah How much longer are you on vacation? ;)

**Comment by mehah** [comment]
I don't know yet, I'm trying to keep the project alive, but few people have come to help me, so when I'm excited, I'll go back to contributing.

**Comment by Klonoa88** [comment]
You have to get excited again and fix the draw bugs I reported :D I have tried myself but it does not work :(
This is the best client in every way and you have done a great job. Is only a little left for it to work perfectly :D
