### ISSUE TITLE
One more drawing bug :)

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#137]
If you use borders **itemid 8129, 8130, 8131, 8132, 8125, 8126, 8127, 8128 and more** on tiles stonewall exemple **itemid 5640, 5639, 5648, 5645, 5646 and more** it does not draw in the correct order. 

In game image [Here](https://i.imgur.com/tlyLdke.jpeg)
Mapeditor image [Here](https://i.imgur.com/3JEwnx3.jpeg)

**Update:** It's not just the red earth borders that draws wrong. It's all borders that have this Patterns [Here](https://i.imgur.com/fe7i1GJ.png)

Hope you understand what I mean by my description; P

**Comment by mehah** [comment]
it's probably because the grounds are being grouped and when using "top ground" - "64x64" gives this problem, the advantage of grouping is that it increases performance, since I ask to draw the same ground only once, I can take that away, but there will be a decrease in performance, just to fix those edges that are between these types of ground, which is rare.

**I can put a flag to enable/disable this.**

**Comment by Klonoa88** [comment]
> I can put a flag to enable/disable this.

Yes do that :) Because it does not look good ingame as it does now

**Comment by Klonoa88** [comment]
> it's probably because the grounds are being grouped and when using "top ground" - "64x64" gives this problem, the advantage of grouping is that it increases performance, since I ask to draw the same ground only once, I can take that away, but there will be a decrease in performance, just to fix those edges that are between these types of ground, which is rare.

Where in the code is this piece so I can do some research myself?

**Comment by mehah** [comment]
Could you send me the part of this map and the location?

because I want to try to fix without putting a flag to disable and enable, if not possible, then I put and you test.

**Comment by Klonoa88** [comment]
Here is that piece of the map.
I have cut in 2 different examples where it goes wrong.

**Download:**
[Map.zip](https://github.com/mehah/otclient/files/7066672/Map.zip)

This is what it looks like in the map editor [Link](https://i.imgur.com/FfyOP37.png)
This is what it looks like in game [Link](https://i.imgur.com/fhyd6QW.jpeg)

**Comment by mehah** [comment]
well, now there's no way not to have fix it. :)

**Comment by mehah** [comment]
I made some changes, see if it fixed.
