### ISSUE TITLE
Camera don't reset cancel walk.

### ISSUE THREAD

**Issue by bearbeatxd** [opentibiabr/otclient#138]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Diagonal walk on 3 boxes
2. If creature blocks path

### Expected behaviour
Camera should reset to player position if it cancels walk, been tested in Edubart, this only occurs in Mehah version

### Actual behaviour
https://gyazo.com/85d843545cffc90e171e8d85803c78c3
As you see here it gets stuck, and im wondering what commit broke this from Edubart

If you have any idea or what code cause this compared to edubart version 

Thanks! nice work with this client overall, its an improvement in many ways

**Comment by bearbeatxd** [comment]
Edubart version
https://gyazo.com/5fcbba6e5a64b69e53045ec9270e77e0

**Comment by mehah** [comment]
here it is working perfectly.

Tibia 10.98
https://user-images.githubusercontent.com/2267386/131070231-ad4613f4-e62e-4d91-98b1-8c42695048dc.mp4

tested with chest with uniqueId with walkback script.

**Comment by mehah** [comment]
with tibia 7.72


https://user-images.githubusercontent.com/2267386/131083223-bf23305c-c26c-43e9-979e-f3b2e8f57538.mp4


server: OTHire
command: doTeleportThing(cid, fromPosition)
