### ISSUE TITLE
error with transparent sprites

### ISSUE THREAD

**Issue by RaylanderWise** [opentibiabr/otclient#139]
I tried to put a transparent water sprite in my game and it happened, probably the error has to do with tibia.otfi and the transparency function on the client.
[https://prnt.sc/1qi0gdq](url) 

The Sprite I'm trying to put is the one that's on this link.
[https://tibiaking.com/forums/topic/101958-água-transparente-no-tibia-70-psd-png-obd/](url)

**Comment by mehah** [comment]
there is no problem with transparency, you must be doing something wrong.

**Comment by RaylanderWise** [comment]
try it yourself using the sprites I sent the link
I met other people who are also with this problem.

**Comment by mehah** [comment]
yes, I tested the transparency myself and it's working perfectly and with other people too, they even reported a bug that wasn't working with transparency through the image editor.

https://github.com/mehah/otclient/issues/123

**Comment by mehah** [comment]
and another thing, this tutorial is for the official tibia client and not for otclient, there are things missing there, like enabling the alpha channel.

**Comment by RaylanderWise** [comment]
yes, I adjusted the Game_Things, but this error is giving anything pass me your sprites.

**Comment by Klonoa88** [comment]
@RaylanderWise, Transparent is not bugged. You must have done something wrong somewhere..

**Comment by RaylanderWise** [comment]
Resolvido! obrigado.
