### ISSUE TITLE
Drawing bug

### ISSUE THREAD

**Issue by Mrpox** [opentibiabr/otclient#141]
### Steps to reproduce (include any configuration/script required to reproduce)
1. /i 355 to create new groundtile
2. Step 1sqm to the right of the new tile

### Expected behaviour
Should render fine

### Actual behaviour
Bug in rendering
![image](https://user-images.githubusercontent.com/72432211/131228257-b5c3a424-c792-4a36-8111-c7da2e14e8ce.png)

**Comment by mehah** [comment]
here it is working perfectly, check if you are using the latest revision, if it is, clean the project and compile again, it may have traces .

**Comment by Mrpox** [comment]
@mehah 
Youre absolutely right, Ill close this
