### ISSUE TITLE
Bug rendering mobs/items semi-hidden

### ISSUE THREAD

**Issue by oarsc** [opentibiabr/otclient#143]
As a continuation of #120, there are still some issues:
- Stacked boxes.
- Creatures that, even being 1 sprite sized, they have an offset value set, so they should be visible in this case.
![image](https://user-images.githubusercontent.com/5507777/132106077-f3d22e81-3fd7-4577-9381-ed6bda04a0a9.png)

### Actual behaviour

https://user-images.githubusercontent.com/5507777/132106205-ac80f6be-f61e-4dab-b19a-43f93ac78e86.mp4

### Environment
Tested in OTHire and ForgottenServer 1.2
Ubuntu 18.04 (make + gcc-11)

**Comment by mehah** [comment]
I'm not able to simulate, you can do a test, on the line:
https://github.com/mehah/otclient/blob/1074ee873f67f8552805b312bc7d9133fa7cc3bb/src/client/tile.cpp#L803
change to
`if(!thing->isSingleDimension() || m_drawElevation)`

**Comment by oarsc** [comment]
After this change you suggested there are still some problems..

**Comment by mehah** [comment]
sry, change
`m_drawElevation`
to
`thing->hasElevation() || thing->hasDisplacement()`

I'm trying on 10.98 and this problem doesn't occur, very strange. = /

**Comment by oarsc** [comment]
With all the conditions it works fine

https://user-images.githubusercontent.com/5507777/135673753-955bba36-f0c7-42af-aa23-61605dec49dd.mp4

:
