### ISSUE TITLE
Frame limiter is broken

### ISSUE THREAD

**Issue by themaoci** [opentibiabr/otclient#146]
![image](https://user-images.githubusercontent.com/33422088/132927946-396f0b04-3c9c-49c8-ac9a-4966b97992a6.png)

stdext::format("%d  Partial: [%d] Frame Delay Hit [%.2f%%] mFrames: [%d] max: [%d] MFD: %d lastFrame: %d", m_lastFps, (int)m_partialFps, getFrameDelayHit(), m_frames, m_maxFps, getMediumFrameDelay(), m_lastFrame);
thats what i was using to display it 

it wrongly limits frames...

**Comment by themaoci** [comment]
its propably because im using AMD Threadripper CPU if its nto that then i dont know how to fix that if i set value by hand for 144 fps it works right but if value is set by program its still the same value but its not working...

**Comment by Dip-Set1** [comment]
Nope, having same issue as well.
