### ISSUE TITLE
Hide creature health is considered dead by client

### ISSUE THREAD

**Issue by gaamelu** [opentibiabr/otclient#155]
Hi, I found a simple bug. When you declare setCreatureHideHealth in server, it is expected to hide your health bar and creature name. It works fine for almost everything... But, when we declare setCreatureHideHealth to our local players, setCreatureHideHealth declares health percent as zero, and it is enough to the client declare it as dead, so the client blocks a lot of interactions of de player by the c++ function canPerformGameAction().

**Comment by mehah** [comment]
seems to be your customization, isn't it, if that's the case, you need to adapt to your need, send a flag to hide the bar or instead of using percent, use the amount of life.
