### ISSUE TITLE
Game ActionBar for protocol below 7.8 needs some tweaking

### ISSUE THREAD

**Issue by themaoci** [opentibiabr/otclient#159]
game_actionbar module needs some tweaking for versions of protocols below 7.8 "use object" need to be edited or removed cause that protocol is not supporting this

**Comment by oarsc** [comment]
Commit: 1b2f9fa730f6a40acea1e3dc98d4588b7090a191

I added the same behaviour that the hotkey_manager does.
In protocols > 7.8, it will search opened containers in order to find the item and use it.
