### ISSUE TITLE
Player Spotlight Entirely Too Bright

### ISSUE THREAD

**Issue by ericlancebrown** [opentibiabr/otclient#16]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Log In. Wait for night cycle.
2. Notice player spotlight.
3. It's way too bright and even supersedes the day cycle.

### Expected behaviour
The player is supposed to be less visible than in day time, but not as visible as it is in the current client. Here are some examples of expected player spotlight lighting.
[Good Spotlight Example 1](https://i.imgur.com/SDybxy9.png)
[Good Spotlight Example 2](https://i.imgur.com/zsx3YJA.png)

### Actual behaviour
The player is visible in a beam of light that is entirely too bright. It also is brighter than the daylight, which is an offputting feel to the lighting.
[OTClient Spotlight Example](https://i.imgur.com/7qhof8j.png)

### Environment
OTClient: Latest - Mehah - x64
TFS: 1.3 - OTLand
OS: Windows 10
Compiler: Visual Studio 2019

**Comment by mehah** [comment]
done
