### ISSUE TITLE
Fade tiles/floors

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#162]
Are you going to add fade tiles/floors? Then you can have it as an option on/off in client_options?

**Comment by Klonoa88** [comment]
Is this difficult to do or do you not know if you want it in your client?

**Comment by mehah** [comment]
No, it's not difficult, I brought the fade tile to tibia.
https://otland.net/threads/otclient-showoff-show-off-your-otclient-project-module-ui-and-other.254460/post-2467539

however I don't want to use the code I had done but develop a new, cleaner one, but I don't want to focus on that now.

**Comment by mehah** [comment]
No, it's not difficult, I was the one who brought the faded tile to Tibia.
https://otland.net/threads/otclient-showoff-show-off-your-otclient-project-module-ui-and-other.254460/post-2467539

however, I don't want to use the code I made, but rather develop a new, cleaner one, but I don't want to focus on that right now.

**Comment by Klonoa88** [comment]
Okay :) Hope it comes to your client in the future. It's a cool feature that many users want. I think it will make your version of OTClient more attractive to new users
