### ISSUE TITLE
Positioning the char name

### ISSUE THREAD

**Issue by DominoGro** [opentibiabr/otclient#164]
Hello,
 I noticed that the character name position is a little strange. It displays in the center of an outfit, what causes covering up the outfit. 
The difference is visible if we use mounts or bigger outfits like: Demon, Golem, Cyclop etc.

We can see it on the pic below:
![image](https://user-images.githubusercontent.com/13680034/139029304-6cfe3d24-536b-4c04-9066-10276168fa3b.png)

I think it should be better to move the name up to the red rectangle.(see pic)

**Comment by SkullzOTS** [comment]
@Misztrz 

in creature.cpp, change:

```
// calculate main rects
    auto backgroundRect = Rect(p.x - (13.5), p.y, 27, 4);
    backgroundRect.bind(parentRect);

    const Size nameSize = m_nameCache.getTextSize();
    auto textRect = Rect(p.x - nameSize.width() / 2.0, p.y - 12, nameSize);
    textRect.bind(parentRect);
```

to:

```
// calculate main rects
    const Size nameSize = m_nameCache.getTextSize();
    int cropSize = Creature::rawGetThingType()->getExactSize();
    auto backgroundRect = Rect(p.x - (13.5), p.y - (cropSize - nameSize.height()), 27, 4);
    backgroundRect.bind(parentRect);

    auto textRect = Rect(p.x - nameSize.width() / 2.0, p.y - (cropSize), nameSize);
    textRect.bind(parentRect);
```

**Comment by DominoGro** [comment]
Thank you for your help.  It looks much better in some cases, but it needs more optimization.

This is the new solution with golem outfit, it looks better:
![image](https://user-images.githubusercontent.com/13680034/140026925-b1b23831-233d-4443-a484-3427d05bc0c1.png)

And here another example looking not good:
![image](https://user-images.githubusercontent.com/13680034/140026584-1f1b6c97-39bd-493a-a6fb-b2b2351f6b22.png)
Its to high, cause it takes the sprite size.

I think it's not worth to care about it, too much work. :D
