### ISSUE TITLE
action bar doesn't save

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#167]
action bar doesn't save

console otclient

https://prnt.sc/1xpw6ce

**Comment by SkullzOTS** [comment]
@daniofordon  change all the function loadActionBar, to:

```
function loadActionBar()
    unbindHotkeys()
    local hotkeySettings = g_settings.getNode('game_actionbar')
    local hotkeys = {}

    if not table.empty(hotkeySettings) then hotkeys = hotkeySettings end
    if not table.empty(hotkeys) then hotkeys = hotkeys[g_game.getCharacterName()] end
    if hotkeys then
        for slot, setting in pairs(hotkeys) do
            slot = actionBarPanel:getChildById(slot)
            slot.itemId = setting.itemId
            slot.words = setting.words
            slot.text = setting.text
            slot.hotkey = setting.hotkey
            slot.useType = setting.useType
            slot.autoSend = setting.autoSend
            slot.parameter = setting.parameter
            if slot.hotkey then
                local text = slot.hotkey
		if type(text) ~= "number" then
                    text = text:gsub("Shift", "S")
                    text = text:gsub("Alt", "A")
                    text = text:gsub("Ctrl", "C")
                    text = text:gsub("+","")
		end
                slot:getChildById('key'):setText(text)
            end
            if slot.words then
                loadSpell(slot)
            elseif slot.itemId and slot.itemId > 0 then
                loadObject(slot)
            elseif slot.text then
                loadText(slot)
            end
        end
    end
    setupHotkeys()
end
```

**Comment by daniofordon** [comment]
ok thx :)

**Comment by daniofordon** [comment]
now there is another problem. if he assigns the text / i to the action bar and assigns the 1 key to this, after pressing the key one enters / i 1 in the chat

**Comment by SkullzOTS** [comment]
@daniofordon with me this is not happening, although I also made several changes and corrections, such as resetting the mouse cursor when not clicking on anything or something that cannot be added to the slots, clicking with the left mouse button on the slot to give the UseWith...

have you reset the settings in appData?

**Comment by SkullzOTS** [comment]
https://user-images.githubusercontent.com/86809689/139488944-df019d9c-75f0-4a1d-82e9-5b7d75732a2e.mp4

**Comment by oarsc** [comment]
He meant disabling the "enviar automaticamente" and having the chat unlocked after pressing the key.

@daniofordon 
Could you try replacing
https://github.com/mehah/otclient/blob/1b2f9fa730f6a40acea1e3dc98d4588b7090a191/modules/game_actionbar/game_actionbar.lua#L438
for `g_keyboard.bindKeyUp(slot.hotkey,  `?

**Comment by daniofordon** [comment]
scopz. this is how it works :)

**Comment by oarsc** [comment]
There is a point I want to make...
My objective is to disable all hotkeys on words, numbers or symbols that can be written when the chat is open (no WASD mode).

I made a change disabling those hotkeys.
If you press a hotkey text (with autosend off) and chat is disabled, it will be enabled automatically with your text in it.

Please, check out the last changes.
