### ISSUE TITLE
NPC black sqm when moving (doing stairhop)

### ISSUE THREAD

**Issue by Lopsitos** [opentibiabr/otclient#168]
I've seen that sometimes, when you go up/down stairs, if an NPC is moving it shows black floor under him or even black sqm.

### Steps to reproduce
1. Place NPC downstairs
2. Go up and down the stairs until the NPC starts moving
3. Black square appears
https://imgur.com/BT19uXI

### Environment
Testing on a 10.98 server with otclient - Redemption (1.2)

**Comment by SkullzOTS** [comment]
occurs with any creature that is moving when you change floors (NPC, Player, Monsters...)
