### ISSUE TITLE
Glitch when trying to walk immobile

### ISSUE THREAD

**Issue by Ryan050** [opentibiabr/otclient#17]
Set player to be immobile (can't move but with normal speed) and try to walk any direction it'll glitch outfit (blink outfit) on the walked tile.

Below the gif to get a better idea:
https://gfycat.com/alarmedgregariousafricanbushviper

Edit:
Tested on normal OTC too and it don't happens (the blink part)

**Comment by mehah** [comment]
how exactly did you leave him immobile?

**Comment by Ryan050** [comment]
old mayNotMove

**Comment by mehah** [comment]
the most recent TFS does not have this command, it must have been removed, as it is no longer suitable to use it.

Therefore, I made this command to solve your problem.

add in data\lib\core\creature.lua

```lua
function Creature.canWalk(self, v)
	if v == nil then
		return self:getSpeed() >= 10
	end

	self:changeSpeed(self:getBaseSpeed() * (v and 1 or -1))
end
```

using:
```lua
player:canWalk(false)  -- stop walk
player:canWalk(true)  -- walk
player:canWalk() -- returns whether or not you can walk.
``` 

this method is better, as the client will understand that it is not for walking and will block the commands

**Comment by Ryan050** [comment]
Thanks i'll close since its a minor issue but if you can do fix it be a easy way it'll be good i think @mehah
