### ISSUE TITLE
OTClient doesnt support old tfs? (0.3.6/0.4)

### ISSUE THREAD

**Issue by trzzu** [opentibiabr/otclient#170]
Hello, 
I use pure OTClient. 
I tried to log in but each time I got the error listed below.
I tried on a clean 0.4 and this error also occurs.

### Actual behaviour
OTClient prints this error when I try to login:
https://i.imgur.com/kLph6vu.png

(in tfs console [Warning - Protocol::RSA_decrypt] Not valid packet size)

### Environment
     
TFS 0.3.6 / TFS 0.4

Client version: 8.54 / 8.60

OTClient Redemption

**Comment by DominoGro** [comment]
Hello @trzzu 
I use 
Client: 8.60
TFS: 0.3.6 
OTClient: 1.2
and it works fine.

**Comment by mehah** [comment]
the error description already says, the client is working perfectly in several otserv distros
