### ISSUE TITLE
Effects with loop do not work properly

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#171]
Effects with loop do not work properly. Them only draws once.
In this case effect 56. Talkaction **!z 56** in game.

Client:
[Video](https://dl.dropboxusercontent.com/s/zquuu4magqb9mfr/OZ4oQ0FTiz.mp4)

Objectbuilder animation properties;
[Image](https://i.imgur.com/U1s9jae.png)

How Objectbuilder show the animation:
[Video](https://dl.dropboxusercontent.com/s/431uybh19nurwna/JjzMUYiLae.mp4)

**Comment by DominoGro** [comment]
@Klonoa88
### Yeap, this shouldn't happen. 

**Solution:**
export that effect from older version like 8.60 and import it to yours.(without any changes)

**Explanation:**
Coz in 8.60 it has 16 frames and in the newer version only 8(looping doesn't work properly)

**Comment by Klonoa88** [comment]
It is better that this issue is fixed correctly so the loop works ;)
