### ISSUE TITLE
Draw order

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#174]
Some items draw strange.
[Img](https://i.imgur.com/bCUTHXD.png)

Saw this in your client discord channel. That it might be the same problem as this with doors.
[Img](https://i.imgur.com/5vV6JbA.gif)

**Comment by mehah** [comment]
there are no problems with the rendering order, the character is bottom and the door is top, but the character is too big and this problem ends up occurring.

**Comment by mehah** [comment]
there are no problems with the rendering order, the character is bottom and the door is top, but the character is too big and this problem ends up occurring.

Tested on tibia 10.98, same "problem".
![image](https://user-images.githubusercontent.com/2267386/142554830-4a21079c-c8d1-4405-b78c-68f11caf35fa.png)

**Comment by Klonoa88** [comment]
Okay doors are apparently not a bug :P but what about this then [link](https://i.imgur.com/bCUTHXD.png) Have tried in edubart OTCLIENT but there it will not be like this

**Comment by Klonoa88** [comment]
In the mapeditor (RME) it looks like this [link](https://i.imgur.com/0YdnXu2.png)

**Comment by mehah** [comment]
what is the id of this item?

**Comment by Klonoa88** [comment]
Item id: 5511, 5512

All pulley has Itemid: 5505-5512

**Comment by mehah** [comment]
some "bug" in oficial cliente
![image](https://user-images.githubusercontent.com/2267386/143666345-e2bec625-7be9-4c7c-8460-e2e354a33b8a.png)

I will close
