### ISSUE TITLE
highlight mouse target disappearing

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otclient#176]
### Steps to reproduce (include any configuration/script required to reproduce)
I'm not sure working and disappearing item have same otb/dat attributes they even are in same fromid toid range in items.xml
![34](https://user-images.githubusercontent.com/35251842/143661259-8287e705-eb65-4a0d-873e-dc793e312732.png)
For new created items by /i command not working unless you relog seems to apply to most of items

### Actual behaviour
![hover_glitch](https://user-images.githubusercontent.com/35251842/143661243-8c3e89e2-6302-4dcd-9676-9becb9382c43.gif)

### Environment
0.4 tfs with custom 8.61v dat/spr and extended option

**Comment by mehah** [comment]
try this

change
https://github.com/mehah/otclient/blob/aa223562a3e22640385e2472d9b382f12ed4a787/src/client/thingtype.cpp#L568
to
```c++
animationPhaseTexture = TexturePtr(new Texture(fullImage, true, false, m_size.area() == 1 && !hasElevation(), false));
```

**Comment by ghost** [comment]
Nice! it repaired disappearing.
Still highlight didnt pop up on new items, after moving this item/reloging/chaning floors/going out of item view and going back sometimes even steping on this item repairs it.
Also sometimes after repairing it also can stop working and than again start working, tried to find something by myself but im confused about not consistency. I assumed that is something with shader timer freezing becouse sometimes even had that after leaving mouse on item for some time suddenly it start to work with no mouse movement or what so ever

#edit
Creatures don't seems to have this problem after creating with /m always work

#2edit
if they are few items on tile stack it seems like moving top item updates all items on tile stack or maybe adding new item with /i command(parseTileAddThing?) updates stackpos - 1 instead of good one

![item_hover2](https://user-images.githubusercontent.com/35251842/143676260-b4831276-2369-4b45-bac5-63ade3d40a2d.gif)

#3edit
i debugged Tile::select seems like looping/rgbcolor/fadelevel working as they should

#4edit
okay so checkForDetachableThing seems to force return getTopCreature even though there is no creature on tile
after moving 
`    if(m_highlight.thing = getTopCreature())
        return true;`
to end of function seems to repair initial problem but it breaks creature prioritizing so the fix must be to proper remove creature from m_things after it moves out of tile

#5edit
I tried few things but couldn't get it to work so im not sure im on right track i'm not realy familiar with otc source so i will leave it for now, maybe you will have some idea
After playing with getTopCreature noticed that  
`    if (creature) {
        g_logger.warning(stdext::format("0 %d", m_position.x));
        g_logger.warning(stdext::format("1 %d", m_position.y));
        return creature;
    }
    if (!m_walkingCreatures.empty()) {

        g_logger.warning(stdext::format("2 %d", m_position.x));
        g_logger.warning(stdext::format("3 %d", m_position.y));
        return m_walkingCreatures.back();
    }
`
log
`
up to item(not working)  left also not work with 4 

WARNING: 2 1458
WARNING: 3 1517
WARNING: 0 1458
WARNING: 1 1516

up from item(not working) left also not work with 4 

WARNING: 2 1458
WARNING: 3 1516
WARNING: 0 1458
WARNING: 1 1515

down to item(working) right also work with 2

WARNING: 0 1458
WARNING: 1 1516

down from item(working)  right also work with 2

WARNING: 0 1458
WARNING: 1 1517
`
