### ISSUE TITLE
character outfit glitching

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otclient#177]
### Steps to reproduce (include any configuration/script required to reproduce)
Seems to apply to characters with bigger movement speed but still is noticable with medium speed 
I have extended sending/parsing map main is 8/6(4:3) I have 16/9(16:9) so maybe the screen ratio is problem becouse its only appear on moving left/right not up/down
 It appear In most client map ranges changed with ctrl+- / ctrl+= but in few it almost completly dissapear
Changing outfit dont seems to help
![outfit_glitch7](https://user-images.githubusercontent.com/35251842/143661975-4a6f14ed-0955-460e-bf98-8ba08899eba7.gif)
![outfit_glitch8](https://user-images.githubusercontent.com/35251842/143662093-709d0d6a-bc3c-400a-a394-4d706f6ff657.gif)
have to lower quality since github prevent sending bigger files so maybe its hard to notice but it glitching very badly in some ranges
playing with options dont change anything and i didnt had this on main edubart otclient so its not the server side problem
### Environment
0.4 tfs with custom 8.61v dat/spr and extended option

**Comment by poxis** [comment]
I noticed the same problem, character graphics as if 'skipped'  - I did not change anything in the size of the windows etc. 
I thought it depends on the height of the graphics, but others of the same size are ok; | (~but others also have this bug -  lotery?)

https://user-images.githubusercontent.com/18105004/144470619-789a485a-dee0-4aea-92dd-3636ad6ec3a8.mp4

~the bug most often occurs when the floor slows down

**Comment by mehah** [comment]
i can't reproduce with official 8.6 spr / dat

**Comment by poxis** [comment]
2 file.  outfit_25 - there is a problem,  outfit_26 work ok
[outfit.zip](https://github.com/mehah/otclient/files/7651851/outfit.zip)

**Comment by mehah** [comment]
the logic is the same for all, if one works and the other the bug occurs, something is different between these two outfits.

**Comment by mehah** [comment]
the logic is the same for all, if one works and the other the bug occurs, something is different between these two outfits.

have you already checked it out to see if there is anything different?

**Comment by poxis** [comment]
I do not know if this is a good clue but if the graphic is over 30px this problem appears (height +32px [64px] this problem does not occur; |) 

BUG: (character height 31px)
![B4cD8KT](https://user-images.githubusercontent.com/18105004/144663165-ece46be8-8510-46ea-a2f0-b40430523c0e.png)
NO BUG ; (character height 30px)
![WVU8kFd](https://user-images.githubusercontent.com/18105004/144663200-a8ed9d9b-0d4a-4964-ae62-309b72138716.png)

only the walking graphics have changed and it works if we shorten the graphics to 30 px 



EDIT 3:
last what i see, the problem arises only if the graphic / character height is from 31-32px |  below/above no problem. (I even tested a character with a height of 64px with the same graphics and I still have this problem)

**Comment by ghost** [comment]
I didn't noticed any differences between ~24x24/~32x16/~32x32/~64x64 outfits all had that problem, after playing with scaleFactor noticed that alterning dest in internalDrawOutfit worsen it badly. Removing scaleFactor from there changed nothing, so problem is probably in m_walkedPixels, I reduced glitching by changing 800
`const float extraSpeed = isLocalPlayer() && !hasSpeedFormula() ? 800.f / static_cast<float>(stepDuration) : 0.f`
to max movement speed 1500
`const float extraSpeed = isLocalPlayer() && !hasSpeedFormula() ? 1500.f / static_cast<float>(stepDuration) : 0.f`
its way more stable upon map range changes but still is noticable, mostly on changing walking directions and start/stop walking

**Comment by poxis** [comment]
I don't know if it will help but: if the character walks on items has offest (eg on box,  ItemID: [1738]) the problem does not occur on any outfit...

![Bjtcccg](https://user-images.githubusercontent.com/18105004/144707226-d4ee4921-6501-4beb-942d-941757954ed3.png)

**Comment by ghost** [comment]
Yeah, walking on elevation seems to works just fine, testing with pickupable(not elevated) but it don't helped. I don't know if i looked at it right but elevation seems to apply for drawoffset that is used also for name and bars place calculation and they stays always in right place, dont glitch along with a character texture.
Tried also changing groundSpeed if null from 150 to 100 that are most of ground tiles on my serv but it dont changed, trying to change double stepDuration = 1000. * groundSpeed; seems to worsen it again.

edit 1
second thoughts maybe it is related to elevation in tile draw calls i will check that later.

edit 2
didn't find anything, 
it dont double draw from m_walkingCreatures and m_things
m_drawElevation always return 0
(creature->getPosition().x - m_position.x) return sometimes +1 higher number on left and right movement even while continous movement but point.x seems to always be same

edit 3
after retesting find some differences in movement basic dest but as i said before, the point result is as should be

`        g_logger.warning("!!!!!!!!!!!!!!NEW!!!!!!!!!!!!!!!!!!!!!!!!!1");

        g_logger.warning(stdext::format("destx: %d", dest.x));

        g_logger.warning(stdext::format("desty: %d", dest.y));

        g_logger.warning(stdext::format("positionx2: %d", ((creature->getPosition().x - m_position.x)* SPRITE_SIZE - m_drawElevation)));

        g_logger.warning(stdext::format("positiony2: %d", ((creature->getPosition().y - m_position.y)* SPRITE_SIZE - m_drawElevation)));

        g_logger.warning(stdext::format("positionx: %d", (creature->getPosition().x - m_position.x)));

        g_logger.warning(stdext::format("positiony: %d", (creature->getPosition().y - m_position.y)));

        g_logger.warning(stdext::format("wholepointx: %f", (dest.x + ((creature->getPosition().x - m_position.x) * SPRITE_SIZE - m_drawElevation) * scaleFactor)));

        g_logger.warning(stdext::format("wholepointy: %f", (dest.y + ((creature->getPosition().y - m_position.y) * SPRITE_SIZE - m_drawElevation) * scaleFactor)));
`


left/up



![left](https://user-images.githubusercontent.com/35251842/144895759-9c7022ca-418f-46e8-a9cc-89f26de07b79.png)


right/down

![right](https://user-images.githubusercontent.com/35251842/144895780-9058ce15-a56d-4fa9-98fe-08bb74a00dda.png)

and finded something like this in mapview seems to appear only on right/down map border. maybe this is breaking some tile calculation 
![map](https://user-images.githubusercontent.com/35251842/144895892-0e74bab2-64ae-4835-be2d-6cc770a7b451.png)

right border seems to produce and remove +2 tiles on movement instead of +1 like rest of borders

**Comment by poxis** [comment]
best part is if you add it to the end of the function  `void Tile::drawCreature(const Point& dest, float scaleFactor, LightView* lightView)`

>     g_logger.warning("___________________________");
>     g_logger.warning(stdext::format("destx: %d", dest.x));
>     g_logger.warning(stdext::format("desty: %d", dest.y));

the client logs everything in the terminal (you know, FPS drops to 5 because spam) but the problem does not occur anymore; d 

~ in general, when we turn on 'Enable vertical synchronization' the problem stops, maybe not 100%, but it is much better, but we have 60 FPS ..  

@InSaiyan42do you have this problem on every outfit?

**Comment by ghost** [comment]
Yes, visualy "Enable vertical synchronization" option is much better enabled, it looks like it removes the animation frame ghosting, much more affects outfits with more animation frames. Ghosting mostly is noticable on ~32x32 characters with weird animation sprites, bigger dont have that much but basicly all of them have glitch that one of frames is on beggining of tile in middle of movement animation. Possible problems that I was thinking about

I recorded frames sometimes it looked like animation produce 4(~25%/0%/50%/75%) frames instead of normally 3(25%/50%/75%) but it is hard to proof and that would point to some key/function overlapping which would be visible also on top/down movement and its not.

Becouse of only left/right glitched the only idea for now is mapview cant get exact center becouse of extra right tile that breaks horizontal middle center because of an even number of tiles on movement. top/down works and they have 17 on idle(+1up/+1down) on movement, but left/right have 31 idle (+1left/+2right) that gives 34 tiles on movement so you dont have extra one to anchor exact center, but i cant proof that becouse i dont knows rendering map functions enough
^Edit
map view bug is related to draw viewport edge option, after enabling it there is no more difference in tiles, but even after getting correct tile numbers it have same problem. The correct tile numbers for me are actualy 34/20 i checked it also on older otc that dont had that problem so it breaks my theory of not centered tiles. 

The last would be something simple like SPRITE_SIZE dont have scale multiplier somewhere or something like that. I will test few more functions this week.

**Comment by poxis** [comment]
only that not all outfits have this problem (at least for me) and when it is on the elevation, the problem does not occur, maybe something with the buffer or also the FPS limitation itself already gives the difference ;| absurd problem..

**Comment by ghost** [comment]
something is related to outfit height for sure as you mentioned before
Without vertical synchronization it seems like full height are only broken and consistent 
![ourfit1](https://user-images.githubusercontent.com/35251842/145304274-f4ccaba8-a0f0-4a12-8336-ecc768017079.gif)
![ourfit2](https://user-images.githubusercontent.com/35251842/145304280-fce48dc9-b017-46d3-8606-7d45e029c311.gif)
![ourfit3](https://user-images.githubusercontent.com/35251842/145304283-fab1bb1f-e677-4bc4-9838-995ea0836b7d.gif)
and on enable synchro it repairs full height but breaks all outfits, glitching differ from sprite to sprite and is just random
![ourfit5](https://user-images.githubusercontent.com/35251842/145308971-c8d84a42-755f-4341-936a-cf203f37880d.gif)

**Comment by poxis** [comment]
I did an idiotic fix... 
in function `void Creature::internalDrawOutfit`

above `if(m_outfit.getCategory() == ThingCategoryCreature) {`

paste: 
>     ThingType* typeEx = g_things.rawGetThingType(1, ThingCategoryEffect);
>     typeEx->draw(dest - (getDisplacement() * scaleFactor), scaleFactor, 0, 0, 0, 0, 0, TextureType::NONE, Color::alpha);

I don't know why but it helps ... maybe it will help to a real fix..

**Comment by mehah** [comment]
well, all my tests are with original dat / spr and with vsync enabled, there are no significant benefits of playing without vsync, it will just consume cpu / gpu horrors.


about the problem:
try to remove this condition, but I believe that is not it, but if it solves this problem, I will remove this cache:
https://github.com/mehah/otclient/blob/25ebdae0531692dcd39651c07a9d913b8ee4305b/src/client/mapview.cpp#L120"

or maybe the problem is with that method.
https://github.com/mehah/otclient/blob/25ebdae0531692dcd39651c07a9d913b8ee4305b/src/client/creature.cpp#L565


**as mentioned before, this issue does not occur with Tibia original spr/dat.**

**Comment by ghost** [comment]
mapview change didn't helped, i noticed this problem is only on localPlayer when you look at outfit from 3rd view you don't see any glitching or tearing. As i posted extraSpeed changes helped after doing something like this
`walkTicksPerPixel = (stepDuration + 0) / SPRITE_SIZE;`
it removes tearing without vsync and removes 90% of glitching

**Comment by mehah** [comment]
hmm, soon I'll post it here rewritten and you guys tell me if it worked.

**Comment by ghost** [comment]
if you want some personal testing i recreated same issues on 8.6 real tibia dat/spr and clean tfs 0.3.6 mostly seems to apply to always animate like 333/19/314/315 but also normal outfits like 211 it's just harder to reproduce on top-down sprites compared to 2d sprites since it seems to relate mostly on outfits that touch max sprite size. As i was writing before something is related to map view distance(camera position that use walkoffset? it will corelate with extraSpeed changes) it seems like most buggy camera position are starting from the nearest limit(3) and all multiplier of 3 are most bugged, 3-1 are middle glitching, 3-2 are mostly working ones. I don't know why it even recognize 32 pixel texture from 30 pixel one but it seems like it does when looking at shaders like ghost that use also background, it square bound to color pixels without alpha not 32x32 texture
![realtibia_glitch](https://user-images.githubusercontent.com/35251842/145678537-6197c9b1-7a78-4d6d-8199-245f95244e8e.gif)

**Comment by mehah** [comment]
I'm still trying to find a solution, this problem is kind of bizarre.

**Comment by Doodiie** [comment]
Sorry to open it again, but the fix didn't fix the bug, it kind of reversed, before what was bugging going west, now it's going east.

**Comment by Doodiie** [comment]
Hello, I was looking for a solution to this issue, and I found that if I change this function in rect.h the problem is fixed 100%:

`std::size_t hash() const { return static_cast<int>(x1) << 16 | static_cast<int>(x2) << static_cast<int>(y1) << 16 | static_cast<int>(y2); }`

Change To:

`std::size_t hash() const { return static_cast<int>(x()) << 16 | static_cast<int>(y()); } `

I don't know if the change can cause bigger problems in otclient, but it was the solution I found. @mehah can give us more information about...
