### ISSUE TITLE
Mouse control improvement

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otclient#178]
More like improvement ideas than bugs since the main otclient had same issues
1. Overriding using map items with right click (classic control) 
Right clicking on map object will move player to that place as it should but when you want to move with arrow it will stop for a second and keep forcing player to move towards objejct , often blocking moving completly until player reach that object instead of overriding like it is with left click
2. High speed movement with mouse
Moving refactor was such a good idea it is way smoother specialy on max movement speed but is seems to only apply for arrow movement when you use left/right click it is same as it was with noticable surroundings tearing and not consistency in the movement itself sometimes it kinda stop for a few ms beetwen next step no matter if it is single left click or spamming right click

### Environment
latest otclient opengl
i7-3770k
gtx 1060
m.2 ssd
localhost server
windows 10

**Comment by mehah** [comment]
If I'm not mistaken these features have already been done, I will close this issue, anything, open it again.
