### ISSUE TITLE
Key events freeze

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otclient#179]
### Steps to reproduce (include any configuration/script required to reproduce)
After pressing more than 2 hotkeys it blocks any new key events if you use 3rd KeyDown on walking it will loop arrow key even if you no longer holding it. Loop last till you release one of hotkeys, bug is from old otclient.

### Expected behaviour
make it register all key events but limit it in lua to make more flexible for custom rework

### Environment
OTC 1.3

**Comment by oarsc** [comment]
My keyboard does strange stuff while pressing more than 2 keys.
For example, while I'm pressing H and J, A/S/D doesn't seem to work, but W does...

Check if it's not a keyboard problem. You can use an online tester:
https://www.google.com/search?q=keyboard+tester

**Comment by ghost** [comment]
My bad it seems like it limit related to windows/keyboard indeed, i was preety sure i dont had that problem with other games and tested with normal keys that block after 4/5 witch is limit what i want to achieve instead of 2/3 like F1 keys. I have spell charging system that need 3/4 KeyDown + walking i will add some toggle i guess, since it is not related to otc itself issue can be closed.
