### ISSUE TITLE
Client crashed while running side by side with normal OTC while moving

### ISSUE THREAD

**Issue by Ryan050** [opentibiabr/otclient#18]
I think this is just to you see if theres anything crash related in the functions/changes below (backtrace of crash)
```
  backtrace:
    1: ./otclient(Tile::removeThing(stdext::shared_object_ptr<Thing> const&)+0x20a) [0x56175ca2633c]
    2: ./otclient(Tile::addThing(stdext::shared_object_ptr<Thing> const&, int)+0xab3) [0x56175ca27263]
    3: ./otclient(Map::addThing(stdext::shared_object_ptr<Thing> const&, Position const&, int)+0x93) [0x56175c9fb97b]
    4: ./otclient(ProtocolGame::parseCreatureMove(stdext::shared_object_ptr<InputMessage> const&)+0xeb) [0x56175ca4c073]
    5: ./otclient(ProtocolGame::parseMessage(stdext::shared_object_ptr<InputMessage> const&)+0x375) [0x56175ca4dc35]
    6: ./otclient(ProtocolGame::onRecv(stdext::shared_object_ptr<InputMessage> const&)+0x6b) [0x56175ca3deb5]
```

Edit:
Crashed again while side by side (OTC normal continues to run without crashing) with the same backtrace/conditions
Edit2:
Crashed again (three times already) while moving but without the other OTC side by side and also in another location. Same backtrace above.

**Comment by mehah** [comment]
could you run in debug mode, to get more details on which line the problem occurred?

**Comment by Ryan050** [comment]
@mehah https://imgur.com/PMAUI0q

Edit:
This happens always close to fire fields

**Comment by mehah** [comment]
@Ryan050

I made some changes, see if it resolves, because with me it doesn't crash.

**Comment by mehah** [comment]
It's this one, @Ryan050, has fixed?

**Comment by Ryan050** [comment]
I'll test it properly tomorrow. So far tested for like 10m and no crash.

**Comment by bulawow** [comment]
i tested it and got no crashes but im not sure that im recreating this bug correctly will be nice if @Ryan050 give the final decision if it exist

**Comment by Ryan050** [comment]
Tested for about a hour and no crash again. I think it's fixed with latest commits so gonna close it and if it happens again i'll open a new issue. Thanks @mehah
