### ISSUE TITLE
Moving items next to wall

### ISSUE THREAD

**Issue by Mrpox** [opentibiabr/otclient#180]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Have a wall (ie. 3460)
2. Put a border ontop of it (ie. 3482)
3. Try to move item to or from the sqm next to the wall.

### Expected behaviour
You should be able to move the item.

### Actual behaviour
You cannot move the item.

![moveitembug](https://user-images.githubusercontent.com/72432211/144558330-6097337e-5f31-4602-8fbd-caa298a7659d.gif)

### Environment
Client 1.3 and TFS1.4(10.98)

**Comment by mehah** [comment]
this is not a bug, there is no way you can move an item to this ground, much less remove it.

**Comment by mehah** [comment]
is working normally.

https://user-images.githubusercontent.com/2267386/146450121-e438f6df-df20-4ba8-b17a-0002a4964381.mp4
