### ISSUE TITLE
spinBox (UI) error: protected lua call

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#182]
Hi, I have a problem, if we open a market and we want to add a new offer and when we want to set the price (or total, amount) an error appears in the terminal when using the mouse scroll. If you click on the arrows next to the number (\\/ or /\\), the client gets a crash.

log:
> ERROR: protected lua call failed: LUA ERROR:
> /corelib/ui/uispinbox.lua:28: attempt to call method 'up' (a userdata value)
> stack traceback:
> 	[C]: in function 'up'
> 	/corelib/ui/uispinbox.lua:28: in function </corelib/ui/uispinbox.lua:25>
> ERROR: protected lua call failed: LUA ERROR:
> /corelib/ui/uispinbox.lua:28: attempt to call method 'up' (a userdata value)
> stack traceback:
> 	[C]: in function 'up'
> 	/corelib/ui/uispinbox.lua:28: in function </corelib/ui/uispinbox.lua:25>
> ERROR: protected lua call failed: LUA ERROR:
> /corelib/ui/uispinbox.lua:30: attempt to call method 'down' (a userdata value)
> stack traceback:
> 	[C]: in function 'down'
> 	/corelib/ui/uispinbox.lua:30: in function </corelib/ui/uispinbox.lua:25>
> ERROR: protected lua call failed: LUA ERROR:
> /corelib/ui/uispinbox.lua:28: attempt to call method 'up' (a userdata value)
> stack traceback:
> 	[C]: in function 'up'
> 	/corelib/ui/uispinbox.lua:28: in function </corelib/ui/uispinbox.lua:25>

**Comment by Klonoa88** [comment]
Confirmed

**Comment by poxis** [comment]
Hmm, i 'fix' this problem:
change file: **/corelib/ui/uispinbox.lua**

add:
> function UISpinBox:up_fix() self:setValue(self.value + self.step) end
> function UISpinBox:down_fix() self:setValue(self.value - self.step) end

change function:

> function UISpinBox:onSetup()
>     g_mouse.bindAutoPress(self:getChildById('up'), function() self:up_fix() end, 300)
>     g_mouse.bindAutoPress(self:getChildById('down'), function() self:down_fix() end, 300)
> end
> 
> function UISpinBox:onMouseWheel(mousePos, direction)
>     if not self.mouseScroll then return false end
>     if direction == MouseWheelUp then
>         self:up_fix()
>     elseif direction == MouseWheelDown then
>         self:down_fix()
>     end
>     return true
> end

I still do not know the reason for this, but it works for now...

**Comment by mehah** [comment]
> Hmm, i 'fix' this problem: change file: **/corelib/ui/uispinbox.lua**
> 
> add:
> 
> > function UISpinBox:up_fix() self:setValue(self.value + self.step) end
> > function UISpinBox:down_fix() self:setValue(self.value - self.step) end
> 
> change function:
> 
> > function UISpinBox:onSetup()
> > g_mouse.bindAutoPress(self:getChildById('up'), function() self:up_fix() end, 300)
> > g_mouse.bindAutoPress(self:getChildById('down'), function() self:down_fix() end, 300)
> > end
> > function UISpinBox:onMouseWheel(mousePos, direction)
> > if not self.mouseScroll then return false end
> > if direction == MouseWheelUp then
> > self:up_fix()
> > elseif direction == MouseWheelDown then
> > self:down_fix()
> > end
> > return true
> > end
> 
> I still do not know the reason for this, but it works for now...

confirm if you really fixed it, if so, open a PR @poxis.

obs: I didn't find these methods, up_fix and down_fix

**Comment by mehah** [comment]
fixed #184
