### ISSUE TITLE
ERROR: failed to compile shader: WARNING: 0:2: '' :  #version directive missing

### ISSUE THREAD

**Issue by helviio** [opentibiabr/otclient#186]
ERROR: failed to compile shader: WARNING: 0:2: '' :  #version directive missing
WARNING: 0:9: '#extension' :  'GL_OES_standard_derivatives' is not supported
ERROR: 0:55: '=' :  cannot convert from '4-component vector of highp float' to '3-component vector of highp float'

ERROR: unable to load fragment shader 'Rain' from source file 'shaders/fragment/rain.frag'

**Comment by mehah** [comment]
what is your video card, as not all video cards support shaders

**so if this error is occurring, it is because it does not support it.
the most you can do is try to update the video driver to see if the error goes away, if not, just change the video card.**
