### ISSUE TITLE
problem with tibia effects 10.98

### ISSUE THREAD

**Issue by Mixlort** [opentibiabr/otclient#188]
first sorry for bad english, i'm using google translator...
There's a problem in tibia 10.98, poketibia sprites, which is the following, most of the effects don't show up on the screen, it doesn't give an error, it doesn't work, but you use some magic or /ze and the effect just doesn't appear, that's not in all the effects but it's mostly, I couldn't find a pattern for the ones that don't work, nor why this happens, the base I use is the dash pota tfs 1.2.

link: https://xtibia.com/forum/topic /253494-1098-pokedash-pota-v10-tfs-12-server-client-sources-site-map-editor-e-item-editor/#comment-1766154

I uploaded the entire client mehah with an edit in map.cpp only for screen expansion and activated some features, everything compiled and ready to play

link: https://www.mediafire.com/file/dmkz8uyiyt3lbh9/otclient-1.4.2.rar/file

scam: https://www.virustotal.com/gui/url/a8e7bde2cd481abc9da7afbf4788455fad050d17cf719e3ab862974bd8246daf?nocache=1

**Comment by poxis** [comment]
try # hash this:
https://github.com/mehah/otclient/blob/01162cef39edf47e72a3b5e88749ab8bc4f4e1ee/src/client/effect.cpp#L34

**Comment by Mixlort** [comment]
> try # hash this:
> 
> https://github.com/mehah/otclient/blob/01162cef39edf47e72a3b5e88749ab8bc4f4e1ee/src/client/effect.cpp#L34

I did it, but to no avail, it's still the same

**Comment by Klonoa88** [comment]
Try set loop to minimum 1 or higher in objectbuilder.
[Image](https://m.imgur.com/U1s9jae)

**Comment by Mixlort** [comment]
> Try set loop to minimum 1 or higher in objectbuilder.
> 
> [Image](https://m.imgur.com/U1s9jae) 

so i saw something around here about this loop, and i was going to try to edit it, but my obd doesn't have it 🥲.  The obj is very old as it is the only one that runs 10.98 sprites

my object builder options:
https://imgur.com/Wq5i9sR

**Comment by Klonoa88** [comment]
This one **(version 0.5.3)** has it and you can download it [here](https://github.com/whiteblXK/ObjectBuilder/releases/download/v0.5.3/ObjectBuilder_0_5_3.zip).

Tested it with tibia .dat and .spr **(10.98)**
[Image](https://i.imgur.com/HGtWrRG.png)

**Comment by Mixlort** [comment]
> This one **(version 0.5.3)** has it and you can download it [here](https://github.com/whiteblXK/ObjectBuilder/releases/download/v0.5.3/ObjectBuilder_0_5_3.zip).
> 
> 
> 
> Tested it with tibia .dat and .spr **(10.98)**
> 
> [Image](https://i.imgur.com/HGtWrRG.png)

It worked!  thank you so much my friend was racking his brain with this and really wanted an updated obd!!
