### ISSUE TITLE
[Lights] FPS DROP with enable light (lava down)

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#190]
I do not know if the problem is only with me, but if we are, for example, on level 8 (underground) and on level -1 (level 9) there is lava  [itemid: 598] then with the 'Enable lights', FPS goes crazy with 2000, it gets even 100 (if our character is moving) 

2 thing, if there is no floor under the outline/wall etc, then you can see the backlight from the lower floor 
![e0ovWsj](https://user-images.githubusercontent.com/18105004/147781241-acf795b6-0a0a-45a7-9822-a6795dfc3fd6.png)
- player: z = 12
- floor up: z = 11

**Comment by mehah** [comment]
the light system needs to be rewritten in a way that doesn't use textures.

if I come to rewrite the light system, I will not release it in a way that is for free.

**Comment by poxis** [comment]
@mehah is there any easy way to turn off the light display from the floor below?
