### ISSUE TITLE
Glitches with floor fading

### ISSUE THREAD

**Issue by sebekkx** [opentibiabr/otclient#193]
After compiling on Linux/Windows/macOS (I don't know if it's compiler related, have not tried on Visual Studio though) there are several floor fade glitches, that seem to happen randomly. Mostly (or entirely) it's rendering higher floor, when it should not have been drawn.

Steps to reproduce:
1. Login on on any server
2. Run around on a map

Expected behavior:
Drawing floors correctly

Actual behavior:
Sometimes drawing higher floor/(s) unexpectedly. Interesting thing happens when roaming in Ab'Dendriel at around 3:34 - floor fading seems to correct itself after a while. Turning off floor fade resovles the issue instantly.
video: https://youtu.be/BQmmTOlSUTc (glitches start at 1:20)

Environment:
macOS 11.6 (compiled with Clang)/Ubuntu 21.10 (compiled with GCC 10)/Windows (compiled with GCC 10)

**Comment by Klonoa88** [comment]
Confirmed in TFS 10.98 to.

**Comment by poxis** [comment]
Generally there are noticeable FPS drops with this system

**Comment by Klonoa88** [comment]
How is the progress of this bug @mehah? Floor fading is an awesome system but hard to play with, **with this bug**.

**Comment by mehah** [comment]
can you test it now?

**Comment by sebekkx** [comment]
@mehah: bug still persists. When e.g. I am standing on floor 5, sometimes floor 6 shows for a second. I don't have to move, it just shows randomly

**Comment by mehah** [comment]
try it now, I redid the lighting system, now it's working with fade on shades, I did my tests and everything seems to be ok.
