### ISSUE TITLE
Light amplification with other light sources

### ISSUE THREAD

**Issue by Source61** [opentibiabr/otclient#195]
I haven't actually tested this on this (mehah)'s client, but unless you've already fixed this this should still be present from the original OTClient.
OS: Windows

This bug is mainly for @scopz or of course anyone else that may want to fix this, as he asked me to report any other bugs if I find them in issue #35.

So the issue I'm going to describe here is partly a feature request (cipclient original behavior), partially a physics issue/bug with OTClient lighting, because even if you don't want cipclient lighting, the current way it works in OTClient is inconsistent or illogical.

Currently the lighting works such that two light sources in proximity amplifies the light's brightness (and to some virtual degree the radius as well).
This isn't how the lighting used to work, and imo it makes the game look kinda weird when the light becomes too bright with light sources that are supposed to be weak, but this may be subject to personal opinion.
More objectively it also makes amplified lighting appear suddenly when you enter the range of both light sources, which kinda makes no logical sense from a physics perspective, lights doesn't just randomly amplify each other unless you're slightly too far away from the second light source I'm pretty sure, but of course since OTClient only is aware of a few tiles at a time this cannot be solved without redesigning how lights should work.

Here's how it looks when you enter the range: https://imgur.com/a/ARku0op

Now if you don't care about any of those arguments or flaws, the main bug aspect of this is that two light sources on the same tile does not amplify each other, another major physics issue which makes no sense (light sources on same tile = no amplification, light sources on different tiles = amplification). This is definitely not how physics work and makes no sense whatsoever, it's also not legacy behavior as cip client doesn't amplify light sources at all (unless this has been changed in newer clients?).

Reporting this here because of @scopz basically telling me to, and because diath on edubart's repo is batshit insane.

**Comment by mehah** [comment]
this problem has already been fixed with the new light system, I ask you to do a quick test for you to solve your doubt, but this light system is not similar to cipsoft, but it breaks a branch. :)

**Comment by Source61** [comment]
> this problem has already been fixed with the new light system, I ask you to do a quick test for you to solve your doubt, but this light system is not similar to cipsoft, but it breaks a branch. :)

Neat.
I tried to compile and run the client, but the project seems to be Visual Studio 2022 only (I tried downgrading, didn't work), so I'm currently installing VS 2022 but it's gonna take some time.
I also tried to run it on Linux, but it seems like the client doesn't work on Linux (it compiles and runs, but can't choose language, and trying to close the client just makes it hang, had to kill it using kill -9).
Searching for commits by name also doesn't work as it seems that most of your light commits "does not belong to any branch", so they don't appear when searching for them, I've only been able to find some through issues.
Do you know which commit fixed this particular light issue?
And did you fix so that lights doesn't amplify each other, or just that sources on same tile doesn't amplify?

Edit: Got VS2022 installed now. It looks like this isn't fixed yet.
Here's how it looks: https://imgur.com/a/pwecUNg
Notice that the light on the left, right, and top side increases in radius/brightness when I'm activating a torch at the bottom, meaning light is definitely amplified.
The only reason the brightness doesn't change much is because OTClient by default has very powerful brightness, so it reaches max level very easily, I couldn't find how to change this formula in OTClient1.0 since lightview.cpp is changed, but if you reduce brightness in the sources you should see the same effect not just with radius but also brightness.

**Comment by mehah** [comment]
1- well i don't see any problem with the light system, you put another torch in another position which will increase the light range.
soon it will increase the brightness where it is dark, do the same test with the old client, you will see that the brightness will be much higher.

2- this problem is with the floor fading system.

**Comment by mehah** [comment]
Left - This Otclient
Right - Edubart Otclient

![diff](https://user-images.githubusercontent.com/2267386/150442604-bd2b0de9-3144-4edc-a1ad-799722cd40ee.png)

**Comment by mehah** [comment]
Cipsoft Client 10.98
![image](https://user-images.githubusercontent.com/2267386/150444151-75f34cea-6e77-481e-970e-c7e8ce1e60f2.png)

**Comment by Source61** [comment]
Unfortunately this is incorrect.
Not only does old Tibia 7.x client not have this, 10.98 does not have this either as it turns out.
There will be more lighting to the bottom side of the screen, naturally, because we activate a torch 1 tile south of the main torch which results in more light towards the bottom, but the top, left, and right side will NOT be lit up as you can see in this video (Tibia.exe 10.98): https://imgur.com/a/ZyiPGuq

2 images aren't informative as they don't show the relative difference between 2nd torch on and 2nd torch off.
For example, with a side by side comparison with 1 torch active, OTClient actually has much less light because its light formula is not correct (too little radius and too much brightness).
The only way to show that this is not a bug is with a video where the 2nd torch is turned on/off, showing clients side by side in a picture doesn't show anything since the light formula is different between the clients, try to take a picture side by side with only 1 torch active and see the results yourself:
![image](https://i.imgur.com/tOYxXYj.png)

Like I said comparing all 3 clients with 2 torches activated in a picture (not video) is flawed because the light formula is off between Cip client and both OTClients, and like I just showed you in the picture above you can see this by activating only 1 torch. If you activate 2 torches then OTClient lighting will be multiplied (amplified), making them both fairly equal, but this is random luck, if you try 1, 3, 4, 5, 6, 7, etc torches (any number except for 2), like I've just shown, the clients will not be similar again, you're basically measuring the wrong metric, namely the light intensity with both torches activated between the two or three clients, what you actually should measure is the difference between both clients first with 1 torch (2 pictures or a video), then with 2 torches (2 pictures or a video), in other words 2 side-by-side comparisons or 4 pictures total (OTC1.0: 1 torch, OTC1.0: 2 torches, Tibia.exe: 1 torch, Tibia.exe: 2 torches), or 2 videos (OTC1.0 video 2nd torch on/off, Tibia.exe video 2nd torch on/off).

**Comment by mehah** [comment]
**I said that the light system is similar to ciptsoft** and not that it is the same, but the light problem has been solved, I will show you using warmer colors.

![image](https://user-images.githubusercontent.com/2267386/150565075-20742031-942c-4c33-9311-2c188706cea2.png)

cipsoft client 10.98
![image](https://user-images.githubusercontent.com/2267386/150565264-67ecbce5-f24e-45a6-8651-3f9e3912c6cf.png)

I configured the light to my liking, if you want something darker, just configure it your way in this line:
https://github.com/mehah/otclient/blob/ba481ae6efba62f77e1ee1addcb329ab0f752c94/src/client/spritemanager.cpp#L222

sample with: brightnessIntensity = .5f;
![image](https://user-images.githubusercontent.com/2267386/150566526-a62ed5e6-23d4-48c4-a863-8f4216a9d090.png)
![image](https://user-images.githubusercontent.com/2267386/150568035-11fb7417-1ed4-4ab8-ae10-b029b652c4c8.png)

**the most I can do is configure the formula to make it more similar to cipsoft, now say that the problem has not been fixed...**

now... if I stop to try to replicate the lighting system like ciptsoft, unfortunately it won't be free.

**Comment by Source61** [comment]
You're showing items like skull staff in your newest picture. These have light intensity 2, this is 2/5ths of a torch, so of course they will be small, also when I've been speaking about radius increase so far it's just been to simplify, radius is not actually increased, only brightness, it's just a complicated subject to simplify this much for someone (what I was trying to simplify is that it may look like radius is increased because even when brightness in the center of the light source is max, the brightness of the full radius is not max, so more and more of the radius / circle will lighten up the more amplification there is).

It's just very unhelpful in general to keep switching items with different light intensities, mix them together with other items of more light intensity, use different colors, all of this is extremely unhelpful and is not an engineering or scientific approach at all, you're supposed to isolate the problem, not mix it all together and pretend there's no problem because there's just a huge chaos of interactions that no one can follow or interpret.

I was already going to pay you a small amount ($50+) if you showed me a working commit or if you would fix this issue after I created this issue, but I'm kinda bored at this point, you keep on ignoring the issue and pretend it's fixed so I'm bored and done, I will either fix it myself or keep trying to hire someone else to fix it, all I've touched/tried so far is lightview.cpp, so there's a lot more to try, I just would prefer to work on more interesting things because I don't enjoy and I'm generally not good at these types of tasks, though everytime I don't find someone to hire I get bored and always fix it myself eventually, so it's np.

Edit: Fixed this in 30-60 minutes of experimentation in my client today. $50 saved baby.

Bye.

Edit: Stay mad haters, I don't see any of you releasing this fix, why not? Are you too incompetent, or also greedy but pretend not to be because you're a huge lying hypocritical asshole, eh? :) Imagine getting so upset that someone that mehah himself is insulting would not release a fix for free that mehah himself demanded money for releasing. How braindead are you guys?

**Comment by poxis** [comment]
preferably some kind of dump ($) because I also don't have time to deal with it (and I also don't know where to start) - as @mehah wrote earlier, there is a new system written (does it work better? https://github.com/mehah/otclient/tree/new-lighting-system ) but not compatible with the latest source files

**Comment by mehah** [comment]
> You're showing items like skull staff in your newest picture. These have light intensity 2, this is 2/5ths of a torch, so of course they will be small, also when I've been speaking about radius increase so far it's just been to simplify, radius is not actually increased, only brightness, it's just a complicated subject to simplify this much for someone (what I was trying to simplify is that it may look like radius is increased because even when brightness in the center of the light source is max, the brightness of the full radius is not max, so more and more of the radius / circle will lighten up the more amplification there is).
> 
> It's just very unhelpful in general to keep switching items with different light intensities, mix them together with other items of more light intensity, use different colors, all of this is extremely unhelpful and is not an engineering or scientific approach at all, you're supposed to isolate the problem, not mix it all together and pretend there's no problem because there's just a huge chaos of interactions that no one can follow or interpret.
> 
> I was already going to pay you a small amount ($50+) if you showed me a working commit or if you would fix this issue after I created this issue, but I'm kinda bored at this point, you keep on ignoring the issue and pretend it's fixed so I'm bored and done, I will either fix it myself or keep trying to hire someone else to fix it, all I've touched/tried so far is lightview.cpp, so there's a lot more to try, I just would prefer to work on more interesting things because I don't enjoy and I'm generally not good at these types of tasks, though everytime I don't find someone to hire I get bored and always fix it myself eventually, so it's np.
> 
> Edit: Fixed this in 30-60 minutes of experimentation in my client today. $50 saved baby.
> 
> Bye.

you are cheeky, you use the client where most of the corrections and improvements were made by me and you haven't even donated anything so far, I pointed you where you could calibrate the light system to make it as close as possible to the client original, since while I was answering you, I was packing to travel and after an hour it supposedly says that it corrected it and not even shared it with the community and still comes to tell me that it saved 50$, honestly , you are toxic.

> preferably some kind of dump ($) because I also don't have time to deal with it (and I also don't know where to start) - as @mehah wrote earlier, there is a new system written (does it work better? https://github.com/mehah/otclient/tree/new-lighting-system ) but not compatible with the latest source files

as soon as i have free time, i try to calibrate the light system.

**Comment by Source61** [comment]
> you are cheeky, you use the client where most of the corrections and improvements were made by me and you haven't even donated anything so far, I pointed you where you could calibrate the light system to make it as close as possible to the client original, since while I was answering you, I was packing to travel and after an hour it supposedly says that it corrected it and not even shared it with the community and still comes to tell me that it saved 50$, honestly , you are toxic.

Never used your client, never will.
I tried it out a year ago (for a random FUN TFS project (for LESS THAN 1 HOUR lmao), and again a week ago just to test lights out that you lied to me about having fixed, the software you write is complete shit, you lie to people, you blame the server (TFS) when you make poor design choices that results in your client DDoSing TFS just by stepping diagonally, you have 0 interesting features, 0 interesting bug fixes (I know because I've looked and you haven't fixed anything, you've just made code unreadable and harder to maintain), 0 interesting bugged-ass client that nobody in their right mind will ever use, and 1000 unfixed bugs that you've created yourself, lmfao.
You have no idea what you're talking about and you're talking out of your ass and you're a liar, **you just said you want money for light fixes that you lied to me about having fixed, over and over again**, it doesn't look like you even understood the problem because you're a dumbass with an inflated ego and an uninteresting project trying desperately to make yourself look like a hero for writing "open source" broken-ass garbage software you want money for without contributing anything useful at all.
You're boring and your project is useless garbage that nobody should ever use unless they want cancer.
Sorry for not being honest with you before, I should've told you earlier that your software is shit so you don't think anyone with a brain actually appreciates this broken-ass software, lmfao.

Cheers

**Comment by mehah** [comment]
@Source61 
I want money? hahahaha

Man, you talk shit after shit, you must be 15 years old, so far I haven't seen any attitude from you, I just see you complaining everywhere.

Now I understand why Edubart left the community.

**Comment by Source61** [comment]
That's right man, you're the next Edubart, keep telling yourself that, Edubart wrote this client himself, you put it 10 years back in time by completely BREAKING it, fixing 0 bugs, and lying to people and ignoring people's issues when they report them, like you told me once before: YOU WILL ONLY FIX BUGS YOU HAVE CAUSED YOURSELF (hahahahahahahahahaha, funny, you break the client and then want applause for cleaning up half the mess you've created, HAHAHAHA).

Please give me an example of me complaining ANYWHERE :)
I'm not even complaining about your software because I've never used it and don't care about it, never will, all I'm "complaining" about here is your shitty child mentality after wasting my time and lying to my face, stop living inside your room all day and thinking you're a hero, grow some balls and some character and do something useful with your life instead of crying when someone's being a little cheeky towards you man, seriously, you think you're royalty or what? XD

**Comment by mehah** [comment]
hahaha poor thing, do I live inside my room? Are you kidding?

Send me a picture of you, you must be ugly, fat, your attitude looks like those people who were bullied, you think you're macho on the internet.

Anyway, I won't waste my time on you anymore.

**Comment by Source61** [comment]
> @Source61 I want money? hahahaha

You don't even remember your own words, do you? You're so lost that you don't even know what you say hahahaha
![image](https://i.imgur.com/mS7uAjo.png)

**Comment by mehah** [comment]
you think I have to do everything for free, honestly, I don't understand your point of view, you can make money and I can't, is that it?!

man, let's end this here, this is getting exhausting.

**Comment by Source61** [comment]
> you think I have to do everything for free, honestly, I don't understand your point of view, you can make money and I can't, is that it?!

No it's just funny, I literally offered you $50 for a fix you lied to me about having made, do whatever you want, just stop lying to people and try to make yourself out to be an open source hero and complain about people that doesn't release their software/projects when you want money yourself and won't release everything (and imo the stuff you release is useless, sorry), lmfao.

I would open source my projects as well if the price was right, that's the nature of work, it's people's choices what they want to release or not and for what price.
I've even tried to release fixes to issues, such as one issue I made here some months ago, in return for the price I paid a freelancer to fix it ($30 or $50, I don't remember).
I've also pushed minor fixes to edubart's otclient for free, and tried to push my old encryption system for FOR FREE that I paid $30 for to edubart's otclient (Diath rejected it so there's nothing more I can do about that) and I made my own repo for it that anyone can use for free here: https://github.com/Source61/otclient-encrypted.
I also host opentibia.dev for free trying to create a censorship-free open tibia community back without egomaniacal moderators banning and censoring people for random, trivial and made-up things, something I earn $0 from, it's all work I do for free and hosting I pay for myself.

And still you're here complaining that I don't release everything I made for free when you just told me that you don't either, hahaha, it's just funny as hell some of the things you say man, I'm not sure if you even know what you're saying.
And it's honestly pretty funky, I'm reporting bugs to you for free, do you think I earn anything from it? I'm not using your shitty client and earn nothing from it, I'm just trynna be nice and help people out and then you lie to my face and start complaining that I posted a sassy comment after you had lied to me and wasted my time, that's some massively childish and entitled shit right there, just saying.

**Comment by lgrossi** [comment]
Just ignore this clown, @mehah. You've been contributing amazingly, don't waste your time with a toxic random that pretends to be something, but in reality doesn't know shit and didn't do any relevant contribution so far. Let it go, it's not worth it.

**Comment by Source61** [comment]
I've contributed more than mehah has because at least my contributions doesn't create 50 new bugs for each update and blaming many of the bugs on vanilla TFS 1.4 (like his client DDoSing TFS 1.4 when moving diagonally #51) because he doesn't know how to fix them and takes 0 responsibility for the bugs he creates :)
When I release a fix or an update I don't have to release 50 more fixes to fix all the bugs I've created afterwards, which makes you look active, but just makes you truly a bad and incompetent programmer who creates more bugs than fixes pretending to be active because you have a million bugs to fix that you created yourself due to poor design and decision making.

Btw, nothing more toxic than jumping in and calling people's clowns and toxic for disagreeing with them or having legitimate criticism to share.
Lemme guess, you're BR, right? :) I wonder why the rest of the world hate you people, especially in Tibia, do you have any clue? :0
Maybe because you're all egomaniacs, trashtalk like crazy like you just demonstrated, and write crazy bugged software that EVERYONE recommends AGAINST using?

Not to mention that, and I'm sorry if this above your level of cognition, but contributions in a competitive business environment, which Open Tibia has become, doesn't really benefit the people, it just makes everyone run copy-paste double click to run servers that they themselves has contributed 0 to to make, and then they spam a million threads in the support section everytime they have a new problem they can't fix in the first 10 seconds.
The way you change things for the better is by creating a hospitable environment for discussion and conversation without calling everyone you disagree with toxic clowns, which is itself a toxic clown-thing to do, and work on solutions and education that benefits everyone, not by trying to make yourself into an important person that can never be wrong or make mistakes or try to lie your way to success, that's the type of thing a toxic clown does.

**Comment by lgrossi** [comment]
You're being acting like a child since comment 1, Mehah pointed things out to you and you started to mumbling that he should be doing this or that for you. He is not your worker, he helped you as he could and he has NO obligation whats or ever. Please stop barking without making sense and get back to your lil cage. If you don't like it just let it go, stop being toxic and diminishing others contribution. Please go do something useful and leave we here in peace, we are fine without your toxicity. 😉 

edit: btw I don't give a s*** about what you or anyone else thinks about BR, I don't care if you're against (or in favor) of us, not sure what triggered you like that, but I really don't care. I just care about you leaving people that are actually contributing alone, doing what they can do to help the community.

**Comment by oarsc** [comment]
I didn't know I had to know everything about otclient to try to help with this project.
Probably, @mehah is the one who knows more here about how this works.
There's a lot of things that I don't know, and I'll have to spend time on it: lightning, protocols between all versions, etc... It's not like we did code everything from scratch. Of course there will be mistakes and things that don't work as expected.
If you have this much knowledge, we'll appreciate some pull requests or reporting bugs, but don't expect a fast response/solution. We'll take a look at this and try to solve it.
This is not a professional project. We're trying to do our best, but we are not receiving anything else apart from the appreciation from the community.
Maybe some day we'll reach to a estable perfect version for older clients (there will always problems with the newer versions as Tibia is releasing them).

PS: I'm not BR nor PL, but that was racist...

**Comment by lgrossi** [comment]
> 

That the kind of attitude I'd like to see more, thanks for the comment. People insist on talking about bugs, I don't know a single codebase in ots community that has test coverage. Pointing fingers in those conditions is just pointless, every code written inside OTS community will have bugs until we learn that tests are a must have. If you're not doing anything to change that - moving us to a more test driven scenario, saying that a code is bugged is just acting in bad faith to diminish others.

**Comment by lgrossi** [comment]
Thanks @scopz for your input, that's the kind of attitude I'd like to see more, bringing value not to criticise and point fingers.. People insist in talking about bugs, I don't know a single codebase in ots community that has test coverage. Pointing fingers in those conditions is just pointless, every code written inside OTS community will have bugs until we learn that tests are a must have. If someone is not doing anything to change that - moving us to a more test driven scenario - and keeps saying that a code x or y is bugged, then this person is just acting in bad faith to diminish others.

**Comment by Source61** [comment]
> You're being acting like a child since comment 1, Mehah pointed things out to you and you started to mumbling that he should be doing this or that for you. He is not your worker, he helped you as he could and he has NO obligation whats or ever. Please stop barking without making sense and get back to your lil cage. If you don't like it just let it go, stop being toxic and diminishing others contribution. Please go do something useful and leave we here in peace, we are fine without your toxicity. 😉
> 
> edit: btw I don't give a s*** about what you or anyone else thinks about BR, I don't care if you're against (or in favor) of us, not sure what triggered you like that, but I really don't care. I just care about you leaving people that are actually contributing alone, doing what they can do to help the community.

What are you even talking about? I never demanded anything. I literally offered him $50 for a fix.
I was just reporting a bug, he said he had fixed it, but he hadn't, and he kept lying to me telling me he had fixed it and at the same time DEMANDING MORE MONEY for the fix.

I wouldn't have diminished Mehah's "contributions" if he didn't start lying to my face and trying to make it out like I'm asking for his help when he's the one that asked me for help.

Did you know HE came to my threads in otland and ASKED ME to try out otclient1.0 FOR HIM?
And I reported several bugs to him TO BE NICE TO HIM even though I never have and never will use his client?
I also kept my mouth shut about this for almost a year because I don't like to insult anyone unnecessarily, never said anything in otland or in here or anywhere else.
Do you have any social awareness at all and maybe understand that people get upset when they're being lied to over and over again and the person is trying to make it out like you're asking him for help when HE asked YOU for help?
It's really dishonest and manipulative, and I don't know why HE got so upset at me telling him I fixed it myself so I saved $50 that I was offering him for fixing it, only reason I did it was because he was lying to my face and wasting my time anyways.
Here's his post, had never talked to this guy before when he made this random post: https://otland.net/threads/for-fun-learning-oldschool-server-8-6.274388/#post-2644029

Full disclosure: I've been an OT developer for several years, but I've only written my own engine in my own secret language mixed with C/C++ (not based on OTServ - https://otland.net/threads/sources-custom-ot-game-engine-typescriptftw.278982), I created this thread just to try out TFS for the first time and try to make a fun project with other people since I hadn't collabed with anyone yet at the time, mehah ASKED me to try out otclient1.0 in MY thread so I did, and I've been nothing but nice and helpful towards him until I created this issue where he just lied to my face over and over again.

**Comment by Source61** [comment]
> I didn't know I had to know everything about otclient to try to help with this project. Probably, @mehah is the one who knows more here about how this works. There's a lot of things that I don't know, and I'll have to spend time on it: lightning, protocols between all versions, etc... It's not like we did code everything from scratch. Of course there will be mistakes and things that don't work as expected. If you have this much knowledge, we'll appreciate some pull requests or reporting bugs, but don't expect a fast response/solution. 

Sorry, but did you read our conversation? I wasn't expecting a fast solution, just for him not to lie to my face over and over again, that's my minimum requirements for working with and respecting someone else.

> We'll take a look at this and try to solve it. This is not a professional project. We're trying to do our best, but we are not receiving anything else apart from the appreciation from the community. Maybe some day we'll reach to a estable perfect version for older clients (there will always problems with the newer versions as Tibia is releasing them).

I fixed it myself, took literally like 30 minutes, I expected it to take longer but I figured out the issue (had to switch from DX9 to OpenGL + a fix I already knew), so don't sweat it.

> PS: I'm not BR nor PL, but that was racist...

BR isn't a race, it's a nationality. Feel free to call it racist all you want but it's just the truth, nobody likes BRs in this community and for a good reason. There's been a few BRs I've liked, but they're an exception, BRs in Tibia are generally known to be toxic, and I don't know if you noticed, but he's the one started with the insults and the dehumanization, calling me a toxic nobody clown, I'm just throwing his own words back in his face + a little extra to make sure "this monkey goes back in his cage" to use his own racist words :)

**Comment by Source61** [comment]
> Thanks @scopz for your input, that's the kind of attitude I'd like to see more, bringing value not to criticise and point fingers.. People insist in talking about bugs, I don't know a single codebase in ots community that has test coverage. Pointing fingers in those conditions is just pointless, every code written inside OTS community will have bugs until we learn that tests are a must have. If someone is not doing anything to change that - moving us to a more test driven scenario - and keeps saying that a code x or y is bugged, then this person is just acting in bad faith to diminish others.

You're not pointing fingers when you come in here and call me a "toxic nobody clown monkey that should go back to his cage", just because I told him I fixed this issue myself (after I was tired of his lies) and didn't release it - just like he said he won't release it for free either? That's all it takes for you to get triggered and start hurling insults at somebody?

**Comment by lgrossi** [comment]
> > Thanks @scopz for your input, that's the kind of attitude I'd like to see more, bringing value not to criticise and point fingers.. People insist in talking about bugs, I don't know a single codebase in ots community that has test coverage. Pointing fingers in those conditions is just pointless, every code written inside OTS community will have bugs until we learn that tests are a must have. If someone is not doing anything to change that - moving us to a more test driven scenario - and keeps saying that a code x or y is bugged, then this person is just acting in bad faith to diminish others.
> 
> You're not pointing fingers when you come in here and call me a "toxic nobody clown monkey that should go back to his cage", just because I told him I fixed this issue myself (after I was tired of his lies) and didn't release it - just like he said he won't release it for free either? That's all it takes for you to get triggered and start hurling insults at somebody?

I'm just responding in the same level you've been talking here, if you wanna talk serious we talk serious, but so far you've been mumbling about Mehah's not having full time for your needs. I won't waste my time with a serious discussion with someone that is just interested in offending and reduce other's contributions.

**Comment by lgrossi** [comment]
> > I didn't know I had to know everything about otclient to try to help with this project. Probably, @mehah is the one who knows more here about how this works. There's a lot of things that I don't know, and I'll have to spend time on it: lightning, protocols between all versions, etc... It's not like we did code everything from scratch. Of course there will be mistakes and things that don't work as expected. If you have this much knowledge, we'll appreciate some pull requests or reporting bugs, but don't expect a fast response/solution.
> 
> Sorry, but did you read our conversation? I wasn't expecting a fast solution, just for him not to lie to my face over and over again, that's my minimum requirements for working with and respecting someone else.
> 
> > We'll take a look at this and try to solve it. This is not a professional project. We're trying to do our best, but we are not receiving anything else apart from the appreciation from the community. Maybe some day we'll reach to a estable perfect version for older clients (there will always problems with the newer versions as Tibia is releasing them).
> 
> I fixed it myself, took literally like 30 minutes, I expected it to take longer but I figured out the issue (had to switch from DX9 to OpenGL + a fix I already knew), so don't sweat it.
> 
> > PS: I'm not BR nor PL, but that was racist...
> 
> BR isn't a race, it's a nationality. Feel free to call it racist all you want but it's just the truth, nobody likes BRs in this community and for a good reason. There's been a few BRs I've liked, but they're an exception, BRs in Tibia are generally known to be toxic, and I don't know if you noticed, but he's the one started with the insults and the dehumanization, calling me a toxic nobody clown, I'm just throwing his own words back in his face + a little extra to make sure "this monkey goes back in his cage" to use his own racist words :)

I never used the word monkey btw, that's on you, afaik monkeys don't bark, I said barking.

**Comment by Source61** [comment]
> > > Thanks @scopz for your input, that's the kind of attitude I'd like to see more, bringing value not to criticise and point fingers.. People insist in talking about bugs, I don't know a single codebase in ots community that has test coverage. Pointing fingers in those conditions is just pointless, every code written inside OTS community will have bugs until we learn that tests are a must have. If someone is not doing anything to change that - moving us to a more test driven scenario - and keeps saying that a code x or y is bugged, then this person is just acting in bad faith to diminish others.
> > 
> > 
> > You're not pointing fingers when you come in here and call me a "toxic nobody clown monkey that should go back to his cage", just because I told him I fixed this issue myself (after I was tired of his lies) and didn't release it - just like he said he won't release it for free either? That's all it takes for you to get triggered and start hurling insults at somebody?
> 
> I'm just responding in the same level you've been talking here, if you wanna talk serious we talk serious, but so far you've been mumbling about Mehah's not having full time for your needs. I won't waste my time with a serious discussion with someone that is just interested in offending and reduce other's contributions.

Brah, you're the one that came in and called me a toxic nobody clown monkey that should go back to his cage.
I called you all of those things back, but except for that, I haven't insulted anyone in here.
I called mehah a liar because it's the truth, he's lying to me over and over again in this thread.

> I never used the word monkey btw, that's on you.

It's 100% implied. What other animal would I be? I can't fit into a "little cage" as a human, so what am I, um gato?
You can dogwhistle and become a liar just like mehah all you want, but it's very clear what the implication are, just like I can say your physical looks reminds me of dogshit, I didn't say anything about the color of your skin, but it's clearly implied.

**Comment by lgrossi** [comment]
> > > > Thanks @scopz for your input, that's the kind of attitude I'd like to see more, bringing value not to criticise and point fingers.. People insist in talking about bugs, I don't know a single codebase in ots community that has test coverage. Pointing fingers in those conditions is just pointless, every code written inside OTS community will have bugs until we learn that tests are a must have. If someone is not doing anything to change that - moving us to a more test driven scenario - and keeps saying that a code x or y is bugged, then this person is just acting in bad faith to diminish others.
> > > 
> > > 
> > > You're not pointing fingers when you come in here and call me a "toxic nobody clown monkey that should go back to his cage", just because I told him I fixed this issue myself (after I was tired of his lies) and didn't release it - just like he said he won't release it for free either? That's all it takes for you to get triggered and start hurling insults at somebody?
> > 
> > 
> > I'm just responding in the same level you've been talking here, if you wanna talk serious we talk serious, but so far you've been mumbling about Mehah's not having full time for your needs. I won't waste my time with a serious discussion with someone that is just interested in offending and reduce other's contributions.
> 
> Brah, you're the one that came in and called me a toxic nobody clown monkey that should go back to his cage. I called you all of those things back, but except for that, I haven't insulted anyone in here. I called mehah a liar because it's the truth, he's lying to me over and over again in this thread.
> 
> > I never used the word monkey btw, that's on you.
> 
> It's 100% implied. What other animal would I be? I can't fit into a "little cage" as a human, so what am I, um gato? You can dogwhistle and become a liar just like mehah all you want, but it's very clear what the implication are, just like I can say your physical looks reminds me of dogshit, I didn't say anything about the color of your skin, but it's clearly implied.

'Please stop barking without making sense and get back to your lil cage' That's what I said. I'm explicitly calling you a dog (a creature that barks), since you're here barking for attention for days and your profile picture is a fucking dog, don't try get any other assumptions from your head other than this one.. You're causing troubles here treating Mehah as your worker or servant since the start. He pointed out that you could use his client, that doesn't make you the owner of his time.

That said, I'm leaving this thread, see ya.

**Comment by Source61** [comment]
> > It's 100% implied. What other animal would I be? I can't fit into a "little cage" as a human, so what am I, um gato? You can dogwhistle and become a liar just like mehah all you want, but it's very clear what the implication are, just like I can say your physical looks reminds me of dogshit, I didn't say anything about the color of your skin, but it's clearly implied.
> 
> 'Please stop barking without making sense and get back to your lil cage' That's what I said. I'm explicitly calling you a dog (a creature that barks), since you're here barking for attention for days and your profile picture is a fucking dog, don't try get any other assumptions from your head other than this one.. You're causing troubles here treating Mehah as your worker or servant since the start. He pointed out that you could use his client, that doesn't make you the owner of his time.
> 
> That said, I'm leaving this thread, see ya.

This is the definition of toxic, you take no responsibility for anything you say and just keep hurling insults and is uninterested in discussion any facts that contradicts your prejudice.
It's just as dehumanizing to call someone a dog as it is to call someone a monkey, and just as much of an insult.

Bye, don't come back, nobody here is interested in your prejudice and list of insults you hurl at anyone that triggers your sorry fragile little ass.

And btw, you look like a weirdo pedophile too.

**Comment by lgrossi** [comment]
> > > It's 100% implied. What other animal would I be? I can't fit into a "little cage" as a human, so what am I, um gato? You can dogwhistle and become a liar just like mehah all you want, but it's very clear what the implication are, just like I can say your physical looks reminds me of dogshit, I didn't say anything about the color of your skin, but it's clearly implied.
> > 
> > 
> > 'Please stop barking without making sense and get back to your lil cage' That's what I said. I'm explicitly calling you a dog (a creature that barks), since you're here barking for attention for days and your profile picture is a fucking dog, don't try get any other assumptions from your head other than this one.. You're causing troubles here treating Mehah as your worker or servant since the start. He pointed out that you could use his client, that doesn't make you the owner of his time.
> > That said, I'm leaving this thread, see ya.
> 
> This is the definition of toxic, you take no responsibility for anything you say and just keep hurling insults and is uninterested in discussion any facts that contradicts your prejudice.
> 
> Bye, don't come back, you're not wanted here :)

Prejudice? Lol, you're the one using my country of origin as argument, xenophobia is definitely a prejudice.
I'm pretty sure I'm wanted in Mehah's repo, differently than you. 🤟

**Comment by Source61** [comment]
> Prejudice? Lol, you're the one using my country of origin as argument, xenophobia is definitely a prejudice. I'm pretty sure I'm wanted in Mehah's repo, differently than you. 🤟
1) I'm not, you called me a toxic clown nobody monkey that should go back to his cage, which btw is racist and xenophobic no matter where I come from.
All I did was tell you the truth back to you, that BRs like yourself are hated in the Open Tibia community, nobody likes you.
2) It's not xenophobic to dislike a group of people. I don't think you know what xenophobia even means, groups of people don't like each other for social and political reasons completely separate from xenophobia, and you're just making my case that BRs are really stupid and ignorant, not understanding basic geopolitical concepts.
3) It's not me that came up with this, it's the entire Open Tibia community. Nobody likes you and nobody likes the software you write, it's always riddled with bugs and crashes every 15 minutes, the only reason you won't hear this stuff on otland is because it's against the rules, but rest assured absolutely nobody likes you, you're famous for being toxic, which you demonstrated that in this comment section, stupid, lazy and obnoxious people.

Now go away back to your little cage and peel some bananas for the rest of the civilized world.

And also learn to clean your quotes and not to spam issues down with insults just because you're a triggered little monkey that can't behave himself or do anything useful with his pathetic pedophile monkey life.

**Comment by Source61** [comment]
I just want to re-iterate by saying thanks for the loving and very constructive criticism, obviously.

Thanks to this lovely very civilized feedback I've decided to publicly share what I really think about otclient1.0 after all of this time, that I highly recommend against supporting this project financially or otherwise.
I will obviously not share any more bug reports or bug fixes either and regret having done so in the past, this project deserves no support by anyone (toxic BRs feel free to support it, you're only going to break the project and make it even worse anyways :))

Cheers 👋

**Comment by oarsc** [comment]
I'm locking this conversation, as it looks it's going nowhere...

**Comment by mehah** [comment]
@Source61 

well, I will not extend, but I will make two notes.

1- I'm rewriting the otclient, so...
2- All my tests are with opengl, I don't even waste my time with directX (So that's it, I was right).

**Comment by mehah** [comment]
done, satisfied now?! @Source61
