### ISSUE TITLE
Items not sitting on top of counter

### ISSUE THREAD

**Issue by Deadsmelly** [opentibiabr/otclient#2]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Add PR #1 
2. Login, look at items in default canary map in depot.

### Expected behaviour

Items should sit on top of counter

### Actual behaviour

Items are merging with counter

### Environment

12.85 OTClient PR #1 
![image](https://user-images.githubusercontent.com/85965963/158282340-dc8ea5a2-3e48-4428-b47d-bd0d1f0d2500.png)

**Comment by MajestyOTBR** [comment]
Thanks for your report.
