### ISSUE TITLE
Cannot use Machete on Jungle Grass

### ISSUE THREAD

**Issue by ericlancebrown** [opentibiabr/otclient#20]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Log in and go to Jungle Grass with a Machete
2. Try to click on machete and use it on Jungle Grass
3. Realize you can't.

### Expected behaviour
To cut the jungle grass.

### Actual behaviour
"You cannot use this object" error.

### Environment
Client Version: Latest
OS: Windows 10
Compiler: Visual Studio 2019

**Comment by andersonfaaria** [comment]
I think the use With is aiming for the ground below and not for the grass that's on top. Perhaps something related to changes done on the 'onUse' function regarding the on top item that should be used.

**Comment by ericlancebrown** [comment]
> I think the use With is aiming for the ground below and not for the grass that's on top. Perhaps something related to changes done on the 'onUse' function regarding the on top item that should be used.

It could possibly be because of the commit fixing the issue where you can't use AoE runes on the ground.
[fixed rune on the ground](https://github.com/mehah/otclient/commit/1a96aa09b3636551a776b7f3c369dfb395335eab)
