### ISSUE TITLE
(Question) Flip/Mirror image OpenGL

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#200]
How do i flip/mirror a image?

**Rotate works with:**
g_painter->saveAndResetState();
g_painter->rotate(dest.x, dest.y, 180);
Draw();
g_painter->restoreSavedState();

But do not understand how to do flip. Have googled and read a lot but it does not work

**Comment by mehah** [comment]
you can try like this:

g_painter->pushTransformMatrix();
g_painter->rotate(dest.x, dest.y, 180);
g_drawPool.add...
g_painter->popTransformMatrix();

**Comment by Klonoa88** [comment]
Solved it with:

g_painter->pushTransformMatrix();

g_painter->translate(-dest);
g_painter->scale(1, -1);
g_painter->rotate(-1.60f);
g_painter->translate(dest);

g_drawPool.add...

g_painter->popTransformMatrix();
