### ISSUE TITLE
Skills window collapses and bugs out if not initialized on login

### ISSUE THREAD

**Issue by Znote** [opentibiabr/otclient#203]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Login to a character, make sure to hide the skills window
2. Logout and login the character
3. Open the skills window
4. Try to adjust the height of the skills window

### Expected behaviour
Adjusting the height of the skills window should smoothly resize the window

### Actual behaviour
Window collapses and gets stuck until you perform another relog
![skillscollapse1](https://user-images.githubusercontent.com/1552144/151725524-3b08021a-2f4e-4584-8f62-312138dde8fd.gif)

### Environment
https://github.com/mehah/otclient/commit/48790a61e237d14c46a78848942d3d6c10bfe717
Windows 10

Note: The commit hash is related to skills window, but I have had this issue for a long time (etc v1.3, 1.4). But it got worse now.

**Comment by oarsc** [comment]
Could you check it now?

**Comment by Znote** [comment]
Works great, thanks. 💯
