### ISSUE TITLE
Still bugged... | Pathfind changes to algorithm Dijkstra

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#205]
The system still needs improvement, I have already added something to PR but there is still a problem, you click on some wall on the map/minmap (uncovered) and the system tries to climb it. Normally you should get a message that there is no way in (the character does not try to go) 

**Fix to click on map:** 
Before this line: 
https://github.com/mehah/otclient/blob/48790a61e237d14c46a78848942d3d6c10bfe717/modules/game_interface/gameinterface.lua#L915
add:
>     local autoWalkTile = g_map.getTile(autoWalkPos)
>     if autoWalkTile and not autoWalkTile:isWalkable(false) then
> 		modules.game_textmessage.displayFailureMessage(tr('There is no way.'))
> 		return false
>     end

with minimap you probably have to dig in source files, if I find something I will add it to PR

**Comment by poxis** [comment]
it seems to work, but I don't know if there aren't other consequences: (fix: click on a wall on the minimap and the character tries to got it (or walk towards it) )
https://github.com/mehah/otclient/blob/48790a61e237d14c46a78848942d3d6c10bfe717/src/client/map.cpp#L980

(from old version)- This fix work on minimap and click on map (instead of changes in  gameinterface.lua )

>    // check the goal pos is walkable
>     if (g_map.isAwareOfPosition(goal)) {
>         const TilePtr goalTile = getTile(goal);
>         if (!goalTile || (!goalTile->isWalkable())) {
>             return ret;
>         }
>     }
>     else {
>         const MinimapTile& goalTile = g_minimap.getTile(goal);
>         if (goalTile.hasFlag(MinimapTileNotWalkable)) {
>             return ret;
>         }
>     }

**Comment by mehah** [comment]
news?
