### ISSUE TITLE
Squirrels Cause Weird Crash and Move Sideways

### ISSUE THREAD

**Issue by ericlancebrown** [opentibiabr/otclient#21]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Log in and summon a squirrel.
2. Attempt to see the squirrel in game with a non-admin character.
3. The Squirrel is moving sideways and the game crashes instantly.

### Expected behaviour
Not to crash when you see a squirrel. Also, to see the squirrel running normally and not sideways.

### Actual behaviour
Squirrel moves erratically in a sideways direction and then the game crashes.

### Environment
Client Version: Latest
TFS: 1.3 Latest
OS: Windows 10
Compiler: Visual Studio 2019

### OTClient Log
[otclient.log](https://github.com/mehah/otclient/files/4944582/otclient.log)

**Comment by andersonfaaria** [comment]
This happens with "Squirrel", "Cobra" and "Minotaur Guard" and it has to do on how those monsters are configured in the spr and dat file.

I've worked around it by making changes on my .dat file but otc definetely should have this fixed 'source side'
