### ISSUE TITLE
error console

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#215]
official tfs and official otclient meh. otclient 1.0 12.81
version without modification

errors immediately after logging in. all functions are working
https://prntscr.com/26o9ad7

**Comment by oarsc** [comment]
Version?
Is the server modified?
What did you do when you received this message?
We need more details...

**Comment by oarsc** [comment]
Are you using the 1.0 version?
Try the latest one:
https://github.com/mehah/otclient/releases/tag/1.4.2

**Comment by nekiro** [comment]
> official tfs and official otclient meh. otclient 1.0 12.81 version without modification
> 
> errors immediately after logging in. all functions are working https://prntscr.com/26o9ad7

Yes, this is a common problem, there is missing classification attribute, use my protobuf pr, it will fix your issues.

**Comment by oarsc** [comment]
The protobuf PR @nekiro mentioned is already in the main branch.
I'm closing it due to a lack of answer.
