### ISSUE TITLE
Compilation error using Docker 

### ISSUE THREAD

**Issue by xWeaver** [opentibiabr/otclient#22]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Try to run "docker build -t opentibiabr/otclient ."

### Expected behaviour

Normal build

### Actual behaviour

 > [builder 15/18] RUN cmake -DCMAKE_CXX_LINK_FLAGS=-no-pie -DCMAKE_BUILD_TYPE=Release ..:
#20 0.321 -- The C compiler identification is GNU 7.5.0
#20 0.392 -- The CXX compiler identification is GNU 7.5.0
#20 0.400 -- Check for working C compiler: /usr/bin/cc
#20 0.460 -- Check for working C compiler: /usr/bin/cc -- works
#20 0.462 -- Detecting C compiler ABI info
#20 0.521 -- Detecting C compiler ABI info - done
#20 0.539 -- Detecting C compile features
#20 0.540 -- Detecting C compile features - done
#20 0.543 -- Check for working CXX compiler: /usr/bin/c++
#20 0.611 -- Check for working CXX compiler: /usr/bin/c++ -- works
#20 0.613 -- Detecting CXX compiler ABI info
#20 0.687 -- Detecting CXX compiler ABI info - done
#20 0.706 -- Detecting CXX compile features
#20 0.707 -- Detecting CXX compile features - done
#20 0.708 CMake Error at CMakeLists.txt:39 (include):
#20 0.708   include could not find load file:
#20 0.708 
#20 0.708     MessageColors
#20 0.708 
#20 0.708 
#20 0.708 CMake Error at CMakeLists.txt:40 (include):
#20 0.708   include could not find load file:
#20 0.708 
#20 0.708     LoggingHelper
#20 0.708 
#20 0.708 
#20 0.708 CMake Error at CMakeLists.txt:71 (log_option_enabled):
#20 0.708   Unknown CMake command "log_option_enabled".
#20 0.708 
#20 0.708 
#20 0.709 -- Configuring incomplete, errors occurred!
#20 0.709 See also "/otclient/build/CMakeFiles/CMakeOutput.log".
------
executor failed running [/bin/sh -c cmake -DCMAKE_CXX_LINK_FLAGS=-no-pie -DCMAKE_BUILD_TYPE=Release ..]: exit code: 1

### Environment
<!-- Please tell which client version are you using (E.g 10.98 OTClient 0.6.6)

**Comment by MajestyOTBR** [comment]
https://github.com/opentibiabr/otclient/commit/da21429e936feeeeeba367b32834a78274a6ed45

**Comment by MajestyOTBR** [comment]
https://github.com/opentibiabr/otclient/blob/develop/Dockerfile
