### ISSUE TITLE
 Encryption procedure does not work

### ISSUE THREAD

**Issue by LeoMarques101** [opentibiabr/otclient#223]
### Steps to reproduce (include any configuration/script required to reproduce)
Encryption procedure

### Expected behaviour
Encryption

### Actual behaviour
nothing change, and the client cant recognize tibia dat file

### Environment
Windows

**Comment by Mrpox** [comment]
Just tested, works with latest build.

Make sure you compile and encrypt with same password.

**Comment by LeoMarques101** [comment]
> Just tested, works with latest build.
> 
> Make sure you compile and encrypt with same password.

works fine in latest build.
