### ISSUE TITLE
Compiling on Arch Linux

### ISSUE THREAD

**Issue by ivopr** [opentibiabr/otclient#224]
We've got to install more things in order to make it work, a wiki page containing the following would be nice. Thanks for the work.

```
sudo pacman -Syu && sudo pacman -S base-devel git cmake boost physfs openssl lua51 glew libvorbis openal zlib libogg nlohmann-json protobuf
```

Get the sources, compile and run

```sh
git clone git://github.com/mehah/otclient.git
cd otclient/src/framework/protobuf/proto/
./generate.sh
cd ../../../../
cmake . -B build
make build -j$((`nproc` + 1))
./build/otclient
```

**Comment by scopz** [comment]
> We've got to install more things in order to make it work, a wiki page containing the following would be nice. Thanks for the work.
> 
> ```
> sudo pacman -Syu && sudo pacman -S base-devel git cmake boost physfs openssl lua51 glew libvorbis openal zlib libogg nlohmann-json protobuf
> ```
> 
> Get the sources, compile and run
> 
> ```shell
> git clone git://github.com/mehah/otclient.git
> cd otclient/src/framework/protobuf/proto/
> ./generate.sh
> cd ../../../../
> cmake . -B build
> make build -j$((`nproc` + 1))
> ./build/otclient
> ```

**Comment by oarsc** [comment]
Sorry, missclick 😂 

Added a wiki page with this info:
https://github.com/mehah/otclient/wiki/Compiling-on-Arch-Linux

If there is something else that you think must be added, just write it here, or send us a .md file and we'll add it.

Thanks!

**Comment by ivopr** [comment]
hey, @scopz, i've found out more about arch in general, and there are some additions that can improve these docs.
Appending `--needed` to the `pacman` command, so it'll skip packages that are already installed (the default behavior is to have them reinstalled). Add the `yu` options, making it just one command instead of two: 
`sudo pacman -Syu base-devel git cmake boost physfs openssl lua51 glew libvorbis openal zlib libogg nlohmann-json protobuf --needed`
And also there's an error in the make command that I didn't realize until now, the correct is `make -c build` instead of `make build`.

**Comment by oarsc** [comment]
Updated. Check if it's ok now.
Thank you @ivopr
