### ISSUE TITLE
Create your own WIKI and update it.

### ISSUE THREAD

**Issue by Vysius** [opentibiabr/otclient#225]
Hi there!
I'm just creating this issue ticket to addreess you the information that the WIKI is not longer synchronized with your current project.
I think you shoiuld create a WIKI in this repository and update the Edubart one so the libraries for openssl and protobuff are added to the lib instalation string, or at least mentioned.

Good job everyone contributing!

**Comment by mehah** [comment]
it was already done, all that was missing was the openssl lib

https://github.com/mehah/otclient/wiki/Compiling-on-Windows
