### ISSUE TITLE
Glitch on change speed

### ISSUE THREAD

**Issue by nok1111** [opentibiabr/otclient#227]
### Steps to reproduce 
1.change creature/player speed via lua or any other similar ways
2.creature get speed from player (mostly summons)

### Expected behaviour
Creature reproduce necesary steps and reach the target or keep walking

### Actual behaviour
Player / creature disappers from sight or stuck walking on same place

### Environment
1098

Gif:

https://hnet.com/video-to-gif/viewimage/20220209-12-M9EHyryPhSEdey7r-ksbCDd-HNET

![move error](https://user-images.githubusercontent.com/35547755/153315008-f5b7707a-95c5-4566-9429-bf6a58eedabf.png)

**Comment by mehah** [comment]
otc version/revision?

**Comment by nok1111** [comment]
1.4.2 release

tried with this changes:

https://github.com/mehah/otclient/commit/d97e6bb24d9c2a58e6ba756be46522dff7ef91c0

https://github.com/mehah/otclient/commit/aa223562a3e22640385e2472d9b382f12ed4a787

https://github.com/mehah/otclient/commit/54e52ab25f10d0cef1c30bf22914b1ed1d7ba081

https://github.com/mehah/otclient/commit/8868b7ec98d0cc52c3c4f2b4cd3eb714cd799c47

**Comment by mehah** [comment]
I need the tests to be done at the last customer review.

**Comment by nok1111** [comment]
Tested with latest commit

calling movements via lua (spells)
player:move()  
brings this into console
![image](https://user-images.githubusercontent.com/35547755/154784524-dd2025a9-1f71-4407-82ad-30f3e6ca0244.png)

_____________________________________________________________
now changing speed via lua
creature:changeSpeed(***)   brings this into console
ERROR: ProtocolGame parse message exception (144 bytes unread, last opcode is 59, prev opcode is 140): unhandled opcode 59
_____________________________________________________________
a mix of both glitch the player or creature entirely
using 10.98 btw

**Comment by mehah** [comment]
I just tested it and it works perfectly

[Client]
Method: parseCreatureSpeed
![image](https://user-images.githubusercontent.com/2267386/155443475-d3b9f262-b15d-42cd-8b55-04cb05fb0530.png)

[Server]
Method: sendChangeSpeed
![image](https://user-images.githubusercontent.com/2267386/155443701-f497d74a-c72d-4f19-a1cd-56c55ecbd783.png)

the order and quantity of packets sent by the server is the same as received by the client.

**Comment by mehah** [comment]
Since I didn't get any response, I'll close it.
