### ISSUE TITLE
glitches in light

### ISSUE THREAD

**Issue by LeoMarques101** [opentibiabr/otclient#228]
### Steps to reproduce (include any configuration/script required to reproduce)
Nothing

### Expected behaviour
for example otclientv8:
![otclientV8_1](https://user-images.githubusercontent.com/68972500/153664361-10b1f20e-97ff-42cf-81a5-32c5dfe79f93.JPG)
![otclientV8_2](https://user-images.githubusercontent.com/68972500/153664373-3f9957ee-8f53-4b75-934e-f60860d332ba.JPG)
![otclientV8_3](https://user-images.githubusercontent.com/68972500/153664378-fd5ef531-f9d2-4003-851b-02e80a93fc1a.JPG)

### Actual behaviour
glitches in otclient:
![otclient_1](https://user-images.githubusercontent.com/68972500/153664413-addd8dda-7c20-412a-86f2-fc59257b6561.JPG)
![otclient_2](https://user-images.githubusercontent.com/68972500/153664417-c0498afd-b5c5-4337-b810-1e0ca2924fc9.JPG)
![otclient_3](https://user-images.githubusercontent.com/68972500/153664424-e8bd1ac7-3028-430e-a77f-b56fd468ef5f.JPG)

### Environment
Tibia 8.6

**Comment by mehah** [comment]
the shades are being rewritten

![image](https://user-images.githubusercontent.com/2267386/153979755-f9fae6a3-6cf8-44a0-a365-6270041317d3.png)
![image](https://user-images.githubusercontent.com/2267386/153979785-28558077-99b5-464f-8792-7bbb832b9fd7.png)
![image](https://user-images.githubusercontent.com/2267386/153979865-3f2787c9-9075-4c0b-a68e-042cae675b1f.png)
![image](https://user-images.githubusercontent.com/2267386/153980404-e0de9381-c241-49f0-a4e1-f67dc6b8fefc.png)
![image](https://user-images.githubusercontent.com/2267386/153980557-e3b3afec-949a-4236-abe8-4bd52ca52111.png)

**Comment by LeoMarques101** [comment]
look nice !

**Comment by mehah** [comment]
test now

**Comment by mehah** [comment]
@LeoMarques101?

**Comment by LeoMarques101** [comment]
![test1](https://user-images.githubusercontent.com/68972500/155617207-c5d76c86-5b3f-432f-8591-18b189830c3b.JPG)
![test2](https://user-images.githubusercontent.com/68972500/155617223-d1365e37-8198-4f63-8fc2-08b68061e596.JPG)

it's better , but the options are not working correct

**Comment by mehah** [comment]
Qual opção, a intensidade da luz, se for, aqui está funcionando perfeitamente, você mesclou ou simplesmente atualizou?

Uploading Otclient 2022-02-24 20-07-38-1.mp4…

**Comment by mehah** [comment]
Qual opção, a intensidade da luz, se for, aqui está funcionando perfeitamente, você mesclou ou simplesmente atualizou?

https://user-images.githubusercontent.com/2267386/155623049-3eec629e-559d-42bd-bd84-f71cb1e583e4.mp4

**Comment by LeoMarques101** [comment]
por algum motivo no meu não esta correto , vou compilar com a ultima versão e testar
