### ISSUE TITLE
otclient error console

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#229]
tfs 1.5 12.81  (13.02.2022.  20:54)
otclient mehah  (13.02.2022.  20:54) 

at the entrance to change clothes
https://prnt.sc/26v78yz

the same errors pop up when I change my appearance

**Comment by nekiro** [comment]
Fixed in https://github.com/mehah/otclient/commit/9fb30950762ec1b0372f8672f8ffdbba8d08e970
