### ISSUE TITLE
Player Runs in Place After Moving in a Quick Diagonal Pattern

### ISSUE THREAD

**Issue by ericlancebrown** [opentibiabr/otclient#23]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Move in a diagonal pattern through bushes, trees, etc. in fast succession.
2. Try to move forward.
3. Your player gets stuck and seems to run in place.

### Expected behaviour
You should be able to fluidly move through the diagonal pattern, then move forward without moonwalking.

### Actual behaviour
You move through the diagonal pattern fluidly, but moonwalk when you move forward.
Video here: [OTClient Bug - Diagonal Pattern Moonwalk](https://vimeo.com/442585811)

### Environment
OTClient: Latest/Mehah
TFS: Latest
OS: Windows 10 / Ubuntu 20.4
Compiler: Visual Studio 2019 / make 4.2.1

**Comment by mehah** [comment]
could test this correction, for me is ok.

**Comment by ericlancebrown** [comment]
> could test this correction, for me is ok.

Seems that the walking part of it is fixed, but when I do the exact same action as before, I am now moving on top of trees, bushes, etc. lol
I made a video here: [OTClient Bug - Diagonal Pattern Moonwalk 2](https://vimeo.com/442778702)

**Comment by mehah** [comment]
and now?

**Comment by ericlancebrown** [comment]
> and now?

Works perfect! I'll close this now. Going to be looking for more bugs.
