### ISSUE TITLE
possibly a light error

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#231]
tfs 1.5 12.81
otclient meh  latest 12.81

before going upstairs
https://prnt.sc/26xzlks

after going upstairs
https://prnt.sc/26xzoqk

**character GM**

before going upstairs
https://prnt.sc/26xzpiy

after going upstairs
https://prnt.sc/26xzt63

**Comment by mehah** [comment]
sry, but I didn't understand.

**Comment by mehah** [comment]
test now with new shading

**Comment by wmaestrots** [comment]
U have probably Floor Shading in Options.
When floor shading is mixed with darkness from game it's completely dark :)

**Comment by mehah** [comment]
I will close in the future if there is no response.
