### ISSUE TITLE
the skill bar does not show progress

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#232]
tfs 1.5 12.81
otclient meh  latest 12.81

the skill bar does not show progress
https://prnt.sc/26xzwsx

**Comment by mehah** [comment]
to my knowledge there is no full support for 12.xx

**Comment by nekiro** [comment]
which skill is that?

**Comment by daniofordon** [comment]
> which skill is that?

all skills are bugged with the magic level

**Comment by nekiro** [comment]
Fixed in https://github.com/mehah/otclient/commit/6243a0ca465e08a365e98f39e563c6e88f4a2ec7
