### ISSUE TITLE
Lightning in ramps

### ISSUE THREAD

**Issue by oarsc** [opentibiabr/otclient#236]
Not sure if intended, but lightning from inside the rooms are visible through ramps in pyramids:
![image](https://user-images.githubusercontent.com/5507777/155227103-d707a65c-7aac-444a-85ce-7206fe5b9088.png)

**Comment by mehah** [comment]
the light behavior does not predict wall blocking and this "problem" also occurs in the cipsoft client.

![image](https://user-images.githubusercontent.com/2267386/155416282-99f1f0ce-4786-4538-b63c-f1e9b2f4c49a.png)
![image](https://user-images.githubusercontent.com/2267386/155416475-333f74f4-fbf8-4b46-9e43-ce4614540a8d.png)
![image](https://user-images.githubusercontent.com/2267386/155416581-3ebcadba-2fc4-4575-9386-7a9686cc83c3.png)

**Comment by oarsc** [comment]
Ok, I guess it's ok like this then
