### ISSUE TITLE
Otclient in Raspberry pi

### ISSUE THREAD

**Issue by LeoMarques101** [opentibiabr/otclient#239]
### Steps to reproduce (include any configuration/script required to reproduce)
Try to compile in the Raspberry pi OS

### Expected behaviour
Success

### Actual behaviour
Impossible to Compile

[Pt-br]
Apos tentar compilar no Raspberry pi OS, tive varios erros e apos pesquisar um pouco verifiquei que trata-se de um problema na arquitetura ARM, aparentemente o otclient não está configurado para este tipo de arquitetura.

Acho que seria uma otima adição incluir a possibilidade de compilar em um Raspberry pi.

**Comment by mehah** [comment]
for now this idea will be shelved, hardly anyone will use raspberry to run OTClient.
