### ISSUE TITLE
the text goes outside the box

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#241]
the text goes outside the box

https://prnt.sc/0FBMaaPm72Ls

**Comment by Mixlort** [comment]
https://github.com/mehah/otclient/pull/217/commits/64114c9bcb0c0ad3e141bdf1c56d3bf39374f5e5

**Comment by oarsc** [comment]
It should have been fixed in #217, and it's in the `main` branch already.
Which version of otclient are you using?

**Comment by oarsc** [comment]
I'm closing it due to the lack of info
