### ISSUE TITLE
because you kill a monster no body still shows itself as alive. and cannot be attacked again

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#242]
because you kill a monster no body still shows itself as alive. and cannot be attacked again

https://prnt.sc/LPZtV4MbAbXO
https://prnt.sc/2wYKY09ar1C0

after a while the monster's bodies disappear

https://prnt.sc/-Cc_F_8lprfa

console error

https://prnt.sc/bj00MDbd7-64

**Comment by daniofordon** [comment]
this only happens on spiders

**Comment by nekiro** [comment]
No errors here on protocol 12.x. What server are you using?
This doesn't seem to be client issue.
