### ISSUE TITLE
Error compiling with VCPKG

### ISSUE THREAD

**Issue by luanluciano93** [opentibiabr/otclient#244]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Compiling release 2.0b with Visual Studio 2022 using VCPKG in release x64

### Error
Error C1189 #error:  This file was generated by an older version of protoc which is (compiling source file ..\src\client\thingtypemanager.cpp) otclient C:\Users\...s\otclient-2.0b\otclient-2.0b\src\framework\protobuf\appearances.pb.h	17	

Error C1189 #error:  This file was generated by an older version of protoc which is (compiling source file ..\src\client\spriteappearances.cpp) otclient C:\Users\...\otclient-2.0b\otclient-2.0b\src\framework\protobuf\appearances.pb.h 17	

my protobuf version is "protocolbuffers-protobuf-v3.19.4.tar"

**Comment by mehah** [comment]
here it is working normal, I downloaded the source manually by git, (CODE) -> DOWNLOAD ZIP

![image](https://user-images.githubusercontent.com/2267386/158889489-d9a6569c-ec23-4fc9-9ab5-d528b84cc29d.png)

**Comment by luanluciano93** [comment]
- plied user-wide integration for this vcpkg root.

- ckage 7zip:x64-windows is already installed
- Package boost-asio:x64-windows is already installed
- Package boost-filesystem:x64-windows is already installed
- Package boost-iostreams:x64-windows is already installed
- Package boost-lockfree:x64-windows is already installed
- Package boost-system:x64-windows is already installed
- Package boost-uuid:x64-windows is already installed
- Package boost-variant:x64-windows is already installed
- Package glew:x64-windows is already installed
- Package libogg:x64-windows is already installed
- Package libvorbis:x64-windows is already installed
- Package luajit:x64-windows is already installed
- Package nlohmann-json:x64-windows is already installed
- Package openal-soft:x64-windows is already installed
- Package opengl:x64-windows is already installed
- Package openssl:x64-windows is already installed
- Package physfs:x64-windows is already installed
- Package protobuf:x64-windows is already installed
- Package zlib:x64-windows is already installed

**Comment by Mrpox** [comment]
You need to run the generate.bat thats located here:
..\src\framework\protobuf\proto

Best is to first move protoc.exe from vcpkg folder to ..\src\framework\protobuf\proto
Which would be located here:
[Path to VCPKG}\installed\x64-windows\tools\protobuf

**Comment by luanluciano93** [comment]
@Mrpox It worked my friend, thank you very much

**Comment by Juanzin93** [comment]
> You need to run the generate.bat thats located here: ..\src\framework\protobuf\proto
> 
> Best is to first move protoc.exe from vcpkg folder to ..\src\framework\protobuf\proto Which would be located here: [Path to VCPKG}\installed\x64-windows\tools\protobuf

this completely f'ed up my vs 
Error	MSB3073	The command "
	set size=0
	for /f %%i in ("../src/protobuf/appearances.pb.cc") do set size=%%~zi
	if %size% EQU 0 (
		cmd /c "D:\vcpkg\installed\x64-windows\tools\protobuf\protoc" --cpp_out=../src/protobuf/ --proto_path=../src/protobuf/ appearances.proto
	)
	  
:VCEnd" exited with code 255.	otclient	D:\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	147
