### ISSUE TITLE
disappearing tiles at the bottom of the screen

### ISSUE THREAD

**Issue by bulawow** [opentibiabr/otclient#25]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Just login and walk

### Expected behaviour
https://gyazo.com/a2d56e7fc8a2eb6ae09f4fce5ae27c4c (using edubart otclient)

### Actual behaviour
https://gyazo.com/3e6ae7650a5ddcee8ea92d7ff0ac21e3  (using otclient 1.0)

### Environment
Using latest otclient 1.0 

Edit:
I know what is causing this if the crop is setted up this way its happening but after resizing the crop to match the sprite its getting fixed, its not happening in edubard otclient so im staying in my report that this is a bug
Gyazo (https://gyazo.com/959edb2f9e730928fa22d80efaabc0bb) (wrong crop size, bug happends)
Gyazo (https://gyazo.com/a5149c62dc6dade1be9ad50030ec4579) (correct crop, bug getting fixed)

**Comment by mehah** [comment]
this is not a bug, just an algorithm to inhibit tiles that are not visible on your screen, based on cropping the image.

if this is bothering you, just remove this line:
https://github.com/mehah/otclient/blob/67c0ff2985cc5e9b13aadf3425dd98272c50f7c4/src/client/mapview.cpp#L129
