### ISSUE TITLE
beach border animation bug

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otclient#258]
![image](https://user-images.githubusercontent.com/64820180/162562126-3a5fd7bb-0dab-4890-844c-efaf9b0996bf.png)
![image](https://user-images.githubusercontent.com/64820180/162562139-8046539a-9637-4ba6-8485-baeac0e3ef20.png)

**Comment by wmaestrots** [comment]
Make sure you have in your Object Builder good properties set for those borders, this is important:
![image](https://i.imgur.com/UYuAxKE.png)
Have to be set as Synchronous and Start frame : first, same as other animated items.

**Comment by Juanzin93** [comment]
> Make sure you have in your Object Builder good properties set for those borders, this is important: ![image](https://camo.githubusercontent.com/b747eeed56dc9be662fee7cd65309b60b4566a3f00aa99a7fcd23777f295ddc4/68747470733a2f2f692e696d6775722e636f6d2f55597541784b452e706e67) Have to be set as Synchronous and Start frame : first, same as other animated items.

version 12.85 does not support dat/spr, must be a version issue with the assets

**Comment by nekiro** [comment]
> > Make sure you have in your Object Builder good properties set for those borders, this is important: ![image](https://camo.githubusercontent.com/b747eeed56dc9be662fee7cd65309b60b4566a3f00aa99a7fcd23777f295ddc4/68747470733a2f2f692e696d6775722e636f6d2f55597541784b452e706e67) Have to be set as Synchronous and Start frame : first, same as other animated items.
> 
> version 12.85 does not support dat/spr, must be a version issue with the assets

Then state this in the issue next time, how do we know what you use if otc supports so many protocols?
Your borders are completely fucked up, give us the map you use (or at least item ids), cant test otherwise, on tfs map all works fine, so might be problem with your map or even items.otb.

**Comment by mehah** [comment]
well, as there hasn't been a response for a long time, I'll close this issue.
