### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#259]
Hello. unable to compile otclient after recent updates. such errors pop up.

https://prnt.sc/6meYggMVkEsa

**Comment by beats-dh** [comment]
> Hello. unable to compile otclient after recent updates. such errors pop up.
> 
> https://prnt.sc/6meYggMVkEsa

The lib asio is missing.

**Comment by beats-dh** [comment]
Follow the tutorial: https://github.com/mehah/otclient/wiki/Compiling-on-Windows
