### ISSUE TITLE
client crash (when tryign to walk when ur looktype dont have animation)

### ISSUE THREAD

**Issue by bulawow** [opentibiabr/otclient#26]
### Steps to reproduce (include any configuration/script required to reproduce)
Im using spell that changes outfit with addevents and while during that i will try to move the client crashes

### Expected behaviour
shound not crash ;p

### Actual behaviour
crashing ;p

### Environment
otclient 1.0
There is the crash log https://pastebin.com/EWgJtRg2

**Comment by mehah** [comment]
your outfit has no animation?

**Comment by bulawow** [comment]
Yes the outfits that im swapping between have no animations
