### ISSUE TITLE
Action Bar bug

### ISSUE THREAD

**Issue by HenriqueMM2** [opentibiabr/otclient#261]
BR ->>> Encontrei um bug na actionbar onde um item colocado nela que contem mira, quando clica na action a mira aparece e some automaticamente, porém quando é setado algum hotkey funciona normalmente.

Como reproduzir o bug :
1. Coloque uma runa na action bar. (testei com avalanche)
2. Clique na runa pela actionbar
3. Assim o bug já é reproduzido, podemos notar que quando há o clique na runa, a mira aparece e já some automaticamente.

OBS: O bug só acontece quando o uso da runa é feito clicando diretamente na actionbar, se for selecionado uma hotkey para uso o bug não acontece.

Versão do cliente é 10.98
e servidor tfs 1.4

https://www.youtube.com/watch?v=hts-S72jUZ0

English ->>>

I found a bug in the actionbar where an item inserted in it contains crosshair, when you click on the action the crosshair appears and some automatically, but when a hotkey is defined it works normally.

How to manage the bug:
1. Place a rune in the action bar. (avalanche test)
2. Click on the action bar
3. As soon as the bug is already executed, we can notice that when the rune appears, the crosshair appears and already some automatically.

OBS: The bug only happens when the use of the rune is done by clicking directly on the actionbar, select to select a hotkey to use the bug does not happen.

Client version is 10.98
and tfs 1.4 server

**Comment by oarsc** [comment]
Test it now please :)
