### ISSUE TITLE
client compiled on Windows identifies as CLIENTOS_OTCLIENT_LINUX 

### ISSUE THREAD

**Issue by Zbizu** [opentibiabr/otclient#262]
**Protocol version**
12.86

**Describe the bug**
calling `for k, v in pairs(player)do print(k,v) end` returns client os "2" (Windows)
should return `CLIENTOS_OTCLIENT_WINDOWS`

if this is some hack to make otc work with version 12 servers, let me know where I can undo it to send client os otc again

**Comment by nekiro** [comment]
You are talking about this?
https://github.com/mehah/otclient/blob/main/src/client/game.cpp#L1726
https://github.com/mehah/otclient/blob/main/src/client/protocolgamesend.cpp#L56

Where does it return 2?

**Comment by Zbizu** [comment]
in `player:getClient()`, tfs
I'll test later with protocol to confirm

edit: for some reason it returned CLIENTOS_OTCLIENT_LINUX to me now, but I'm on Windows
(tested both in Lua and in `ProtocolGame::onRecvFirstMessage`)
```
16:00 [0]: > print(Player("administrator"):getClient().os)
16:00 [0]: 10
```
```
	OperatingSystem_t operatingSystem = static_cast<OperatingSystem_t>(msg.get<uint16_t>());
	std::cout << static_cast<int>(operatingSystem) << std::endl;
	// this printed 10
```

**Comment by nekiro** [comment]
Yeah, cause otc returns value 10 for windows os, which happens to be CLIENTOS_OTCLIENT_LINUX in tfs for some reason, who's wrong about that?
Edubart's version also does return 10 for windows os.
https://github.com/otland/forgottenserver/blob/master/src/enums.h#L150

**Comment by Zbizu** [comment]
looking at the pattern of constants, I'd say otc

**Comment by nekiro** [comment]
Otc doesnt even have a proper constants defined for these versions, lol. Gotta fix that
