### ISSUE TITLE
Encryption Bug 

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otclient#263]
**Protocol version**
10.98/12.x
772 - nekiro downgrade
**Describe the bug**
after encryption you can move anything on the game window(where player walks) , cant pick up or push items/people/mosnters

on otbr version 12.85 the assets dont load with encryption, the screen gets all black out
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mehah** [comment]
if your problem is with encryption in asserts, why do you mention 7.x?

**Comment by mehah** [comment]
well, as I didn't get an answer, I'll close it.
