### ISSUE TITLE
Missing handler for CREATURETYPE_HIDDEN

### ISSUE THREAD

**Issue by Zbizu** [opentibiabr/otclient#266]
**Protocol version**
12.x + older if they use CREATURETYPE_HIDDEN

**Describe the bug**
Monsters with CREATURETYPE_HIDDEN are not being displayed (errors in terminal)
The error message gets reported from this line:
https://github.com/mehah/otclient/blob/2e1019c1fab15d8c19ad77a450daff94e577aae9/src/client/protocolgameparse.cpp#L2564

**To Reproduce**

`/m flamethrower`

**Expected behavior**
![obraz](https://user-images.githubusercontent.com/5205079/165175865-d8f7d097-e68a-4b19-81a8-7ee61c05810e.png)

**Observerd behavior**
no summon, this in terminal:
![obraz](https://user-images.githubusercontent.com/5205079/165175921-e3b2242c-8ee8-414d-a621-56d75d912543.png)

**Possible workaround**
CREATURETYPE_HIDDEN = CREATURETYPE_MONSTER

**Comment by mehah** [comment]
try to change it on the line: https://github.com/mehah/otclient/blob/878337bea3f1e2a8770ff9019a1c8a30f8375f9a/src/client/protocolgameparse.cpp#L2548

```c++
if (creature) {
    creature->setName(name);
} else {
    if (id == m_localPlayer->getId())
        creature = m_localPlayer;
    else if (creatureType == Proto::CreatureTypePlayer) {
        // fixes a bug server side bug where GameInit is not sent and local player id is unknown
        if (m_localPlayer->getId() == 0 && name == m_localPlayer->getName())
            creature = m_localPlayer;
        else
            creature = PlayerPtr(new Player);
    } else if (creatureType == Proto::CreatureTypeMonster)
        creature = MonsterPtr(new Monster);
    else if (creatureType == Proto::CreatureTypeNpc)
        creature = NpcPtr(new Npc);
    else
        g_logger.traceError("creature type is invalid");
}
```

to

```c++
if (creature) {
    creature->setName(name);
} else if (id == m_localPlayer->getId() ||
           creatureType == Proto::CreatureTypePlayer && !m_localPlayer->getId() && name == m_localPlayer->getName())
    creature = m_localPlayer;
else switch (creatureType) {
    case Proto::CreatureTypePlayer:
        creature = PlayerPtr(new Player);
        break;

    case Proto::CreatureTypeNpc:
        creature = NpcPtr(new Npc);
        break;

    case Proto::CreatureTypeHidden:
    case Proto::CreatureTypeMonster:
    case Proto::CreatureTypeSummonOwn:
    case Proto::CreatureTypeSummonOther:
        creature = MonsterPtr(new Monster);
        break;

    default:
        g_logger.traceError("creature type is invalid");
}
```

I think that would solve other possible problems, could you test?

**Note: I'm not sure, but I don't think this is necessary:**  ``creatureType == Proto::CreatureTypePlayer && ``

**Comment by mehah** [comment]
@Zbizu ?

**Comment by Zbizu** [comment]
I forgot to test it. I'm doing too many things at once lately.

**Comment by Zbizu** [comment]
@mehah it works
only problem now is that summon emblem for others has wrong icon
![obraz](https://user-images.githubusercontent.com/5205079/166163062-2c09e6e3-ad74-4def-9062-6cd31787dcc2.png)

**Comment by mehah** [comment]
@Zbizu
and what would the icon be, do you have a sample?

**Comment by Zbizu** [comment]
`CreatureTypeSummonOther` and `CreatureTypeSummonOwn` (when masterId != localPlayer id) should have this icon ![obraz](https://user-images.githubusercontent.com/5205079/166239104-ca7adba2-35dc-41da-bc1e-175b3587332b.png)

**Comment by mehah** [comment]
@Zbizu 
from what I analyzed, the images are shown according to the ids sent by the server.

```lua
CreatureTypePlayer = 0
CreatureTypeMonster = 1
CreatureTypeNpc = 2
CreatureTypeSummonOwn = 3
CreatureTypeSummonOther = 4
CreatureTypeHidden = 5

function getTypeImagePath(creatureType)
    local path
    if creatureType == CreatureTypeSummonOwn then
        path = '/images/game/creaturetype/summon_own'
    elseif creatureType == CreatureTypeSummonOther then
        path = '/images/game/creaturetype/summon_other'
    end
    return path
end
```

**Comment by mehah** [comment]
@Zbizu

I tested it and it works perfectly, look:
![image](https://user-images.githubusercontent.com/2267386/166494086-eb2671b4-5b77-4969-a3b3-bec35686b2ce.png)

there is no client side logic, the client just receives the creature type id which is sent by the server and points to the corresponding texture.

```lua
CreatureTypePlayer = 0
CreatureTypeMonster = 1
CreatureTypeNpc = 2
CreatureTypeSummonOwn = 3
CreatureTypeSummonOther = 4
CreatureTypeHidden = 5

function getTypeImagePath(creatureType)
    local path
    if creatureType == CreatureTypeSummonOwn then
        path = '/images/game/creaturetype/summon_own'
    elseif creatureType == CreatureTypeSummonOther then
        path = '/images/game/creaturetype/summon_other'
    end
    return path
end
```

**Comment by Zbizu** [comment]
It was changed at some point

QT client protocol (some older version):
expecting type OWN/OTHER, no masterId

QT client protocol now:
expecting only type OWN, icon is determined client side by a check masterId == localPlayerId

sending type OTHER to QT crash the client now

**Comment by mehah** [comment]
so this is out of my scope, i don't even have a tibia 12.x server to proceed with testing.

I'll leave it to another dev.

**Comment by Zbizu** [comment]
you just have to give the creature object masterId (or 0 as default)
https://github.com/mehah/otclient/blob/878337bea3f1e2a8770ff9019a1c8a30f8375f9a/src/client/protocolgameparse.cpp#L2543
https://github.com/mehah/otclient/blob/878337bea3f1e2a8770ff9019a1c8a30f8375f9a/src/client/protocolgameparse.cpp#L2612

and compare that number to `m_localPlayer->getId()`

If you need a version 12 test server, pm me on discord. We have evo project running 12.86 on a vps (the "otc compatibility" commits from my tfs fork aren't present on that server).

**Comment by mehah** [comment]
the point is that I'm not fixing anything related to 12xx, just what existed before that, implementation or correction of the new protocol, I'm leaving it to the community.
