### ISSUE TITLE
ChangeMapAwareRange gamefeature not working correctly.

### ISSUE THREAD

**Issue by Sifl46** [opentibiabr/otclient#269]
**Protocol version**
8.00 (don't think it matters)

**Describe the bug**
ChangeMapAwareRange, a OTClient specific feature which enables you to resize the aware range (how much of the map you can see at once), no longer works properly. Last time I messed with this project(about 4 months ago) it was working fine.
From what I can gather, this feature is a bit obscure. So here's a basic explanation of how it works:

1. When feature is enabled, calling `g_game.changeMapAwareRange` via Lua will cause the client to send a packet to the server with a new aware range (length and width of viewable area) 
`ProtocolGame::sendChangeMapAwareRange`

2. (if implemented) Server will parse the packet, and send a packet back to the client with the new map aware range `ProtocolGame::parseChangeMapAwareRange`, followed up with `SendMapDescription` to redraw the screen in order to view beyond the original viewable boundaries set beforehand.

The problem right now, is that sending `SendMapDescription` no longer updates viewable boundaries.
I have found some workarounds that temporarily fix the problem:
1. Calling `MapView::setVisibleDimension` seems to properly update the viewable range. I found this out by zooming in/out with ctrl +/-.

2. Commenting out `updateViewportDirectionCache();` in `MapView::updateGeometry` seems to make it "work", but of course this is very much not ideal.

**To Reproduce**
You can send this packet via the server at any point when you're online with a character. You don't even need to enable the feature in the client, as the feature only controls whether the client will send a request for said packet or not.
```
NetworkMessage msg;
msg.addByte(0x33); //parseChangeMapAwareRange opcode
msg.add<uint8_t>(30); //arbitrary width
msg.add<uint8_t>(22); //arbitrary height
writeToOutputBuffer(msg);
sendMapDescription(player->getPosition()); //refresh map
```
You can then change the client's mapview size via editing `gameMapPanel:setVisibleDimension({width = 15, height = 11})` in gameinterface.lua
To match my screenshots below, you can do(before the above packet is received by the client):
```
gameMapPanel:setVisibleDimension({width = 18, height = 11})
gameMapPanel:setZoom(12)
```

**Expected behavior**
` SendMapDescription` to properly update viewable boundaries.

**Screenshots**
Build from about 4 months ago:
http://puu.sh/IXqBh/12fa65ec42.jpg
Latest revision(with same exact modules folder):
http://puu.sh/IXqCN/c550b4bc9a.jpg

**Additional context**
I attempted to fix the issue myself, however, I lack the proper understanding of how the client processes `SendMapDescription`, and don't currently have the time to look much further. I figured I'd drop an issue until I have the time to fix it myself.

**Comment by mehah** [comment]
try enabling the "Draw Viewport Edge" option in graphics.

**Comment by Sifl46** [comment]
Enabling the option does fix it.
However, it seems like it doesn't get saved at all. Logging out and logging back in disables the option again.
I also reverted to clean data and modules to be 100% sure.
