### ISSUE TITLE
protocolgame errors

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otclient#273]
using nostalrius base
otclient latest version downloaded today, no changes were made, connecting to 7.72 version

![image](https://user-images.githubusercontent.com/64820180/168464039-157f00d7-5bb6-4766-90d5-6371cb26a547.png)

a potential fix could be changing 760 to 772 on:
-- Hack fix to resolve some 760 login issues
    if g_game.getClientVersion() <= 760 then g_game.setCustomOs(2) end
    
but doing that disables ping and opcode(and maybe more stuff i didnt see)

**Comment by nekiro** [comment]
Nostalrius is not 1:1 772 protocol, so it's most likely your server having problems, not this otc issue.
Try to test this with TFS 1.5 downgrade 772 and if it still doesn't work then we can assume it might be otc protocol problem. (1.5 downgrade is made to use cip client, so it's 1:1 protocol.)
