### ISSUE TITLE
Drawing order issue

### ISSUE THREAD

**Issue by Emerald2630** [opentibiabr/otclient#284]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

So we recently updated to this Client since it has a lot improvements in general but we've started to notice a lot of issues with how items and effects are drawn. 

This is mainly regarding effects and how bodies are rendered but we've also experienced some issues with some borders.
Here are some examples. 
Inside Remeres:
![inside remeres](https://user-images.githubusercontent.com/28225553/172354951-bbc8422a-e5e9-4367-83c1-e519f47fb553.png)
In game:
![in game](https://user-images.githubusercontent.com/28225553/172354945-ad757e35-ec8e-4d2f-a19a-6795e08ce036.png)

Inside Remeres:
![inside remeres2](https://user-images.githubusercontent.com/28225553/172355097-7bb2d8ed-f3b3-46c8-bde6-fee555e2ece4.png)
Ingame:
![ingame2](https://user-images.githubusercontent.com/28225553/172355090-c1b5e22b-8873-4b06-9fd6-51d8e796692a.png)

I am aware that the borders shouldn't even be there in the first place but I am wondering why there is such a discrepancy between remeres and the client itself all of a sudden. 

Same thing here, we've had this "fancy" stair that has worked fine in our old client but no longer renders properly.
This is what it looks like in remeres:
![inside remeres 4](https://user-images.githubusercontent.com/28225553/172355762-70815a62-8cc9-4eb4-9168-81ce6de7b767.png)
This is how it looks like in the old client:
![ingame old](https://user-images.githubusercontent.com/28225553/172355741-959613bd-35d3-4df6-b4ec-e8232a85336a.png)
And this is the new updated client:
![ingame new](https://user-images.githubusercontent.com/28225553/172355735-5c9e9222-2afa-4714-9b83-b694b04e9753.png)

You can also view these videos here to see what i mean. The ground borders no longer get drawn with any sort of elevation even though they do have elevation inside remeres and the old client.

Old:

https://user-images.githubusercontent.com/28225553/172357136-981ad1a7-4333-4bda-9660-4a16c0dff67e.mp4

New:

https://user-images.githubusercontent.com/28225553/172357132-2db869dd-7e37-49b4-aebb-217cd7144472.mp4

There is also a problem with effects and corpses being drawn in the wrong order.
For example in the old client when it came to doorways the effects were drawn inside the doorway. Now they're instead drawn on top of the door way as you can see in these two examples

Old:

https://user-images.githubusercontent.com/28225553/172357362-1d9885e0-6c57-4653-8f3b-7b5e400d5bc5.mp4

New:

https://user-images.githubusercontent.com/28225553/172357357-067d139b-f30c-4529-811b-fdc3dddc15eb.mp4

And then also the corpses come with their own issue

Old:

https://user-images.githubusercontent.com/28225553/172357455-c59f7ee7-4194-4c04-b666-52df6c2112d7.mp4

New:

https://user-images.githubusercontent.com/28225553/172357450-d7c936ab-3379-4254-b70a-9d71d009d97f.mp4

This can't be how it's really meant to be since it's incredibly different from how the old client used to work and how it's displayed inside remeres. I tried to fix this on my own but I wasn't able to do it on my own that's why I am opening this issue.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I need a map with the problems pointed out so I can do the tests and fix them, tibia version too.

**Comment by Emerald2630** [comment]
I have attached a world here with all the test cases that I've ran across so far where you should be able to test everything.
This is tibia version 10.98

[world.zip](https://github.com/mehah/otclient/files/8854668/world.zip)

**Comment by mehah** [comment]
- This bug will be fixed with drawpool v2
![image](https://user-images.githubusercontent.com/2267386/176592256-68d6b0af-1ca8-4267-81a9-d781b02ab18d.png)


- this happens on all clients, and on 10.98 it crashes.
  and anyway, this is wrong, you have to correct it in RME, it will draw a border that you will not see.
![image](https://user-images.githubusercontent.com/2267386/176592405-3818a4fb-e28c-46d1-aad8-5fd3234d3bce.png)


**problem with effect and body, they will come vim as config as it is not a bug.**
