### ISSUE TITLE
Client does not start the game - ERROR: ProtocolGame parse message exception (2 bytes unread, last opcode is 239, prev opcode is -1)

### ISSUE THREAD

**Issue by alcuard86** [opentibiabr/otclient#285]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

The game does not start. It keeps telling me to hang while it connects to the server. 

I have compiled TFS and OTC using the last code versions available. However, I get the errors in the log file below. 

[Log file](https://www.mediafire.com/file/4q325n5bohfknfh/otclient.log/file)

Some errors I get:

Startup done :]
Unable to translate: "Hotkey delay: %sms"
Unable to translate: "Turn delay: %sms"
Unable to translate: "You have %s hours and %s minutes left"
Unable to translate: "You don't may receive experience and loot from monsters"
ERROR: ProtocolGame parse message exception (4806 bytes unread, last opcode is 0, prev opcode is 160): unhandled opcode 0
ERROR: ProtocolGame parse message exception (2 bytes unread, last opcode is 239, prev opcode is -1): unhandled opcode 239
ERROR: ProtocolGame parse message exception (2 bytes unread, last opcode is 239, prev opcode is -1): unhandled opcode 239
ERROR: ProtocolGame parse message exception (2 bytes unread, last opcode is 239, prev opcode is -1): unhandled opcode 239

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nekiro** [comment]
Are you using proper dat/spr files?

**Comment by alcuard86** [comment]
> Are you using proper dat/spr files?

I have got them from this page: https://otland.net/threads/downgraded-12-x-assets-to-dat-spr-format.273902/

If they are not proper for these new versions, please send me the link of proper ones. I´d be glad.

**Comment by nekiro** [comment]
I just double checked with cip assets dropped directly into things directory and all works fine.
I dont use these dat files so I dont know if these work.

**Comment by alcuard86** [comment]
> I just double checked with cip assets dropped directly into things directory and all works fine. I dont use these dat files so I dont know if these work.

May you send ones u are using?

**Comment by Limmek** [comment]
> > I just double checked with cip assets dropped directly into things directory and all works fine. I dont use these dat files so I dont know if these work.
> 
> May you send ones u are using?

Download the official cip client and copy the assets folder to data/things then rename it to 1287.

**Comment by forgee** [comment]
`OTClient 0.6.6 rev 0 (devel) built on Jun  9 2022 for arch x64`
That log file looks like it was built with old sources. 0.6.6 was changed to 1.0.0 2 years ago in edubart/otclient and this fork has never used 0.6.6 as far as I know.
https://github.com/edubart/otclient/commit/190131a1b88d0e6ec899d278b0b0ef7c7a561d8c

It is also missing modules from this repository like game_actionbar, game_healthcircle and game_shaders.

**Comment by nekiro** [comment]
Yeah, so as previously said, there is no issue and this works just fine, closing this issue. If you need help go to forums.
