### ISSUE TITLE
Desync & Skip Effect frames

### ISSUE THREAD

**Issue by Rekoms90** [opentibiabr/otclient#287]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Uhm this is my first ever reporting something on github. So bare in mind if I'm doing the process incorrect.
I'm experiencing a desync on certain tiles like this. 

https://gyazo.com/6d8f697d8b918cd563ca715f05a24050

Also I'm experiencing skips in frames of effects when attack speed is too high.
I have unchecked the options for it as well.

![image](https://user-images.githubusercontent.com/97104576/173186333-7b209810-d884-4cea-a7eb-880b2dd88ae2.png)

https://gyazo.com/47a99ef945265d9b121baebb6aa1e039

Can this be fixed easily or does it have to be done in source as I might think?

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BahamutxD** [comment]
I've been facing the desync issue too. https://i.imgur.com/lkMOO0D.mp4

![image](https://user-images.githubusercontent.com/6182531/176676835-437df767-1438-42cf-852e-598bb6640337.png)![image](https://user-images.githubusercontent.com/6182531/176676911-772255f8-e9fc-4502-b350-73d3c50deef4.png)




Using 12.87 TFS with assets from CIP Client unmodified (12.87).

It seems to only happen to borders that are sand/water - although I tryed to find other borders with this issue I haven't been able to find any.

![image](https://user-images.githubusercontent.com/6182531/176673893-c8aae3bc-5c61-4607-b2fc-31736d38539f.png)![image](https://user-images.githubusercontent.com/6182531/176673947-f78743f0-1e46-48d2-8062-a91903223b65.png)![image](https://user-images.githubusercontent.com/6182531/176674005-1b6e4697-37bc-4579-a013-462d6a319f63.png)

Tested several other moving (non border) sprites like magic walls, waterfalls, steam, fire/poison, campfire... they all seem to be fine.

![image](https://user-images.githubusercontent.com/6182531/176677084-12426d07-eca5-4437-adf7-8e11a295d635.png)![image](https://user-images.githubusercontent.com/6182531/176677137-d185366c-bd95-4f19-b20e-87d5bda643db.png)





A fast look into assets editor compared to a similar border (snow/water) doesn't show anything different in the animation section.

![image](https://user-images.githubusercontent.com/6182531/176676010-7f29ffd6-920b-4c74-a50a-05c608dbb324.png)

Test map

[borders.zip](https://github.com/mehah/otclient/files/9019762/borders.zip)

**Comment by mehah** [comment]
> Also I'm experiencing skips in frames of effects when attack speed is too high. I have unchecked the options for it as well.
> 
> https://gyazo.com/47a99ef945265d9b121baebb6aa1e039

in https://github.com/mehah/otclient/blob/a1feed9119e2ad23e26b3731d69117ce11eca1a8/src/client/effect.cpp#L95
change to
m_timeToStartDrawing = 0;

**Comment by Rekoms90** [comment]
> 

Now its half solved :D

**Comment by mehah** [comment]
well, I'm going to close, I just tested it with 1285 and it's without problems.
