### ISSUE TITLE
Some crash reports

### ISSUE THREAD

**Issue by sebekkx** [opentibiabr/otclient#293]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Hey there,

I am not sure if it will be helpful for the code, but I reckoned I'll share some crashreports from my testing OT, cause anyway I am not sure how to fix them. File in the attachment. Regards.
[crashe.txt](https://github.com/mehah/otclient/files/9046428/crashe.txt)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
could test with a more current build, from may until today, there have already been several improvements and fixes.

**Comment by mehah** [comment]
news?
