### ISSUE TITLE
Inventory module does not render second item of the same type

### ISSUE THREAD

**Issue by sebekkx** [opentibiabr/otclient#294]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Hello

I compiled the newest rev of OTC 2.0, and I came upon the problem with the Inventory module. When classicEquipmentSlots is set to true in TFS and we put e.g. one gold coin in left hand and one gold coin in the right hand, the first gold coin is invisible. Expected behavior is to have both gold coins visible. The principle of the bug is shown in the movie in the attachment. Happens on both Windows and Linux

https://user-images.githubusercontent.com/6154527/178001606-0e40c53c-c811-4d63-a283-eb2adf8cea02.mp4

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SkullzOTS** [comment]
@djseban https://github.com/mehah/otclient/commit/eaac351d78ab2b81373fb292a1f6ac031b04f0d4

have you tested with this?

**Comment by sebekkx** [comment]
> @djseban [eaac351](https://github.com/mehah/otclient/commit/eaac351d78ab2b81373fb292a1f6ac031b04f0d4)
> 
> have you tested with this?

Tested now, now it works all right. The commit rate of this repo is just insane! :D

**Comment by SkullzOTS** [comment]
> > @djseban [eaac351](https://github.com/mehah/otclient/commit/eaac351d78ab2b81373fb292a1f6ac031b04f0d4)
> > have you tested with this?
> 
> Tested now, now it works all right. The commit rate of this repo is just insane! :D

Already enjoy and apply the last commits since the Drawpool v2 RC merge...

Start at this: https://github.com/mehah/otclient/commit/b80f66289cf8e4e3937d5a39733f627e7fe03580

**Comment by mehah** [comment]
> > @djseban [eaac351](https://github.com/mehah/otclient/commit/eaac351d78ab2b81373fb292a1f6ac031b04f0d4)
> > have you tested with this?
> 
> Tested now, now it works all right. The commit rate of this repo is just insane! :D

haha, I'm refactoring the project, that's why there are so many commits.

I will close...
