### ISSUE TITLE
appearances protobuf not compatible with new version

### ISSUE THREAD

**Issue by miah-sebastian** [opentibiabr/otclient#296]
### Priority

Medium

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

The current appearances protobuf is not compatible with newer protobuf version. I went and generated a new version with protoc, but I'm getting errors that I'm not familiar with. The errors are all of the same type:
`'otclient::protobuf::appearances::_Appearances_default_instance_': illegal initialization of 'constinit' entity with a non-constant expression	otclient	C:\NewClients\otclient\src\protobuf\appearances.pb.cc	59`

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by miah-sebastian** [comment]
@mehah I'm still getting these errors, on both Debug and Release. 
![Screenshot (65)](https://user-images.githubusercontent.com/16799955/178636459-f0832c17-bff1-47f9-8993-5b557d4cd088.png)

**Comment by mehah** [comment]
> @mehah I'm still getting these errors, on both Debug and Release. ![Screenshot (65)](https://user-images.githubusercontent.com/16799955/178636459-f0832c17-bff1-47f9-8993-5b557d4cd088.png)

this is a protobuf bug that has already been fixed by them, but vcpkg has not yet been updated.
solution: delete everything related PROTOBUF_CONSTINIT in appearances.pb.cc file

**Comment by dudantas** [comment]
A second solution (which solves it for good, while vcpkg doesn't update to solve the problem)

In folder: vcpkg\installed\x64-windows\include\google\protobuf\port_def.inc
Change from
```cpp
#if defined(__cpp_constinit)
```
to 
```cpp
#if defined(__cpp_constinit) && !defined(_MSC_VER)
```
