### ISSUE TITLE
[request] The macOS support

### ISSUE THREAD

**Issue by paulocoutinhox** [opentibiabr/otclient#297]
### Priority

Enhancement

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

Hi,

Do you plan add macOS support?

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by humbertogontijo** [comment]
Macos is no longer supported because of stduuid dependency
