### ISSUE TITLE
Blinking Black & Moving Window 

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#303]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

**1.**
Sometimes when playing, the entire screen flashes black **(Including modules such as minimap, inventory, battle etc)**. Is there any delay in drawing?

**2.**
When you drag around the client **(Window mode)** on the desktop, everything in the client freezes.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
here everything is normal, when you move the window, everything that is being processed on the client is no longer processed, this is normal behavior and even here on my PC I didn't feel any difference, just a drop in FPS that soon recovered .

**Comment by Klonoa88** [comment]
About Window dragging: 
Okay then I understand :)

About the screen blinking black: 
It seems to happen if a lot is happening on the game screen. Creatures walking, effects and distance effects that draws etc, Especially underground. If I hunt on my server, it happens. if I stand still in example Depot, it does not flash.

**Comment by mehah** [comment]
but does everything blink or just the UI?

**Comment by Klonoa88** [comment]
All .. UI, Items, Characters, Effects. Everything the eye can see :P But it does not happen very often. Have tried to record it for you, but sometimes it takes like 20 min: P

**Comment by Klonoa88** [comment]
Hmm. Have been trying for a while now to make it flash, but have not succeeded yet. I will test more and try to record it for you :)

**Comment by mehah** [comment]
try this
https://github.com/mehah/otclient/commit/9e2a7ed9b345d34acd98373ec5346945c74ec63e

**Comment by Klonoa88** [comment]
Will try it now. But I have to test for a while to see if the flash is gone :)

**Comment by Klonoa88** [comment]
I haven't received any more black flash :D So I think we can close this now.

**Comment by mehah** [comment]
> I haven't received any more black flash :D So I think we can close this now.

niceee, what a straight shot. :laughing:
