### ISSUE TITLE
[Request] Item Shaders

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#305]
### Priority

Enhancement

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

Is it possible to do so you can put shaders on items (grounds, borders, walls and others)?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
![image](https://user-images.githubusercontent.com/2267386/180897423-4f4abbad-9fdf-4985-89b0-a82c07e517da.png)

Example:
https://github.com/mehah/otclient/blob/d4d26fcb05b35fa7e798d488e3614297aad0374e/src/client/item.cpp#L91
