### ISSUE TITLE
Ambient Light Client Settings

### ISSUE THREAD

**Issue by NRH-AA** [opentibiabr/otclient#307]
### Priority

Medium

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

I think whenever the light system was redone it messed up the ambient light in the client.

Whenever I modify the ambient light settings there are only 2 things that happen.
1) The light goes to the normal light set by the server
2) When I set ambient light to 100% it makes the screen full light.

There is no in-between values. The client is either full light or default light. Unless you relog into the game. If you log out and back in the light will be the correct value for the client.

It should slowly make the light higher or lower based on the % setting.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
if I understand correctly, here it is working perfectly.

https://user-images.githubusercontent.com/2267386/180504282-9e3b2067-c015-4956-9ab3-7c79a51d4030.mp4

If not, please explain it to me with a video.

**Comment by NRH-AA** [comment]
It may have something to do with me not using default light in cofig.lua but it shouldn't cause a problem anyway. I set the world light myself through globalevent code.

After checking again. The light works fine on a GOD character but not a normal one.


https://youtu.be/YFq8Yek7ZwM

**Comment by mehah** [comment]
I understand, so in this case it is this delay that there is in the change of light, correct?!

I will correct.

**Comment by NRH-AA** [comment]
I have to log out of the character and back in for it to work. The only time it actually changes the light when I am logged in is when its at 99%+ or at 98%- and its only 2 intensities. Either full light or normal light. Nothing more or less.
