### ISSUE TITLE
Otclient v2.0b Minimal requirements

### ISSUE THREAD

**Issue by themaoci** [opentibiabr/otclient#308]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

Hello i would like to know detailed minimal requirements for otclient 2.0b

as of 
windows / linux / mac / android
x32 / x86 versions

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
Test, discover and let us know.
