### ISSUE TITLE
item:getName() and item:getMarketData().name returns empty string

### ISSUE THREAD

**Issue by miah-sebastian** [opentibiabr/otclient#309]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I'm trying to fix market and I noticed there's no way to display the item name, all the ways to get the item name returns an empty string. I looked into it, and it seems like a protobuf error, I'm not sure how to fix it, maybe when protobuf fix is updated in vcpkg it'll fix itself.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
tested with the last commit and it's working perfectly.
