### ISSUE TITLE
Walk after character dead.

### ISSUE THREAD

**Issue by ramosluis16** [opentibiabr/otclient#310]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I compiled the repository everything fine, on testings using 7.72 protocol after your character is dead you can still move.

I've added 

`if (isDead())
        return false;`

Inside function 

`bool LocalPlayer::canWalk(bool ignoreLock)`

I dont know if is a real fix but it solve my problem.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
fixed, thx.

**Comment by ramosluis16** [comment]
You're welcome, thanks for work in this great client.
