### ISSUE TITLE
Clicking "Use with..." - wrongly selects tile data

### ISSUE THREAD

**Issue by themaoci** [opentibiabr/otclient#314]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

When you click "Use with..." on the item for example "Pick" and you want to use it on a tile with structure as follows:
```
- Tile: Stone (this has UID and AID for "Use With...")
- Tile: Border Lava/Ground
- Tile: Border Lava/Ground (By Default this tile-layer is getting selected by the script)
- Tile: Ground Lava
```
Script is located in: src/client/tile.cpp in line 506
this line looks like 
```c
if (!thing->isGround() && !thing->isOnTop())
```
if you change it to
```c
if (!thing->isGround() && !thing->isGroundBorder() && !thing->isOnTop())
```
it will start skipping Borders of the tile and go straight to the proper tile with AID and UID

Was testing on server: https://otland.net/threads/8-6-12x-tfs1-3-global-source-web-tools-quest-reward-system.268391/
On Quest: POI in this part: 
![Image](https://tibiopedia.pl/images/static/quests/the_pits_of_inferno_quest_poi_pick.gif)

### What OS are you seeing the problem on?

Linux, Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
> if you change it to
> 
> if (!thing->isGround() && !thing->isGroundBorder() && !thing->isOnTop())

is this a fix?
