### ISSUE TITLE
Draw order issue

### ISSUE THREAD

**Issue by BenDol** [opentibiabr/otclient#318]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Seems there's something wrong with the draw ordering:

![titanclient_gB9a1IJzxw](https://user-images.githubusercontent.com/1935706/184049317-4250efd0-28f1-4139-8687-3dcaf9260342.png)

On regular otclient

![titanclient_OI7vqayp2b](https://user-images.githubusercontent.com/1935706/184049334-0202c0bf-ec8c-435d-9b64-5b26cd6ca530.png)

I'm on the latest commit as of the time of this posting.

I'll be investigating too, but figured I'd report this issue.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenDol** [comment]
### Investigation Notes
The wall item:
![image](https://user-images.githubusercontent.com/1935706/184051959-d2531ea8-a757-4bdd-afeb-896891d2faa4.png)
Draws here in `tile.cpp#draw`:
```c++
if (m_countFlag.hasBottomItem) {
    for (const auto& item : m_things) {
        if (!item->isOnBottom()) continue;
        drawThing(item, dest - m_drawElevation * scaleFactor, scaleFactor, true, flags, lightView);
    }
}
```

The Fire Item:
![image](https://user-images.githubusercontent.com/1935706/184052195-41953560-f848-488a-808d-583db708a51a.png)
Draws here in `tile.cpp#draw`:
```c++
if (m_countFlag.hasCommonItem) {
    for (const auto& item : m_things | std::views::reverse) {
        if (!item->isCommon()) continue;
        drawThing(item, dest - m_drawElevation * scaleFactor, scaleFactor, true, flags, lightView);
    }
}
```

Though likely an issue in the DrawPool ?

EDIT: I think the issue is that we're drawing all the items on each tile, rather than drawing on tiles by "layer"
Shouldn't we draw bottomItem's on all tiles then draw the commonItems on all tiles after?

**Comment by BenDol** [comment]
This likely isn't the greatest solution, but if I copy paste the tiles loop and call a `drawBottom` which draws ground and bottom items and call this on all the tiles before we `draw` everything else it resolves the issue.
```c++
void Tile::drawBottom(const Point& dest, const MapPosInfo& mapRect, float scaleFactor, int flags, bool isCovered, LightView* lightView)
{
    m_drawElevation = 0;
    m_lastDrawDest = dest;

    for (const auto& thing : m_things) {
        if (!thing->isGround() && !thing->isGroundBorder())
            break;

        auto id = thing->getId();
        drawThing(thing, dest - m_drawElevation * scaleFactor, scaleFactor, true, flags, lightView);
    }

    if (m_countFlag.hasBottomItem) {
        for (const auto& item : m_things) {
            if (!item->isOnBottom()) continue;
            auto id = item->getId();
            drawThing(item, dest - m_drawElevation * scaleFactor, scaleFactor, true, flags, lightView);
        }
    }
}
```

(This isn't optimal, just copy pasting the original loop and add it prior to the draw tile loop)
```c++
for (const auto& tile : map.tiles) {
    uint32 tileFlags = flags;

    if (!m_drawViewportEdge && !tile->canRender(tileFlags, cameraPosition, m_viewport, lightView))
        continue;

    bool isCovered = false;
    if (tile->hasCreature()) {
        isCovered = tile->isCovered(m_cachedFirstVisibleFloor);
    }

    if (alwaysTransparent) {
        const bool inRange = tile->getPosition().isInRange(_camera, TRANSPARENT_FLOOR_VIEW_RANGE, TRANSPARENT_FLOOR_VIEW_RANGE, true);
        isCovered = isCovered && !inRange;

        g_drawPool.setOpacity(inRange ? .16 : .7);
    }

    tile->drawBottom(transformPositionTo2D(tile->getPosition(), cameraPosition), m_posInfo, m_scaleFactor, tileFlags, isCovered, lightView);
                
    if (alwaysTransparent)
        g_drawPool.resetOpacity();
}
```

Just demoing how I resolved it so far.

**Comment by BenDol** [comment]
Replaced with a lambda (until I find a better solution), this works and doesn't have a massive FPS impact.
```c++
drawTiles(map, cameraPosition, alwaysTransparent, flags, lightView, [&](const TilePtr& tile, uint32 tileFlags, bool isCovered) {
    tile->drawBottom(transformPositionTo2D(tile->getPosition(), cameraPosition), m_posInfo, m_scaleFactor, tileFlags, isCovered, lightView);
});

drawTiles(map, cameraPosition, alwaysTransparent, flags, lightView, [&](const TilePtr& tile, uint32 tileFlags, bool isCovered) {
    tile->draw(transformPositionTo2D(tile->getPosition(), cameraPosition), m_posInfo, m_scaleFactor, tileFlags, isCovered, lightView);
});
```
Look forward to a more optimized solution if there is one.

EDIT: This actually has some problems right now with other items drawing underneath things like railings, etc

![image](https://user-images.githubusercontent.com/1935706/184061578-7d982822-6f75-47d1-9bc1-8f54bf2caaa4.png)

**Comment by mehah** [comment]
try this:
on the line:
https://github.com/mehah/otclient/blob/50a3df2ad81288210b348195b4da43efa194ef59/src/client/thing.cpp#L90

change to:

```c++
void Thing::generateBuffer()
{
    m_drawBuffer = nullptr;

    DrawPool::DrawOrder order = DrawPool::DrawOrder::NONE;
    if (isSingleGround())
        order = DrawPool::DrawOrder::FIRST;
    else if (isGroundBorder())
        order = DrawPool::DrawOrder::SECOND;
    else if ((isCommon() || isOnBottom()) && isSingleDimension() && !hasDisplacement() && isNotMoveable())
        order = DrawPool::DrawOrder::THIRD;
    else if (isTopGround() || g_app.isDrawingEffectsOnTop() && isEffect())
        order = DrawPool::DrawOrder::FOURTH;
    else if (isMissile())
        order = DrawPool::DrawOrder::FIFTH;

    if (order != DrawPool::DrawOrder::NONE)
        m_drawBuffer = std::make_shared<DrawBuffer>(order);
}
```

**for you to understand, i put it to check if the common item has offset, because if it does, it won't try to group with a similar item that was rendered before it.**

**Comment by BenDol** [comment]
Nice, yep that solves it. Thanks!
