### ISSUE TITLE
Ground tiles not rendering causing "flickers"

### ISSUE THREAD

**Issue by BenDol** [opentibiabr/otclient#324]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

As seen here (towards the end): https://youtu.be/BzJhRI1u690?t=25

Occasionally when on snowy areas like in this video it doesn't render the floor or there is a tile under it over the tile? I have no idea with this one.

![flicker](https://user-images.githubusercontent.com/1935706/184441308-2d2146fd-382e-4144-ba01-5cb84e288211.png)

Settings:
![image](https://user-images.githubusercontent.com/1935706/184439027-c89be8cf-cd58-47a2-907d-011dcdafe510.png)
![image](https://user-images.githubusercontent.com/1935706/184439102-f58c9b4c-56ec-4ad9-ae5b-352a9bc306f0.png)

Same thing happens with Vertical sync off, tried playing with the setting and nothing solves it

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenDol** [comment]
Test map [flickering.zip](https://github.com/mehah/otclient/files/9329646/flickering.zip)

**Comment by BenDol** [comment]
## Notes
- Appears to only happen on z < 8

**Comment by mehah** [comment]
did you apply this fix?
https://github.com/mehah/otclient/commit/50a3df2ad81288210b348195b4da43efa194ef59

**Comment by BenDol** [comment]
Experiencing this issue on the latest commit 19bf5b0d76ece32b49885f14834aecd5ae53f6a7

**Comment by BenDol** [comment]
Confirmed this is resolved now
