### ISSUE TITLE
Draw ordering issue (possibly related to #324)

### ISSUE THREAD

**Issue by BenDol** [opentibiabr/otclient#325]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Strange draw order flickering that could be related to #324 I've added it here in case it is a separate issue.

Seen here: https://youtu.be/FKYJHkGbssc

Its worth noting that it doesn't happen in Fullscreen Mode or at least I wasn't able to reproduce it in Fullscreen.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
sorry but I couldn't reproduce it, try removing common in "generateBuffer" method

**Comment by BenDol** [comment]
Yeah that resolves it for me

**Comment by mehah** [comment]
@BenDol 
can you test it now?

**Comment by BenDol** [comment]
Yep both issues are resolved now.

EDIT: Nevermind I reproduced this issue just now

**Comment by BenDol** [comment]
So the only thing that solves this issue right now is removing `isCommon` from `generateBuffer`

**Comment by BenDol** [comment]
Of note the item on top of this box is not a rope, its a hawser (`Item ID: 6392, Client ID: 6391`)

![image](https://user-images.githubusercontent.com/1935706/184716226-1ce75c88-40cf-44d8-b3b9-a89075808c79.png)

**Comment by BenDol** [comment]
My bad I thought it was resolved, it was not

**Comment by BenDol** [comment]
Confirmed resolved for me also

**Comment by mehah** [comment]
@BenDol 

Are you interested in helping to maintain this repository, because I want to take a break to take care of my personal projects and I don't want to let this repository die and I'm already inviting other people to help too.

**Comment by BenDol** [comment]
Sure I don't mind helping out here as I work on my project

**Comment by mehah** [comment]
thx, I sent you an invite.
