### ISSUE TITLE
Cannot load spr/dat/assets

### ISSUE THREAD

**Issue by danilomagalhaes** [opentibiabr/otclient#328]
### Priority

Medium

### Area

- [x] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

I'm configuring the client to play a custom OtServer  [Next Stage](next-stage.pl) and I got this error using client 1286 assets.

![image](https://user-images.githubusercontent.com/8502778/185635105-22f7ab0c-80fa-4f3b-8144-b5ee1de6b311.png)

And this error with client 1000 dat and spr files.

![image](https://user-images.githubusercontent.com/8502778/185640057-de1ed9fb-5594-4f2e-bc3b-764c124958ed.png)

Tested with1.4, 1.4.2, 2.0 and the latest success [Build](https://github.com/mehah/otclient/actions/runs/2886516442)

PS: I can use the spr and dat using the OTCv8.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nekiro** [comment]
Console error says you wanted to use client version 12.2, this client is not supported, so that's probably why it doesn't work. Protocols supported are from 12.85 to 12.92
