### ISSUE TITLE
http does not work

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#339]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

HTTP.post, HTTP.get, HTTP.postJSON, HTTP.getJSON does not work! The server returns:
> {
>     "files": {
>         "test.txt": "00000000",
>         "CMakeLists.txt": "f4c9b288"
>     }
> }HTTP/1.1 400 Bad Request
> Date: Fri, 07 Oct 2022 18:16:28 GMT
> Server: Apache
> Content-Length: 226
> Connection: close
> Content-Type: text/html; charset=iso-8859-1
> 
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>400 Bad Request</title>
> </head><body>
> <h1>Bad Request</h1>
> <p>Your browser sent a request that this server could not understand.<br />
> </p>
> </body></html>

Any solution?

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nekiro** [comment]
How does this explain that it's problem with otc code and not your website - or whatever you send the request to - that does not accept it?
From what I see request is sent correctly, shape also matches.

**Comment by patrykq112** [comment]
I'm using the lastest source of mehah otc. I think the problem is in this source and I am looking for a solution

**Comment by patrykq112** [comment]
I'm using the lastest source of mehah otc. I have tried sending this request to different websites, it always gets this error so I think the problem is in this source and I am looking for a solution

**Comment by patrykq112** [comment]
I'm using the lastest source of mehah otc. I have tried sending this request to different websites, it always gets this error so I think the problem is in this source and I am looking for a solution

**Comment by patrykq112** [comment]
I'm using the lastest source of mehah otc. I have tried sending this request to different websites, it always gets this error so I think the problem is in this source and I am looking for a solution.

i think i am using this function correctly:
```
HTTP.postJSON(url, {build = g_app.getVersion(), os = g_app.getOs(), platform = g_window.getPlatformType()}, function(data, err)
    if err then      
      return Updater.error(err)
    end
    print(data)
  end)
```

**Comment by patrykq112** [comment]
From apache.log:
`[08/Oct/2022:11:02:42 +0200] "POST /updater/files.php HTTP/1.1" 200 0 "-" "Mozilla/5.0"`

anyone have any idea how to fix it?

**Comment by patrykq112** [comment]
nobody uses these functions?

**Comment by patrykq112** [comment]
???

**Comment by patrykq112** [comment]
?????

**Comment by patrykq112** [comment]
i fixed it
