### ISSUE TITLE
Name plates disapear

### ISSUE THREAD

**Issue by Andreas-wl** [opentibiabr/otclient#34]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Move in and out of screen where a character leaves your screen area.

### Expected behaviour
Name should always be shown

### Actual behaviour
In some cases the name of creatures/players are not loaded, leaving a creature/player without a name.

### Environment
10.98 Latest version of TC

**Comment by mehah** [comment]
could you give me more details, like video?

**Comment by Andreas-wl** [comment]
Sure, Will try to film next time.
Regards Andreas

fre 11 sep. 2020 kl. 21:35 skrev Renato Machado <notifications@github.com>:

**Comment by mehah** [comment]
fixed #37
