### ISSUE TITLE
Minimap erasing when spamming spell and moving

### ISSUE THREAD

**Issue by sebekkx** [opentibiabr/otclient#344]
### Priority

High

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Like in the title. The bug is pretty self-explanatory. Attached a recording presenting the issue.

https://user-images.githubusercontent.com/6154527/195785487-0d07abb6-2883-49ec-9857-7de454876e24.mp4

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by boldenon** [comment]
Confirmed issue, same thing happening here.
