### ISSUE TITLE
Client "shits" itself after playing with hotkeys and using shared timings for spells

### ISSUE THREAD

**Issue by themaoci** [opentibiabr/otclient#345]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

modules/gamelib/spells.lua

```lua
function Spells.getSpellByClientId(id)
    for profile, data in pairs(SpellInfo) do
        for k, spell in pairs(data) do
            if spell.id == id then
                return spell, profile, k
            end
        end
    end
    return nil
end
```

this is missing function that is making client shiver in pain after ppl are using too much spells eventually ending up with some unwanted behaviour

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nekiro** [comment]
I have no idea what are you reporting, rephrase your issue please

**Comment by mehah** [comment]
I didn't understand either.
