### ISSUE TITLE
Low FPS causes strange rendering issues

### ISSUE THREAD

**Issue by BenDol** [opentibiabr/otclient#348]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

![low_fps](https://user-images.githubusercontent.com/1935706/198586335-1eb58b82-b9b7-4294-a1b4-d7c576d1b389.gif)

Reproduced on the latest `main` commit 9acf8b6ebc36622b0e06148e7daa0afc013eb6a8

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
It's not a bug, there's a logic that when the FPS is below 50, it will send the objects in batch, ignoring the order, this will consume less CPU, to confirm what I'm saying, just disable the optimization system.

this system is to try to keep the FPS above 50 FPS when the player's machine is not that good.

in the future I will add an optimization level option.

**Comment by BenDol** [comment]
I see, thanks for clarifying!
