### ISSUE TITLE
Otclient.exe

### ISSUE THREAD

**Issue by lopez65** [opentibiabr/otclient#35]
Hello there
I would like to know how to download the executable otclient (otclient.exe) for version 1264 of OTServBR-Global
Thanks

**Comment by Costallat** [comment]
https://github.com/opentibiabr/otclient/suites/3789904667/artifacts/93465109

**Comment by lopez65** [comment]
> https://github.com/opentibiabr/otclient/suites/3789904667/artifacts/93465109

Thank you so much

**Comment by MajestyOTBR** [comment]
https://github.com/opentibiabr/otclient#builds
https://github.com/opentibiabr/otclient#where-do-i-download
