### ISSUE TITLE
Map traversal (autowalk) bug -> infinite traversal loop

### ISSUE THREAD

**Issue by Source61** [opentibiabr/otclient#35]
Found this bug initially on my 1 year old (edubart) otclient.
Replicated the bug on the (almost) "latest" edubart otclient, specifically commit 59059321a6276890e4a14841957f6838fab342f1.
Replicated on the latest mehah otclient today, can make a new recording using this client if necessary.

The recording failed to capture the cursor despite being set to do so, in the recording I'm clicking the minimap once to the center south in between the large grey area on the right side and the small house area on the left side which is being traversed in the recording.
[https://s8.gifyu.com/images/ezgif.com-optimize06e7958970442f0d.gif](https://s8.gifyu.com/images/ezgif.com-optimize06e7958970442f0d.gif)

**Comment by mehah** [comment]
sorry, but I will only fix bugs that were caused by my modifications.

**Comment by Source61** [comment]
For anyone interested in a fix for this, I hired a C++ developer that fixed this issue for $35.
This isn't just a fix for ab'dendriel, but works for all places like this.
Here's how it looks when working properly: https://imgur.com/HI0eveN
Will release this fix for $35, you decide where (mehah or edubart).
You can find more about my otclient work/fixes here: https://wiki.opentibia.dev/view/User:Admin/Projects/Open_Tibia/Otclient

**Comment by oarsc** [comment]
It should be fixed in the next release.

**Comment by Source61** [comment]
Welp, I'm happy you solved it, but no more bug reports from me, I can't afford giving away money.

**Comment by oarsc** [comment]
Sad you feel that way. Sorry we couldn't fix it earlier.
Come back whenever you feel, so you can report a bug and have a chance to have it fixed without hiring a dev.

**Comment by Source61** [comment]
Unfortunately I can't wait potentially several years for a bug to be fixed, and although I know you mean well, it's not actually profitable (or rather it has a negative economic effect if you can afford to hire someone since competitors won't have the fix and might not even know about it) to report bugs as long as you can afford to hire someone to fix it (unless it's like a really difficult bug with very little use, but nobody here would bother to fix that in all likelihood), the only reason I decided to report this bug is because I want to give back, but not more than I can afford, and I think it's reasonable to promote a healthier business model than the ones you see on OTLand like "just pay $1000 and you'll have access, but don't share it with anyone else!", a healthier model is basically what I'm trying to promote here - a form of crowdsourcing where everyone has access even if they haven't paid anything.
And because the bug is cheap, people don't have to worry about me scamming since I have enough history in this community (and 2 OT websites and a relatively active OT blog + an OT yt channel) to outweigh the risk of $35.

Not to mention just finding the bug is often half of the work, I was just trying to be charitable without giving my wallet away (think about it, what do I earn? in the end the only achievement made by this crowdsourcing project would be an improved client for everyone that I had to spend my own time to find/figure out, explain, and then investment (money) to hire someone to fix it with 0 actual profit in the end).
