### ISSUE TITLE
Bug with potions, etc

### ISSUE THREAD

**Issue by Akanetfs** [opentibiabr/otclient#351]
### Priority

Medium

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

hi all, I will be brief, when using a potion it happens that it is consumed but the sprite continues to appear in the inventory but without a name or anything (it ceases to exist)

![Captura](https://user-images.githubusercontent.com/52334736/201496828-a0b848d8-4020-4070-9c15-25ab6a10aae1.PNG)

 and the following error appears on the console:

![2](https://user-images.githubusercontent.com/52334736/201496836-4228ef18-d4e1-4f00-a14a-344041ecd499.PNG)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
protocol?

**Comment by Akanetfs** [comment]
12.86

**Comment by mehah** [comment]
bug fixed.

error corrected, but the way it should be presented on the screen, I will let someone correct it.
