### ISSUE TITLE
problem with light system

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#354]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

There is a light issue in the latest source, it only occurs in OpenGL ES 2.0. Any idea how to fix it?
![image](https://user-images.githubusercontent.com/16617982/201882230-a1536cdf-ba75-45c2-ad35-853eccb09c18.png)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
apparently you are not using clean source code from the repository, we do not fix bugs due to third party changes.

**Comment by patrykq112** [comment]
this problem occurs in clean source when compiling with "-OPENGL_ES=2"

**Comment by mehah** [comment]
> this problem occurs in clean source when compiling with "-OPENGL_ES=2"

well, none of our tutorials on how to compile, mention using -OPENGL_ES=2, this macro is used for compiling on Android and is not currently supported for windows.

https://github.com/mehah/otclient/wiki
