### ISSUE TITLE
Account or password incorrecto

### ISSUE THREAD

**Issue by lopez65** [opentibiabr/otclient#36]
Hello there
When I try to enter with the otclientdevelop it gives me the wrong account or password, I try it with the tibia 1064 and I enter without problems. Can somebody help me.

Thank you.

**Comment by MajestyOTBR** [comment]
https://github.com/opentibiabr/otclient#need-help

**Comment by MajestyOTBR** [comment]
The issue tracker is not a support forum, if you need help use the discord:
https://discord.com/invite/3NxYnyV

**Comment by MajestyOTBR** [comment]
The issue tracker is not a support forum, if you need help use the discord:
https://discord.com/invite/3NxYnyV
