### ISSUE TITLE
Bug on target monsters

### ISSUE THREAD

**Issue by samueldev45** [opentibiabr/otclient#360]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

The client is bugging the target when selecting mobs.

![image](https://user-images.githubusercontent.com/76446373/204278129-5136fe96-19d2-4ac1-988b-941522704574.png)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I don't understand, you are using the updated client and its modules, because the target bugs have already been corrected a while ago, however it is necessary to use the updated modules.

**Comment by patrykq112** [comment]
This bug still occurs. Happens if you don't have a battle window open.
