### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by br-it0** [opentibiabr/otclient#361]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Client crash when try move an item direct for a hotkey slot above chat logs.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
no crash here, are you using the updated client?

**Comment by br-it0** [comment]
> no crash here, are you using the updated client?
 
Sim, até na 2.0.1.

Então vou colocar em PT aqui pra tentar ser mais claro, me pareceu ser um pouco situacional, tentei reproduzir de várias formas diferentes, mas a que deu mais certo foi seguindo o seguinte passo. abrir o cliente e não fazer mais nada além de mover o item que não se usa em hotkey por padrão, armor por exemplo, direto do slot de armor do personagem para o box do hotkey que fica em cima dos chats.

**Comment by mehah** [comment]
2.0.1 é muito antigo, é preciso compilar o mais recente e testar, eu acabei de testar novamente, exatamente como vc reportou e não está dando crash,

**Comment by mehah** [comment]
poderia fazer um vídeo demonstrando o problema?

**Comment by br-it0** [comment]
> poderia fazer um vídeo demonstrando o problema?

Sim, claro.

Segue. https://youtu.be/ThR3O37LUlM

**Comment by mehah** [comment]
Então acabei de vê que vc está usando 2.0.1, por isso que está dando ruim, isso já foi corrigido, logo lançarei uma nova versão.

![image](https://user-images.githubusercontent.com/2267386/207465158-263aba25-5157-4259-9087-f14ccabb8352.png)

irei fechar, qnd eu lançar a nova versão e ainda continuar apresentando problema, vc abre novamente esse issue, mas testei aqui e está tudo ok.
