### ISSUE TITLE
Problem with sprites from Tibia 8.60.

### ISSUE THREAD

**Issue by anderkrox** [opentibiabr/otclient#363]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

In November I downloaded and compiled Otclient, I put it to work in version 8.60, but the sprites are having problems.
The sprites are stepping over each other incorrectly, and as I walk around the map, the situation reverses.
Depending on where I am, the sprites may or may not be normal.
![Capturar5](https://user-images.githubusercontent.com/103259709/205896031-1598a812-aa72-4b63-86fe-5239f86a10d1.JPG)
![Capturar4](https://user-images.githubusercontent.com/103259709/205896034-222b777b-27b9-460c-acdf-1f441ec192a2.JPG)
![Capturar3](https://user-images.githubusercontent.com/103259709/205896036-4d67ba18-f121-4b43-a7c5-80ddd38d43a9.JPG)
![Capturar2](https://user-images.githubusercontent.com/103259709/205896037-92f5efc1-4d80-47db-bd50-06cad7c25df3.JPG)
![Capturar](https://user-images.githubusercontent.com/103259709/205896039-35304d39-f481-494e-b561-2005f66e830a.JPG)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
compile in release mode.

and please, always when reporting, make sure you are using the most current revision, as any bugs you may find may have already been fixed.

**Comment by anderkrox** [comment]
My Otclient was compiled in release mode, however, this problem still happens, but today I found out what causes it.
That's when the "optimize fps" option is active.
When the "optimize fps" option is disabled then the problem doesn't happen.

**Comment by rodrigopaixaorj** [comment]
Renato, I'm having the same issue as everyone...
Just downloaded the sources today and compiled

Check it out (this is 8.6 version, managed to modify the client to read higher versions):
![GIF 06-12-2022 21-16-27](https://user-images.githubusercontent.com/7372287/206056228-25489253-be53-49f3-bbac-e503a7eb001a.gif)

Now with "Optimize FPS" disable and "Limit Visible Dimension" enabled:
![GIF 06-12-2022 21-26-05](https://user-images.githubusercontent.com/7372287/206056721-b524815f-ac8e-4012-b9db-9d1a18a7b054.gif)

**Comment by mehah** [comment]
this is very strange, what is your PC?
@anderkrox 
@Nottinghster

**Comment by rodrigopaixaorj** [comment]
@mehah Vou escrever em português mesmo:

Lenovo Legion y540
Processador: i7-9750HF
Placa de vídeo: RTX 2060 de 6 GB VRAM

Uma máquina mais que suficiente pra rodar qualquer coisa....

**Comment by mehah** [comment]
> @mehah Vou escrever em português mesmo:
> 
> Lenovo Legion y540 Processador: i7-9750HF Placa de vídeo: RTX 2060 de 6 GB VRAM
> 
> Uma máquina mais que suficiente pra rodar qualquer coisa....

Pois eh, me adiciona no discord
Mehah#7775

**Comment by anderkrox** [comment]
Mesmo caso do Nitthinghster, meu computador roda Cyberpunk

**Comment by anderkrox** [comment]
Note: I compiled the most current version and the problem no longer exists. You can close the topic!
