### ISSUE TITLE
OTC BUG IMAGEM

### ISSUE THREAD

**Issue by linkzzjr** [opentibiabr/otclient#365]
### Priority

Missing Content

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What is missing?

GOSTARIA DE SABER COMO RESOLVER ESSE PROBLEMA ... OS LUGARES DO MAPA FICAM PRETOS OU SOMEM 

GOSTARIA DE UMA AJUDA, SE POSSIVEL :/[https://ibb.co/jLb6ThT](url)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
bem possível que seja problema de protocolo, olha o console e ve se não há erros.

também não sei se você está usando o cliente mais atualizado, isso tb é relevante.

**Comment by mehah** [comment]
já q não obtive uma resposta, irei fechar o issue.
