### ISSUE TITLE
No items to browse on market,TFS 1.4.2 (1098)

### ISSUE THREAD

**Issue by ramosluis16** [opentibiabr/otclient#370]
### Priority

Medium

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

When i open market it show with not items to browse.

Image: https://ibb.co/KbbjHrq

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
The market was rewritten to work with Canary, if you want to use a market for TFS, you will need to rollback or get it from another otclient.

or adapt it to work on both distros and share it with us. :D

**Comment by mehah** [comment]
since I didn't get a response, I will close the issue.

**Comment by h4b00** [comment]
@mehah We should leave this information in the readme as many people may struggling with this

**Comment by mehah** [comment]
@h4b00 

I put it, but I believe a lot of people won't read it.

**Comment by h4b00** [comment]
@mehah 
Can you help me with this?
I don't want to open a next issue but it seems like a bug for me.

I imported clean 10.98 tibia.dat file & sprites.
This method gives me 0 results.
`g_things.findThingTypeByAttr(ThingAttrMarket, 0)` 

however if I use `ThingAttrCloth` it is working.

Any idea?

![image](https://user-images.githubusercontent.com/8171005/219184800-4b48745e-8318-4473-aaf6-1ea4ce785868.png)



I have found an issue

https://github.com/mehah/otclient/pull/423
