### ISSUE TITLE
Extended view port constants not working

### ISSUE THREAD

**Issue by ErikasKontenis** [opentibiabr/otclient#372]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Issue:
After change of the extended view port constants the view port is not extending and remaining the same. Example of 16x16 viewport changes in otclient and tfs sources.
![image](https://user-images.githubusercontent.com/33052216/207939467-dfffc4fb-c22f-41ce-afc9-1eee16f2a702.png)

Reproduce steps:
Pull the latest TFS sources and increase max client view port constants like x16,y16 or anything more. 
https://github.com/otland/forgottenserver/blob/master/src/map.h#L153
Apply the same changes to the latest otclient sources
https://github.com/mehah/otclient/blob/main/src/client/map.cpp#L41

Bonus ideas:
There is an otland thread about that in Aug 2022 it was still a working thing however now it does not.
https://otland.net/threads/tutorial-adding-more-tiles-to-game-window-updated-7-6-2018.228243/page-12#post-2703114

I am still new in otclient development so not that much sure where to fix for but will try to fix this issue myself too and make PR however tips or suggestions would be appreciated since today no idea where to look for :) 

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
did you zoom out?

ctrl + -

the extended view system is working perfectly, you probably don't know how to configure it.

**Comment by ErikasKontenis** [comment]
![image](https://user-images.githubusercontent.com/33052216/208147191-f6a995e7-5d31-4c1e-9fe3-8bdf060c6557.png)
I didn't knew about the ctrl +- functionality. It works perfectly indeed. Thank you!
