### ISSUE TITLE
Turning the chat on and off with the enter key doesn't work.

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#373]
### Priority

Medium

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Turning the chat on and off with the enter key doesn't work.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
here is working normally.

https://user-images.githubusercontent.com/2267386/209885518-306bceaf-6ac3-4c72-a95a-919e42ba4aec.mp4

**Comment by mehah** [comment]
well, since there was no response, I will close this issue.
