### ISSUE TITLE
animation bug in lastest source

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#378]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

In the latest source there is a bug with animations, it does not always occur every time a client is turned on.
![Animation](https://user-images.githubusercontent.com/16617982/209557593-d831c8ec-70d6-40ae-9044-c5ae1eff946e.gif)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrykq112** [comment]
![Animation2](https://user-images.githubusercontent.com/16617982/209561676-aceb6074-b60b-48d4-b206-0f1f43f4130f.gif)

**Comment by mehah** [comment]
you can test it?

**Comment by patrykq112** [comment]
> you can test it?

i just downloaded the latest source and the bug is still there. It's something with multithreading, because when I replaced the GraphicalApplication::run() function with the one without multithreading, the problem does not occur
![Animation3](https://user-images.githubusercontent.com/16617982/209586882-bb982c2f-edd5-4829-9fd1-364ff23cc0e4.gif)

**Comment by mehah** [comment]
Tibia version?

**Comment by patrykq112** [comment]
> Tibia version?

800

**Comment by mehah** [comment]
[1098]
![image](https://user-images.githubusercontent.com/2267386/209698455-74a3f252-01a3-4a66-8994-78170080a61b.png)

[860]
![image](https://user-images.githubusercontent.com/2267386/209698694-c3c0a08f-5445-43c4-9dd4-ace6628c564c.png)

I am not able to reproduce this problem, what are the steps you follow, do you simply walk to this area and it stays like this or do you already login to this area?

**Comment by patrykq112** [comment]
After yesterday's update, this problem no longer exists

**Comment by mehah** [comment]
that's good, I'll close, thank you.
