### ISSUE TITLE
NPC names lag

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#38]
### Steps to reproduce (include any configuration/script required to reproduce)
1.The name of npcs lags when walking,  but not on monsters or players.

![fLOBviYfpM](https://user-images.githubusercontent.com/61473553/96347301-14d1b980-10a1-11eb-90d5-d091dc680766.gif)

### Expected behaviour
Name should be stable when walking

### Actual behaviour
Lagg/Moving/Jump

### Environment
10.98 Latest version of TFS and your OTC sources

**Comment by mehah** [comment]
enable vsync
