### ISSUE TITLE
Where can i get BOT for this client?

### ISSUE THREAD

**Issue by zippo7291** [opentibiabr/otclient#381]
### Priority

Missing Content

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What is missing?

Im trying to figure out were to get the bot to be added to otclient. ive had no luck searching for it.
And ive also been told a bot is already added into the client?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zippo7291** [comment]
Am i able to put the otcv8 client bot into this?

**Comment by mehah** [comment]
there is a simple bot you can use.
https://github.com/strndi/otcbot

> Am i able to put the otcv8 client bot into this?

no

**Comment by pabloapdz** [comment]
> there is a simple bot you can use. https://github.com/strndi/otcbot
> 

I put that but the client doens't open =\
