### ISSUE TITLE
setChaseMode...

### ISSUE THREAD

**Issue by KaroKas** [opentibiabr/otclient#388]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Hello, i have  problem/question.. look:

https://img001.prntscr.com/file/img001/WdIaRp3SSde4mHkicJpj5w.png

make:
1. check on: chase Mode (after selecting a monster, the player follow it)
2. select any monster
3. left click somewhere on the map.

error: Normally the follow should turn off and the player should go to the clicked spot, but it doesn't happen in the console: 

```
ERROR: caught a lua call to a bot protected game function, the call was cancelled
stack traceback:
	[builtin#142]: at 0x7ff6f6e855a0
	[C]: in function 'setChaseMode'
```

function:
```
 function check()
     if modules.client_options.getOption('autoChaseOverride') then
         if g_game.isAttacking() and g_game.getChaseMode() == ChaseOpponent then
             g_game.setChaseMode(DontChase)
         end
     end
 end
```
if we leave on the keys (arrows) there is no such problem

2 Question: Is it possible to compile to make this version work under windows7? 

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
This is not a problem, there are actions you can't put on certain events, this was done to avoid using bots, you can configure it to disable bot-check on the event you want or disable the anti-bot system .

removing this line
https://github.com/mehah/otclient/blob/30fe3e032ff0c4afd5618c1e6cf14b9e2768fbc8/vc17/settings.props#L9

**Comment by mehah** [comment]
no user feedback.
