### ISSUE TITLE
crash after last update

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#390]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Crash after last Fix glGenerateMipmap

`build compiler: Visual Studio - x86
build date: Jan 19 2023
build type: RelWithDebInfo
crash date: Jan 19 2023 17:58:37
exception: Access violation (0xc0000005)
exception address: 0x007b9e8e
  backtrace:
    0: E:\otclient\otclient.exe(std::vector<std::pair<TRect<int>,TRect<int> >,std::allocator<std::pair<TRect<int>,TRect<int> > > >::_Emplace_reallocate<TRect<int> &,TRect<int> &>+0xbe) [0x00000000007B9E8E]
    1: E:\otclient\otclient.exe(std::vector<std::pair<TRect<int>,TRect<int> >,std::allocator<std::pair<TRect<int>,TRect<int> > > >::emplace_back<TRect<int> &,TRect<int> &>+0x5b) [0x00000000007B8BDB]
    2: E:\otclient\otclient.exe(UITextEdit::drawSelf+0xe9) [0x000000000087F079]
    3: E:\otclient\otclient.exe(UIWidget::draw+0x23f) [0x000000000088461F]
    4: E:\otclient\otclient.exe(UIWidget::drawChildren+0x12d) [0x00000000008848AD]
    5: E:\otclient\otclient.exe(UIWidget::draw+0x2d2) [0x00000000008846B2]
    6: E:\otclient\otclient.exe(UIWidget::drawChildren+0x12d) [0x00000000008848AD]
    7: E:\otclient\otclient.exe(UIWidget::draw+0x2d2) [0x00000000008846B2]
    8: E:\otclient\otclient.exe(UIWidget::drawChildren+0x12d) [0x00000000008848AD]
    9: E:\otclient\otclient.exe(UIWidget::draw+0x2d2) [0x00000000008846B2]
    10: E:\otclient\otclient.exe(UIWidget::drawChildren+0x12d) [0x00000000008848AD]
    11: E:\otclient\otclient.exe(UIWidget::draw+0x2d2) [0x00000000008846B2]
    12: E:\otclient\otclient.exe(UIWidget::drawChildren+0x12d) [0x00000000008848AD]
    13: E:\otclient\otclient.exe(UIWidget::draw+0x2d2) [0x00000000008846B2]
    14: E:\otclient\otclient.exe(UIWidget::drawChildren+0x12d) [0x00000000008848AD]
    15: E:\otclient\otclient.exe(UIWidget::draw+0x2d2) [0x00000000008846B2]
    16: E:\otclient\otclient.exe(UIWidget::drawChildren+0x12d) [0x00000000008848AD]
    17: E:\otclient\otclient.exe(UIWidget::draw+0x2d2) [0x00000000008846B2]
    18: E:\otclient\otclient.exe(UIManager::render+0xc6) [0x000000000087A8A6]
    19: E:\otclient\otclient.exe(std::thread::_Invoke<std::tuple<`GraphicalApplication::run'::`2'::<lambda_2> >,0>+0x63) [0x000000000079FB33]
    20: E:\otclient\otclient.exe(thread_start<unsigned int (__stdcall*)(void *),1>+0x58) [0x0000000000BD9905]
    21: C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x19) [0x0000000077BF00F9]
    22: C:\WINDOWS\SYSTEM32\ntdll.dll(RtlGetAppContainerNamedObjectPath+0x11e) [0x0000000077EB7BBE]
    23: C:\WINDOWS\SYSTEM32\ntdll.dll(RtlGetAppContainerNamedObjectPath+0xee) [0x0000000077EB7B8E]
`

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
how to reproduce, is it intermittent?

note: try to rebuild the whole project again.

**Comment by mehah** [comment]
No user feedback
