### ISSUE TITLE
small inconsistencies in the datapack

### ISSUE THREAD

**Issue by janmix** [opentibiabr/otclient#393]
### Priority

Low

### Area

- [X] Data
- [x] Source
- [ ] Docker
- [ ] Other

### What happened?

https://i.imgur.com/0kuDov7.png
Não sei se está acontecendo em todas versões, mas não está arredondando quando o personagem carrega um item com valor quebrado exemplo: "It weighs 2.70 oz."

https://i.imgur.com/j69Uf9y.png
Ao selecionar uma certa quantidade de itens para comprar no NPC exibe o valor correto de peso * quantidade, porem quando seleciona "buy with backpack" mostra o valor unitario. (caso selecione buy with backpack antes de determinar uma quantidade não acontece isso).

https://i.imgur.com/cdVnvFP.png
Apos a primeira modificação do speed padrão do personagem por magia ou item o valor que mostra fica vermelho (como se tivesse alguma penalidade na velocidade) e fica monstrando (65535 -64035)... Só uma obs. na imagem estava em uma conta de administrador, mas acontece igualmente em conta de jogadores.

lembrando que tudo isso ai foi testado em um servidor de versão 8.60, se acontece os mesmos erros nas versões mais novas não testei. Baixei ontem a ultima versão do cliente e fui notando isso, estava usando uma versão mais antiga.

Perdão caso não tenha elaborado corretamente o issue.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
Confirmo todos os bugs acima, também testado na versão 8.6x

**Comment by janmix** [comment]
Look apertando os dois botões ao mesmo tempo [left/right] (usando classic control) ao inves de shift+left na maioria das vezes não está funcinando. Se por exemplo tento dar look dessa forma em uma bag ela abre, se tento dar look em um piso o personagem anda até o sqm.
Se for necessario depois faço um gif mostrando.

**Comment by mehah** [comment]
testem ai por favor,

soul aqui está normal, testei no 772 e 1098

![image](https://user-images.githubusercontent.com/2267386/214188721-4d27aaff-836e-49c1-9ce8-b9d121a27a92.png)

> Look apertando os dois botões ao mesmo tempo [left/right] (usando classic control) ao inves de shift+left na maioria das vezes não está funcinando. Se por exemplo tento dar look dessa forma em uma bag ela abre, se tento dar look em um piso o personagem anda até o sqm. Se for necessario depois faço um gif mostrando.

nem sabia q tinha isso. :D

**Comment by janmix** [comment]
Quanto ao look sempre dei look dessa forma no tibia kkk, na versão de alguns meses atrás que eu estava usando funcionava o look normal do jeito que expliquei, mas essa mais atual não está.

Testei o cap/speed e aparentemente está funcionando corretamente agora.
Testei o peso tambem no NPC e aparentemente está funcionando corretamente tambem.

Edit: Acredito que o soul não estava com problemas, provavelmente foi algo que eu fiz de errado, agora já está normal.

**Comment by rodrigopaixaorj** [comment]
@mehah Todos os bugs relatados acima, de fato estão corrigidos, pode encerrar o issue ;)
@janmix sobre o look com os dois botões, basta pressionar o RMB e em seguida o LMB, isso com o Classic Control ativo

**Comment by janmix** [comment]
> @mehah Todos os bugs relatados acima, de fato estão corrigidos, pode encerrar o issue ;) @janmix sobre o look com os dois botões, basta pressionar o RMB e em seguida o LMB, isso com o Classic Control ativo

na realidade não, tenta dar look em uma bag ou backpack da forma que voce falou, vai abrir ela, depois vou fazer um gif mostrando em uma versão mais antiga do cliente e essa mais nova, pq esse tipo de look é basicamente apertando os dois ao mesmo tempo RMB e LMB, não um e em seguida o outro, só fazer o teste ai depois que vai ver o que acontece, mas sim os issues reportados já foram corrigidos, só ficou isso ai mesmo do look que tá estranho pra mim.

**Comment by mehah** [comment]
> na realidade não, tenta dar look em uma bag ou backpack da forma que voce falou, vai abrir ela, depois vou fazer um gif mostrando em uma versão mais antiga do cliente e essa mais nova, pq esse tipo de look é basicamente apertando os dois ao mesmo tempo RMB e LMB, não um e em seguida o outro, só fazer o teste ai depois que vai ver o que acontece, mas sim os issues reportados já foram corrigidos, só ficou isso ai mesmo do look que tá estranho pra mim.

infelizmente vou ficar devendo essa, essa bug ocorre por causa do multi-thread e não vale o esforço para tentar corrigir,

só explicando, esse bug ocorre pois os eventos executados do click, são enviando para a segunda thread e isso tem um delay e sinceramente, não vou perder tempo procurando uma solução para isso, sugiro que, para não deixar de utilizar essa função, pressionar o botão esquerdo e dps clica com o direito, invés de clicar ambos simultaneamente.

**Comment by mehah** [comment]
pronto galerinha, tudo corrigido, irei fechar.

nota: bem q vcs podiam ajudar com uns módulos em... :smile:
