### ISSUE TITLE
only support outdated 10.00 and version 12.00 allowed

### ISSUE THREAD

**Issue by kozmo604** [opentibiabr/otclient#4]
First time using OTClient do i have to add my ip somewhere inside of otclient folder?
How come i am getting this error when i used the 10 client dat and spr?

**Comment by MajestyOTBR** [comment]
Change in server config.lua:
`clientVersionMin = 1100` 
to 
`clientVersionMin = 1000`

This will be changed soon.

**Comment by kozmo604** [comment]
I could login but see no sprites its just a black screen i added 10.00 spr
and dat like github said.
and if some random person were to use this how does it know to login to my
server?
