### ISSUE TITLE
Can't use items that are covered by some item on above floor and when item have flag: Bottom in ObjectBuilder don't have "Use" action to use item too.

### ISSUE THREAD

**Issue by wmaestrots** [opentibiabr/otclient#4]
If you have flag at Item in object builder: Bottom, on item for example: window (and you want to close window by using it) or on other item you have Bottom flag. In game - client don't have "Use" action. ( **LEFT screen** )

also if you have any item on upper floor ( **RIGHT screen** ) for example sewer crate that normally is able to open (before Mehah changes with drawFlags) by "Use" action and is covered with item that is on above floor (ex. tree leaves) you CAN'T use item that is covered by something on upper floor.

Screen:
https://i.imgur.com/r5T6zjI.png

**Comment by mehah** [comment]
Fixed
