### ISSUE TITLE
Monsters isNpc bug

### ISSUE THREAD

**Issue by trzzu** [opentibiabr/otclient#40]
Hello, i found a small bug, monsters are NPC.

![isnpc1](https://user-images.githubusercontent.com/76270247/102703012-c4760400-4269-11eb-944e-847a168b86b7.png)

**Comment by mehah** [comment]
normal here
![testenpc](https://user-images.githubusercontent.com/2267386/102703776-085d0f00-4252-11eb-8139-5596272d8a3d.png)
