### ISSUE TITLE
diagonal walking 

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#401]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

In my case there is a problem with walking on the diagonal  (7 9 3 1 numeric keypad).
After walking 1-2 sqm on a slant, click on the map with the mouse to make the character move on > takes a step > gets 'lag' you can see that he walks in place and moves to the clicked spot 

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
Check this:
https://github.com/otland/forgottenserver/blob/master/src/creature.cpp#L484

**Comment by mehah** [comment]
as @Nottinghster mentioned, it's very likely that it's a formula problem, check if your server's formula is the same as the client's.

pay attention to this:
https://github.com/mehah/otclient/blob/601f89d78f0439739385d5de13f92d36e975ead2/init.lua#L7

people are mixing formulas of a protocol X with Y and that will be a big problem.

**Comment by mehah** [comment]
no user feedback.
