### ISSUE TITLE
Walking bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#402]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I found a walking bug. Occurs when the creature has an item outfit.
![bug](https://user-images.githubusercontent.com/16617982/216124370-32d2f4f4-e478-409d-8199-a5ea58fabe1f.gif)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
this is totally out of tibia reality and you are mixing isometric with top down.

**Comment by patrykq112** [comment]
> this is totally out of tibia reality and you are mixing isometric with top down.

It doesn't matter what graphics I use, because it's a bug in the source. Look:
![image](https://user-images.githubusercontent.com/16617982/216178490-0c80c5ce-9ba4-48a0-a113-3ae8a0117f00.png)
![image](https://user-images.githubusercontent.com/16617982/216178634-bfa7658d-1b06-4f56-aeb0-6ba3b2bcd6a7.png)
![image](https://user-images.githubusercontent.com/16617982/216178676-347e4273-d97e-46ef-ba60-9e8058593154.png)
![image](https://user-images.githubusercontent.com/16617982/216178714-7707bbac-d229-42ec-ab43-7b211fd51ee9.png)

When we change the outfit to an item then the m_thingType is replaced with that of the item and returns the functions "isGround", "isGroundBorder", "isOnBottom", "isOnTop" of this item.

**Comment by patrykq112** [comment]
If someone is looking for a solution to this error, you should change the function int Thing::getStackPriority() to this:

`int Thing::getStackPriority()
{
    if (isCreature())
        return 4;

    if (isGround())
        return 0;

    if (isGroundBorder())
        return 1;

    if (isOnBottom())
        return 2;

    if (isOnTop())
        return 3;

    // common items
    return 5;
}`

**Comment by patrykq112** [comment]
If someone is looking for a solution to this bug, you should change the function int Thing::getStackPriority() to this:

```
int Thing::getStackPriority()
{
    if (isCreature())
        return 4;

    if (isGround())
        return 0;

    if (isGroundBorder())
        return 1;

    if (isOnBottom())
        return 2;

    if (isOnTop())
        return 3;

    // common items
    return 5;
}
```

**Comment by patrykq112** [comment]
@mehah Check it out and make changes to the source.

**Comment by mehah** [comment]
@patrykq112 
as you pointed out where the problem could probably be occurring, so it was easier to solve. test and see if it works.

**Comment by patrykq112** [comment]
The problem is solved, I close the issue
