### ISSUE TITLE
Outfit render picker scaling issues

### ISSUE THREAD

**Issue by xmish** [opentibiabr/otclient#405]
### Priority

Low

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

There's a problem with rendering scaled outift in Outfit selection window.
Some outfits look bad in a preview (sprite mask is applied with little shift- some rounding issue maybe when scale factor is applied)

![obraz](https://user-images.githubusercontent.com/95135755/217343780-f17144bf-3208-451a-ab52-964c2fab13a6.png)
![obraz](https://user-images.githubusercontent.com/95135755/217345903-8d08c763-4f5b-4a08-a21c-c6e9ee823eab.png)

Fox some old style even worse (white on shoes)
```<outfit type="1" looktype="160" name="Dwarf" premium="no" unlocked="no" enabled="yes" />```

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
![image](https://user-images.githubusercontent.com/2267386/217371217-942d0a14-fa36-4726-b8bf-0bbf244e00c1.png)
I applied scale 2x and look how it turned out.
