### ISSUE TITLE
countWindow issue - keyboard navigation

### ISSUE THREAD

**Issue by xmish** [opentibiabr/otclient#410]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

There's a issue with SpinBox, there's no way to change item count with keyboard

![obraz](https://user-images.githubusercontent.com/95135755/218255403-04736b6e-24da-477a-b483-8889405bf1db.png)

Errors:
![obraz](https://user-images.githubusercontent.com/95135755/218255387-e2ce734f-47b9-4956-8f0e-b1f8d46a4de6.png)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by xmish** [comment]
Note: while debugging that I also found out that reload `CTRL+SHIFT+R` crashes entire client

**Comment by xmish** [comment]
Fix:
`up()` => `upSpin()`
`down()` => `downSpin()`
Seems like in the base class it's a `field`

**Comment by mehah** [comment]
> Note: while debugging that I also found out that reload `CTRL+SHIFT+R` crashes entire client

use auto-reload
https://github.com/mehah/otclient/blob/1026132e3dfa661807a1ff10ced2f4e09f1b7a7d/init.lua#L4
