### ISSUE TITLE
Attach System

### ISSUE THREAD

**Issue by mattpozzobon** [opentibiabr/otclient#411]
### Priority

Enhancement

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What is missing?

Primeiramente desculpa se é a area errada pra fazer perguntas, eu nao sabia onde perguntar... O meu problema é mais uma duvida do que qualquer outra coisa, eu estou tentando entender o attached system. Pelo que eu entendi os efeitos sao criados usando o lua e importados pelo cliente, porem como eu posso fazer para os efeitos serem visiveis para todos os players e nao apenas o local player? 

Espero que a pergunta tenha feito sentido e mais uma vez, desculpe e obrigado

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
O local para dúvidas é aqui: https://discord.gg/tRCx7MGp

**Comment by mattpozzobon** [comment]
@dudantas Otimo, obrigado!
