### ISSUE TITLE
Draw delay

### ISSUE THREAD

**Issue by rodrigopaixaorj** [opentibiabr/otclient#412]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

https://user-images.githubusercontent.com/7372287/218318760-b0c5ff3a-ac5f-46a8-8f34-9e71817870e8.mp4

![GIF_11-02-2023_02-41-06](https://user-images.githubusercontent.com/7372287/218318766-f8f302ea-4dc7-456a-88d2-f7ed2404728a.gif)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
fix https://github.com/mehah/otclient/commit/8ec5cb598ad81f41d553c48f057bdcf8702f0966
