### ISSUE TITLE
Move Stackable Item window

### ISSUE THREAD

**Issue by rodrigopaixaorj** [opentibiabr/otclient#413]
### Priority

Low

### Area

- [x] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

https://user-images.githubusercontent.com/7372287/218320937-5c038341-6cac-4a8a-b844-8be11a472211.mp4

If you move a stackable item, and then click outside the stackable item window, the window should disappear, and not move/control the character

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xmish** [comment]
On real client if you have this window open there's even no way to click on map, there's like a transparent overlay (whole interface is locked) and clicking outside has no effect at all. Onyl `Escape/Enter` or `Ok/Cancel` buttons can be used to close it. 

But it's rather a thing of OTClient layout, if it's regular behavior for other dialogs then it should be unified.
From what I see things like "Edit text" dialogs (e.g. labels) works exactly like "Move stackable Item".
