### ISSUE TITLE
Fullscreen Crash Client

### ISSUE THREAD

**Issue by rodrigopaixaorj** [opentibiabr/otclient#414]
### Priority

Critical

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

As posted in Discord channel (https://discord.com/channels/888062548082061433/888132186446917663/1074136924794654770), if you press "CTRL+SHIFT+F" 3 times, it will crash the client

https://user-images.githubusercontent.com/7372287/218321748-68500884-2ae1-453c-bbed-af6ccbd77a71.mp4

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by themaoci** [comment]
its something with setFullscreen code in framework c++ files
error i captured is
Exception thrown at 0x76BCB812 (KernelBase.dll) in otclient.exe: 0xE24C4A02.

**Comment by mehah** [comment]
fixed https://github.com/mehah/otclient/commit/943c3bb54a608a926b2db51a40a67879baa509d9
