### ISSUE TITLE
Missing attack square

### ISSUE THREAD

**Issue by rodrigopaixaorj** [opentibiabr/otclient#416]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Attack square doesn't showing, only if you use Battle Window

https://user-images.githubusercontent.com/7372287/218449115-83c1f03f-ea4e-40e8-9a3e-0cc28bce6104.mp4

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xmish** [comment]
At the battle list, creatures are walking 😮 
They should stay still facing south I think.

**Comment by xmish** [comment]
#416 Cannot reproduce on  56c8f7f57ccfac607d0f54aa8e5cde3da54dee42 , seems like a valid fix 2me

**Comment by rodrigopaixaorj** [comment]
> Cannot reproduce on [56c8f7f](https://github.com/mehah/otclient/commit/56c8f7f57ccfac607d0f54aa8e5cde3da54dee42) , seems like a valid fix 2me

Isn't fixed, they're still walking in battle list...

**Comment by xmish** [comment]
> > Cannot reproduce on [56c8f7f](https://github.com/mehah/otclient/commit/56c8f7f57ccfac607d0f54aa8e5cde3da54dee42) , seems like a valid fix 2me
> 
> Isn't fixed, they're still walking in battle list...

Sorry, I meant the reported issue with red attack square

**Comment by xmish** [comment]
@mehah What about these walking creatures in battle window?

**Comment by mehah** [comment]
> @mehah What about these walking creatures in battle window?

I didn't understand.

**Comment by xmish** [comment]
@mehah They're constantly rendered, walking animation is shown, they change direction:
![anim](https://user-images.githubusercontent.com/95135755/219112365-fa5eb33a-d5e2-4fb9-9bf2-719b6090d24f.gif)
