### ISSUE TITLE
Sidestep bug through corners

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#42]
When you sidestep through corners, player light disappears. 
I have tried both below and above sea floor and it is the same.

![e8Mj3Vr4q4](https://user-images.githubusercontent.com/61473553/103046916-2c8a5a00-458a-11eb-921e-3a3fdab6ffe9.gif)
![wPGCMvnbl1](https://user-images.githubusercontent.com/61473553/103046923-31e7a480-458a-11eb-94f5-67ab2421bba0.gif)

**Comment by Klonoa88** [comment]
Latest TFS and your OtClient

**Comment by mehah** [comment]
I'm not able to simulate, I would have any tips, of the object that is happening or if it is a specific corner?

or even share at least that part of the map.

**Comment by mehah** [comment]
I couldn't simulate it your way, but I found other problems that caused this blinker, could you test again?

**Comment by Klonoa88** [comment]
I have tried your changes now and it's still the same :(

**Comment by mehah** [comment]
could you give me more details, even a part of the map, because I'm not able to simulate here.

**Comment by Klonoa88** [comment]
It is the same here.
![QSB8rM7SSw](https://user-images.githubusercontent.com/61473553/103089112-43ae6380-45ed-11eb-895e-f1c51ffbf1b4.gif)

But if I remove the stone and the tile/border over me (corner), it works
![kTFw6r8iRy](https://user-images.githubusercontent.com/61473553/103089160-617bc880-45ed-11eb-9bca-0e4e6c353489.gif)

**Comment by mehah** [comment]
can you export that part of the map for me?

**Comment by Klonoa88** [comment]
We use custom items but it should work if you take import in map editor
https://easyupload.io/h3laak

**Comment by Klonoa88** [comment]
Same here floor 9
https://easyupload.io/jac0rp

![103046916-2c8a5a00-458a-11eb-921e-3a3fdab6ffe9](https://user-images.githubusercontent.com/61473553/103090198-9f2e2080-45f0-11eb-8468-f02cca94ac53.gif)

**Comment by mehah** [comment]
me adiciona o discord se for possivel: Mehah#7775

**Comment by mehah** [comment]
add me the discord if possible: Mehah#7775, because I am not able to open your map in RME and apparently the townid is not configured a correct position to be born and therefore, I am unable to enter the game.

> [Error - IOLoginData::loadPlayer] Teste has Town ID 1 which doesn't exist

**Comment by Klonoa88** [comment]
I have set town id for you. Town id 1
https://easyupload.io/yztq07

**Comment by mehah** [comment]
![spriteerror](https://user-images.githubusercontent.com/2267386/103094254-ac8ce000-45db-11eb-8587-38fbd3f67524.png)

> [Warning - IOMap::loadMap] This map needs an updated items.otb. 

:weary:

**Comment by Klonoa88** [comment]
Here:
https://easyupload.io/50c8vh

**Comment by mehah** [comment]
![spriteerror](https://user-images.githubusercontent.com/2267386/103095397-3e4a1c80-45df-11eb-9e7b-aa315c71ea67.png)

what is the version of your sprite/dat, I am using 11.40.

-- Edited:

**I managed to simulate, I will be analyzing here.**

**Comment by Klonoa88** [comment]
We use modified dat/ spr/ items (10.76) with transparent

**Comment by mehah** [comment]
test again

**Comment by Klonoa88** [comment]
Now it works as it should with corners. But it has become a new bug with your recent changes. Effects and Missiles are now drawn strangely and Light from Effects and Missiles sometimes passes through floors

Draw Bug
https://imgur.com/E4vt8W3
https://imgur.com/MmVtXuL

Light Bug
https://imgur.com/vOxQ9ly

**Comment by mehah** [comment]
the dark part of the map was fixed, but the missile light did not occur here.

**Comment by Klonoa88** [comment]
The draw bug is now fixed but light is still coming through floors. When walking and stand still etc.
https://i.imgur.com/iWnjAPY.gif
https://i.imgur.com/StDFLbt.gif

**Comment by mehah** [comment]
can you send me that part of the map and tell me how to simulate?

**Comment by Klonoa88** [comment]
> 
> 
> The draw bug is now fixed but light is still coming through floors. When walking and stand still etc.
> https://i.imgur.com/iWnjAPY.gif
> https://i.imgur.com/StDFLbt.gif


> 
> 
> can you send me that part of the map and tell me how to simulate?

This commit [fix for #42](https://github.com/mehah/otclient/commit/3c7d61686a6afdcade33ab018167a84d04b24286) is the problem.

It is creature light that goes through floors when they walk around.

**Comment by Klonoa88** [comment]
> 
> 
> can you send me that part of the map and tell me how to simulate?

**Comment by Klonoa88** [comment]
An example .. Spawn (/m) an Worker Golem or a War Golem under ground (Floor 10) and let him fight with an equal creature (/summon). Jump up one floor (/up) and walk around. Then you will see their creature light area, You see it most when you walk around yourself, but also when they move. The light flashes and then disappears.

I'm sure it's commit [fix for #42](https://github.com/mehah/otclient/commit/3c7d61686a6afdcade33ab018167a84d04b24286). It fixed the light problem of player walk through corners, but destroyed creature light in general. Creature Light worked as it should through floors before that commit.

**Comment by mehah** [comment]
confirm to me if it's ok now.

**Comment by Klonoa88** [comment]
Now it works :) Good job. You can close this now.
