### ISSUE TITLE
Item marking bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#420]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

The bug occurs when the item is transparent. See gif:
![mark bug](https://user-images.githubusercontent.com/16617982/219080686-2074fd5f-0243-42c1-b9af-ea4d91e57482.gif)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrykq112** [comment]
Fix:

```
void Item::internalDraw(int animationPhase, const Point& dest, const Color& color, bool isMarked, uint32_t flags, LightView* lightView)
{
    if (isMarked)
        g_drawPool.setShaderProgram(g_painter->getReplaceColorShader(), true);
    else {
        drawAttachedEffect(dest, lightView, false); // On Bottom
        if (m_shader)
            g_drawPool.setShaderProgram(m_shader, true, m_shaderAction);
    }
    getThingType()->draw(dest, 0, m_numPatternX, m_numPatternY, m_numPatternZ, animationPhase, flags, color, lightView, m_drawConductor);
    if (!isMarked)
        drawAttachedEffect(dest, lightView, true); // On Top
        
    if(isMarked || m_shader)
        g_drawPool.resetShaderProgram();
}
```

**Comment by mehah** [comment]
can you test this solution?

**Comment by kokekanon** [comment]
Work , solution of patrykq

**Comment by patrykq112** [comment]
> can you test this solution?

Your fix doesn't work, the solution I provided works

**Comment by mehah** [comment]
@patrykq112 
the solution is not to reset the shader, because it wasn't supposed to be drawn something that you can't see.

- I have some questions, is this transparent object needed on the map?
- This transparency was made by an image editor, as the client currently does not know how to identify whether it is fully transparent or not, just by the m_opacity property, color.af, ...
