### ISSUE TITLE
player does not appear in the battle if he is in the same sqm

### ISSUE THREAD

**Issue by ericcobblepot** [opentibiabr/otclient#421]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

I have this bug
For some reason, if I go up a stairs(both on floor +1 or -1) and there is a player in the square that I go up, he doesn't appear in the battle This bug only occurs in otc (v8, mehah)

**I think it's not the client. because it works on other servers** but the classic client does work

video is
nekiro 1.5 8.00 clean (edit map add lader) + mehah 2.8 clean (v8 same)

After 3 days trying to fix it, I come to ask for help xd

I have tried several things, I think the solution is in the **checkCreatures() function (module / game_battle)**

https://user-images.githubusercontent.com/125500615/219124552-2076b88f-bafa-4e20-add6-bd9e6010ebee.mp4

```
if there is player in the same stack then
checkCreatures()
end --xd something very crude xd

```

additional lursky user information in otland

"Well, server sends the information:"

![1676490263641](https://user-images.githubusercontent.com/125500615/219148620-97990550-31f1-4edc-a5ca-eef3f85c3b17.png)

"otclient:"
![1676490294619](https://user-images.githubusercontent.com/125500615/219154217-0ab1c368-829a-43a7-a803-84920bc48285.png)

"It's most likely:"

https://github.com/mehah/otclient/blob/main/modules/game_battle/battle.lua#L410

`   local spectators = modules.game_interface.getMapPanel():getSpectators()`

src
`std::vector<CreaturePtr> getSpectators(const Position& centerPos, bool multiFloor)`

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xmish** [comment]
![appear](https://user-images.githubusercontent.com/95135755/219160356-80040ee6-6994-46ae-a6a4-f0341541c0bc.gif)

Confirm, will test that on newer protcol to test if it's something with "canWalkthrough" but on CipClient it works fine so not a server issue
EDIT: On 12.x  protocol it works fine

**Comment by xmish** [comment]
Moved `m_oldPosition` assign into event at it works:
```cpp
void Creature::onDisappear()
{
    if (m_disappearEvent)
        m_disappearEvent->cancel();

    m_oldPosition = m_position;

    // a pair onDisappear and onAppear events are fired even when creatures walks or turns,
    // so we must filter

    const auto self = static_self_cast<Creature>();
    m_disappearEvent = g_dispatcher.addEvent([self] {
        self->m_removed = true;
        self->stopWalk();
...
    });

    Thing::onDisappear();
}
```

to

```cpp
void Creature::onDisappear()
{
    if (m_disappearEvent)
        m_disappearEvent->cancel();

    const auto oldPosition = m_position;
    // a pair onDisappear and onAppear events are fired even when creatures walks or turns,
    // so we must filter
    const auto self = static_self_cast<Creature>();
    m_disappearEvent = g_dispatcher.addEvent([self, oldPosition] {
        self->m_oldPosition = oldPosition;
        self->m_removed = true;
        self->stopWalk();
...
    });

    Thing::onDisappear();
}
```

**Comment by mehah** [comment]
this only occurs in older protocols, as I am not able to simulate in 1098.?

update1:
I just tested it with 8.6 and it works fine.

**Comment by ericcobblepot** [comment]
> Moved `m_oldPosition` assign into event at it works:
> 
> ```c++
> void Creature::onDisappear()
> {
>     if (m_disappearEvent)
>         m_disappearEvent->cancel();
> 
>     m_oldPosition = m_position;
> 
>     // a pair onDisappear and onAppear events are fired even when creatures walks or turns,
>     // so we must filter
> 
>     const auto self = static_self_cast<Creature>();
>     m_disappearEvent = g_dispatcher.addEvent([self] {
>         self->m_removed = true;
>         self->stopWalk();
> ...
>     });
> 
>     Thing::onDisappear();
> }
> ```
> 
> to
> 
> ```c++
> void Creature::onDisappear()
> {
>     if (m_disappearEvent)
>         m_disappearEvent->cancel();
> 
>     const auto oldPosition = m_position;
>     // a pair onDisappear and onAppear events are fired even when creatures walks or turns,
>     // so we must filter
>     const auto self = static_self_cast<Creature>();
>     m_disappearEvent = g_dispatcher.addEvent([self, oldPosition] {
>         self->m_oldPosition = oldPosition;
>         self->m_removed = true;
>         self->stopWalk();
> ...
>     });
> 
>     Thing::onDisappear();
> }

it works, it appears in the battle but
I think that change generates a performance problem





https://user-images.githubusercontent.com/125500615/219214527-d12c541f-6b42-4f20-91d8-eb18a634293b.mp4

**Comment by xmish** [comment]
@ericcobblepot Yea it was only to check why it's like that, as on `Creature::onAppear()` it cancels `m_disappearEvent` and there are some checks like `m_oldPosition != m_position`

**Comment by xmish** [comment]
@mehah I'll check other distros implementation of `GetTileDescription` and let you know

**Comment by xmish** [comment]
@mehah 
Tried with few other distributions and problem is still there (only on OTC, nonOTC client works fine):
https://github.com/Brunowots/RealMap-Global-8.0-TFS1.2
https://github.com/Ezzz-dev/OTHire

It seemed to work when I reworked order of sending creature to the client (reversed) but that change causes bugs for nonOTC players.

I mainly played with:
`Tile::getClientIndexOfCreature` & `Tile::getStackposOfCreature`
https://github.com/Brunowots/RealMap-Global-8.0-TFS1.2/blob/main/src/tile.cpp#L1140
https://github.com/Brunowots/RealMap-Global-8.0-TFS1.2/blob/main/src/tile.cpp#L1166


`creatures->insert(creatures->end(), creature);`
https://github.com/Brunowots/RealMap-Global-8.0-TFS1.2/blob/main/src/tile.cpp#L1400
https://github.com/Brunowots/RealMap-Global-8.0-TFS1.2/blob/main/src/tile.cpp#L799


`Map::moveCreature`
`oldStackPosVector.push_back(oldTile.getClientIndexOfCreature(tmpPlayer, &creature));`
`tmpPlayer->sendCreatureMove(&creature, newPos, newTile.getStackposOfCreature(tmpPlayer, &creature), oldPos, stackpos, teleport);`
https://github.com/Brunowots/RealMap-Global-8.0-TFS1.2/blob/main/src/map.cpp#L245

**Comment by xmish** [comment]
@mehah Comparison:
![client](https://user-images.githubusercontent.com/95135755/219446330-f06cbd14-ecf9-4614-8b6c-44884c9d33b6.gif)

**Comment by mehah** [comment]
@xmish 
I just need a server and the client so I can test.

**Comment by xmish** [comment]
@mehah sent you server deatils & credentials on forum

**Comment by kokekanon** [comment]
I also have this error xd, I had not noticed, someone discovered the solution?

in v8 and client CipSoft works correctly.

1.5 nekiro downgrade 8.00
