### ISSUE TITLE
fps bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#424]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

The fps limit does not work properly if it is set below 'max'. Fps is well below the set limit.
![fps limit](https://user-images.githubusercontent.com/16617982/219332258-a5a4151e-4cca-4278-9f68-5675d59cc467.png)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I came back with the limit for 200, because it is not computing correctly above that value..

**Comment by patrykq112** [comment]
@mehah the bug still occurs after returning.
![image](https://user-images.githubusercontent.com/16617982/219448909-42b4f63c-3e94-4e03-9cc8-c8462af7fcfa.png)

**Comment by mehah** [comment]
- did you clean the project?
- are you in the game or in the ui?

![image](https://user-images.githubusercontent.com/2267386/219458109-e2d5181a-fbcc-44a2-b13b-a8174aab3977.png)

**Comment by themaoci** [comment]
for me this feature works well... i have similar problem it ended up that some programs was blocking my fps'es
1. ingame settings
2. riva tuner
3. nvidia control panel
