### ISSUE TITLE
Starting Client on windows 7 (even VM) crashes

### ISSUE THREAD

**Issue by themaoci** [opentibiabr/otclient#428]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Compile build on windows 10 and run on windows 7 (that's what i tested cause i think you cant compile it anywhere else...)

I found a way to skip CreateFile2 error but it showed next error...

vcpkg.json
```json
{  
  "name": "otclient",  
  "version-string": "1.0.0",  
  "dependencies": [  
    "asio",  
    "libogg",  
    "libvorbis",  
    "nlohmann-json",  
    "openal-soft",  
    "openssl",  
    "physfs",  
    "protobuf",  
    "zlib",  
    "liblzma",  
    "parallel-hashmap",  
    "stduuid",  
    "discord-rpc",  
    {  
      "name": "luajit",  
      "platform": "!android"  
    },  
    {  
      "name": "opengl",  
      "platform": "windows | linux"  
    },  
    {  
      "name": "glew",  
      "platform": "windows | osx"  
    }  
  ],  
  "overrides": [  
    {  
      "name": "physfs",  
      "version-semver": "3.0.2",  
      "port-version": 7  
    }  
  ],  
  "builtin-baseline":"0e67f312e831b4b897c7f492cf1e2858522c6e18"  
}
```

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by themaoci** [comment]
if i will have a 32 bit 1.0 version with source for it (cant find release for it for some reason...) i could test that as well i remember old version was working on win7

**Comment by patrykq112** [comment]
it's not windows 7's fault, if you don't have OpenGL version >= 2.0 then it's a crash.

**Comment by themaoci** [comment]
![image](https://user-images.githubusercontent.com/33422088/220769784-6d60776e-13b9-4db3-8eea-6a7cb73fcc57.png)

**Comment by themaoci** [comment]
after lots of testings i got left jsut with "opengl" not meets minimal requiremtns / because i was running windows 7 on virtual machine and it capped opengl on v1.1 where as someone above stated minimum required is 2.0+
there is no errors with createfile2 not found etc.
game just starts and closes after that (for my virtual machine), will wait on my friend to do futher testing but so far editing vcpkg.json file in such manner (as below) fixed most of problems

```json
{
  "name": "otclient",
  "version-string": "1.0.0",
  "dependencies": [
    "asio",
    "libogg",
    "libvorbis",
    "nlohmann-json",
    "openal-soft",
    "openssl",
    "physfs",
    "protobuf",
    "zlib",
    "liblzma",
    "parallel-hashmap",
    "stduuid",
    "discord-rpc",
    {
      "name": "luajit",
      "platform": "!android"
    },
    {
      "name": "opengl",
      "platform": "windows | linux"
    },
    {
      "name": "glew",
      "platform": "windows | osx"
    }
  ],
  "overrides": [
    {
      "name": "physfs",
      "version-semver": "3.0.2",
      "port-version": 7
    },
    {
      "name": "opengl",
      "version-date": "2022-03-14",
      "port-version": 0
    },
    {
      "name": "glew",
      "version-semver": "2.2.0",
      "port-version": 0
    },
    {
      "name": "openal-soft",
      "version-semver": "1.22.2",
      "port-version": 0
    },
    {
      "name": "protobuf",
      "version-semver": "3.21.6",
      "port-version": 0
    },
    {
      "name": "asio",
      "version-semver": "1.23.0",
      "port-version": 0
    }
  ],
  "builtin-baseline":"0e67f312e831b4b897c7f492cf1e2858522c6e18"
}
```

**Comment by mehah** [comment]
the project no longer supports opengl 1.0, so the problem must be there.

opengl 1.0 is very old.

**Comment by themaoci** [comment]
@mehah it seems that this vcpkg.json fixes the issue and runs on windows 7 like a butter :)

```json
{
  "name": "otclient",
  "version-string": "1.0.0",
  "dependencies": [
    "asio",
    "libogg",
    "libvorbis",
    "nlohmann-json",
    "openal-soft",
    "openssl",
    "physfs",
    "protobuf",
    "zlib",
    "liblzma",
    "parallel-hashmap",
    "stduuid",
    "discord-rpc",
    {
      "name": "luajit",
      "platform": "!android"
    },
    {
      "name": "opengl",
      "platform": "windows | linux"
    },
    {
      "name": "glew",
      "platform": "windows | osx"
    }
  ],
  "overrides": [
    {
      "name": "physfs",
      "version-semver": "3.0.2",
      "port-version": 7
    },
    {
      "name": "opengl",
      "version-date": "2022-03-14",
      "port-version": 0
    },
    {
      "name": "glew",
      "version-semver": "2.2.0",
      "port-version": 0
    },
    {
      "name": "openal-soft",
      "version-semver": "1.22.2",
      "port-version": 0
    },
    {
      "name": "protobuf",
      "version-semver": "3.21.6",
      "port-version": 0
    },
    {
      "name": "asio",
      "version-semver": "1.23.0",
      "port-version": 0
    }
  ],
  "builtin-baseline":"0e67f312e831b4b897c7f492cf1e2858522c6e18"
}
```
if you could please replace it with the current vcpkg.json in the project thanks :)

**Comment by dudantas** [comment]
> @mehah it seems that this vcpkg.json fixes the issue and runs on windows 7 like a butter :)
> 
> ```json
> {
>   "name": "otclient",
>   "version-string": "1.0.0",
>   "dependencies": [
>     "asio",
>     "libogg",
>     "libvorbis",
>     "nlohmann-json",
>     "openal-soft",
>     "openssl",
>     "physfs",
>     "protobuf",
>     "zlib",
>     "liblzma",
>     "parallel-hashmap",
>     "stduuid",
>     "discord-rpc",
>     {
>       "name": "luajit",
>       "platform": "!android"
>     },
>     {
>       "name": "opengl",
>       "platform": "windows | linux"
>     },
>     {
>       "name": "glew",
>       "platform": "windows | osx"
>     }
>   ],
>   "overrides": [
>     {
>       "name": "physfs",
>       "version-semver": "3.0.2",
>       "port-version": 7
>     },
>     {
>       "name": "opengl",
>       "version-date": "2022-03-14",
>       "port-version": 0
>     },
>     {
>       "name": "glew",
>       "version-semver": "2.2.0",
>       "port-version": 0
>     },
>     {
>       "name": "openal-soft",
>       "version-semver": "1.22.2",
>       "port-version": 0
>     },
>     {
>       "name": "protobuf",
>       "version-semver": "3.21.6",
>       "port-version": 0
>     },
>     {
>       "name": "asio",
>       "version-semver": "1.23.0",
>       "port-version": 0
>     }
>   ],
>   "builtin-baseline":"0e67f312e831b4b897c7f492cf1e2858522c6e18"
> }
> ```
> 
> if you could please replace it with the current vcpkg.json in the project thanks :)

I'm not sure if this change is correct. Since Windows 7 is an outdated system and no longer supported. Have you tested its impact on other systems? The vcpkg.json you proposed may replace newer libraries with older ones, causing issues on newer operating systems and installing outdated libraries, which is not the expected behaviour.
