### ISSUE TITLE
When encrypting, the interface screen is black

### ISSUE THREAD

**Issue by ericcobblepot** [opentibiabr/otclient#429]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

1 download master 02/23/2023
2 edit config.h
3
```
// ENCRYPTION SYSTEM
// Enable client encryption
#define ENABLE_ENCRYPTION 1
// Enable client encryption maker/builder.
// You can compile it once and use this executable to only encrypt client files once with command --encrypt which will be using password below.
#define ENABLE_ENCRYPTION_BUILDER 1
// for security reasons make sure you are using password with at last 100+ characters
#define ENCRYPTION_PASSWORD "BUG_ENCRYPT______SET_YOUR_PASSWORD_HERE"
```
4 send to a new folder the files, data,modules, init.lua, otclient_x64
5.- open cmd
```
D:
cd D:\desktop\mehah\23_02_23\encrypt
otclient_x64 --encrypt
```
6 open the client

7

![image](https://user-images.githubusercontent.com/125500615/221009370-84fba132-bbb5-466d-ab7a-0ab4f13f1d5d.png)

PD:  is not the first time that I encrypt

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
encryption is not to be used, it is written in the project description, it is just an implementation so that you have an idea of how to implement a new encryption.

**Comment by themaoci** [comment]
You are missing half of the steps looking at your message

1. Get sources
2. Edit config.h enabling encryption / encryption builder / setting your password
3. Compile
4. Copy files
5. Run in copied files *.exe --encrypt
6. Edit config.h file disabling encrypt builder
7. Compile
8. Replace exe file in copied files with compiled one
9. Run

Black screen can also be the cause of wrongly set viewport dimensions it happend to me when i was researching how that worked.
