### ISSUE TITLE
Player occupying two sqms at the same time - hitbox

### ISSUE THREAD

**Issue by damiansky** [opentibiabr/otclient#43]
### Steps to reproduce (include any configuration/script required to reproduce)
1. While player walks from one tile to the other you can shoot either of the sqms and the player will get hit.
2.  https://gyazo.com/83f967afa8cb4e97e5616eb3723c79f3
3. https://gyazo.com/9a1e97f142b531665d7d5998ecdb8712
4. Also magic walls cannot be thrown 'behind him' because he basically occupies two tiles.
5.https://gyazo.com/6063e5109ef0ac4196450ffcd2458a02

### Expected behaviour
Player should only occupy one tile , he shouldnt be able to hit USING hmm on the sqm  he is clearly already left.

### Environment

Newest tfs -> 10.98 tibia

**Comment by Klonoa88** [comment]
Confirmed.
