### ISSUE TITLE
Monsters with invisible name and health bar in battle list

### ISSUE THREAD

**Issue by rodrigopaixaorj** [opentibiabr/otclient#436]
### Priority

Low

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

![1](https://user-images.githubusercontent.com/7372287/221357823-9ecac82a-b7e8-4da9-ac52-ea87492546ca.png)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by themaoci** [comment]
yea thats deffenetly not a trap monster and its deffenetly not have a ```<flag hidehealth="1" />```

**Comment by rodrigopaixaorj** [comment]
> yea thats deffenetly not a trap monster and its deffenetly not have a `<flag hidehealth="1" />`

What ?
![image](https://user-images.githubusercontent.com/7372287/221364819-d87a51f9-4293-4c00-939b-f28cb9f53e3e.png)

**Comment by themaoci** [comment]
am i talking to the wood plank or what ?? you just explained why its not showing its name and health... jesus why i even need to answer it...

**Comment by themaoci** [comment]
and about left side (the battle list) simply its adding empty monster even tho its empty... its lua things that need to be corrected tbh.

battle module -> doCreatureFitFilters need to be adjusted for your needs
fix in image 
![image](https://user-images.githubusercontent.com/33422088/221365943-d3e19192-bfcf-4d40-b1df-a745a6d0bf35.png)

**Comment by Nottinghster** [comment]
> am i talking to the wood plank or what ?? you just explained why its not showing its name and health... jesus why i even need to answer it...

Keep the respect, you're not talking to your mom ;)
Also stick that wood plank into your ass... stupid!
