### ISSUE TITLE
Error in login php otserv br

### ISSUE THREAD

**Issue by timek26** [opentibiabr/otclient#44]
i use otservbr global, gesior acc, login php to tibia 12 and otclient 12,72. Ichange ip in client by client editor and i got error

[https://user-images.githubusercontent.com/65622633/84103202-5f02aa00-a9e0-11ea-8035-980b54f26251.png](https://github.com/Znote/ZnoteAAC/issues/url)

i get error when i use other version of login php 1.7

{"errorCode":3,"errorMessage":"Unrecognized event ."}

**Comment by Costallat** [comment]
This repo is for the OTC.
