### ISSUE TITLE
Unable to move after going down the ladder

### ISSUE THREAD

**Issue by damiansky** [opentibiabr/otclient#44]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Go down the ladder and try to move immediately in any direction using arrow keys.

### Expected behaviour
When you go down the ladder and try to move u should immediately be able to.
https://gyazo.com/ddc65744491071ebe8baba2d89eed771

### Actual behaviour
You are unable to move for a solid amount of time (around 1 second)
https://gyazo.com/5bd62d4bf45d27192c073f9f1fa61a72

### Environment
Newest tfs 1.3 -> 10.98 Mehah's OTC

**Comment by Klonoa88** [comment]
Strange. I have tried this and I do not have that problem :(

**Comment by mehah** [comment]
> Strange. I have tried this and I do not have that problem :(

this happens when the player speed is very slow, but I have already corrected it.
