### ISSUE TITLE
Animated background does not show instantly

### ISSUE THREAD

**Issue by Kamenuvol** [opentibiabr/otclient#442]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

I have an animated png that the first frame is 15 seconds.
When opening the client background, it only shows up after that time, jumping the first frame.
After that, the loop works correctly, including the first frame.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
everything is normal here, I tested it with this image:
https://starbeamrainbowlabs.com/blog/images/20190216-Night-Pan.apng

**Comment by Riverlance** [comment]
> everything is normal here, I tested it with this image: https://starbeamrainbowlabs.com/blog/images/20190216-Night-Pan.apng

Yours have the first frame almost instantly executed, that's why you cannot see it.
As @Kamenuvol said, the first frame duration is 15 seconds.
This is the image that he mentioned:
[client_background.zip](https://github.com/mehah/otclient/files/10853510/client_background.zip)
