### ISSUE TITLE
bug: light flickering

### ISSUE THREAD

**Issue by BenDol** [opentibiabr/otclient#449]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Light is flickering when moving, not sure if this is related to the latest changes. I am on https://github.com/mehah/otclient/commit/8f1d07e7c9ab787588df144aed1e418ce915e786

https://youtu.be/faQrvQRnTzw

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SkullzOTS** [comment]
after the implementation of this last lighting system this problem started to appear

https://youtu.be/xtvkmaUpDeE
