### ISSUE TITLE
animation bug in lastest source

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#455]
### Priority

Critical

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Animation bug in latest source. When i reverted "fix: animated background does not show instantly" then bug does not occur

![animation bug](https://user-images.githubusercontent.com/16617982/222596597-e3cb116c-8b77-4ce5-bfa6-01ecda3b503c.gif)

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
strange, the code only affects png images, which is not the case, do you not have async texture loading enabled?
