### ISSUE TITLE
Modules don't reopen after closing them or minimizing them.

### ISSUE THREAD

**Issue by vicaren95** [opentibiabr/otclient#464]
### Priority

High

### Area

- [x] Data
- [x] Source
- [ ] Docker
- [ ] Other

### What happened?

So I've been messing with the inventory, but even without messing with it, other modules like skills, the minimap, battle, etc. Stopped working and opening their respective windows.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SkullzOTS** [comment]
@vicaren95 
try this > https://github.com/mehah/otclient/commit/f734bf34f346ead82e6aa97209082fa723684e9e
and this > https://github.com/mehah/otclient/commit/d8f90874fae054c82e9e29343fab2584c2c5f94b

**Comment by vicaren95** [comment]
Worked, but windows that had been previously closed can't open anymore.
Is there a way to reset that?

**Comment by SkullzOTS** [comment]
@vicaren95 go to your user's appData, where you save all the cache and delete the config.otml

**Comment by SkullzOTS** [comment]
![image](https://user-images.githubusercontent.com/86809689/224170204-4b339210-fedb-4637-bca0-282ad680e9b9.png)

![image](https://user-images.githubusercontent.com/86809689/224170273-5f23466a-bbe2-4456-aaba-1c9aa698b16c.png)

**Comment by SkullzOTS** [comment]
@vicaren95 close the client before... if you are not going to save again, after closing and deleting the cache, reopen it

**Comment by vicaren95** [comment]
Everything working correctly!

**Comment by SkullzOTS** [comment]
nicee

**Comment by themaoci** [comment]
FIX AKA IF MINIMIZED DO NOT SAVE THAT

fix for that to never happen again 
open modules/corelib/ui/uiminiwindow.lua
line start 77
```lua
function UIMiniWindow:setup()
    self:getChildById('closeButton').onClick = function()
        self:close()
    end

    self:getChildById('minimizeButton').onClick = function()
        if self:isOn() then
            self:maximize()
        else
            self:minimize(true)
        end
    end

    self:getChildById('miniwindowTopBar').onDoubleClick = function()
        if self:isOn() then
            self:maximize()
        else
            self:minimize(true)
        end
    end
end
```
