### ISSUE TITLE
Target texture unloads (red square)

### ISSUE THREAD

**Issue by Tofame** [opentibiabr/otclient#468]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [X] Other

### What happened?

You can see on the video that when you go out of the visible range for monster the red square disappears, but the target stays on the battle list and can be attacked. This shouldn't happen, the red square should still be visible.

According to maomao from discord, the issue is that "there is something called unload tiles or something and that thing is propably on a tile if you move out of bounds it disapears". If it's possible and the issue lays there I think that red square should be excluded from this unload tile or whatever this is. (or the target should atleast be removed from target list).

https://user-images.githubusercontent.com/80583148/224554518-afaefa27-81f8-4653-820b-7d9acb756a2a.mp4

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
your modules are up to date, because here I can not reproduce.
