### ISSUE TITLE
Player diagonal direction lag

### ISSUE THREAD

**Issue by Riverlance** [opentibiabr/otclient#469]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

![89172a5ae0907fbbc5f9e84bcdccfd49](https://user-images.githubusercontent.com/2280432/224558092-36d8afe7-e72e-42ef-a4e3-43c7b4da5bfd.gif)

# How to reproduce

1. Walk in diagonal using your keyboard (numpad 7/9/1/3 numbers with numlock disabled).
2. Click to walk anywhere with your mouse.

Note: I tried this with the original code of 12th March 2023 with original TFS 1.5.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by poxis** [comment]
try https://github.com/mehah/otclient/issues/401 but in my case it did not help....

**Comment by poxis** [comment]
hmm i found fix bug "walk on one sqm' work for me..

void Creature::updateWalk(const bool isPreWalking)



change:
```
    if (!isPreWalking && m_walkedPixels == SPRITE_SIZE) {
        terminateWalk();
    }
```
to:
```
   if (m_walkedPixels == SPRITE_SIZE) {
        if (!isPreWalking)
             terminateWalk();
        else
            m_walkAnimationPhase = 0;
    }
```

**Comment by mehah** [comment]
- Tibia Version?
- I don't understand, delay of what?
- Did you make sure that the server's formula is the same as the client's?
