### ISSUE TITLE
Login/Relog underground and Others

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#47]
**(1. Sometimes but not always)** When you login or relog underground, the light does not draw. You have to walk for it to be updated.
https://i.imgur.com/FQkJLns.gif

**(2. Always)** When you log in, it flashes black before everything is draw.

**(3. Always)** If you run through things with GM (Ctrl+Arrows), there will be a black border at the edge of the game window in the direction you are running. It's like not everything is draw fast enough.

**Comment by mehah** [comment]
you are testing in debug mode, as there is a delay when you compile in this mode

**Comment by Klonoa88** [comment]
No i have compile it in Release x64
https://i.imgur.com/rW1v0jg.png
https://i.imgur.com/EzN0weY.png

I have merge all your commits from [Adaptive Rendering](https://github.com/mehah/otclient/commit/6c3a60904fe42b900aa215c725805e4f2c72e739) to [new feature FORCE_ANIMATED_RENDERING](https://github.com/mehah/otclient/commit/c42cb22ef3306e3ce17f128a44f8d4bb021e7ade). 
Somewhere between them commits, the problems came

Tried now with (FORCE_ANIMATED_RENDERING 1) and it works better :)

**Comment by mehah** [comment]
I solved the login problem, I don't know if it will solve your light problem, because I'm not able to reproduce here, on the black part, I also couldn't, you put the right amount in AwareRange, the right thing is, what you are seeing +2.

https://github.com/mehah/otclient/commit/980dca94ac634054c022bc9b564d0de3adc4a7f6

**Comment by Klonoa88** [comment]
Yes. i have the right amount in AwareRange :)

**Comment by mehah** [comment]
could you make a video showing me?

**Comment by Klonoa88** [comment]
When I walk normally, there are no problems.
**Normally walk video:**
https://www.dropbox.com/s/ybgm0qt51gtod61/ZrekoaWu5G.mp4?dl=0

But when i walk with (Ctrl+Arrows) **Fast**, sometimes there is a black stripe in the direction i am going. 
Check out the beginning of the video.
**Black bug video:**
https://www.dropbox.com/s/s775rymnqhrg63q/uQvb1NwyCK.mp4?dl=0

And if I go around for a while with (Ctrl+Arrows) the client crashes. No errors.
**Crash and black bug video:**
https://www.dropbox.com/s/q0h1ba4176j96l2/2or2eYrcE8.mp4?dl=0

**Comment by mehah** [comment]
your gm is moving faster than normal, you will have to change the variable FrameBuffer :: MIN_TIME_UPDATE on this line:

https://github.com/mehah/otclient/blob/a2005e2df5b7f0b0f5fbf91f61a5699f697b26c0/src/client/mapview.cpp#L352

try "<= 10" and tell me if it is resolved, if not, remove the line, but I do not recommend it, as it is a problem that the GM is moving very fast.

**Comment by Klonoa88** [comment]
Yes "<= 10" fixed the problem with the black line. But the client still crashes when I run too fast with (Ctrl+Arrows) for about 20 seconds. The client has never crashed before because of it. 

It does not crash when I walk normally.

**Comment by mehah** [comment]
you are out of the standard, so I will not be able to reproduce in my environment.

**Comment by Klonoa88** [comment]
I have merged all your recent commits and the problem is now solved. So we can close this :)
