### ISSUE TITLE
m_glyphsTextRectCache random crash

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#470]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Random crashes occur from time to time, related to "m_glyphsTextRectCache"
![crash](https://user-images.githubusercontent.com/16617982/224660539-c581ca6e-88aa-46f3-9d35-57d385fa05c8.png)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by themaoci** [comment]
its propably glyphsCords array that is out of bounds (simple check for that should fix that)

**Comment by patrykq112** [comment]
> its propably glyphsCords array that is out of bounds (simple check for that should fix that)

You mean something like this?
![image](https://user-images.githubusercontent.com/16617982/224668223-f06050e6-cb5b-4e87-9c70-c2487b40bb40.png)

**Comment by mehah** [comment]
@patrykq112 
you didn't print the error.
