### ISSUE TITLE
Arch Linux compile error: FATAL_ERROR,Failed to generate protobuf files

### ISSUE THREAD

**Issue by wick3dr0se** [opentibiabr/otclient#473]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

The Arch Linux compiling instructions are outdated. Directory 'protobuf' does not exist in otclient/src/framework. Attempting to compile otclient via `cmake . -B build` without protobuf leads to the following result:

```
-- Enabled: ipo
-- Found Protobuf Compiler: /usr/bin/protoc
FATAL_ERROR,Failed to generate protobuf files
-- Bot protection: ON
-- Use precompiled header: OFF
-- Disabled: asan
-- Disabled: DEBUG LOG
-- Build type: 
-- Build commit: 
-- Build revision: 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find asio (missing: ASIO_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findasio.cmake:4 (find_package_handle_standard_args)
  src/CMakeLists.txt:179 (find_package)

-- Configuring incomplete, errors occurred!
```

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
@scopz

**Comment by rodrigopaixaorj** [comment]
Seems like it's missing ASIO package

**Comment by mehah** [comment]
@wick3dr0se 
try this:

sudo pacman -Syu base-devel git cmake asio physfs openssl lua51 glew libvorbis openal zlib libogg nlohmann-json protobuf --needed

Compile protobuf .proto files

cd src/protobuf/
./generate.sh
cd ../../

**Comment by wick3dr0se** [comment]
@mehah @scopz
I just fresh installed Arch Linux yesterday evening, following your advice, then attempting `cmake . -B build` results in:

```
-- Found Protobuf: /usr/lib/libprotobuf.so (found version "3.21.12") 
-- Found Protobuf Compiler: /usr/bin/protoc
FATAL_ERROR,Failed to generate protobuf files
-- Bot protection: ON
-- Use precompiled header: OFF
-- Disabled: asan
-- Disabled: DEBUG LOG
-- Build type: 
-- Build commit: 
-- Build revision: 
-- Found ZLIB: /usr/lib/libz.so  
-- Looking for lzma_auto_decoder in /usr/lib/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib/liblzma.so - found
-- Found LibLZMA: /usr/lib/liblzma.so (found version "5.4.1") 
-- Found nlohmann_json: /usr/share/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found version "3.11.2") 
-- Found asio: /usr/include  
-- Found Threads: TRUE  
CMake Error at src/CMakeLists.txt:181 (find_package):
  Could not find a package configuration file provided b
y "STDUUID" with any
  of the following names:

    STDUUIDConfig.cmake
    stduuid-config.cmake

  Add the installation prefix of "STDUUID" to CMAKE_PREFIX_PATH or set
  "STDUUID_DIR" to a directory containing one of the above files.  If
  "STDUUID" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

Executing generate.sh with `./generate.sh` or `bash generate.sh` ends true, so appears the command `protoc --cpp_out=. *.proto` works as expected. Making generate.sh executable by default would be nice  (e.g. `chmod a+x generate.sh`) or just dropping the BASH script and executing the single command itself. Seems like less work than switching directories and such. If that parts necessary than a single chain of commands would still be simple, like: `cd src/protobuf; protoc --cpp_out=. *.proto; cd ../../`

**Comment by mehah** [comment]
as I don't use this OS it's difficult, maybe @ranisalt can help us.

**Comment by ranisalt** [comment]
@wick3dr0se install stduuid from AUR: https://aur.archlinux.org/packages/stduuid and change `src/framework/util/crypt.h` to include `#include <uuid.h>` instead of `#include <stduuid/uuid.h>`

To go a bit deeper on that, what happened is that `vcpkg` decided by itself to install `stduuid` to a different location than the upstream wants to. This repo relies entirely on `vcpkg` so for several distros the files are not where they are expected.

I submitted a patch upstream to install `stduuid` to its own directory: https://github.com/mariusbancila/stduuid/pull/75, but it looks abandoned.

**Comment by wick3dr0se** [comment]
> install stduuid from AUR: https://aur.archlinux.org/packages/stduuid and change `src/framework/util/crypt.h` to include `#include <uuid.h>` instead of `#include <stduuid/uuid.h>`

Got around to trying this finally. Following the wiki for Arch Linux instructions then the commands previously given above which just added asio to the install target, finally installing stduuid from the AUR as you suggested and modifying to `#include <uuid.h>`; returns:

```
-- Enabled: ipo
-- Found Protobuf Compiler: /usr/bin/protoc
FATAL_ERROR,Failed to generate protobuf files
-- Bot protection: ON
-- Use precompiled header: ON
-- Enabled: Build unity for speed up compilation
-- Disabled: asan
-- Disabled: DEBUG LOG
-- Build type: 
-- Build commit: 
-- Build revision: 
CMake Error at src/CMakeLists.txt:192 (find_package):
  Could not find a package configuration file provided by "pugixml" with any
  of the following names:

    pugixmlConfig.cmake
    pugixml-config.cmake

  Add the installation prefix of "pugixml" to CMAKE_PREFIX_PATH or set
  "pugixml_DIR" to a directory containing one of the above files.  If
  "pugixml" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

I then found/installed `pugixml` with `pacman` and attempted `cmake` again, which returned:

```
-- Enabled: ipo
-- Found Protobuf Compiler: /usr/bin/protoc
FATAL_ERROR,Failed to generate protobuf files
-- Bot protection: ON
-- Use precompiled header: ON
-- Enabled: Build unity for speed up compilation
-- Disabled: asan
-- Disabled: DEBUG LOG
-- Build type: 
-- Build commit: 
-- Build revision: 
CMake Deprecation Warning at /usr/lib/cmake/OpenAL/OpenALConfig.cmake:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  src/CMakeLists.txt:211 (find_package)


CMake Error at src/CMakeLists.txt:213 (find_package):
  Could not find a package configuration file provided by "Vorbis" with any
  of the following names:

    VorbisConfig.cmake
    vorbis-config.cmake

  Add the installation prefix of "Vorbis" to CMAKE_PREFIX_PATH or set
  "Vorbis_DIR" to a directory containing one of the above files.  If "Vorbis"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

**Comment by mehah** [comment]
I'm cleaning the issue list, if anyone wants to open a new one with the same subject, feel free.
