### ISSUE TITLE
[Highlight] Wrongly updated mouse position on floor change

### ISSUE THREAD

**Issue by Riverlance** [opentibiabr/otclient#475]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

![d3a2cd0738a026bf5b4afb5b5d6a25ea](https://user-images.githubusercontent.com/2280432/225531623-985096d6-f898-47a9-9b1c-ce229e7bc236.gif)

# How to reproduce the floor up issue

1. Stand in the stairs position or around, to go up (as showed on gif).
2. Position your mouse in the same position of the stairs.
3. Hold `Ctrl` and `left-click` with your mouse on stairs **_without moving it_**.

Sometimes it will update the position wrongly, **_not necessarily always in the same way_**.

---

![636e4379827434ea8e0450035ca0f60c](https://user-images.githubusercontent.com/2280432/225532254-947a5acd-3d1b-4e3a-a86c-d9652f775345.gif)

# How to reproduce the floor down issue

1. Stand around the stairs, to go down (as showed on gif).
2. Position your mouse anywhere on a game screen position.
3. Go down in the stairs moving your character necessarily with your keyboard.

If you do exactly the same as explained, **_it will always move the highlight position 1 SQM to the north_**.

It won't happen if you click to go down, don't know why.
But it happens if you walk with your keyboard as explained.

---

# Conclusion

The floor up issue updates the position wrongly, not necessarily always in the same way.
But the floor down issue will always move the highlight position 1 SQM to the north.

Note: I tried this with the original code of 16th March 2023 with original TFS 1.5 and protocol 12.87.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by poxis** [comment]
I confirm, if we go diagonally up the stairs it misaligns the position of the mouse cursor ;|
