### ISSUE TITLE
Light bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#477]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Bug with light

https://s2.gifyu.com/images/light-bug.gif
https://s10.gifyu.com/images/light-bug-2.gif

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
which source you tested, compile the latest source and test again.

**Comment by patrykq112** [comment]
> which source you tested, compile the latest source and test again.

This bug occurs in the latest source, the place where it was recorded is underground (Z: 14)

**Comment by mehah** [comment]
I just tested it on the 12th, 14th and 15th floor and it doesn't happen.

**Comment by patrykq112** [comment]
This bug occurs even in the source you just downloaded. This is what the map looks like in the map editor
![my map](https://user-images.githubusercontent.com/16617982/225712471-f8d4284c-aed1-4c82-a9ae-2d16f89ebfd5.gif)

**Comment by mehah** [comment]
are you using anti-aliasing or smooth retro?
if you are using smooth retro, test with anti-aliasing.

because here I am not able to reproduce this problem.


**you need to give me more details about how is your client, viewport and etc..**

**Comment by patrykq112** [comment]
> are you using anti-aliasing or smooth retro? if you are using smooth retro, test with anti-aliasing.
> 
> because here I am not able to reproduce this problem.
> 
> **you need to give me more details about how is your client, viewport and etc..**

My settings:
```
static constexpr uint8_t MAX_VIEWPORT_X = 13;
static constexpr uint8_t MAX_VIEWPORT_Y = 11;
```

Normal map view (classic, there is a bug):
![bug1](https://user-images.githubusercontent.com/16617982/225713914-dbe25a85-6532-44f1-8f6f-df7b8124722e.png)

New view mode (there is no bug):
![no bug](https://user-images.githubusercontent.com/16617982/225715151-5a80436d-7873-4be9-88e4-b5d9aab07ade.png)

**Comment by mehah** [comment]
@patrykq112 

is ok now?

**Comment by patrykq112** [comment]
> @patrykq112
> 
> is ok now?

it's okay now
