### ISSUE TITLE
[ERRO] Unable to load data file (Extended Feature Enabled)

### ISSUE THREAD

**Issue by tdp157** [opentibiabr/otclient#478]
### Priority

High

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Hello

I downloaded the compiled version, however, when I put my Tibia.dat and Tibia.spr from my server it gives this error

**"Unable to load data file"**

**I'm using OTX2 version 0.7**

Can someone help me?

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
![image](https://user-images.githubusercontent.com/2267386/225729003-86097088-e008-44fd-b52a-3da33483f762.png)
extended feature is enabled.

use: g_game.enableFeature(GameSpritesU32);
