### ISSUE TITLE
I cant move, some errors in console.

### ISSUE THREAD

**Issue by ShiruDevelopment** [opentibiabr/otclient#479]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

https://gyazo.com/bd57ec217ec4aad1bbc0ec89ee3a5920

I cant move, can't do anything.

When i press CTRL + T, there is some information.

```
ERROR: failed to decompress message - invalid block type
at:
    [C++]: ?internalRecvData@Protocol@@AEAAXPEAEG@Z
ERROR: Unable to send extended opcode 1, extended opcodes are not enabled
```

Cipsoft client - works
OT redemption - not
 :(

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I think it would be easier to help you if you gave more information.  :upside_down_face:

server, protocol version...

**Comment by ShiruDevelopment** [comment]
ya canary, 12.91, using assets not dat/spr
latest compiled client released on github

**Comment by ShiruDevelopment** [comment]
![image](https://user-images.githubusercontent.com/112799014/226048590-5eeef413-4b9b-41e4-bd8b-1ca2a652085a.png)


fix:

**Comment by mehah** [comment]
was your canary server out of date?

**Comment by ShiruDevelopment** [comment]
Yes, it was only my fault.

**Comment by ShiruDevelopment** [comment]
But i saw that a lot of ppl have the same problem, so i post the 'fix'
