### ISSUE TITLE
font

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#480]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

When I write something in the chat it is badly shown. In addition, the font of the character name is too large

https://prnt.sc/Wl24OCX8UnDj

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SkullzOTS** [comment]
@daniofordon modules/client_options/options.lua 
![image](https://user-images.githubusercontent.com/86809689/226072083-f0bf19dc-75f0-4703-9923-5d9f05a8b54e.png)

**Comment by SkullzOTS** [comment]
change from 0 to 1
then just drag the scroll in options/general to correct yours which probably should have already been saved with another value

**Comment by daniofordon** [comment]
thanks :)

**Comment by daniofordon** [comment]
Text written in chat still shows badly

**Comment by mehah** [comment]
@daniofordon 

https://user-images.githubusercontent.com/2267386/225743134-cd23ad94-bb8a-4857-bfc3-15c88255ceaf.mp4
