### ISSUE TITLE
Feature: Rich Presence on Discord

### ISSUE THREAD

**Issue by Aerwix** [opentibiabr/otclient#496]
### Feature Request: Rich Presence on Discord

Hello, Idk how familiar you are with Discord but my idea it's to add Rich Presence from Discord to OTC.
In a few words, it's the message in discord that says "Now Playing Tibia" or other games.

[Introduction to Rich Presence ](https://discord.com/developers/docs/rich-presence/how-to)

##What we could show there?
**Character Name**
Level: 300 - Vocation
**Guild**: Godbreakers
**World**: Name
Create Account Button

Showoff
![image](https://user-images.githubusercontent.com/26527255/229631351-f2e07127-dc4c-4f11-b472-774295127760.png)

I have to be honest, Idk if this can work but can be cool to see it =)

**Comment by SkullzOTS** [comment]
@Aerwix this feature has already been implemented by me, you can configure it in src/client/config.h

**Comment by SkullzOTS** [comment]
![image](https://user-images.githubusercontent.com/86809689/229634204-9e57d081-3ed5-4f94-b388-c34ac54915ae.png)

**Comment by Aerwix** [comment]
Oh amazing, sorry, I didn't saw it hahah amazing! =D
