### ISSUE TITLE
It is hard to target monster while moving

### ISSUE THREAD

**Issue by mrianura123** [opentibiabr/otclient#5]
It is hard to target monster when monster is in move

**Comment by mehah** [comment]
target with what, rune or right click?

**Comment by mrianura123** [comment]
right click - attack - on mapView

**Comment by mehah** [comment]
here is normal.

**Comment by wmaestrots** [comment]
I didn't notice any bug with targetting :O

**Comment by mrianura123** [comment]
hmm, Ok. On Sunday I will apply recent changes from mehah and try to reproduce that + make a video if still facing the issue.

**Comment by mrianura123** [comment]
not sure why, but problem disappeared after applaying recent "getTopUseThing" modifications
