### ISSUE TITLE
Lite bug

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#50]
Lite bug: only player or monster

fix:

>              if(id >= Proto::PlayerStartId && id < Proto::PlayerEndId)
>                     creatureType = Proto::CreatureTypePlayer;
> 				else if (id >= Proto::MonsterStartId && id < Proto::MonsterEndId)
> 					creatureType = Proto::CreatureTypeMonster;
> 				else
> 					creatureType = Proto::CreatureTypeNpc;

https://github.com/mehah/otclient/blob/2ed5ff015959491d7b20a442506a2eadb9319255/src/client/protocolgameparse.cpp#L2222

**Comment by mehah** [comment]
if you want, you can open a PR and I accept.

**Comment by poxis** [comment]
@mehah  unfortunately I don't know how 

i found next bug:
https://github.com/mehah/otclient/blob/faa1808ade2ca7dc8fc87e9ef020090de715d81b/src/client/tile.cpp#L136
double 'dest - m_drawElevation * scaleFactor'  (on the elevation, the magic effectt is too high )
https://github.com/mehah/otclient/blob/faa1808ade2ca7dc8fc87e9ef020090de715d81b/src/client/tile.cpp#L200
