### ISSUE TITLE
otclietn error change outfit gm account

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#504]
### Priority

High

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

https://prnt.sc/JUUIx9LQMt36

I use the latest TFS 12.87 and the latest client OTCLIENT MEH.  Nothing has changed. there is such an error only on the GM account when I want to change the appearance of the character

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
Download and compile lastest commit, it was fixed

The fix -> https://github.com/mehah/otclient/commit/58dfe506f5eff046a49413bd6468d9458493ff0a

**Comment by mehah** [comment]
As there was no response, I will close.

**Comment by daniofordon** [comment]
https://prnt.sc/DnwWd-ZzMjYd

**Comment by daniofordon** [comment]
all the time the same when changing the appearance on GM Account
