### ISSUE TITLE
Smartwalk diagonal walking causes packet flooding

### ISSUE THREAD

**Issue by Source61** [opentibiabr/otclient#51]
Tried out Otclient1.0 for downgraded TFS 1.3 to v7.72 today.
The movement speed is great, great improvement over otclient, but smartwalking causes massive packet flooding, it's almost instant disconnect at 25pps, increased to 65pps and I still get disconnect after about 3 seconds on a level 8 character (but not on a GM char with max speed unless I set pps lower than 65).
Diagonal walking is also so much slower than normal, it doesn't seem right, like maybe 5x slower than a normal movement, should only be about 2x slower I think.

### Steps to reproduce (include any configuration/script required to reproduce)
1. Compile latest otclient1.0 version
2. Enable smartwalking
3. Login and hold down two arrow keys with a 90 degree angle e.g. up+right or up+left

### Environment
Latest otclient1.0 version, cloned yesterday, compiled 32bit release.
Running Windows 10 on client side, Debian 10 with TFS 1.3 downgraded to protocol 7.72 by Nekiro.

**Comment by mehah** [comment]
well, I don't have a 7.72 server, I tested it with 8.6, and it's working correctly, how's your server's walk formula?

the line where the diagonal formula is located is this and is correct, same as in the official otclient.

https://github.com/mehah/otclient/blob/e40b760fc36802c9501aa3cdbc68a268a4db4bca/src/client/creature.cpp#L952

Server 8.6: https://otland.net/threads/8-6-tfs1-3-alkurius-global-coustom.273912/

**I also didn't get any problems with the package.**

**Comment by Source61** [comment]
You can try ours at https://server.opentibia.dev :)

I use Nekiro's downgraded TFS 1.3 since two days ago, you'll have to give me a function name to lookup for the formula on server side.

**Comment by Source61** [comment]
Searched for 'diagonal' in creature.cpp and found this:

https://github.com/nekiro/forgottenserver/blob/7.72-downgrade/src/creature.cpp#L460
https://github.com/nekiro/forgottenserver/blob/7.72-downgrade/src/creature.cpp#L1320

Even if the server is the potential cause of long diagonal walks which I'm still not sure, client still shouldn't be spamming packets like crazy when waiting for the step to finish and afaik the server sends map data when step is done as a confirmation of the step being finished, I believe that's the correct implementation, so to me it's clearly a client-sided issue either way.

**Comment by Source61** [comment]
Found a new bug upon entering TFS 1.3 10.98 and killing a few rats. This bug does not exist in latest original otclient:
https://imgur.com/a/KGnYFWc

**Comment by mehah** [comment]
The developers are making a mix of formulas for the old versions of tibia, the most compatible one I found with the client is otHire 7.72

https://github.com/TwistedScorpio/OTHire

**I haven't tested it, but looking at the formula quickly, it's the most compatible.**

> Found a new bug upon entering TFS 1.3 10.98 and killing a few rats. This bug does not exist in latest original otclient:
> https://imgur.com/a/KGnYFWc

battle module?

**Comment by Source61** [comment]
Shouldn't the client try to be server-agnostic, compatible with all servers, not just working with a single server for a single version?

> battle module?

Looks like it. The unique errors I can find in the logs are:
ERROR: /client_options/options.lua:205: attempt to index field 'game_interface' (a nil value)
/game_battle/battle.lua:550: attempt to concatenate local 'sortType' (a nil value)
/gamelib/protocolgame.lua:23: opcode 246 already registered will be overriden

**Comment by mehah** [comment]
I had said that I would not support protocols below 10.98, but with requests from some people I ended up giving in, but it would not be difficult to maintain compatibility, if there was no discrepancy in the formulas.

Did you test with 'OThire'?

**Comment by Source61** [comment]
Well, it's up to you. I understand if you think it's too much work.
Just keep in mind for the sake of clarity here that normal otclient works fine with the server while yours does not, so it's not an issue with the server as far as I see it when it works fine with otclient, but you may see it differently.
I guess it's also possible that otclient doesn't bug out because it's walking slower and that your speed boost is not compatible with all servers.

Either way I was just reporting this bug since you asked me to try otclient1.0 out and I thought you wanted bug reports, I've decided to stick to using old otclient personally.

**Comment by Feliipe93** [comment]
I Will check tomorrow @mehah 
Thanks for check this issue i and so many players want otc 1.0 support old versions like 7.72i will check othire code and if it work I will make an adaptation on tfs 1.3

**Comment by mehah** [comment]
> Well, it's up to you. I understand if you think it's too much work.
> Just keep in mind for the sake of clarity here that normal otclient works fine with the server while yours does not, so it's not an issue with the server as far as I see it when it works fine with otclient, but you may see it differently.
> I guess it's also possible that otclient doesn't bug out because it's walking slower and that your speed boost is not compatible with all servers.
> 
> Either way I was just reporting this bug since you asked me to try otclient1.0 out and I thought you wanted bug reports, I've decided to stick to using old otclient personally.

the walking system is not as smooth as this one and I am not refusing to maintain compatibility, the problem that, the old version has many unnecessary conditions, version 1.0 follows the same formula as the server without extra conditions, so if the formula is really different between the server and the client, it will be a problem.

> I Will check tomorrow @mehah
> Thanks for check this issue i and so many players want otc 1.0 support old versions like 7.72i will check othire code and if it work I will make an adaptation on tfs 1.3

ok
