### ISSUE TITLE
Request : player:setMapShader resembling player:attachEffectById

### ISSUE THREAD

**Issue by ericcobblepot** [opentibiabr/otclient#512]
### Priority

Enhancement

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

Hello good morning

I recently saw the "Attached effect (Server Support)"

server
Would it be possible to add a player:setMapShader(ID,time,temporary?) Server Support?

otc
ID |   Name
1.- "Default"
2.- "Map - Rain"
....

interesting things could be done

![ezgif com-optimize](https://user-images.githubusercontent.com/125500615/231571969-af55e556-7317-4402-bc1c-686812a3bc35.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I'm going to implement it, but what you want to do, you have to implement it directly on the client and not on the server, imagine the server with 800+ players, having to check if it's in an area where it rains or not and put the shader.

**Comment by ericcobblepot** [comment]
thanks for answering . the gif was just an example xd no need if `"isInRange"`
I imagined a moveEvent.onStepIn on the floor actions and giving `player:setMapShader`
or a spell
to give `player:setMapShader` to viewers `local spectators = Game.getSpectators(settings.position, false, true, 7, 7, 5, 5)`, etc..

Thanks for answering .
greetings
you do a great job
