### ISSUE TITLE
Item (96x96) disappears when you move behind the field of view

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#513]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Description in the video: 

https://imgur.com/a/XmWOZXP

this happens on the top and left side

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
the ideal is 64x64, as Tibia's border only contains 2 SQMs, 96x96 will occupy 3 SQMS.

but to fix your problem, put true in that line:
https://github.com/mehah/otclient/blob/9ac32648210a31239c27dee63b2ad5e099b9aff1/src/client/mapview.cpp#L526

but again, it will cause other problems, which there will be no solution, just that you put more tile to draw.

**Comment by mehah** [comment]
@poxis 

try this:

in:
https://github.com/mehah/otclient/blob/9ac32648210a31239c27dee63b2ad5e099b9aff1/src/client/tile.cpp#L779

change to:
```c++
else if ((cameraPosition.y - checkPos.y >= viewPort.top) || (checkPos.y - cameraPosition.y == viewPort.bottom && !hasTallThings() && !hasWideThings() && !hasDisplacement() && !hasThingWithElevation() && m_walkingCreatures.empty()))
```

**Comment by poxis** [comment]
@mehah THANKS! work it, but again when we are at the top you can't see it, I did as in the old version and for me this solution works (I don't know if something doesn't cause other problems, I will test)

https://github.com/mehah/otclient/blob/9ac32648210a31239c27dee63b2ad5e099b9aff1/src/client/mapview.cpp#L791
change to:
```
        vp.top = m_posInfo.awareRange.top;
        vp.right = m_posInfo.awareRange.right;
        vp.bottom = vp.top+1;
        vp.left = vp.right+1;
```

**Comment by mehah** [comment]
@poxis 

the "problem" is not there.


edit this:
https://github.com/mehah/otclient/blob/9ac32648210a31239c27dee63b2ad5e099b9aff1/src/client/tile.cpp#L777

change to
```c++
 if ((cameraPosition.x - checkPos.x >= viewPort.left) || (checkPos.x - cameraPosition.x == viewPort.right && !hasWideThings() && !hasTallThings() && !hasDisplacement() && !hasThingWithElevation() && m_walkingCreatures.empty()))
```
and

https://github.com/mehah/otclient/blob/9ac32648210a31239c27dee63b2ad5e099b9aff1/src/client/tile.cpp#L781

change to
```c++
        else if ((checkPos.x - cameraPosition.x > viewPort.right && (!hasWideThings() || !hasTallThings() || !hasDisplacement() || !hasThingWithElevation())) || (checkPos.y - cameraPosition.y > viewPort.bottom))

```

**Comment by poxis** [comment]
first 
`if ((cameraPosition.x - checkPos.x ..`
no work

second
` else if ((checkPos.x - ca`
 no work

work for me change only:
https://github.com/mehah/otclient/blob/9ac32648210a31239c27dee63b2ad5e099b9aff1/src/client/tile.cpp#L781

to
        `else if (((checkPos.x - cameraPosition.x > viewPort.right && (!hasWideThings() || !hasDisplacement() || !hasThingWithElevation())) || (checkPos.y - cameraPosition.y > viewPort.bottom)) && !hasTallThings())`

works without changing the first
`if ((cameraPosition.x - checkPos.x ..`

**Comment by mehah** [comment]
@poxis 
can you test this fix?

**Comment by poxis** [comment]
@mehah  work, but I think you've already checked

**Comment by mehah** [comment]
@poxis 

this fix is for items occupying 3sqms, with the old method, objects occupying 2sqms will be drawn even if they don't show up in your view.

and tibia doesn't have 96x96 objects (3 sqms) so there's no way for me to test.
