### ISSUE TITLE
after uploading the patch still pops up an error when changing the appearance of the GM account

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#514]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

https://prnt.sc/DnwWd-ZzMjYd

after uploading the patch still pops up an error when changing the appearance of the GM account

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
@daniofordon 
Protocol? TFS or Canary?
