### ISSUE TITLE
Light System

### ISSUE THREAD

**Issue by rodrigopaixaorj** [opentibiabr/otclient#517]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Check out the video:

https://user-images.githubusercontent.com/7372287/233856480-9e121457-c951-4b9d-a61e-69103cfff2f3.mp4

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nottinghster** [comment]
Fixed
