### ISSUE TITLE
Bugged smooth retro

### ISSUE THREAD

**Issue by xrddw126** [opentibiabr/otclient#523]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

So when I change the antialiasing mode to smooth retro in the options, these types of errors occur frequently while walking, and the view then appears to be distant.
![smooth](https://user-images.githubusercontent.com/125150224/235724795-9ebca402-ec64-4674-a03f-55df738e706e.png)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
here it is working perfectly, did you compile the latest src?

test:

https://user-images.githubusercontent.com/2267386/235741717-8b7b107c-c963-45da-a2b8-6f8485d66091.mp4

**Comment by xrddw126** [comment]
Yes, I have the latest sources. I'm afraid it's not easy to trigger it because sometimes nothing happens for several minutes. Unfortunately, I haven't been able to determine exactly what might be causing it yet. I will continue to test it further tomorrow
