### ISSUE TITLE
Possible bug in skills modules using 1098 protocol

### ISSUE THREAD

**Issue by mateusbellei** [opentibiabr/otclient#524]
### Priority

Low

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I was testing the latest version of the master branch, and after I compiled it, and used it for the 10.98 protocol, the game_skills module just opened without any error in the terminal, but without rendering the skills window.

The fact is: i don't know if it's a general problem, or just in my project.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I tested with TFS 1.3 1098 and everything is fine.

**Comment by yrpen** [comment]
I tested it on TFS 1.4 1098 and I have similar bug. But with some conditions.

* My charater should die with open skill window
* OR Server should be restarted while my charcter is logged in with skill window open.
* Relog to this character

It's exact same with other windows (EQ, etc).

# OTClient version
commit 32828964e943b0cfc1c9b4c4a52692eb31b77081

# Operating system
Ubuntu 20.04, using docker.

I run client using this script:
```
#!/bin/bash

cd "${HOME}/git/public/otclient"

# Disable access control for the X server.
xhost +

# Run the container image with the required bindings to the host devices and volumes.
docker run -it --rm \
  --network="host" \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix \
  --volume /home/user_name/git/public/otclient/data/things:/otclient/data/things \
  --volume /home/user_name/git/public/otclient/modules:/otclient/modules \
  --device /dev/dri \
  --device /dev/snd mehah/otclient /otclient/otclient

# Enable access control for the X server.
xhost -

```

**Comment by mateusbellei** [comment]
sorry, forgot to mention that I'm using TFS 1.4 as well. but I didn't notice if it happened to me with the conditions that @yrpen said

**Comment by yrpen** [comment]
I don't have this bug any more in latest OTC.
Using protocol 10.98

**Comment by mehah** [comment]
Fixed https://github.com/mehah/otclient/commit/5b409487880010db14deb189ec928c2684263673
