### ISSUE TITLE
Market Not found

### ISSUE THREAD

**Issue by Mau005** [opentibiabr/otclient#526]
### Priority

Medium

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Hello, I have a problem because in this version the market does not work
I am using TFS 1.4
Protocol 10.98

I have not found a solution in forums, if there are any, they are related to other OTC variants,

the mistake is:
When looking for my depot objects in the market, it does not find anything,
When selecting an item that I have, the outfits system opens,
and you cannot view publications made with the tibia.com client

Thank you very much in advance

PS: the discord link no longer works

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
@Mau005

https://github.com/mehah/otclient/issues/370
https://github.com/mehah/otclient/pull/319

![image](https://user-images.githubusercontent.com/2267386/236250532-e4db7773-62d2-427d-a8ce-ee2d32632c7e.png)

you can rollback the market to get it working again.
