### ISSUE TITLE
Using exura infir throw error

### ISSUE THREAD

**Issue by yrpen** [opentibiabr/otclient#527]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Using spells from Dawnport throw errors in console. I have no problem with other spells like `exura` or `utevo lux`.
https://tibia.fandom.com/wiki/Dawnport#Spells

Spells I tested:
* exura infir
* exori infir tera
* exevo infir frigo hur

```
ERROR: Lua exception: /game_actionbar/game_actionbar.lua:931: attempt to index local 'spell' (a nil value)
stack traceback:
	[C]: in function '__index'
	/game_actionbar/game_actionbar.lua:931: in function </game_actionbar/game_actionbar.lua:927>
ERROR: protected lua call failed: LUA ERROR:
/game_actionbar/game_actionbar.lua:931: attempt to index local 'spell' (a nil value)
stack traceback:
	[C]: in function '__index'
	/game_actionbar/game_actionbar.lua:931: in function </game_actionbar/game_actionbar.lua:927>
```

On server side I use TFS 1.4, client version 10.98, OTC commit 32828964e943b0cfc1c9b4c4a52692eb31b77081 with default spells.
Here is spells.xml part for one spelll:
```
	<instant group="healing" spellid="174" name="Magic Patch" words="exura infir" level="1" mana="6" aggressive="0" selftarget="1" cooldown="1000" groupcooldown="1000" needlearn="0" script="healing/magic_patch.lua">
		<vocation name="Sorcerer" />
		<vocation name="Druid" />
		<vocation name="Paladin" />
		<vocation name="Master Sorcerer" />
		<vocation name="Elder Druid" />
		<vocation name="Royal Paladin" />
	</instant>
```

Spell id for those spells based on TFS 1.4 spells.xml
* Magic Patch - 174
* Mud Attack - 172
* Chill Out - 173
* Lightest Missile Rune - ??? (7)
* Light Stone Shower Rune - ??? (116) 
* Buzz - 177
* Scorch - 178
* Arrow Call - 176
* Bruise Bane - 175

There is 126 graphics for spells in `data/images/game/spells/defaultspells.png`

I can get rid of this error message adding after line 930 `local spell, profile, spellName = Spells.getSpellByIcon(spellId)` in `modules/game_actionbar/game_actionbar.lua`
```
        if not spell then
          return true
      end
```

But I guess it's not proper fix. Propably there is missing spell cooldown icon?

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yrpen** [comment]
I investigated a little bit spells problem.

I can see missing spells cooldown and spells group cooldown.

# Spells group
## Data
Based on: https://tibia.fandom.com/wiki/Cooldown

Name | Type | OTC 1.0 | OTCv8
-- | -- | -- | --
Attack Spells | Primary Group | YES | YES
Healing Spells | Primary Group | YES | YES
Support Spells | Primary Group | YES | YES
Special Spells | Secondary Group | YES | YES
Crippling Spells | Secondary Group | NO | YES
Focus Spells | Secondary Group | NO | NO
Ultimate Strike Spells | Secondary Group | NO | NO
Great Beams Spells | Secondary Group | NO | NO
Burst of Nature Spells | Secondary Group | NO | NO

## What need to be changed?
Alter image with spell groups: `data/images/game/spells/cooldowns.png`
Alter `modules/gamelib/spells.lua`

# Spells
## Data
Spell ID for versions 9.80 and 10.55 are based on TFS 1.4.2

Spell ID for other versions are based on canary repository

Collumn OTCv8 is based on: https://github.com/OTCv8/otcv8-dev



Spell name | Words | TFS ID | Version | URL | OTC 1.0 | OTCv8
-- | -- | -- | -- | -- | -- | --
Practise Fire Wave | exevo dis flam hur | 167 | 9.80 | https://tibia.fandom.com/wiki/Practise_Fire_Wave | NO | NO
Practise Healing | exura dis | 166 | 9.80 | https://tibia.fandom.com/wiki/Practise_Healing | NO | NO
Apprentice's Strike | exori min flam | 169 | 9.80 | https://tibia.fandom.com/wiki/Apprentice's_Strike | NO | NO
Practise Magic Missile | adori dis min vis | ? ? ? | 9.80 | https://tibia.fandom.com/wiki/Practise_Magic_Missile | NO | NO
Magic Patch | exura infir | 174 | 10.55 | https://tibia.fandom.com/wiki/Magic_Patch | NO | NO
Scorch | exevo infir flam hur | 178 | 10.55 | https://tibia.fandom.com/wiki/Scorch | NO | NO
Mud Attack | exori infir tera | 172 | 10.55 | https://tibia.fandom.com/wiki/Mud_Attack | NO | NO
Chill Out | exevo infir frigo hur | 173 | 10.55 | https://tibia.fandom.com/wiki/Chill_Out | NO | NO
Buzz | exori infir vis | 177 | 10.55 | https://tibia.fandom.com/wiki/Buzz | NO | NO
Bruise Bane | exura infir ico | 175 | 10.55 | https://tibia.fandom.com/wiki/Bruise_Bane | NO | NO
Arrow Call | exevo infir con | 176 | 10.55 | https://tibia.fandom.com/wiki/Arrow_Call | NO | NO
Conjure Diamond Arrow | exevo gran con hur | 192 - later removed from game | 11.40.5409 | https://tibia.fandom.com/wiki/Conjure_Diamond_Arrow | NO | NO
Conjure Spectral Bolt | exevo gran con vis | 193 - later removed from game | 11.40.5409 | https://tibia.fandom.com/wiki/Conjure_Spectral_Bolt | NO | NO
Conjure Wand of Darkness | exevo gran mort | 92 | 11.40.5409 | https://tibia.fandom.com/wiki/Conjure_Wand_of_Darkness | NO | YES
Summon Druid Familiar | utevo gran res dru | 197 | 11.40.5409 | https://tibia.fandom.com/wiki/Summon_Druid_Familiar | NO | YES - Need id fix
Summon Knight Familiar | utevo gran res eq | 194 | 11.40.5409 | https://tibia.fandom.com/wiki/Summon_Knight_Familiar | NO | YES - Need id fix
Summon Paladin Familiar | utevo gran res sac | 195 | 11.40.5409 | https://tibia.fandom.com/wiki/Summon_Paladin_Familiar | NO | YES - Need id fix
Summon Sorcerer Familiar | utevo gran res ven | 196 | 11.40.5409 | https://tibia.fandom.com/wiki/Summon_Sorcerer_Familiar | NO | YES - Need id fix
Chivalrous Challenge | exeta amp res | 237 | 12.55.10451 | https://tibia.fandom.com/wiki/Chivalrous_Challenge | NO | YES - Need id fix
Fair Wound Cleansing | exura med ico | 239 | 12.55.10451 | https://tibia.fandom.com/wiki/Fair_Wound_Cleansing?so=search | NO | YES - Need id fix
Expose Weakness | exori moe | 243 | 12.55.10451 | https://tibia.fandom.com/wiki/Expose_Weakness?so=search | NO | YES - Need id fix
Sap Strenght | exori kor | 244 | 12.55.10451 | https://tibia.fandom.com/wiki/Sap_Strength?so=search | NO | YES - Need id fix
Great Fire Wave | exevo gran flam hur | 240 | 12.55.10451 | https://tibia.fandom.com/wiki/Great_Fire_Wave?so=search | NO | YES - Need id fix
Restoration | exura max vita | 241 | 12.55.10451 | https://tibia.fandom.com/wiki/Restoration?so=search | NO | YES - Need id fix
Nature's Embrace | exura gran sio | 242 | 12.55.10451 | https://tibia.fandom.com/wiki/Nature's_Embrace?so=search | NO | YES - Need id fix
Divine Dazzle | exana amp res | 238 | 12.55.10451 | https://tibia.fandom.com/wiki/Divine_Dazzle | NO | YES - Need id fix
Find Fiend | exiva moe res | 20 | 12.80.11430 | https://tibia.fandom.com/wiki/Find_Fiend | NO | NO
Avatar of Light | uteta res sac | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Avatar_of_Light | NO | NO
Avatar of Nature | uteta res dru | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Avatar_of_Nature | NO | NO
Avatar of Steel | uteta res eq | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Avatar_of_Steel | NO | NO
Avatar of Storm | uteta res ven | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Avatar_of_Storm | NO | NO
Divine Empowerment | utevo grav san | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Divine_Empowerment | NO | NO
Divine Grenade | exevo tempo mas san | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Divine_Grenade | NO | NO
Executioner's Throw | exori amp kor | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Executioner's_Throw | NO | NO
Gift of Life | ? ? ? | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Gift_of_Life | NO | NO
Great Death Beam | exevo max mort | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Great_Death_Beam | NO | NO
Ice Burst | exevo ulus frigo | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Ice_Burst | NO | NO
Terra Burst | exevo ulus tera | - no data | 13.10.12852 | https://tibia.fandom.com/wiki/Terra_Burst | NO | NO


## What need to be changed?
Alter image with spell groups: `data/images/game/spells/defaultspells.png`
Alter `modules/gamelib/spells.lua`

# Question
Anybody know how I can extract those graphics from Tibia to glue them together and put in OTC?

**Comment by yrpen** [comment]
I guess I can work a little bit on this problem and create spells up to `Find Fiend` and make Merge Request.

**Comment by yrpen** [comment]
FYI
It's almost done. I need to do some tests before PR.
So probably I'll create PR in next week.

**Comment by rodrigopaixaorj** [comment]
This case should be closed, since there's no more activity.

**Comment by mehah** [comment]
https://github.com/mehah/otclient/commit/70d0579be7cfd734959075899fa0b73579a63cde
