### ISSUE TITLE
DataBuffer has no member named 'size'

### ISSUE THREAD

**Issue by ranzar** [opentibiabr/otclient#530]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

i'm following the wiki instructions for Debian 11 and when i'm running make, this happens

![1683712709_pantallazo](https://github.com/mehah/otclient/assets/83372894/6b017672-f458-4686-ae92-1e3314a05cfe)

i had no issues a couple weeks ago, before #497 

am i missing something?

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by conde2** [comment]
This looks like namespace conflict, because it clearly has the .size() method, do you have any other lib called DataBuffer?

**Comment by ranzar** [comment]
i don't think so, it's a fresh vm and i was just following the wiki article
edit: how can i check, though? just it case

**Comment by mehah** [comment]
the ideal is to finish this PR(https://github.com/mehah/otclient/pull/510), it replaces the databuffer with std::vector,

**Comment by ranzar** [comment]
okay, gotcha
