### ISSUE TITLE
Android Compile

### ISSUE THREAD

**Issue by xrddw126** [opentibiabr/otclient#537]
### Priority

High

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

Is the Android version still supported?

I am using the latest source code, following all the instructions, but unfortunately I am unable to compile the client. I am encountering the following error.

![dsdsds](https://github.com/mehah/otclient/assets/125150224/6acf8162-8fb0-4ee9-9d7c-e1d4f63aba63)

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tuliomagalhaes** [comment]
Can you please try to compile with your own phone until we fix the build for this kind emulator?

**Comment by dudantas** [comment]
> Can you please try to compile with your own phone until we fix the build for this kind emulator?

With the phone itself it seems that it also has some error. I compiled and it even compiles, but when I install it, it doesn't install.

**Comment by tuliomagalhaes** [comment]
I updated Android libs, can both of you download it again and try to compile?

**Comment by mehah** [comment]
@xrddw126 @dudantas 
it's working?

**Comment by SkullzOTS** [comment]
![image](https://github.com/mehah/otclient/assets/86809689/ceda7904-4ada-49c3-a3f1-d882c1fb5404)

I was able to compile normally using my device
