### ISSUE TITLE
[8.6] Player is always on top [OTC vs OLD]

### ISSUE THREAD

**Issue by xmish** [opentibiabr/otclient#541]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

OLD:
![old](https://github.com/mehah/otclient/assets/95135755/2c6ac862-2b32-445c-bd77-ab498c6e2173)

OTC:
![OTC](https://github.com/mehah/otclient/assets/95135755/d4e50528-a5eb-4707-94a4-5f462082f38f)

Player is always on top on OTC:
- when there's 11 monsters at the tile then on the player client it's still on top but on other players it's moved to the bottom once some monster from tile turns
- if there's e.g. 5 monsters he's always on top but on OLD client it's not on the top

### What OS are you seeing the problem on?

Windows 10
https://github.com/MillhioreBT/forgottenserver-downgrade

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
this is only on 8.6?

**Comment by xmish** [comment]
I’ll check that on monday (can’t check now)
@mehah It seems like it's something related to old clients where 10 creatures sent by sever to a single tile could crash client. Not sure if that's a thing for nowadays clients but seems like some distros still have such logic;
```cpp
if (stackpos >= 10) {
	return;
}
```
So it seems like there's some issue when creatures on stack do rotate and there's also some player on the tile, looks like players are force rendered on top even though they shouldn't (for client where player on stack is the one who's currently logged in "localplayer")>


There's also a question how does that should work, whether there should be a diff on what player sees on his client (so server forces that player is always on stackpos that is visible). Some servers have a logic that check:
```
if ++count(things) == 9 then
     put "player A" (logged one) on tile to make sure our creature is always on tile no matter how many others are there
end
```

but from perspective of other players it would be a different creatures on tile due to the limit and logic that makes sure to always send "us" to the tile.
I guess the best would be to try realOTS 7.7x files to check how it worked back in the days and whether client was responsible to correct some stack order or it was always a server responsibility


https://github.com/opentibiabr/canary/blob/main/src/server/network/protocol/protocolgame.cpp#L5901

It seems like it's all server job so client shouldn't bring local player to the top

**Comment by mehah** [comment]
well, I don't understand tibia, and I think it's kind of irrelevant for the client's operation, as my focus is not that, I'll leave it to the community to correct it.
