### ISSUE TITLE
font-scale scale the entire widget

### ISSUE THREAD

**Issue by conde2** [opentibiabr/otclient#544]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Whenever setting font-scale to a widget it resizes the entire widget. I was expecting that it only scaled the font. 

Reproduction on MainWindow put font-scale: 2

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
The text is an Image and that image is bound to the widget, so the text in itself is a widget.

https://github.com/mehah/otclient/blob/52e9e8714bf71efa138efa311cdea728176e0388/src/framework/ui/uiwidgettext.cpp#L51

https://github.com/mehah/otclient/blob/52e9e8714bf71efa138efa311cdea728176e0388/src/framework/ui/uiwidgettext.cpp#L71

https://github.com/mehah/otclient/blob/52e9e8714bf71efa138efa311cdea728176e0388/src/framework/ui/uiwidgettext.cpp#L109

https://github.com/mehah/otclient/blob/52e9e8714bf71efa138efa311cdea728176e0388/src/framework/ui/uiwidgettext.cpp#L111

https://github.com/mehah/otclient/blob/52e9e8714bf71efa138efa311cdea728176e0388/src/framework/ui/uiwidgettext.cpp#L117

**Comment by conde2** [comment]
![image](https://github.com/mehah/otclient/assets/2137569/022f6624-b7d1-4018-91ef-472cefb275b7)

But it is possible to scale only when drawing the bitmap image from the text, in here
