### ISSUE TITLE
Compiling on Ubuntu 22.04 by Wiki

### ISSUE THREAD

**Issue by diogocamaral** [opentibiabr/otclient#545]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

When running the code:
`cmake -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake .. --preset linux-release`

Got the error on terminal:
-- Fixing pkgconfig file: /home/diogo/vcpkg/packages/rapidjson_x64-linux/lib/pkgconfig/RapidJSON.pc
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:163 (message):
  Could not find pkg-config.  Please install it via your package manager:

sudo apt-get install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:203 (vcpkg_find_acquire_program)
  buildtrees/versioning_/versions/rapidjson/b33122751fc9d722f05cc50538aa9b6d08e2d105/portfile.cmake:27 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:147 (include)

error: building rapidjson:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+rapidjson
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[rapidjson]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fdiogo%2Fotclient%2Fbuild%2Flinux-release%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed
CMake Error at /home/diogo/vcpkg/scripts/buildsystems/vcpkg.cmake:893 (message):
  vcpkg install failed.  See logs for more information:
  /home/diogo/otclient/build/linux-release/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:32 (project)

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hriqueXimenes** [comment]
Estranho aqui funciona normal

**Comment by majestyotbr** [comment]
I tested with a normal user on Ubuntu 22.04 and it is working.
Read the error, it says that is missing `pkg-config` in your package manager.
Follow the tutorial step by step correctly: [Compiling on Ubuntu 22.04](https://github.com/mehah/otclient/wiki/Compiling-on-Ubuntu-22.04).
Next time, use the [OpenTibiaBR Discord](https://discord.gg/gvTj5sh9Mp) or [OTClient Redemption Discord](https://discord.gg/HZN8yJJSyC) to ask for support.
