### ISSUE TITLE
The mini map does not open in Windows

### ISSUE THREAD

**Issue by Zainox** [opentibiabr/otclient#547]
### Priority

High

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

When using OTClient, all windows open without any issues, except for the mini map. When clicking on the "minimap" button, it remains pressed but the window displaying the mini map does not appear.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yrpen** [comment]
I can confirm this on 12.86 (login.eloria.pl) and on 10.98 (local TFS 1.4.2).

# What OS are you seeing the problem on?
Linux, Ubuntu 20.04
I'm using docker container.

# OTC commit I tested this
5b409487880010db14deb189ec928c2684263673

**Comment by yrpen** [comment]
I spotted this on relogin with console error:

```
ERROR: caught a lua call to a bot protected game function, the call was cancelled
stack traceback:
	[builtin#142]: at 0x55d332e13de3
	[C]: in function 'close'
	/game_containers/containers.lua:106: in function </game_containers/containers.lua:105>
	[C]: in function 'pcall'
	/corelib/util.lua:326: in function 'signalcall'
	/corelib/ui/uiminiwindow.lua:34: in function 'close'
	/corelib/ui/uiminiwindowcontainer.lua:83: in function 'fitAll'
	/corelib/ui/uiminiwindow.lua:416: in function 'fitOnParent'
	/corelib/ui/uiminiwindow.lua:425: in function 'setParent'
	/corelib/ui/uiminiwindow.lua:165: in function 'setupOnStart'
	/game_minimap/minimap.lua:99: in function '__onGameStart'
	/gamelib/controller.lua:14: in function </gamelib/controller.lua:13>

```

**Comment by yrpen** [comment]
I can reproduce it **only** when start client with no saved otclient data.
Similar as mention here in reproduction steps: https://github.com/mehah/otclient/issues/553

But I use Linux with docker container. I don't save client data after container is stopped. So every time when I run it I have no "appdata" files.

# What functions in module are called when bug occur? When I log in.
```
minimap - updateCameraPosition
  .  UIminimap - onCameraPositionChange
  .  UIminimap - setCrossPosition
  .  UIminimap - setCrossPosition - not self.cross [first if]
  .  UIminimap - setCrossPosition - pos [second if]
minimap - onGameStart
  .  UIminimap - load
```

# When I click few times to minimap button and relog to another character it still dont work.
```
minimap - toggle
minimap - UI:close
minimap - toggle
minimap - UI:close
minimap - onGameEnd
  .  UIminimap - save
minimap - updateCameraPosition
  .  UIminimap - onCameraPositionChange
  .  UIminimap - setCrossPosition
  .  UIminimap - setCrossPosition - pos [second if]
  .  UIminimap - setCrossPosition
  .  UIminimap - setCrossPosition - pos [second if]
minimap - onGameStart
  .  UIminimap - load
```
# Third login work's
```
minimap - onGameEnd
  .  UIminimap - save
minimap - updateCameraPosition
  .  UIminimap - onCameraPositionChange
  .  UIminimap - setCrossPosition
  .  UIminimap - setCrossPosition - pos
  .  UIminimap - setCrossPosition
  .  UIminimap - setCrossPosition - pos
minimap - onGameStart
  .  UIminimap - onVisibilityChange
minimap - onMiniWindowOpen
minimap - updateCameraPosition
  .  UIminimap - setCrossPosition
  .  UIminimap - setCrossPosition - pos
  .  UIminimap - load
```

**Comment by Zainox** [comment]
Nice
