### ISSUE TITLE
Protocol 12.86 - error on login

### ISSUE THREAD

**Issue by yrpen** [opentibiabr/otclient#548]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

When I login into 12.86 server it throw error:

```
[libprotobuf ERROR /opt/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean/src/google/protobuf/wire_format_lite.cc:618] String field 'otclient.protobuf.appearances.Appearance.description' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
[libprotobuf ERROR /opt/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean/src/google/protobuf/wire_format_lite.cc:618] String field 'otclient.protobuf.appearances.Appearance.description' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
```

OTClient commit: 5b409487880010db14deb189ec928c2684263673
Tested on: https://poland.otservlist.org/ots/1649339

### What OS are you seeing the problem on?

Linux, Ubuntu 20.04
Running from docker container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
this looks like the problem is in your assets, with all the ones I've tested, they work perfectly.
