### ISSUE TITLE
HUD for HP/MANA/EXP

### ISSUE THREAD

**Issue by Warchas** [opentibiabr/otclient#55]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Go and lose HP
2. Go away so you will not lose HP
3. Heal up with a rune and the hud will NOT update

### Expected behaviour
When you heal the HUD should update

### Actual behaviour
HP Hud updates when you take damage and not when you heal

### Environment
I am using client 7.7 but I would guess that this applys to any protocol version

https://i.gyazo.com/b7467798e41c6b141807e143d14fdabc.mp4

Video of the issue above

**Comment by Warchas** [comment]
From what I understood from talking with a friend this issue doesn't happen on 8.6 so if you want to close the issue feel free, it does happen on 7.7 but it's all good, I know the project isnt supporting older protocols, I thought it was client wide issue.

**Comment by mehah** [comment]
but either way, I’ll analyze if there’s really a problem with updating the hud.

**Comment by mehah** [comment]
I tested it and it works normally, but not in Tibia 7.x, but make sure you are using all the original ot1.0 code
