### ISSUE TITLE
Battlelist error |  first time you open the client (no appdata)

### ISSUE THREAD

**Issue by kokekanon** [opentibiabr/otclient#553]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Battlelist error . first time you open the client (no appdata)

the bug is reproduced:
1) delete appdata folder (to simulate the first time you open the client)
2) enter any server
3) you will see that the battlelist is "freeze" with the first target you saw when starting the client
4) when doing login it is fixed

https://github.com/mehah/otclient/assets/114332266/4f71ede0-4228-4650-b75d-82fb28b53c72

test in 3.1 and server 8.60

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
console error?

**Comment by kokekanon** [comment]
> console error?

`Startup done :]`xd


no error console

**Comment by mehah** [comment]
the battle by default does not open open, did you change that?

**Comment by kokekanon** [comment]
> the battle by default does not open open, did you change that?

the battle does open. always opened xd

how to reproduce the bug:

1.- delete cache AppData\Roaming\otbr\otclient\otclient
(simulates that you open the client for the first time.)
2.- login to the server
3.- look at the battlelist
4.- approach an npc,monster or player.
5.- you will see the bug where they don't appear in battlelist.

6.- log in
7.- the battlelist is fixed.

bug only if:


1) only if you open the client for the first time (no cache). 
or
2)  if you delete the cache 
or
3)  change the cache folder (NOT AppData cache).


the battle list does not work correctly, it gets stuck with the first thing it saw,
