### ISSUE TITLE
The screen is broken by several in-game factors

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otclient#559]
### Priority

High

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

This is just an example using the monster when it is moved, however it also happens when there is a lot of information on the screen like spells etc...

Unfortunately, I'm not sure what kind of problem this is to name or if the solution already exists. I researched a lot before opening this topic and didn't find anything related to it.

![MoveMonster](https://github.com/mehah/otclient/assets/41605307/2db55347-871f-41c9-95f7-64f4e24426c3)

No Error
![Noerror](https://github.com/mehah/otclient/assets/41605307/ad9eb950-0d41-4a4b-8a2e-809b1f902344)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
Você precisa testar com o cliente limpo, sem modificação nenhuma, a gente não vai dar solução para algo que a gente não fez, quando você altera o cliente ou até mesmo o servidor e ocorre esses problema, a responsabilidade é totalmente sua.

resumindo: para que a gente possa corrigir o problema, vc precisa demonstrar que isso está acontecendo com o cliente e servidor sem modificações.

**Comment by LeoTKBR** [comment]
@mehah 
I understand, I am using the extended map, I noticed that this problem in the case when moving the monster only happens when it moves from 1 sqm to 1 sqm when there are 2 sqm or more, this problem does not, could you provide me with some north to look for in the src? 0.3.6 TFS

**Comment by LeoTKBR** [comment]
@mehah 
I was able to debug and return an error

apparently it's due to the fact that I made the change to have the map extended

following this tutorial

https://otland.net/threads/tutorial-adding-more-tiles-to-game-window-updated-7-6-2018.228243/

`ERROR: ProtocolGame parse message exception (2325 bytes unread, last opcode is 81, prev opcode is 100): unhandled opcode 81
ERROR: ProtocolGame parse message exception (2325 bytes unread, last opcode is 81, prev opcode is 100): unhandled opcode 81
 
ERROR: no thing at pos:5228 5219 7, stackpos:0
at:
    [C++]: ?getMappedThing@ProtocolGame@@QEBA?AV?$shared_ptr@VThing@@@std@@AEBV?$shared_ptr@VInputMessage@@@3@@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AEAAXAEBV?$shared_ptr@VInputMessage@@@std@@@Z
ERROR: no thing at pos:5230 5219 7, stackpos:0
at:
    [C++]: ?getMappedThing@ProtocolGame@@QEBA?AV?$shared_ptr@VThing@@@std@@AEBV?$shared_ptr@VInputMessage@@@3@@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AEAAXAEBV?$shared_ptr@VInputMessage@@@std@@@Z
ERROR: no thing at pos:5231 5219 7, stackpos:0
at:
    [C++]: ?getMappedThing@ProtocolGame@@QEBA?AV?$shared_ptr@VThing@@@std@@AEBV?$shared_ptr@VInputMessage@@@3@@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AEAAXAEBV?$shared_ptr@VInputMessage@@@std@@@Z
ERROR: no thing at pos:5224 5221 7, stackpos:0
at:
    [C++]: ?getMappedThing@ProtocolGame@@QEBA?AV?$shared_ptr@VThing@@@std@@AEBV?$shared_ptr@VInputMessage@@@3@@Z
ERROR: no thing`

![BugMap](https://github.com/mehah/otclient/assets/41605307/87b68110-6b26-4950-b587-002b6ee5b6d0)
