### ISSUE TITLE
Animations messed up

### ISSUE THREAD

**Issue by Warchas** [opentibiabr/otclient#56]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Go to venore above depot and stand  above the two race dogs and you'll see the coal basins like this
https://i.gyazo.com/2bc258bb505f0063a2c48ba92c86ccff.mp4

### Expected behaviour
Well it shouldn't move the coal basins like this

**Comment by mehah** [comment]
plz, use the latest rev and see if this problem has stopped occurring.
