### ISSUE TITLE
Problem holding keyboard buttons to walk

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otclient#560]
### Priority

Low

### Area

- [x] Data
- [x] Source
- [ ] Docker
- [ ] Other

### What happened?

The problem boils down to holding down any button to walk, whether it's the WASD or the keyboard arrows, the result will be the same I'm testing it in TFS 0.3.6 8.60

GIF:
https://imgur.com/OH5xB3y

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LeoTKBR** [comment]
@mehah what could be changed in the otc settings to try to fix this issue?

**Comment by mehah** [comment]
Calm down, everything has its time. 😊

**Comment by mehah** [comment]
@LeoTKBR 
test this PR(https://github.com/mehah/otclient/pull/562), plz.
