### ISSUE TITLE
Request instructions to compile in Mac OSX

### ISSUE THREAD

**Issue by paulo-roberto-rosa** [opentibiabr/otclient#561]
### Priority

Missing Content

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

There is no wiki or any instructions on how to compile it in Mac OSX. Since otclient_v8 does have that support i imagine that this one also haves the support?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodogd** [comment]
Hey there!

I hope you're doing well! I was wondering if there are any plans to include instructions for compiling the client on macOS? 

Thanks so much!
