### ISSUE TITLE
difference in the way one walks with the mouse in the different otc

### ISSUE THREAD

**Issue by ericcobblepot** [opentibiabr/otclient#563]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

I noticed that there was a difference in the way one walks with the mouse **right button** in the different otc

so test

otc mehah
otc v8  
and clipsoft

I tried with the right button (I got used to it xd)
in this race

I think the problem is in .lua

in game_interface ->processMouseAction
https://github.com/mehah/otclient/blob/main/modules/game_interface/gameinterface.lua#L918
why?
because in the only client that says
"you cannot use this object " is in mehah
I'm not very skilled in lua or c++ but maybe here is a quick solution:
v8 has this function resetLeftActions()
https://github.com/OTCv8/otclientv8/blob/master/modules/game_interface/gameinterface.lua#L601

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
Is the problem only with the right mouse button?

**Comment by ericcobblepot** [comment]
> Is the problem only with the right mouse button?

@mehah only with the right mouse
