### ISSUE TITLE
module_minimap bug?

### ISSUE THREAD

**Issue by kokekanon** [opentibiabr/otclient#565]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

I have a rare error.

tests on **windows 10 and windows 11**
compiled today 12/ 07/ 20023

I can't open the minimap module.
(the weird thing is that it used to open).

if I delete the appdata does not open module either

 don't know how I caused the bug

see this

https://github.com/mehah/otclient/assets/114332266/0ad8c860-9f6c-4e28-b171-7cb10ceefee1

or
https://www.youtube.com/watch?v=qARzEP0ACEY

# I tried with  in release 2.8 and the minimap works

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
#547

**Comment by kokekanon** [comment]
ups sorry
