### ISSUE TITLE
client not display the effect well when effect(spr/dat) is too big (width // height) specifically in the south and east

### ISSUE THREAD

**Issue by ericcobblepot** [opentibiabr/otclient#569]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

# **client not display the effect well when effect(spr/dat) is too big (width // height) specifically in the south and east**

Client compiled 07/16/2023
windows
test in server 1.5
normal view NO extend view

compare the 3 Clients
cipsoft displays efffect well
v8 displays effect well
Redemption does not display the effect well when effect(spr/dat) is too big . specifically in the south and east

https://github.com/mehah/otclient/assets/125500615/04d8d1fb-6298-4b65-98cb-1f855b037093

![a](https://github.com/mehah/otclient/assets/125500615/0dccf6bc-7112-4e35-b02d-a1c91cd4abf8)
![b](https://github.com/mehah/otclient/assets/125500615/f20d9046-affd-483f-a8f7-c9a83f99a213)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I can only test with tibia sprite, only if you make this spr/dat available to me.

**Comment by ericcobblepot** [comment]
> I can only test with tibia sprite, only if you make this spr/dat available to me.

https://drive.google.com/file/d/1W_4ouUoNC48kM29GguDTtutuXzBtN4T7/view?usp=sharing


![image](https://github.com/mehah/otclient/assets/125500615/bf198119-1d0b-4b1e-87a5-89401c98b0a7)


https://www.virustotal.com/gui/file/855a823cb101591d4c2bfeb06af272b80c98c2cf331e37046dc350b33b6e44dd?nocache=1

**Comment by mehah** [comment]
@ericcobblepot 

I haven't had time yet, but try to enable this feature: GameMapOldEffectRendering https://github.com/mehah/otclient/blob/8b2d662c56b9df1e714b90b47116bb3778584f0c/src/client/effect.cpp#L58


or remove this "for":
https://github.com/mehah/otclient/blob/8b2d662c56b9df1e714b90b47116bb3778584f0c/src/client/tile.cpp#L155

**Comment by ericcobblepot** [comment]
> @ericcobblepot
> 
> I haven't had time yet, but try to enable this feature: GameMapOldEffectRendering
> 
> https://github.com/mehah/otclient/blob/8b2d662c56b9df1e714b90b47116bb3778584f0c/src/client/effect.cpp#L58
> 
> or remove this "for":
> 
> https://github.com/mehah/otclient/blob/8b2d662c56b9df1e714b90b47116bb3778584f0c/src/client/tile.cpp#L155

1) with  Game_feature:
g_game.enableFeature(GameMapOldEffectRendering)
**Not work**

2) with delete for
![image](https://github.com/mehah/otclient/assets/125500615/10ddb680-319e-4866-8723-ab2e2bba7e92)

compilate main 24/07/2023
**not work**



3) with GameMapOldEffectRendering + delete for

**not work**

**Comment by mehah** [comment]
@ericcobblepot 

I already understand what's going on, I took a look at your script, the effects are being placed outside the screen, on the edges, the right thing is to adjust the offset, but anyway, this client does not render the edges under certain conditions, because they are not visible, to force the drawing, set this flag to true.

https://github.com/mehah/otclient/blob/fd4833cbe887f1be9fa0150b5f2b235623636ad3/src/client/mapview.h#L305

**Comment by ericcobblepot** [comment]
> @ericcobblepot
> 
> I already understand what's going on, I took a look at your script, the effects are being placed outside the screen, on the edges, the right thing is to adjust the offset, but anyway, this client does not render the edges under certain conditions, because they are not visible, to force the drawing, set this flag to true.
> 
> https://github.com/mehah/otclient/blob/fd4833cbe887f1be9fa0150b5f2b235623636ad3/src/client/mapview.h#L305

not work
![image](https://github.com/mehah/otclient/assets/125500615/8d4153eb-52d6-4773-932f-9cc6e3488ba4)

**Comment by mehah** [comment]
@ericcobblepot 

sry, have to change here:
https://github.com/mehah/otclient/blob/d884038a89d6926e7fb73b7ce1189ec278bf708f/src/client/mapview.cpp#L530

Change this:
`m_drawViewportEdge = m_forceDrawViewportEdge;`
to
`m_drawViewportEdge = true;`

![image](https://github.com/mehah/otclient/assets/2267386/68bae23a-9043-40b6-8488-be3127120e85)

**Comment by ericcobblepot** [comment]
Thanks, now works
