### ISSUE TITLE
Question / problem 

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#57]
Hello, I have a problem and a question 

my problem is, I downloaded the latest version, compiled, put my DAT (8.6) in and the light system doesn't work 
 + added to options light version
 what else have I forgotten? 

ok i forgotten:   
```
elseif key == 'lightVersion' then
    gameMapPanel:setLightVersion(value)
    lightVersionComboBox:setCurrentOptionByData(value, false)
```

my question remains: 
and the question, if the character is standing, the nickname and hp bars are visible if one moves away from the character 1-2 square off the screen 

https://i.imgur.com/rYJuYh4.png
https://i.imgur.com/5CxCjs5.png
https://i.imgur.com/kHBxIq4.png

https://i.imgur.com/aZJ7ZlE.png
https://i.imgur.com/xxfer0V.png

**Comment by mehah** [comment]
You are using the clean version of the project, apparently you are not.

[Tibia 8.6 - Clean Project]
HUD - https://i.ibb.co/JQC82L7/prova.png
Light System - https://i.ibb.co/1f3SYfR/prova2.png

**Comment by poxis** [comment]
Light now work perfect ;p  i forgotten:

 `elseif key == 'lightVersion' then
    gameMapPanel:setLightVersion(value)
    lightVersionComboBox:setCurrentOptionByData(value, false)`

move your character to the left so that NPC Liane is out of the game screen (and look to HP/name bar)
use last 'cache-for-all' but my data folder

**Comment by mehah** [comment]
1- https://ibb.co/YpVFgpL
2- https://ibb.co/jJ6vqYg

the tests have to be done with the project clean, without any modifications.

**Comment by poxis** [comment]
on clean (edubart/otclient)  it's ok, I just asked about your modification (mehah/otclient)

**Comment by Klonoa88** [comment]
> move your character to the left so that NPC Liane is out of the game screen (and look to HP/name bar)
> use last 'cache-for-all'

> my question remains:
> and the question, if the character is standing, the nickname and hp bars are visible if one moves away from the character 1-2 square off the screen

I have the same problem. it's the same for monsters, npc and players.


Exemple, Look to the right:
**Creature names and bars draws over panels**
https://www.dropbox.com/s/0dw44uar4yjbtx8/cJW3WEZj3m.mp4?dl=0

**If i add in creature.cpp, Its follow the gamescreen**
`backgroundRect.bind(parentRect);` - Line: 245
`textRect.bind(parentRect);` - Line: 248
https://www.dropbox.com/s/75d3tuckgarbngk/dxyPJxL86J.mp4?dl=0


On (edubart/otclient) i dont have this problem :(

**Comment by poxis** [comment]
it is possible that in general it is displaying the creation of a called function 
`void Creature::drawInformation(const Rect& parentRect, int drawFlags)`

Edit:
I found a 'solution' but I don't know if it's a good idea


https://github.com/mehah/otclient/blob/b910f21108a2a4e5bfa84a15a05c168687a031d3/src/client/mapview.cpp#L245

add:
```
if (!getCameraPosition().isInRange(creature->getPosition(), 7, 7, 5, 5, true))
	continue;
```

**Comment by Klonoa88** [comment]
Yes it works for me to :P But this looks better :P

```
if (!getCameraPosition().isInRange(creature->getPosition(), m_awareRange.left - 1, m_awareRange.right - 2, m_awareRange.top - 1, m_awareRange.bottom - 2, true))
        continue;
```

**Comment by mehah** [comment]
> > move your character to the left so that NPC Liane is out of the game screen (and look to HP/name bar)
> > use last 'cache-for-all'
> 
> > my question remains:
> > and the question, if the character is standing, the nickname and hp bars are visible if one moves away from the character 1-2 square off the screen
> 
> I have the same problem. it's the same for monsters, npc and players.
> 
> Exemple, Look to the right:
> **Creature names and bars draws over panels**
> https://www.dropbox.com/s/0dw44uar4yjbtx8/cJW3WEZj3m.mp4?dl=0
> 
> **If i add in creature.cpp, Its follow the gamescreen**
> `backgroundRect.bind(parentRect);` - Line: 245
> `textRect.bind(parentRect);` - Line: 248
> https://www.dropbox.com/s/75d3tuckgarbngk/dxyPJxL86J.mp4?dl=0
> 
> On (edubart/otclient) i dont have this problem :(

now i managed to understand the problem, i'll check after the carnivall. :)

**Comment by Dip-Set1** [comment]
> Yes it works for me to :P But this looks better :P
> 
> ```
> if (!getCameraPosition().isInRange(creature->getPosition(), m_awareRange.left - 1, m_awareRange.right - 2, m_awareRange.top - 1, m_awareRange.bottom - 2, true))
>         continue;
> ```

This works, however monsters to the north lose their hp bar
https://gyazo.com/3c0963d4943e829bb5d5da04ac14a613
and monsters to the west have a weird delay
https://gyazo.com/a04402026d61665712d29e8c3e60ee1d
