### ISSUE TITLE
Loading OTB files crashes client

### ISSUE THREAD

**Issue by Ziore-GD** [opentibiabr/otclient#571]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Attempting to load OTB files crashes the client.

g_things.loadOtb(path)
Unhandled exception at 0x00007FFC90E3C1F9 (ntdll.dll) in OTClient.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFC90EB18A0).

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SkullzOTS** [comment]
Maybe this will help to find the problem so that it can be solved...

![Screenshot_1](https://github.com/mehah/otclient/assets/86809689/552507ba-f2f1-4f79-b43a-1bf982886774)

**Comment by Ziore-GD** [comment]
I've located the issue but I am unsure about how to resolve this.

The issues is  : 

void ThingTypeManager::loadOtb(const std::string& file)=>
`const auto& root = fin->getBinaryTree();`

BinaryTreePtr FileStream::getBinaryTree() =>
`return std::make_shared<BinaryTree>(std::shared_ptr<FileStream>(this));`

changing this to =>
` FileStreamPtr fs = std::shared_ptr<FileStream>(this);
    return nullptr;`
Still crashes the client meaning the shared_ptr crashes the client.

**Comment by Ziore-GD** [comment]
Becuase a shared pointer is already made while opening the file and the filestream makes another when doing the getBinaryTree() it causes two shared pointers to exist and the client to crash.

```
BinaryTreePtr FileStream::getBinaryTree(FileStreamPtr ptr)
{
    if (const uint8_t byte = getU8(); byte != static_cast<uint8_t>(BinaryTree::Node::START))
        throw Exception("failed to read node start (getBinaryTree): %d", byte);

    return  std::make_shared<BinaryTree>(ptr);
}
```
