### ISSUE TITLE
"fillTextCoords" multithread

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#572]
### Priority

Enhancement

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

Are there plans to add multi-threading to functions like "fillTextCoords"? When calculating a large amount of text on weaker computers, the client freezes for a few seconds. In OTCv8, this is done multi-threaded. It would surely help many users.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
what were the tests you did to discover that the fillTextCoords is taking a long time to be processed, because I need to do the same tests to see a solution.

**Comment by patrykq112** [comment]
> what were the tests you did to discover that the fillTextCoords is taking a long time to be processed, because I need to do the same tests to see a solution.

when more than 50 monsters are spamming spells and dealing damage at the same time, it lags

**Comment by mehah** [comment]
@patrykq112 
all the texts are already in another thread, the only one that is not, is the names of the creatures.

https://github.com/mehah/otclient/blob/1707856ab8fa188c058c11c3a85204ba71a69785/src/framework/core/graphicalapplication.cpp#L186


do you have a weak pc to test?

you just need to disable all text rendering options in options and then go enabling one by one and see which one is consuming a lot of CPU.

**Comment by mehah** [comment]
@patrykq112 

test the last commit(https://github.com/mehah/otclient/commit/206da188c58d99f5674b5a3171ea94a076dd0274), there were significant improvements regarding threads.

**Comment by kokekanon** [comment]
Windows 10
ram 32 gb
GPU 3080
intel i7 10700-k 
monitor 1080P 144hz

I think g window.vsync Enabled() is causing performance issues
bug reproduces in populated zone
only when starting client with (vsync)
or clean cache

![image](https://github.com/mehah/otclient/assets/114332266/18bbdc52-e779-4912-8586-bf1673eed91e)

 if vsync is disabled it is fixes
 if logout it is fixes

https://github.com/mehah/otclient/assets/114332266/6ef04e74-9b34-4b69-8034-bfed87c40064
