### ISSUE TITLE
[Bugs] when update is activated

### ISSUE THREAD

**Issue by kokekanon** [opentibiabr/otclient#578]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

<details>
  <summary>original bug that was opened the issue, currently cannot be reproduced.

I keep this as history</summary>

if enable updater black screen

out of 10 attempts 9 were black screens

the 9th attempt enter a portal or stairs and black screen

only happens with updater enable

compilate today right now

no error console

https://github.com/mehah/otclient/assets/114332266/eceb5798-672d-438b-89a1-6a4b06d16213

windows 10
test
server 8.6 | 0.4
server 8.6 | 1.5
PLAYER., no gm privileges 
</details>

# Edit : after 6 months, the original  error: "black screen if enable update" has been fixed(I don't know in which commits)

# I'm keeping the post open because there are other bugs mentioned in the comments.

**Comment by kokekanon** [comment]
ps: ultra low priority xd
shader bug widget if activate update

**Comment by kokekanon** [comment]
0.-  in the last commit I cannot reproduce the black screen


1.- crash o not respond or akes too much time [is odd because I have 4 PCs:
On 2 of them, it's fast.
On 1 it's slow, and
last one client doesn't respond. xd ]


2.- Attacheffect  ?   although it lasts 1 second


maybe #645  ?

![image](https://github.com/mehah/otclient/assets/114332266/ad907fe2-be8f-4acb-a0a3-d5872c991cfd)



https://github.com/mehah/otclient/assets/114332266/1fd7cc01-d2fd-4e93-a153-318eacbae840

**Comment by mehah** [comment]
https://github.com/mehah/otclient/commit/6064940cac9e49e0939892753416de516d35ba9b

**Comment by kokekanon** [comment]
# 1.-Regarding the texture displayed at the end of the bar

additionally the cache configurations are not loaded correctly if the update is enabled. 
For example I have disable audio, after finishing the bar, it does not respect the configuration and the music plays, when it is disabled. 
Just as it happens with music, what would happen if a more significant configuration is not respected?


![image](https://github.com/mehah/otclient/assets/114332266/246c173e-59f3-4157-a9ec-b44ae3a04177)

https://github.com/mehah/otclient/assets/114332266/1bf8e595-79c1-4e4a-b6b9-d2520e277d38
 ## 1.2  Posible fix : 
  load-later:
    - client_background
    - game_interface
    - client_options
    
  why work ? idk jaj
and use 
```
if g_app.hasUpdater() then
        connect(g_app, {
            onUpdateFinished =
```
?     
            

# 2.- Regarding the performance issue, i trace the problem back to g_resources.filesChecksums() I believe the issue lies within g_resources.filesChecksums().
on some pc*
https://github.com/mehah/otclient/blob/6b112c2b9b10ce1156632d8ada371680c95eb336/src/framework/core/resourcemanager.cpp#L572C1-L592C2


this fixes the freezing bug or no response, 
but applies only to small amounts of files.
what would happen with large amounts
I'm not a programmer cpp, but maybe IF
only checks the files that are specifically marked for updating, rather than reviewing all files in the system.

 ## 2.2  Posible fix : 
I'm not good at cpp
```lua
  if updateData.files == {} then
    localFiles = {}
  else 
    localFiles = g_resources.filesChecksums(updateData.files)
  end
  ```
  ```cpp
  std::unordered_map<std::string, std::string> ResourceManager::filesChecksums(const std::unordered_map<std::string, std::string>& filesToUpdate)
{
    std::unordered_map<std::string, std::string> ret;

    for (const auto& fileEntry : filesToUpdate) {
        const auto& filePath = fileEntry.first;

        PHYSFS_File* file = PHYSFS_openRead(filePath.c_str());
        if (!file)
            continue;

        int fileSize = PHYSFS_fileLength(file);
        std::string buffer(fileSize, 0);
        PHYSFS_readBytes(file, (void*)&buffer[0], fileSize);
        PHYSFS_close(file);

        auto actualChecksum = g_crypt.crc32(buffer, false);
        ret[filePath] = actualChecksum;
    }

    return ret;
}
```
```h
    std::unordered_map<std::string, std::string> filesChecksums(const std::unordered_map<std::string, std::string>& filesToUpdate);
```


# 3 Inexistent variables

`ALLOW_CUSTOM_SERVERS`
`APP_VERSION`

error:
![image](https://github.com/mehah/otclient/assets/114332266/bb4aebbe-b18e-40f9-b9c0-96b7ed29fc47)

3.1 posible fix: 
` version = g_app.getVersion()`
del : ALLOW_CUSTOM_SERVERS

**Comment by patrykq112** [comment]
this bug still exists @mehah

**Comment by rodrigopaixaorj** [comment]
@kokekanon bug remains or not ?

**Comment by kokekanon** [comment]
https://github.com/mehah/otclient/assets/114332266/29757094-9ad7-4fd8-a610-279e5d2f3a49

| Bug   | Description                                               |
|-------|-----------------------------------------------------------|
| [ -  ] | A texture appears at the end of the bar or cancel![image](https://github.com/mehah/otclient/assets/114332266/882aee55-d086-413c-9c6a-ead3bb45a93f)    |
| [ -  ] | Lag when running  g_resources.filesChecksums(updateData.files) [depends on computer] |

I proposed a solution, but I'm not good at cpp.
