### ISSUE TITLE
Add WASD Walking and extra hot key binding

### ISSUE THREAD

**Issue by Nug0** [opentibiabr/otclient#58]
Hello,

Just wondering if you can add WASD walking and extra functionality around binding hotkeys. Similar to kondrahs OTclientv8

I have attached some screenshots for example

https://gyazo.com/7532a3e2ecc12cd7471d064548e13da5
https://gyazo.com/bb51ab288e1814b1408aade41cfaeca8
https://gyazo.com/e201cbb00f029e821192a6aee2540125

**Comment by mehah** [comment]
otclient already has WASD walking and about hotkeys, my focus is not this, I will leave it up to you in the community to develop.

**Comment by oarsc** [comment]
Added Shift+Enter to toggle WASD walking.
You can press Enter to set it off.

The WASD mode is now preserved after restarting client.

It will be available on the next release (or you can build the latest code by yourself)
