### ISSUE TITLE
Request ,Feature : g_game.enableFeature(GameNegativeOffset)

### ISSUE THREAD

**Issue by ericcobblepot** [opentibiabr/otclient#583]
### Priority

Enhancement

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

I count like 3 or 4 people on discord asking how to offset creatures,

and recently
punkice3407/ObjectBuilder v0.5.5 https://github.com/punkice3407/ObjectBuilder/releases/tag/v0.5.5

> New versions 12.31+
> A window to change frame durations for all objects at once.
> **Support for negative offsets.**
> Fixes related to duration settings and frame groups.
> Fixed sort order when adding, replacing, or drag-dropping sprites and objects.

enable the negative offset option.

![image](https://github.com/mehah/otclient/assets/125500615/0b351dbe-4d94-44d3-983b-c941b926b344)

g_game.enableFeature(GameNegativeOffset)  -- https://github.com/punkice3407/ObjectBuilder/releases/tag/v0.5.5

Would it be possible to add this?

aplication 
![zxcq](https://github.com/mehah/otclient/assets/125500615/56b8d150-6d77-4c94-9102-57c46983fe72)

photoshop xd

Currently if I try, the outfit disappears

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by linkzzjr** [comment]
try adding the transparency effects in the otclient initialization file (init.lua)
