### ISSUE TITLE
Rendering error on tiles with opacity

### ISSUE THREAD

**Issue by csantbr** [opentibiabr/otclient#585]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

**Test Environment**
TFS: 1.4
Protocol: 10.98

When entering and exiting structures with roofs that have opacity the tile under that roof disappears turning black.

This problem happens without and with custom sprites, the problem does not occur in OTCV8 as can be seen in the GIF below.

**OTClient Mehah:**
![Mehah](https://github.com/mehah/otclient/assets/61211407/984d147f-335c-408f-99c9-6994b04343e9)

**OTClient V8:**
![V8](https://github.com/mehah/otclient/assets/61211407/d5fc5d45-33d9-455e-82d3-b16160a56370)

I invoke the brave: @mehah @conde2 @ranisalt 

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by conde2** [comment]
Was this fixed? @csantbr

**Comment by csantbr** [comment]
Not that I remember @conde2, but @mehah at the time explained why this happened as far as I remember, I just don't remember what the reason was haha.

**Comment by conde2** [comment]
To be honest I think this is fixed, it was probably with the reset once opacity state

https://github.com/mehah/otclient/commit/e0a21e09dcc331b67ae7567a28b2fca7aa9a6ca8
