### ISSUE TITLE
White tile on hold shift

### ISSUE THREAD

**Issue by Riverlance** [opentibiabr/otclient#586]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

When you hold `Shift` in some tiles, the north-east tile turns into fully white.
It started to happen after commit [fix](https://github.com/mehah/otclient/commit/2e5d2b6774f8ba328c16bec288b1ef7f9516a21d) https://github.com/mehah/otclient/issues/474.

### How to reproduce it?

I reproduced it by creating the item id 6491 (firefly) at Position(94, 127, 7), and then by holding `Shift` at this position some times:

![cd0c1494912dc2d1a3e1cc92b3a479b6](https://github.com/mehah/otclient/assets/2280432/bc43608e-2102-485b-8b54-07b74b5579ad)

I think this happens maybe because the firefly decays to another item and transforms to it again.
I noticed this happens only when it transforms to 6494 (nothing shown), but not when it transforms to 6491, but I'm not really sure about that.

---

Note: I tried this with the original code of 19th August 2023 (latest commit: [feat: GameCountU16](https://github.com/mehah/otclient/commit/371eeec2a7731c0b4437146515108b01f7be00d5)) with original TFS 1.5 and protocol 12.87.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
looks like --> https://github.com/mehah/otclient/issues/420


test patrykq112 solution
