### ISSUE TITLE
[Docker] vpkg git checkout

### ISSUE THREAD

**Issue by Kizuno18** [opentibiabr/otclient#587]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [X] Docker
- [ ] Other

### What happened?

A bug happened!
Here is the screenshot of the issue.

Steps to reproduce:
1 - clone repository
2 - run docker build -t mehah/otclient .

![Screenshot 2023-08-20 124911](https://github.com/mehah/otclient/assets/110933270/bba71225-cb6b-4c89-84d2-50fd7d4bca5a)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
This case should be closed, since there's no more activity.

**Comment by Kizuno18** [comment]
> This case should be closed, since there's no more activity.

i think it is fixed in recent commits, thanks.
