### ISSUE TITLE
Cannot compile source files in Arch Linux

### ISSUE THREAD

**Issue by gsguilioti** [opentibiabr/otclient#588]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

The instructions in wiki for arch linux compiling are outdated, but searching myself i found the new location of files. After run the script generate.sh from protobuf, i'm trying to use cmake . -B build, however this error occur with libvorbis: 

CMake Error at src/CMakeLists.txt:213 (find_package):
  Could not find a package configuration file provided by "Vorbis" with any
  of the following names:

    VorbisConfig.cmake
    vorbis-config.cmake

  Add the installation prefix of "Vorbis" to CMAKE_PREFIX_PATH or set
  "Vorbis_DIR" to a directory containing one of the above files.  If "Vorbis"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thiagomedeiros11** [comment]
Same issue on Fedora 39.

**Comment by mehah** [comment]
I'm cleaning the issue list, if anyone wants to open a new one with the same subject, feel free.
