### ISSUE TITLE
possible bug with isOpaque()

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#59]
I noticed a certain problem when we put an item on the parcel that is 'opaque' then if I log in next to it, you cannot see the floor (black grid) 

or if the items are 'ON' an opaque object after logging in next to it you can only see this item, the rest is under it but in the look you can see that there is something on it

**Comment by mehah** [comment]
could you do a demonstration?

**Comment by poxis** [comment]
Here: https://imgur.com/a/uVU0xBU

And found next bug? with item "top" eg. archway. (id: 1125)
- when we put items under an item from 'TOP', it displays them in the wrong order but after relog / when it disappears from the screen it's ok. : https://imgur.com/a/0794V0q

**Comment by mehah** [comment]
strange that you can move a ground, this is your customization, correct?
even if it is, try to set 0 in this line, you should fix your problem:
https://github.com/mehah/otclient/blob/a98c586db189a04ab2b01ccdb3256e7c6162a2ad/src/client/features.h#L43
