### ISSUE TITLE
Build/Compiling Issues in 'Windows with Visual Studio using Solution' Tutorial

### ISSUE THREAD

**Issue by Uore** [opentibiabr/otclient#599]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [X] Other

### What happened?

I encountered several compilation errors when trying to build the otclient project from a fresh clone of the main repo, without making any modifications. The errors occur in the qrcodegen.cpp file.

Environment Details:
Otclient version: (The Main Repo).

Operating System: Windows (Windows 11 Professional).
Compiler: [Visual Studio 2022 Community], Vcpkg.

These are the errors below:
`1>C:\Users\Mario\Desktop\mehah otclient\src\framework\stdext\qrcodegen.cpp(302,24): error C2589: '(': illegal token on right side of '::' (compiling source file x64\Release\unity_UGAZKTKLSWTCC5YP.cpp)`

`1>C:\Users\Mario\Desktop\mehah otclient\src\framework\stdext\qrcodegen.cpp(302,19): error C2062: type 'unknown-type' unexpected (compiling source file x64\Release\unity_UGAZKTKLSWTCC5YP.cpp)`

`1>C:\Users\Mario\Desktop\mehah otclient\src\framework\stdext\qrcodegen.cpp(302,78): error C2059: syntax error: ')' (compiling source file x64\Release\unity_UGAZKTKLSWTCC5YP.cpp)`

`1>C:\Users\Mario\Desktop\mehah otclient\src\framework\stdext\qrcodegen.cpp(468,20): error C2589: '(': illegal token on right side of '::' (compiling source file x64\Release\unity_UGAZKTKLSWTCC5YP.cpp)`

`1>C:\Users\Mario\Desktop\mehah otclient\src\framework\stdext\qrcodegen.cpp(468,15): error C2062: type 'unknown-type' unexpected (compiling source file x64\Release\unity_UGAZKTKLSWTCC5YP.cpp)`

`1>C:\Users\Mario\Desktop\mehah otclient\src\framework\stdext\qrcodegen.cpp(468,20): error C2059: syntax error: ')' (compiling source file x64\Release\unity_UGAZKTKLSWTCC5YP.cpp)`

`1>C:\Users\Mario\Desktop\mehah otclient\src\framework\stdext\qrcodegen.cpp(480,43): error C2589: '(': illegal token on right side of '::' (compiling source file x64\Release\unity_UGAZKTKLSWTCC5YP.cpp)`

`1>C:\Users\Mario\Desktop\mehah otclient\src\framework\stdext\qrcodegen.cpp(480,38): error C2062: type 'unknown-type' unexpected (compiling source file x64\Release\unity_UGAZKTKLSWTCC5YP.cpp)`

`1>C:\Users\Mario\Desktop\mehah otclient\src\framework\stdext\qrcodegen.cpp(480,79): error C2059: syntax error: ')' (compiling source file x64\Release\unity_UGAZKTKLSWTCC5YP.cpp)`

`1>Done building project "otclient.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 6:22 AM and took 13:52.482 minutes ==========`

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by conde2** [comment]
The latest commit should fix it.
Do you have your source updated?

**Comment by rodrigopaixaorj** [comment]
> The latest commit should fix it. Do you have your source updated?

Not fixed bro, I told u

**Comment by Uore** [comment]
> The latest commit should fix it. Do you have your source updated?

Still right now it ain't working , and yes I'm already using a fresh sources.

**Comment by rodrigopaixaorj** [comment]
The fix:

`Line 302 -> bb.appendBits(0, std::min<int>(4, static_cast<int>(dataCapacityBits - bb.size())));`
`Line 468 -> int dist = std::max<int>(std::abs(dx), std::abs(dy));  // Chebyshev/infinity norm`
`Line 480 -> setFunctionModule(x + dx, y + dy, std::max<int>(std::abs(dx), std::abs(dy)) != 1);`

**Comment by rodrigopaixaorj** [comment]
@mehah You can close this thread (PR #600)
