### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by Olddies710** [opentibiabr/otclient#6]
tryed to compile latest revision and got this problem
src\client\mapview.h(173,16): error C2065: 'MapViewControl': undeclared identifier (compiling source file .. \ src \ client \ viewportcontrol.cpp)

EDIT::

FIXED SORRY

**Comment by mehah** [comment]
Strange, the file 'viewportcontrol.cpp' no longer exists, download it again from main branch, cache-for-all.
