### ISSUE TITLE
ERROR: Failed to read dat '/data/things/1000/Tibia.dat'

### ISSUE THREAD

**Issue by Piksel91** [opentibiabr/otclient#601]
### Priority

Medium

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Hello, 

I had compile latest source code otclient from this repository. I've got occurs problem with login to ex. gunzodus.net with custom Tibia.dat (1000).
Maybe someone know how to fix login problem ?

Log information: `
ERROR: Failed to read dat '/data/things/1000/Tibia.dat': corrupt data (id: 628, category: 0, count: 255, lastAttr: 0)'`

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by conde2** [comment]
Hello, unfortunately this is not a place to ask for help. You are trying to load a custom spr and day with a different format, so this is not a bug in the client.

You can ask for help in the discord.
