### ISSUE TITLE
error when opening purchase dialog (trade) with NPC

### ISSUE THREAD

**Issue by luanluciano93** [opentibiabr/otclient#603]
### Priority

Low

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

When trading with an NPC, the player is unable to buy anything and an error log is generated.

Tested with tibia client and NPC sells normally.

![image](https://github.com/mehah/otclient/assets/6209529/d64cd643-4825-4734-b650-b97e1bb297e1)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csantbr** [comment]
I couldn't reproduce it with Protocol 10.98 and TFS 1.4.2. Which version of TFS and Protocol are you using?

**Comment by luanluciano93** [comment]
canary 13.21
