### ISSUE TITLE
Is it possible to add vbot 4.8 or 1.3?

### ISSUE THREAD

**Issue by otmexa** [opentibiabr/otclient#604]
### Priority

Missing Content

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What is missing?

Hello, I was wondering if it is possible to add vbot 4.8 or 1.3 to this client. Or is it just not compatible?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kizuno18** [comment]
yes

**Comment by otmexa** [comment]
> yes

How Bro only add game module ?

**Comment by csantbr** [comment]
The same is not compatible, perhaps this could be done in the future but it is not a priority.

**Comment by rodrigopaixaorj** [comment]
Check it out #621
