### ISSUE TITLE
onLook is selecting incorrect floor as (first) reference

### ISSUE THREAD

**Issue by dev-blackstone** [opentibiabr/otclient#607]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

When I am hovering on another floor it is focusing the items on the floor that I am standing at.
I can not "look" at items above either. It is always printing the information for the items below, unless there is nothing below.
I can't find a change since it has worked in the past aside the use of 'FlagProp' for explicit visibility.

![image](https://github.com/mehah/otclient/assets/100410789/21560c6d-045d-48e8-af56-63d3d81ab225)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
Confirmed +1

https://github.com/mehah/otclient/assets/7372287/f8acede9-4e4e-43e3-ba50-0949642a9938

**Comment by rodrigopaixaorj** [comment]
Well, in my case, I found the problem....
It was missing a blank tile (red square) below sign in railing (only with 1 fuckin' sign)

![image](https://github.com/mehah/otclient/assets/7372287/5b0843a0-4cb8-4339-8b82-5ac70dea3424)

In fact, there's no error in function getTopLookThing(), must be a flag problem in item @dev-blackstone , use Object Builder and compare with old version

@mehah @conde2 This case should be closed ;)

FYI -> Opened a thread in OTAcademy Discord (https://discord.com/channels/965178465915633674/1197615795245695067)

**Comment by dev-blackstone** [comment]
@Nottinghster 
I tend to disagree. There should not be the need of putting the red tile underneat.
(I will check the possibility of invalid flags on my items tho)
However! This issue also occurs on other spots and not only at the edges.

Example:

1) I have a house and put something on the top floor.
2) I put something on the floor below the item.
3) I make an "onLook" on the top floor to view the top floor item.
==> it prints me the item that is below

I mean, maybe something blew up my items completely. 
I will check that but I never used the itemeditor or objectbuilder to alter it in the first place. It is still the same files as when it worked.

**Comment by dev-blackstone** [comment]
@Nottinghster @mehah 

I reverted a change that fixed the issue with the onLook.

[Cleanup Commit](https://github.com/mehah/otclient/commit/f5f6d48ba22d78ca757475810e58ab624b9f4114#diff-6fc2dd756d2a405d13292fd3ceab8308ee31d46de740ea68e8151a369aa6f22b)


src/client/tile.h
src/client/tile.cpp

Someone refactored method "Tile::isClickable" and after undoing your changes the onLook worked flawless again.
