### ISSUE TITLE
Half-stairs are no longer working visually

### ISSUE THREAD

**Issue by dev-blackstone** [opentibiabr/otclient#608]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

In the most recent version of OTClient Redemption "half-stairs" are no longer working (visually).
This is due to the fact that the drawing order is incorrect. Ground borders are no longer rendered on top of elevated items as they are meant to be if they are placed on top.

![image](https://github.com/mehah/otclient/assets/100410789/f88fae52-995d-470e-9016-10102e937d24)
![image](https://github.com/mehah/otclient/assets/100410789/9000f2e1-8c63-4f2d-bf6d-872b5f0ab224)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev-blackstone** [comment]
This is probably the wrong drawing priority bug as for:

![image](https://github.com/mehah/otclient/assets/100410789/26cc409c-e5a1-475f-8df5-484afeb0997d)
![image](https://github.com/mehah/otclient/assets/100410789/6c8d5714-4045-4c50-bfa1-9df96890c019)

**Comment by rodrigopaixaorj** [comment]
@dev-blackstone Could you compile the newer version and test if it's okay ?
If yes, this should be closed!

Already tested and seems working 100%

**Comment by dev-blackstone** [comment]
@Nottinghster 

Tested with 10.98 and it is sadly still not working with the newest version of OTClient.
Using the same items files for OTCv8 + RME does work.

**Comment by rodrigopaixaorj** [comment]
@mehah @conde2 could u guys, take a look at this ?

**Comment by mehah** [comment]
It is necessary to provide me with the map with these rendering problems so that I can analyze what is happening.

**Comment by dev-blackstone** [comment]
@mehah 

I am using https://ots.me/downloads/data/tibia-clients/dat_and_spr/1098.zip
See the map file attached

[test.zip](https://github.com/mehah/otclient/files/13823442/test.zip)

By the way: The "onLook" does print the correct item information that is visually below.

**Comment by mehah** [comment]
@dev-blackstone , I need the positions where this problem occurs.

**Comment by dev-blackstone** [comment]
@mehah 
Position {x = 1023, y = 1022, z = 7} in the sample file

**Comment by mehah** [comment]
![image](https://github.com/mehah/otclient/assets/2267386/bc93c1d9-e045-4aa6-aa02-beda99c63690)
You can fix this by removing this trunk, it shouldn't even be the first object, all common items are automatically cast to be rendered in third order, it was done this way to optimize rendering.

1- ground
2- ground borders
3- ...

![image](https://github.com/mehah/otclient/assets/2267386/1d563845-9786-4284-bdfe-b14417a652e3)
This seems to be a general bug, it happens in all OTC, even v8.

I will close this topic.
