### ISSUE TITLE
Performance problem when killing a lot of monsters at the same time on screen.

### ISSUE THREAD

**Issue by conde2** [opentibiabr/otclient#609]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

If there are a lot of monsters in screen and you kill all them at the same time there is a freeze in the client

https://github.com/mehah/otclient/assets/2137569/c3a0a489-e100-4c30-933a-ebef2b03f57c

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by conde2** [comment]
After some investigation the problem was found in the game_console, because there is a lot of messages being added to the Server Log (a lot of new widgets being created simultaniusly) the client freezes.

Propoused solution: Create and cache some widgets at the startup and reuse them when adding a new message to server log.

![image](https://github.com/mehah/otclient/assets/2137569/21fe2ec2-00d4-442f-8c22-83dd8f557b2c)

**Comment by csantbr** [comment]
Contributing my 2 cents haha, when testing on protocol 10.98 and TFS 1.4.2 the same thing happens here.

**Comment by 4drik** [comment]
The issue is caused of updateChildrenIndexStates. I have a hackfix for it but we should find a proper way to update it.

**Comment by luanluciano93** [comment]
sorted out?

**Comment by mehah** [comment]
@luanluciano93 
I believe so, there was a critical correction when creating the widgets and I am almost certain that this was what was causing the lag reported by this issue.

commit: https://github.com/mehah/otclient/commit/a75536d507bc9c9a83185b207cea014834521928
