### ISSUE TITLE
Missile bug?

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#61]
after adding 'isMissile' at this point it better displays distance animations but first I have to do **!x 1** on the server to make the animation smooth 

> if(isItem() || isEffect() || isMissile()) {
https://github.com/mehah/otclient/blob/f308791b8abddafb027e8523c6c9cec110b34847/src/client/thing.cpp#L42

**Comment by mehah** [comment]
try define 1 in:
https://github.com/mehah/otclient/blob/ae9657252512d86636df7bbf77c34bfa6e7021b5/src/client/features.h#L33

**Comment by poxis** [comment]
Unfortunately it did not help. It is strange that with e.g. '!x 20' the animation is smooth, but not when casting a spell.
And only after that eg. '!x 20' animation when casting ranged spells is ok (+ change to 'if(isItem() || isEffect() || isMissile()) {')

**Comment by poxis** [comment]
I search 'fix'  and work for me:

change:
https://github.com/mehah/otclient/blob/69da7d8c2da26bd78a77b67420165db4e7dbd44a/src/client/missile.cpp#L91

`schedulePainting(getAnimationInterval());`
to
`schedulePainting(17);`




//// BTW  I hash (//) this lane and I don't see any difference in works 
https://github.com/mehah/otclient/blob/69da7d8c2da26bd78a77b67420165db4e7dbd44a/src/client/map.cpp#L151

**Comment by mehah** [comment]
I tested it with SQM 10 and now it looks good, but on certain occasions, when there are many draw requests, there may be a delay, to correct this, you can force the animation draw by setting 1 in FORCE_ANIMATED_RENDERING
