### ISSUE TITLE
possible to change layout to retro?

### ISSUE THREAD

**Issue by realmaddev1337** [opentibiabr/otclient#614]
### Priority

Missing Content

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What is missing?

possible to change layout to retro? I tried to copy layouts folders from otclient 8 and added inside but it had no effect, is there any way to force/enable by default the retro layout?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
try https://otland.net/threads/otclient-classic-ui.279994/

**Comment by realmaddev1337** [comment]
its not what we archieve when using layout/retro

**Comment by mehah** [comment]
in dev: https://discord.com/channels/888062548082061433/888067068207960094/1220400021694976040
