### ISSUE TITLE
Character Bug After Death.

### ISSUE THREAD

**Issue by KingOlafPrimeiro** [opentibiabr/otclient#615]
### Priority

Critical

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

im using base canary, with otc mehah. 
after dead player no teleport to temple, need relog.

https://github.com/mehah/otclient/assets/147228488/5053ed80-18f7-4701-8b3b-6e88c3416d47

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KingOlafPrimeiro** [comment]
ProtocolGame parse message exception (15384 bytes, 1599 unread, last opcode is 0x03 (3), prev opcode is 0xe9 (233), proto: 1100): unhandled opcode 3




anyone?

**Comment by mehah** [comment]
I'm cleaning the issue list, if anyone wants to open a new one with the same subject, feel free.
