### ISSUE TITLE
outfits lua for wings/shaders/auras?

### ISSUE THREAD

**Issue by realmaddev1337** [opentibiabr/otclient#616]
### Priority

Critical

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

Is there anyway we can use the game_outfits module from https://github.com/OTCv8/otclientv8/blob/master/modules/game_outfit/outfit.lua since it has support for wings/auras etc

I tried using it directly but it seems the format is differently :(

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
Why priority : critical JAJAJa

**Comment by realmaddev1337** [comment]
cause this outfit.lua/system inside the otclient looks like tibia 7.4 lol i dont really understand why it was implemented like that when it was way more advanced in otc8? this only has addon/mount look like 7.4

**Comment by csantbr** [comment]
This is not a BUG and has no impact on the functioning of the application, so it has no critical priority.

**Comment by rodrigopaixaorj** [comment]
@conde2 this should be closed

**Comment by felipecasadia** [comment]
This is a good feature to be implemented... Any news?

**Comment by mehah** [comment]
I'm cleaning the issue list, if anyone wants to open a new one with the same subject, feel free.
