### ISSUE TITLE
please add support for ots ezodus "login error: only clients with protocol...", "error: unable to load dat"

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otclient#617]
### Priority

Missing Content

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What is missing?

<img width="689" alt="features problem" src="https://github.com/OTAcademy/otclientv8/assets/130997613/0711ac53-9293-42a8-8f0e-c04e1e65088c">

by default working on:
https://github.com/OTCv8/otclientv8
https://github.com/OTAcademy/otclientv8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
+12xx = port 80

**Comment by Piksel91** [comment]
> +12xx = port 80

@mehah  how to connect ezodus 12xx via port 80?

I used `https://www.ezodus.net/game/login/1320?nservice.php` withoud port and I received "login and password is not correct". 
Can you help with this ?

**Comment by Zbizu** [comment]
@Piksel91 web login standard is your e-mail in "account name" field

**Comment by Piksel91** [comment]
@Zbizu I know that and I was try do that but always receive the same information.

**Comment by Piksel91** [comment]
@mehah can you help with login problem in 10.00 Client? We have tibia.dat and tibia.spr but probably you not support something. On defauld OTclientv8 works fine. Can you fix that? We can't play on gunzo/ezo on client 13+ unfortunattely but maybe we try on 10...

`g_game.enableFeature(GameSpritesU32)` not working.

**Comment by rodrigopaixaorj** [comment]
@conde2 this should be closed
