### ISSUE TITLE
Faltando DLL ao compilar com cmake no modo debug

### ISSUE THREAD

**Issue by luanluciano93** [opentibiabr/otclient#619]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

Ao compilar em modo debug e iniciar o executável está dando erro pois faltam 2 DLL.

**zlib1.dll e clang_rt.asan_dbg_dynamic-x86_64.dll**

![image](https://github.com/mehah/otclient/assets/6209529/7bc847f3-025d-46d9-a44a-ad722d4faefe)

![image](https://github.com/mehah/otclient/assets/6209529/e947f128-8bb1-4a60-b447-d909fdd477a9)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csantbr** [comment]
Realizei o teste localmente e ocorre o mesmo problema. Conforme as pesquisas que realizei isso não é bem um erro, na realidade essas DLLs já vem por padrão na instalação do Visual Studio, se você adicionar na sua variável **PATH** o caminho a seguir, esse problema será resolvido: `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\<VERSION>\bin\Hostx86\x64`.

**Comment by luanluciano93** [comment]
obrigado
