### ISSUE TITLE
Cannot compile on Windows 10 using SLN

### ISSUE THREAD

**Issue by gesior** [opentibiabr/otclient#623]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

@Giorox 
After this commit https://github.com/mehah/otclient/pull/611 I cannot compile anymore on Windows 10 using .sln file.

![image](https://github.com/mehah/otclient/assets/2642737/3b5af81f-d8ab-4bc7-8590-93c6d421fd63)

It says that there is a bug in `shellapi.h` as it uses `EXTERN_C` which is not defined.
This file is part of Windows 10 SDK. I've installed 3 available versions. All have same problem:
![image](https://github.com/mehah/otclient/assets/2642737/769ea05e-9302-4d49-a98b-99e182844a5a)

After removing:
```
#include <shellapi.h>
```
It works again.

IDK what fixed this commit for Giorox, but it looks like it may break build on other machines.

Tested debug/release and 32/64 bit version. Before this commit all worked, after commit all have same problem.

Evaluated preprocessor config:
![image](https://github.com/mehah/otclient/assets/2642737/183d0083-195a-4964-a4dc-01b1214e4639)
Maybe there is something different, which makes my `shellapi.h` does not load `winnt.h` or `guiddef.h` (`EXTERN_C` is defined in these 2 files).

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Giorox** [comment]
This is very weird. I'm not home currently, but when I come back I'll check my project properties, pre-processor configs etc to see if we can find some difference that might cause this.

I am on 64bit Windows, not sure if that might have something to do with this.

**Comment by gesior** [comment]
Test it few more times. Always with Rebuild Solution.

With this line:
```cpp
#include <timeapi.h>
```
it builds Release, but does not build Debug. There are some errors about redefinition of some variables.

With this line:
```cpp
#include <shellapi.h>
```
it does not build at all.

I will install clean Windows 10 in VM and run VS2022 there.

**Comment by mehah** [comment]
@gesior try this:

ex:
```c++
#ifdef EXTERN_C
#include <shellapi.h>
#endif
```

**Comment by gesior** [comment]
After last Mehah commit I can compile all versions (release/debug 32/64) on my Windows 10 and Ubuntu 22.04.
@Giorox Can you confirm that it works on your VS2022 too?

**Comment by Giorox** [comment]
> After last Mehah commit I can compile all versions (release/debug 32/64) on my Windows 10 and Ubuntu 22.04.
> @Giorox Can you confirm that it works on your VS2022 too?

I can compile aswell over here, seems like that fixes it :)
