### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#63]
when there is 'border' and there is no ground you can try to go towards the 'border'
https://i.imgur.com/BgSf7R6.png

"'FIX":
```
	if (thing->isGroundBorder() && !getGround())
		m_countFlag.notWalkable += value;
```
https://github.com/mehah/otclient/blob/34b55ddd2382ec2be9124a34af71c3da69839e06/src/client/tile.cpp#L904

**Comment by mehah** [comment]
this is a little strange, isn't it?

The verification is done in this method:
https://github.com/mehah/otclient/blob/34b55ddd2382ec2be9124a34af71c3da69839e06/src/client/tile.cpp#L660

**Comment by poxis** [comment]
you are right, I changed this code and it's ok for me 
https://github.com/mehah/otclient/blob/31d4a4f1d5ef8d4eb4007a1db61905ee4ab0b981/src/client/tile.cpp#L657

to `if(m_countFlag.notWalkable > 0 || !getGround())`
