### ISSUE TITLE
"lto-wrapper: warning: using serial compilation" - missing linker flag "-flto=auto" on Linux

### ISSUE THREAD

**Issue by gesior** [opentibiabr/otclient#630]
### Priority

Enhancement

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What is missing?

Compilation on Ubuntu 22.04 shows this warning:
```
lto-wrapper: warning: using serial compilation of 16 LTRANS jobs
```
To fix it I added line:
```
target_link_options(${PROJECT_NAME} PUBLIC -flto=auto)
```
in `src/CMakeLists.txt`.

**Now it runs LTO on all CPU cores, not just 1.**
This change reduced compilation time 3 times on 24 cores CPU. Now it's the same as in VS2022.

IDK if it breaks compatibility on other system. **Can someone try to add it and compile on Windows with cmake?**
Maybe it should be enabled by some cmake parameter as option or detect, if it's compiling on Linux.

**// COMPILATION TIME TESTS**

#### I've tested multiple compilation parameters combinations
**Debug**
```
52 sec - OPTIONS_ENABLE_IPO ON, SPEED_UP_BUILD_UNITY ON
55 sec - OPTIONS_ENABLE_IPO ON, SPEED_UP_BUILD_UNITY OFF
47 sec - OPTIONS_ENABLE_IPO ON, SPEED_UP_BUILD_UNITY ON,  -flto=auto
50 sec - OPTIONS_ENABLE_IPO ON, SPEED_UP_BUILD_UNITY OFF, -flto=auto
26 sec - OPTIONS_ENABLE_IPO OFF, SPEED_UP_BUILD_UNITY ON
27 sec - OPTIONS_ENABLE_IPO OFF, SPEED_UP_BUILD_UNITY OFF
26 sec - OPTIONS_ENABLE_IPO OFF, SPEED_UP_BUILD_UNITY ON, -flto=auto
27 sec - OPTIONS_ENABLE_IPO OFF, SPEED_UP_BUILD_UNITY OFF,-flto=auto
```
`-flto=auto` speeds up Debug build with IPO by 5 seconds, but in process manager I can't see more than 1 LTO process running at once :thinking: 

Fastest Debug build is `OPTIONS_ENABLE_IPO OFF, SPEED_UP_BUILD_UNITY ON`.

**Release:**
```
63 sec - OPTIONS_ENABLE_IPO ON, SPEED_UP_BUILD_UNITY ON
66 sec - OPTIONS_ENABLE_IPO ON, SPEED_UP_BUILD_UNITY OFF
20 sec - OPTIONS_ENABLE_IPO ON, SPEED_UP_BUILD_UNITY ON,  -flto=auto
22 sec - OPTIONS_ENABLE_IPO ON, SPEED_UP_BUILD_UNITY OFF, -flto=auto
30 sec - OPTIONS_ENABLE_IPO OFF, SPEED_UP_BUILD_UNITY ON
30 sec - OPTIONS_ENABLE_IPO OFF, SPEED_UP_BUILD_UNITY OFF
29 sec - OPTIONS_ENABLE_IPO OFF, SPEED_UP_BUILD_UNITY ON, -flto=auto
30 sec - OPTIONS_ENABLE_IPO OFF, SPEED_UP_BUILD_UNITY OFF,-flto=auto
```
Fastest Release build is `OPTIONS_ENABLE_IPO ON, SPEED_UP_BUILD_UNITY ON,  -flto=auto`.
`-flto=auto` **reduced time from 63 seconds to 20 seconds.**

Somehow Release with IPO disabled compiles slower than with IPO enabled and `flto=auto`. IDK why, but I've tested it 5 times and compilation times were always the same. IPO ON: 20 sec, IPO OFF: 30 sec.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by conde2** [comment]
Tested with Cmake in visual studio and there is no difference in compilation time, but it works anyways.

![image](https://github.com/mehah/otclient/assets/2137569/4627fa80-cf79-428e-9d02-cd46d98b71dd)

Tested in release mode.

**Comment by mehah** [comment]
I'm cleaning the issue list, if anyone wants to open a new one with the same subject, feel free.
