### ISSUE TITLE
OTClient without rendering

### ISSUE THREAD

**Issue by IntinteDAO** [opentibiabr/otclient#632]
### Priority

Enhancement

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

It's only a proposal if the bot system is built into the game. In a nutshell, the idea is that I have an idea (but it may be useful to someone else) for a certain character system controlled by Bots that would perform certain functions.

Unfortunately, a certain problem may be the graphics card, or more precisely 3D acceleration.

A good option would be to be able to run OTClient with a Bot script without rendering graphics (CLI only).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenDol** [comment]
I have added `FRAMEWORK_GRAPHICS` option but we need to update the `ConsoleApplication` to support it. Also not sure how much work is involved in removing the rendering and not breaking things, that part @mehah would have a better idea.

EDIT: Not sure if this is even something we want to invest time into though honestly.
