### ISSUE TITLE
[BOT] Hotkeys not working when any analyzers options are opened

### ISSUE THREAD

**Issue by rodrigopaixaorj** [opentibiabr/otclient#646]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [X] Other

### What happened?

Video preview -> https://streamable.com/2qsych

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
https://github.com/mehah/otclient/blob/main/mods/game_bot/default_configs/vBot_4.8/vBot/analyzer.lua#L139-L145

Edit in the cache folder and off/on bot or 
delete the cache and edit the mod folder, open client


@Nottinghster 
try
```
local toggleAnalyzer = function(window)
    if window:isVisible() then
        window:close()
        --window:setOn(false)
    else
        window:open()
        --window:setOn(true)

    end
end
```
