### ISSUE TITLE
drawpool 3.0 bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#657]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

The new drawpool has high CPU usage

previous version of drawpool: 
![image](https://github.com/mehah/otclient/assets/16617982/66147db2-1bfe-4078-b82b-0ce786c6d901)

drawpool new version (3.0):
![image](https://github.com/mehah/otclient/assets/16617982/38bf2e10-6e0c-4b5c-b4a3-8497e029cdd4)

There is also a black screen blink when entering the game with viewmode 2 enabled
https://github.com/mehah/otclient/assets/16617982/e0251f8e-877c-4546-af86-862f53c4f681

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wmaestrots** [comment]
Also, sometimes it doesn't remove from Windows Processes after quitting the application (it stays in taskbar processes). I noticed that if you close the client in fullscreen, it stays more often than if you close it in windowed mode.

**Comment by patrykq112** [comment]
> Also, sometimes it doesn't remove from Windows Processes after quitting the application (it stays in taskbar processes). I noticed that if you close the client in fullscreen, it stays more often than if you close it in windowed mode.

That's right, I have this problem too.

FPS are also not as stable as in the previous version

previous version of drawpool:
![image](https://github.com/mehah/otclient/assets/16617982/4d968fe0-d607-496d-8685-7b766fb7135d)

drawpool new version (3.0):
![image](https://github.com/mehah/otclient/assets/16617982/82dc1ce3-3d06-42f3-ae0a-78db8df7139e)
