### ISSUE TITLE
Random tile color in random sqm

### ISSUE THREAD

**Issue by ericcobblepot** [opentibiabr/otclient#667]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

https://github.com/mehah/otclient/assets/125500615/0c3590a4-e579-4e35-bc7e-0d8fea12daf6

I have seen this bug since 3.1

with black, white, light blue, blue, red colors.

I don't know how this error is reproduced, I just play and eventually find the sqm bug.
It only affects the floor I am on, I can see the floors above.

If I logout, it is fixed, until I find the sqm bug again

compiled with today's main repo

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenDol** [comment]
Can you post a screenshot of the in-game display settings you have enabled?

**Comment by ericcobblepot** [comment]
###  **in commit  "Fix local client attachable object effects and some clean up"**






![image](https://github.com/mehah/otclient/assets/125500615/4a63e32e-a0f9-4231-8c38-501025bdde3d)


https://github.com/mehah/otclient/assets/125500615/313fbd09-4740-487d-b325-54baffb1f479

**Comment by patrykq112** [comment]
This has been happening for a long time, I had this problem a few months ago

**Comment by rodrigopaixaorj** [comment]
Guys, could you test with this scenario:

1 - Change Floor View Mode to Normal and walk, check if bug happens
2 - Change Floor View Mode to Locked and walk, check if bug happens

**Comment by ericcobblepot** [comment]
I already tried normal and locked, same error

8.6

**Comment by ericcobblepot** [comment]
![image](https://github.com/mehah/otclient/assets/125500615/dfc0d2aa-2756-4eec-ac1c-956001959656)


another person with the same error

**Comment by kokekanon** [comment]
yes, I know, the server is custom, don't discriminate against me xd.

but I think the error must be in Missile::draw



https://github.com/mehah/otclient/assets/114332266/8fb98e90-2de4-452a-9aa7-50f6e8e5eb43

**Comment by ericcobblepot** [comment]
i "save dump as"
while I was with the bug

last commits : fix: avoid potential crash, when layout is not created yet
https://drive.google.com/file/d/1nx4Lt0rF6D7cbt8mUSHOVhHn70iNmrb-/view?usp=sharing

**Comment by linkzzjr** [comment]
It appears to me to be an error sending data from the server to the otclient. Try reviewing the otserver source screen settings with Otclient

**Comment by ericcobblepot** [comment]
> It appears to me to be an error sending data from the server to the otclient. Try reviewing the otserver source screen settings with Otclient

i use TFS 1.2
"thales duarte" uses 0.4
"kokekanon" uses 1.5
"patrykq11" I don't know what he uses.

it's not the server's problem

**Comment by mehah** [comment]
I can't reproduce, sry.

**Comment by glecko** [comment]
Same issue here, seems to be happening quite often but repro steps are uncertain. And repro rate is low (once per 3-4h of playing)

When it repros, a given tile will trigger a blue/brown screen everytime somebody walks on it. But closing and re-opening the client does (sometimes) fix that particular tiles.

Interestingly, this only seems to repro with Release clients. Might be pure chance, but I've never had the issue repro while on Debug mode.
