### ISSUE TITLE
error compilacao por solution: 'getMapWidget': is not a member of 'UIManager'

### ISSUE THREAD

**Issue by luanluciano93** [opentibiabr/otclient#672]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2039	'getMapWidget': is not a member of 'UIManager'	otclient	....\src\client\tile.cpp	888		

### What OS are you seeing the problem on?

Linux, Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenDol** [comment]
The map is no longer a part of `g_ui` (UIManager) its now in `g_client` (Client). Just update to `g_client.getMapWidget()` this must have been missed in your merge.
