### ISSUE TITLE
Pressing arrow once walks 2 tiles in high speeds

### ISSUE THREAD

**Issue by Zbizu** [opentibiabr/otclient#679]
### Priority

High

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

In new game versions 750 speed cap is lifted. Player character walks too many tiles at once resulting in loss of walking precision.
This is annoying the most when trying to reach depot chest through 1 sqm wide corridor.

This issue does not occur in otcv8, though their walking system is entirely different.

**Related Files:** gameinterface.lua, game.cpp

**Proposed Solution:** walking should be somewhat capped unless dash walking is selected

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by conde2** [comment]
https://github.com/mehah/otclient/blob/72744edc3b9913b920e0fd12e929604f682fda75/modules/game_interface/gameinterface.lua#L125

Change to 200

**Comment by Zbizu** [comment]
works, but shouldn't it be decoupled from gameRootPanel and tied to a slider in settings?

**Comment by conde2** [comment]
This not only affect the press from walking but all the onKeyPress, so I don't think players should mess with it.

What this function do is check every 200ms if the key is still pressed and call the keyPress event.
