### ISSUE TITLE
Is this otclient working ?

### ISSUE THREAD

**Issue by dguprado** [opentibiabr/otclient#686]
### Priority

Missing Content

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What is missing?

I compiled the otclient source, the compilation finished without any errors. However, when I click on the executable i get a error

![foto](https://github.com/mehah/otclient/assets/151960974/34aeb707-9fbc-480c-b1e9-ce4ffb721e87)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 4drik** [comment]
It's old issue:
https://github.com/mehah/otclient/issues/428

**Comment by conde2** [comment]
Not on windows 7, update your SO.

**Comment by rodrigopaixaorj** [comment]
But if you want to continue using Windows 7, and using OTC too, try this:

https://github.com/mehah/otclient/issues/428#issuecomment-1446033414

**Comment by dguprado** [comment]
When I try to run it on Windows 10, on the same PC where I compiled the project, nothing happens, the program doesn't open.
