### ISSUE TITLE
outfit bug + creature informations bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#690]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

- The "Smooth Retro" option is bugged - when it is turned on, outfits are not displayed.
- While running, information about other creatures (nickname, health, etc.) is displayed in the wrong place

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
Confirmed +1

https://github.com/mehah/otclient/assets/7372287/506ac1f7-acce-4e5f-a858-9a263f0b15e5

**Comment by mehah** [comment]
@patrykq112 
no evidence = no bugs!

**Comment by patrykq112** [comment]
> @patrykq112 no evidence = no bugs!

These bugs never appear in the latest release
