### ISSUE TITLE
Using top ground item not working!

### ISSUE THREAD

**Issue by rodrigopaixaorj** [opentibiabr/otclient#694]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I recorded two videos showing an example, check below:

OTClient Redemption (not working)

https://github.com/mehah/otclient/assets/7372287/63ac004e-eb85-4fd7-93da-f0f5d6b49abc

OTClient v8 (working)

https://github.com/mehah/otclient/assets/7372287/b00b8e18-d82a-4cb8-8090-521aea5b1bdb

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gesior** [comment]
`Tile::getTopUseThing()` in Mehah ( https://github.com/mehah/otclient/blob/main/src/client/tile.cpp#L418 ):
```cpp
if (!thing->isGround() && !thing->isGroundBorder() && !thing->isCreature() && !thing->isSplash())
```
in OTCv8 ( https://github.com/OTCv8/otcv8-dev/blob/master/src/client/tile.cpp#L531):
```cpp
if (!thing->isSplash() && !thing->isCreature())
```
as you can see, Mehah skips over `ground border items` (`!thing->isGroundBorder()`) ex. carpet and goes to `return m_things[0];`, which make it send 'use ground item' to server.

IDK if ground border item should be usable or not. Maybe there are some reasons for some protocol versions (with different `Tibia.dat` attributes).

**Comment by rodrigopaixaorj** [comment]
@gesior 

Thanks for your help, you're the greatest
