### ISSUE TITLE
about Fix #67 

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#70]
https://github.com/mehah/otclient/blob/31d4a4f1d5ef8d4eb4007a1db61905ee4ab0b981/src/client/mapview.cpp#L357

This causes (at least for me) that when you go up the stairs a black image appears 

https://i.imgur.com/mLdDAMa.png

**Comment by Klonoa88** [comment]
Strange. Not for me. Have tried in several places and on different floors.

**Comment by poxis** [comment]
That's strange, for example there was no 'flash back' on '/a 50' 

It is possible that on my version because I only add fixes to the version that I already have made for myself.

**Comment by mehah** [comment]
it's really strange, I tested it and it's ok.

try this:
` if(!m_forceTileUpdateCache && (cameraPosition.distance(m_lastCameraPosition) < m_drawDimension.width() && cameraPosition.z == m_lastCameraPosition.z ) && m_timeUpdateVisibleTilesCache.ticksElapsed() <= 10) 
`

**Comment by poxis** [comment]
Tested, work.
