### ISSUE TITLE
Panels/widgets not saving positions

### ISSUE THREAD

**Issue by rodrigopaixaorj** [opentibiabr/otclient#703]
### Priority

Medium

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Videos explains for themselves

https://github.com/mehah/otclient/assets/7372287/7420190a-af2c-44cb-99f7-8e51f555642e

https://github.com/mehah/otclient/assets/7372287/244fc492-a586-450c-8922-d215125b7b61

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
@Zbizu @conde2 @SkullzOTS @mehah @kokekanon @oe

Any news about that or someone able to fix it ??

**Comment by dundermave** [comment]
> @Zbizu @conde2 @SkullzOTS @mehah @kokekanon @oe
> 
> Any news about that or someone able to fix it ??

#621 causes this problem, replace uiminiwindow.lua with any older changes before that commit and problem will be solved as temporary solution.
