### ISSUE TITLE
Updater - missing APP_VERSION in init.lua

### ISSUE THREAD

**Issue by xmish** [opentibiabr/otclient#706]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Updater code is cleary a copy from some other version of otclient where they define `APP_VERSION` '& `APP_NAME` in `init.lua`.
Here there's no such global as `APP_VERSION`

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xmish** [comment]
https://github.com/mehah/otclient/blob/6b112c2b9b10ce1156632d8ada371680c95eb336/modules/updater/updater.lua#L219-L230

**Comment by kokekanon** [comment]
https://github.com/mehah/otclient/issues/578

**Comment by mehah** [comment]
APP_VERSION = g_app.getVersion()
APP_NAME = g_app.getName()

![image](https://github.com/mehah/otclient/assets/2267386/77672532-4b48-4389-86ac-c4b3e46af673)
