### ISSUE TITLE
Request: screenshot 

### ISSUE THREAD

**Issue by ericcobblepot** [opentibiabr/otclient#707]
### Priority

Missing Content

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

Would it be possible to add the screenshot function?
It would be interesting to make it compatible with this.

TFS
https://github.com/otland/forgottenserver/pull/4459

canary
https://github.com/opentibiabr/canary/pull/2116/files

Or a simple module that automatically takes a screenshot when you level up or when you die, for example.
https://github.com/EgzoT/-OTClient-Mod-game_autoscreenshot

![image](https://github.com/mehah/otclient/assets/125500615/28a5882b-9453-4528-971d-f61066565f28)

Preferably in the same folder as the client. Not in AppData. (For users with basic computer skills.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ericcobblepot** [comment]
why was it closed? @Nottinghster  @mehah  @majestyotbr

**Comment by ericcobblepot** [comment]
I waited 5 days for a response from an admin regarding the reasons why the issue was closed @Nottinghster . If by the sixth day I don't receive a response, I will assume it was an error and will create a new issue.

The code is ready; it's just in the wrong Thread , or perhaps it's something related to the drawpool 3. Personally, I've tried the code from v8 and Edubart in redemption. The code generates an image with screen resolution, but the created image is empty; it has no content inside and weighs 8kb.

Here are three sources of information with the code already implemented; it just needs adaptation:

### edubart: 


`https://github.com/otland/otclient/pull/17`


### v8:

`https://github.com/OTCv8/otcv8-dev/blob/master/src/framework/graphics/framebuffer.cpp#L205`

`https://github.com/OTCv8/otcv8-dev/blob/master/src//framework/core/graphicalapplication.cpp#L417`

clearly applies the "**Missing Content**".



that feature is in the tfs main by omarcopires and in canary there is a pr by @luanluciano93

attach the links to the respective pr in main post


is in otcv8 and edubart, only redeptiom is missing.

**Comment by kokekanon** [comment]
I tried xd I'm not good at cpp

https://github.com/mehah/otclient/pull/812
