### ISSUE TITLE
Possible bug (TFS: isMovementBlocked)

### ISSUE THREAD

**Issue by poxis** [opentibiabr/otclient#71]
the problem: If we set that the player cannot move (server side) when we click somewhere on the map, the character tries to go to click place (every ~1000ms) 
https://github.com/mehah/otclient/blob/94c76e873c8791493ca81805ceb2f3ecabae0d57/src/client/localplayer.cpp#L149

- on OTClient there is no problem, the character tries to move once and stop.

TFS:
https://github.com/otland/forgottenserver/blob/201c2e4e1f3274212fd068be36e4acd974c0348e/src/creature.cpp#L258

BTW:
And the question of whether someone has such a problem, if we have a monster selected (to attack) and we click somewhere on the map and characters go to click on map, when the server sends 'target lost', client stops walking (on tibia client I did not notice this [micro-lag but character goes on])

**Comment by mehah** [comment]
well, I didn’t understand very well, since I don’t play Tibia and I don’t know how it works, do you have any suggestions for fixing this problem?

**Comment by Znote** [comment]
> well, I didn’t understand very well, since I don’t play Tibia and I don’t know how it works, do you have any suggestions for fixing this problem?

If server sends cancelwalk, the client should not try to continue walking its calculated path, even if the path is valid.
