### ISSUE TITLE
 http login not working

### ISSUE THREAD

**Issue by luanluciano93** [opentibiabr/otclient#717]
### Priority

Low

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

http login not working
tibi version 13.21

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
![image](https://github.com/mehah/otclient/assets/32709570/f47a4c7e-012f-4fea-8cb8-cbb05030cb07)
![image](https://github.com/mehah/otclient/assets/32709570/2f910aff-1897-4ecf-9b53-b723472d9969)
![image](https://github.com/mehah/otclient/assets/32709570/ded3eb3b-c8b5-4996-afe7-d312a6d754b6)
![image](https://github.com/mehah/otclient/assets/32709570/3bba8348-ce55-45d4-97d4-d92e1868463a)

**Comment by majestyotbr** [comment]
![image](https://github.com/mehah/otclient/assets/32709570/a6076cec-2085-43d2-b214-82b7ae4c7c0e)
![image](https://github.com/mehah/otclient/assets/32709570/ffa15b0e-3a05-4ce0-9997-d30939a611de)
![image](https://github.com/mehah/otclient/assets/32709570/d53c215e-29de-46c3-afad-f98b2b271a5b)
![image](https://github.com/mehah/otclient/assets/32709570/3ea48788-f20d-4b24-b746-2d0d3a9d9051)

**Comment by AzizsFroes** [comment]
Aqui também não esta indo.
![image](https://github.com/mehah/otclient/assets/162846956/6cc629b4-dbd5-4ccf-9a81-dc9da91b51f3)
![image](https://github.com/mehah/otclient/assets/162846956/0f1736c5-a114-4c6e-a9e8-a944d1978a3e)
![image](https://github.com/mehah/otclient/assets/162846956/5df35459-f891-4cd3-baea-c58e917e5d16)

**Comment by luanluciano93** [comment]
@Costallat

**Comment by luanluciano93** [comment]
I tested it again like what Majesty said in the discord group, and it didn't work, the same "Success (no error)" screen

**Comment by AzizsFroes** [comment]
Fiz confome mostrado no grupo do discord tbm e não deu certo.

**Comment by rodrigopaixaorj** [comment]
Did you test this? #723

**Comment by luanluciano93** [comment]
> Did you test this? #723

it does not solve

**Comment by luanluciano93** [comment]
the problem was in the site's login.php, I had to remove HTTP_USER_AGENT
