### ISSUE TITLE
Movement/Animation Bug

### ISSUE THREAD

**Issue by csantbr** [opentibiabr/otclient#72]
Erro de movimentação em criaturas, pode ser reproduzido com criaturas com animações de corrida.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/61211407/112779056-466d8a00-901c-11eb-810f-7e750f2eb8d4.gif)

**Comment by poxis** [comment]
try change:
https://github.com/mehah/otclient/blob/94c76e873c8791493ca81805ceb2f3ecabae0d57/src/client/creature.cpp#L507

to:
`const int footAnimPhases = getTotalAnimationPhase()-1;`

**Comment by csantbr** [comment]
> try change:
> https://github.com/mehah/otclient/blob/94c76e873c8791493ca81805ceb2f3ecabae0d57/src/client/creature.cpp#L507
> 
> to:
> `const int footAnimPhases = getTotalAnimationPhase()-1;`

if make this change cause bug in other outfits

**Comment by mehah** [comment]
Não é a primeira vez que reclamam desse bug, porem isso acontece apenas nesses dat/spr de pokemon, já testei no tibia 7.72, 8.6 e 10.98 e não ocorre esses problemas, e como não tenho acesso a esses arquivos, logo...

**Comment by csantbr** [comment]
> Não é a primeira vez que reclamam desse bug, porem isso acontece apenas nesses dat/spr de pokemon, já testei no tibia 7.72, 8.6 e 10.98 e não ocorre esses problemas, e como não tenho acesso a esses arquivos, logo...

Essa SPR é publica é do The Ruby Server: https://www.dropbox.com/sh/aba8pwepy364yg8/AAAteTPnKULj0j61_M9Xo9Rfa?dl=0
https://github.com/OLDtherubyproject/rubyclient

**Comment by mehah** [comment]
@csantbr qual é a versão do tibia, precisa de um servidor customizado, me passe todas as informações necessárias para q eu possa montar o ambiente.

**Comment by csantbr** [comment]
> @csantbr qual é a versão do tibia, precisa de um servidor customizado, me passe todas as informações necessárias para q eu possa montar o ambiente.

TFS 1.3 / Protocolo 10.98

O Servidor é esse: https://github.com/OLDtherubyproject/rubyserver
O Cliente é esse: https://github.com/OLDtherubyproject/rubyclient
A SPR é essa: https://www.dropbox.com/sh/aba8pwepy364yg8/AAAteTPnKULj0j61_M9Xo9Rfa?dl=0
o Repositório geral é esse: https://github.com/OLDtherubyproject

**Comment by mehah** [comment]
você fez merge do ot1.0 com o do ruby, pois vi que tem coisas mexida na src do cliente do ruby, isso vai dar trabalho. >.<

**Comment by csantbr** [comment]
Eu acredito que o problema aconteça mesmo sem as modificações do cliente do ruby, se precisar de ajuda você tem meu contato no discord.

**Comment by csantbr** [comment]
Problema solucionado, era conflito com uma modificação do cliente do ryby, o mesmo problema não ocorre com esse cliente sem modificações. Obrigado @mehah continue fazendo realizando esse belo trabalho.
