### ISSUE TITLE
13.10 Support.

### ISSUE THREAD

**Issue by Codinablack** [opentibiabr/otclient#721]
### Priority

Missing Content

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

Currently the main branch of TFS is using client 13.10. It has been for quite awhile now, but there is no client out there that actually supports this version. 

I request the changes made to add client version 13.10 as a supported client for this OTC, please.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I'm cleaning the issue list, if anyone wants to open a new one with the same subject, feel free.

**Comment by fernandorrmartins** [comment]
@Codinablack, want to open this again?

**Comment by mehah** [comment]
I'll just warn you that I (Mehah) will not implement this, I don't support Tibia, I'm just here to improve the engine, but the community is free to contribute.

**Comment by Codinablack** [comment]
> @Codinablack, want to open this again?

I mean I would, but there isn't any point if its just going to sit here and do nothing. I am not that knowledgeable on the changes between protocols and what packets should be U32 and which should be U16 and in which order and such... 

Nobody cares about TFS anymore it is really starting to seem. I guess since Canary already has support from OTC that is all that there will be from now on.

I have also raised this issue in otacedemy, and with the TFS devs as well... pretty much got crickets back... other than a few people telling me its a problem with "bytes", as if that wasn't already apparent...
