### ISSUE TITLE
text bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#724]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

In the latest source there is a bug with the text when fps are below 60. The text jumps around strangely while walking.

https://github.com/mehah/otclient/assets/16617982/13d1e554-a482-4125-93cc-1a6160cec86b

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
@patrykq112 

For this to be corrected, I would be forced to synchronize the processing of the texts with the map, this will take away the advantage of being multithreaded, I believe it is not worth it, no one will use FPS10, however I can give the option to disable multithreading for the texts , then it will be up to each developer to choose.

**Comment by patrykq112** [comment]
with the extended view this happens at 60 fps

**Comment by patrykq112** [comment]
with the extended view it happens at 60 fps

@mehah
