### ISSUE TITLE
bug g_platform.openDir does not open the correct folder

### ISSUE THREAD

**Issue by kojimhojo** [opentibiabr/otclient#728]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

how to reproduce?
console
g_platform.openDir("%appdata%/otcr")

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
This is not a bug, with a few minutes of searching on Google, I discovered that the command is this:
g_platform.openDir("shell:AppData\\\otcr")

https://www.vbforums.com/showthread.php?529776-RESOLVED-Open-a-folder-in-AppData&s=ac9c924ed1a34817bc5f9ad522d70897&p=3272945&viewfull=1#post3272945
