### ISSUE TITLE
Option to change the client layout

### ISSUE THREAD

**Issue by Riverlance** [opentibiabr/otclient#729]
### Priority

Enhancement

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What is missing?

I remember that an old version of OTClient (I couldn't find where, unfortunately) had a ComboBox on top menu to change the layout style of the client.
I think they removed because almost nobody was using it.

On that time, I remember that the files inside `/data/styles/` were organized in subfolders.
For example:

1. `/data/styles/default/10-buttons.otui` (and all other style files inside `default` folder);
2. `/data/styles/mehah/10-buttons.otui` (and all other customized style files inside `mehah` folder);
3. And so on, if there are more than 2 styles.

I have no idea how it was implemented, but I guess maybe was something using `UIWidget:setStyle(styleName)`?
Probably it was fully implemented in Lua.

Would be great if the layout style could be updated without destroying the widgets. I think this is very important.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
There's no intention to create a layout system, but, we're working on a new layout to OTClient Redemption, check it out:
https://github.com/Nottinghster/otclient/tree/new-layout

**Comment by ericcobblepot** [comment]
The idea is quite good,

the layout would be optional between 

- StoneDrake, https://otland.net/threads/otclient-mehah-1-4-1-stonedrake-ui.287618/
- your new layout, 
- the one currently in use. https://otland.net/threads/otc-tibia-theme-v1-2.230988/
- Mobile
