### ISSUE TITLE
Vip list group

### ISSUE THREAD

**Issue by Riverlance** [opentibiabr/otclient#730]
### Priority

Missing Content

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

![image](https://github.com/mehah/otclient/assets/2280432/1421e5e9-1c90-4845-be68-208a40a5388c)

The feature `Otc::GameVipGroups` is not implemented, as shown below:

![image](https://github.com/mehah/otclient/assets/2280432/54712f91-c0e3-4e08-8494-9ad8fc0bd33f)
![image](https://github.com/mehah/otclient/assets/2280432/9274ac2c-4d09-4368-aac5-3b0ccaf9b731)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luanluciano93** [comment]
Can you explain better? the feature is automatically activated in versions 12+
https://github.com/mehah/otclient/blob/11cc1536ebd9b39b4bb77cfb7c544e5d28f945b3/modules/game_features/features.lua#L184

**Comment by Riverlance** [comment]
> Can you explain better? the feature is automatically activated in versions 12+
> 
> https://github.com/mehah/otclient/blob/11cc1536ebd9b39b4bb77cfb7c544e5d28f945b3/modules/game_features/features.lua#L184

Sure.
It is activated indeed, although it is not implemented.

When you write lines like:
```c++
msg->getU8(); // Group ID
msg->getString(); // Group name
msg->getU8(); // Can edit group? (bool)
```
You are receiving data from server about vip groups, but doing nothing with them.
You need to assign them to variables, then use into a function that should pass through a Lua callback which will implement the visual of groups on Vip List mini window.
See `id`, `name`, `status`, `desc`, `iconId`, `notifyLogin` used on `g_game.processVipAdd` to see how it should be done.

---

1. The correct would be something like `myVariable = msg->getU8();`, not just `msg->getU8();` without signing it to a variable nor using it.
2. And then using `myVariable` in `g_game.processVipAdd` (in case of `ProtocolGame::parseVipAdd`) or in `g_game.processVipStateChange` (in case of `ProtocolGame::parseVipLogout`).
3. Finally, it should be implemented on Lua in `g_game.onAddVip` (in case of `g_game.processVipAdd`) or in `g_game.onVipStateChange` (in case of `g_game.processVipStateChange`).
4. Once you have the data about groups on Vip List mini window Lua module, you can use it to implement the visual in this mini window.

**Comment by kokekanon** [comment]
I use 8.6 I will never use that function. but Well I tried xd .
only  "addvip"  and "refreshgruop" function lua are missing.
I'm not good with MiniWindowContents

I wont continue
if anyone wants to see the changes or continue: 
see this
`https://github.com/kokekanon/otclient.readme/commit/582d7909c9ec7aafbdfeca243664a997172b06d7`
https://github.com/kokekanon/otclient.readme/commit/582d7909c9ec7aafbdfeca243664a997172b06d7

![image](https://github.com/user-attachments/assets/8c518369-4b28-4a1a-aa6d-5b05ea0f5a56)
modules.game_viplist.toggleViewMode()

![image](https://github.com/user-attachments/assets/e038fe39-b3ff-4049-aa21-111fe6eec1b1)

![image](https://github.com/user-attachments/assets/66b56a62-2ad1-41d6-8570-6e112ef72900)

![image](https://github.com/user-attachments/assets/3ae5cbff-c7aa-45f2-b0ce-ab955aaa4386)

![image](https://github.com/user-attachments/assets/05a010e7-910f-4dbd-80e8-0c3fcecd5d90)


```
groups.groupsName = { 
    [1] = { 
        [1] = 1, -- ID group
        [2] = "Enemies",  -- group name
        [3] = false --idk
    },
    [2] = { 
        [1] = 2,
        [2] = "Friends",
        [3] = false
    },
    [3] = { 
        [1] = 3,
        [2] = "Trading Partner",
        [3] = false
    },
    [4] = { 
        [1] = 4,
        [2] = "weas",
        [3] = true
    },
    [5] = { 
        [1] = 5,
        [2] = "nvbnvbn",
        [3] = true
    },
    [6] = { 
        [1] = 6,
        [2] = "1",
        [3] = true
    },
    [7] = { 
        [1] = 7,
        [2] = "pocoyo",
        [3] = true
    }
}

function onAddVip(id, name, state, description, iconId, notify, groupID)
    print('onAddVip', id, name, groupID)
    onAddVip    6    GOD    {1,2}
    
    onAddVip    4    Paladin Sample {2}
end
```
