### ISSUE TITLE
This repository has been disabled. 

### ISSUE THREAD

**Issue by Odisey25** [opentibiabr/otclient#735]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

HI Everyone ! 

1>C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): error MSB3073: The command ""C:\vcpkg\vcpkg.exe" install --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "C:\vcpkg\\" "--x-manifest-root=C:\otclient-main\\" "--x-install-root=C:\otclient-main\vcpkg_installed\x64-windows-static\\" " exited with code 1.
1>Compiling project "otclient.vcxproj" finished -- ERROR.

checking the first repository gives error and cancels it 
![imagen](https://github.com/mehah/otclient/assets/65802862/cb5d15e6-8680-4175-9c07-434f75011378)

https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
![imagen](https://github.com/mehah/otclient/assets/65802862/9c69d42d-2bbb-44db-aa49-8f8d9f6270b4)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jorgelx** [comment]
For more info:

https://arstechnica.com/security/2024/04/what-we-know-about-the-xz-utils-backdoor-that-almost-infected-the-world/
