### ISSUE TITLE
ProtocolGame parse message exception 

### ISSUE THREAD

**Issue by Odisey25** [opentibiabr/otclient#739]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

**happens at any time.**

ProtocolGame parse message exception (9138 bytes, 1529 unread, last opcode is 0x02 (2), prev opcode is 0xe9 (233),  unhandled opcode 2
ProtocolGame parse message exception (9138 bytes, 1529 unread, last opcode is 0x02 (2), prev opcode is 0xe9 (233),  unhandled opcode 2
ProtocolGame parse message exception (9138 bytes, 1529 unread, last opcode is 0x02 (2), prev opcode is 0xe9 (233), unhandled opcode 2
ProtocolGame parse message exception (9183 bytes, 1529 unread, last opcode is 0x02 (2), prev opcode is 0xe9 (233),  unhandled opcode 2
ProtocolGame parse message exception (6667 bytes, 1355 unread, last opcode is 0x03 (3), prev opcode is 0xe9 (233),  unhandled opcode 3
ProtocolGame parse message exception (7640 bytes, 1684 unread, last opcode is 0x02 (2), prev opcode is 0xe9 (233),  unhandled opcode 2
ProtocolGame parse message exception (362 bytes, 246 unread, last opcode is 0xb4 (180), prev opcode is 0xa0 (160),  InputMessage eof reached
ProtocolGame parse message exception (361 bytes, 245 unread, last opcode is 0xb4 (180), prev opcode is 0xa0 (160),  InputMessage eof reached
ProtocolGame parse message exception (6686 bytes, 1554 unread, last opcode is 0x02 (2), prev opcode is 0xe9 (233),  unhandled opcode 2
ProtocolGame parse message exception (6859 bytes, 1554 unread, last opcode is 0x02 (2), prev opcode is 0xe9 (233), unhandled opcode 2
ProtocolGame parse message exception (6507 bytes, 1657 unread, last opcode is 0x02 (2), prev opcode is 0xe9 (233), unhandled opcode 2
ProtocolGame parse message exception (550 bytes, 435 unread, last opcode is 0xb4 (180), prev opcode is 0xa0 (160), InputMessage eof reached
ProtocolGame parse message exception (586 bytes, 471 unread, last opcode is 0xb4 (180), prev opcode is 0xa0 (160), InputMessage eof reached
ProtocolGame parse message exception (366 bytes, 251 unread, last opcode is 0xb4 (180), prev opcode is 0xa0 (160), InputMessage eof reached
ProtocolGame parse message exception (364 bytes, 249 unread, last opcode is 0xb4 (180), prev opcode is 0xa0 (160), InputMessage eof reached
ProtocolGame parse message exception (548 bytes, 433 unread, last opcode is 0xb4 (180), prev opcode is 0xa0 (160),  InputMessage eof reached
ProtocolGame parse message exception (541 bytes, 427 unread, last opcode is 0xb4 (180), prev opcode is 0xa0 (160),  InputMessage eof reached

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luanluciano93** [comment]
what version of the client and what version of otserv are you using?

- for 0xe9 (233) do a test with: https://github.com/Nottinghster/otclient/pull/27
- for 0xb4 (180) do a test with: https://github.com/opentibiabr/canary/pull/2510
