### ISSUE TITLE
Light/Shadow Update Problem

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#74]
When items drawns in game with an (example) action script, light/shadows are not update correctly. You have to go one step with the character for it to be updated, Watch video below. 

Also when an item disappears, that tile flashes in black. Watch the Video below when the bridge disappears, Time: 0:10

**Video**
[HERE](https://dl.dropboxusercontent.com/s/4vk4w4fp3zyhfmq/Ef5M33fJsj.mp4)

### Environment
10.98 Latest version of TFS and your Latest OTC sources (cache-for-all)

@mehah

**Comment by mehah** [comment]
change this line:
https://github.com/mehah/otclient/blob/2f458d57afe6468fc6a9d630b9997e73546ebdf5/src/client/thing.cpp#L51
to
if(isLocalPlayer() || hasLight() || isOpaque()) frameFlag |= Otc::FUpdateLight;

and tell me if it worked

**Comment by Klonoa88** [comment]
Okay a new update on this. 

Changed what you said in line 51 in thing.cpp **(Thing::schedulePainting)** to this:
`if(isLocalPlayer() || hasLight() || isOpaque()) frameFlag |= Otc::FUpdateLight;`

Then I changed line 247 in map.cpp **(Map::removeThing)** to this:
`if(thing->hasLight() || thing->isOpaque()) frameFlag |= Otc::FUpdateLight;`

And now it works :) The only thing left now is that tiles flash black when tiles disappear. There seems to be some delay in the draw function. Watch video below.
[Video](https://dl.dropboxusercontent.com/s/7ggvm66horblzib/Pdl9hj0iI5.mp4)

**Comment by mehah** [comment]
in Map::removeThing, change this:
```
        if(thing->hasLight()) frameFlag |= Otc::FUpdateLight;
        if(thing->isCreature()) frameFlag |= Otc::FUpdateCreatureInformation;
        schedulePainting(thing->getPosition(), static_cast<Otc::FrameUpdate>(frameFlag));
```
to
```
        uint16_t delay = FrameBuffer::MIN_TIME_UPDATE;
        if(thing->isOpaque()) delay = FrameBuffer::FORCE_UPDATE;
        if(thing->hasLight() || thing->isOpaque()) frameFlag |= Otc::FUpdateLight;
        if(thing->isCreature()) frameFlag |= Otc::FUpdateCreatureInformation;
        schedulePainting(thing->getPosition(), static_cast<Otc::FrameUpdate>(frameFlag), delay);
```

**Comment by Klonoa88** [comment]
I have tried this changes now but bridgetiles are still flashing black when they disappears.

I also tried to change:

`uint16_t delay = FrameBuffer::MIN_TIME_UPDATE;`
**to**
`uint16_t delay = 10;`

but it was the same result.

[Video](https://dl.dropboxusercontent.com/s/lfm3j5kh1yao3q4/N1ojyDkg3s.mp4)

**Comment by mehah** [comment]
this is default value:
`uint16_t delay = FrameBuffer::MIN_TIME_UPDATE;`

what matters is this line
`if(thing->isOpaque()) delay = FrameBuffer::FORCE_UPDATE;`

Did you put it exactly like I said?

not forgetting that you must pass the delay variable in the schedulePainting method, exactly as I showed you.

if it still didn’t work, I’ll have to simulate it here in my environment so I can fix it.

**Comment by Klonoa88** [comment]
Yes, I put it exactly where you said :)

https://i.imgur.com/NQBodws.png

More speed in the action script:
[Video](https://dl.dropboxusercontent.com/s/ya9wponwj5ewsig/NKD2LQ1YFC.mp4)

**Comment by mehah** [comment]
what is the id of this item, is it ground?
