### ISSUE TITLE
support .CWM  "HDMod - cwm enchanced" by mrianura

### ISSUE THREAD

**Issue by kojimhojo** [opentibiabr/otclient#741]
### Priority

Enhancement

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

this looks interesting

https://otland.net/threads/how-to-use-upscaled-sprites-64x64-or-bigger-in-otcv8.288544/
Example of 64x64 sprites in-game
![image](https://github.com/mehah/otclient/assets/164669689/42dc763f-8068-42f7-83ee-b158cc83e28e)
Example of 96x96 sprites in-game
![image](https://github.com/mehah/otclient/assets/164669689/0bf5037a-c08b-4a4b-9742-1a99f77b30d9)
Example of 128x128 sprites in-game
![image](https://github.com/mehah/otclient/assets/164669689/78e1f787-d058-4ef3-a38b-4ad2e1d413d7)

by: mrianura 
https://github.com/OTCv8/otcv8-dev/blob/master/src/framework/util/pngunpacker.cpp
https://github.com/OTCv8/otcv8-dev/blob/master/src/framework/util/pngunpacker.h

https://github.com/OTCv8/otcv8-dev/blob/master/src/client/spritemanager.cpp#L351
https://github.com/OTCv8/otcv8-dev/blob/master/src/client/spritemanager.cpp#L52

I have Node, I'm willing to send the CWM to test, tell me which version to send.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrianura** [comment]
xD

**Comment by nekiro** [comment]
You can provide the CWM file or simply test this pull request #922 .

**Comment by mrianura** [comment]
860: https://drive.google.com/file/d/1nNJu0JrDLAZmAXCFi6aMm2pS04o0Q4K9/view?usp=sharing
