### ISSUE TITLE
Normal players cant change outfit.

### ISSUE THREAD

**Issue by br-it0** [opentibiabr/otclient#747]
### Priority

Medium

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Window dont open, canary last release.

Only with normal players, with god works ok!

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by br-it0** [comment]
ERROR: ProtocolGame parse message exception (4494 bytes, 4393 unread, last opcode is 0xc8 (200), prev opcode is 0xffffffff (-1)): InputMessage eof reached
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1321)

Console Error.

**Comment by Odisey25** [comment]
> ERROR: ProtocolGame parse message exception (4494 bytes, 4393 unread, last opcode is 0xc8 (200), prev opcode is 0xffffffff (-1)): InputMessage eof reached Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1321)
> 
> Console Error.

protcol 1321 ? 
if we are at 13.32

**Comment by luanluciano93** [comment]
@br-it0 Can you test now with the latest updates?
