### ISSUE TITLE
The creature attacking red square does not vanish when changing floor, and sometimes doesn't appear while changing target 

### ISSUE THREAD

**Issue by fdc23** [opentibiabr/otclient#75]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Open/close battle channel while attacking a target
2. Do a floor change while attacking
3. Simply changing target

### Expected behaviour
1. The red square vanish when changing floor.
2. Red square always appear when changing target
3. Render the viewport normally if battle channel is full of monsters.

### Actual behaviour
All the behaviour has been described here
https://otland.net/threads/red-square-vanish-on-change-target.275806/

Also, **here is the recorded evidence** of the tests
https://www.youtube.com/watch?v=kKiyPIuiaaI
https://www.youtube.com/watch?v=bB7fo9bayHs

There's also an **unexpected render behaviour** while having battle channel full of monsters 
_(this doesn't drop FPS like happened in edubart battle module)_
https://www.youtube.com/watch?v=X1UoxSg1fmA

### Environment
Client version 8.60 
OTClient (current mehah's repository) (13/4/2021)

PS. I know you don't support older protocols, but i'm up-to-date with tfs main branch commits (applied them on my sources).

**Comment by fdc23** [comment]
More information about the error, now i'm getting this on terminal
![battle_Error](https://user-images.githubusercontent.com/26353603/114893097-5c7c9800-9ddb-11eb-8054-58cca5c8b780.png)
![error](https://user-images.githubusercontent.com/26353603/114893100-5dadc500-9ddb-11eb-908f-eb09ecae24be.png)

**Comment by mehah** [comment]
I tested it and everything is working correctly, make sure you are using all the original modules in the repository.

evidence:
https://streamable.com/hcoucu

**Comment by mehah** [comment]
update these two folders with the latest revision and see if it fixes your problem:

https://github.com/mehah/otclient/tree/cache-for-all/modules/game_battle
https://github.com/mehah/otclient/tree/cache-for-all/modules/gamelib/ui

And update your src.
