### ISSUE TITLE
Linux Compile Issue

### ISSUE THREAD

**Issue by aboogesnickle** [opentibiabr/otclient#753]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [X] Other

### What happened?

Was following the Compiling on Arch Linux guide. Current issue is 
```
-- Enabled: ipo
-- Found Protobuf Compiler: /usr/bin/protoc
FATAL_ERROR,Failed to generate protobuf files
-- Bot protection: ON
-- Use precompiled header: ON
-- Enabled: Build unity for speed up compilation
-- Disabled: asan
-- Disabled: DEBUG LOG
-- Build type: 
-- Build commit: 
-- Build revision: 
CMake Deprecation Warning at /usr/lib/cmake/OpenAL/OpenALConfig.cmake:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  src/CMakeLists.txt:217 (find_package)


CMake Error at src/CMakeLists.txt:219 (find_package):
  Could not find a package configuration file provided by "Vorbis" with any
  of the following names:

    VorbisConfig.cmake
    vorbis-config.cmake

  Add the installation prefix of "Vorbis" to CMAKE_PREFIX_PATH or set
  "Vorbis_DIR" to a directory containing one of the above files.  If "Vorbis"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```
when trying to run cmake . -B build

I installed all the required dependency packages but ran into a couple missing dependencies.
Ran

- pacman -S asio
- yay -S stduuid
- yay -S cpp-httplib

to fix the previous errors where it couldn't find those packages, but libvorbis is in the guide already, and tried reinstalling it as well. I know just enough about Arch Linux to get in trouble, and I don't know why this isn't working.

Also the src/framework/protobuf/proto/ doesn't seem to exist in the current repo, but I found src/protobuf/ with a generate.sh in it, and just ran that. Not sure if that is why it is also getting the Fatal_ERROR, Failed to generate protobuf files.

Please let me know if I need to provide more information.

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aboogesnickle** [comment]
I changed the title to just Linux. This appears to also effect Ubuntu 24.04. The vorbis now has headers (aka. includes) in the /usr/include/vorbis directory on both Arch Linux and Ubuntu 24.04 and at least on Arch the library is in /usr/lib. I think Ubuntu 24.04 has it in a subdirectory of /usr/lib. In /src/CMakeLists.txt on line 219 is where this fails because it is looking for config files that do not exist anymore 	

`find_package(Vorbis CONFIG REQUIRED)`

I removed the CONFIG parameter and it makes it past that part, but it fails further down on line 545 when it is trying to link the libraries. I was able to get it to link the libraries by statically putting in the path, and did get it to complete the cmake . -B build command. It however does fail when attempting to run make -C build, but that is as far as I have got for now.

**Comment by tornadia** [comment]
@aboogesnickle I created a PR to address the issue of conditional sound in compile time. Can you please take a look, and propose suggestions to using the different directory in arch linux for cmake files? Also thanks for the pointer with protobuf, I was unaware that a script needed to be run in order to generate and compile with a newer version.
