### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#755]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

client crashes on startup after commit "perf: more fps and less memory usage"

![image](https://github.com/mehah/otclient/assets/16617982/690b2fba-8454-4ac2-802a-231122da54fc)

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
Did you clean the project and compile it, or just recompile it?

**Comment by patrykq112** [comment]
I cleaned and compiled

**Comment by mehah** [comment]
try this:

in otclient\src\framework\core\graphicalapplication.cpp
![image](https://github.com/mehah/otclient/assets/2267386/36124712-dc93-4288-bf41-9da6317b4375)

replace for
```c++
    // THREAD - FOREGROUND UI
    threads.emplace_back(g_asyncDispatcher.submit_task([&] {
        std::unique_lock lock(uiPool->getMutexPreDraw());
        uiCond.wait(lock, [this]() {
            if (m_drawEvents->canDraw(DrawPoolType::MAP))
                g_ui.render(DrawPoolType::FOREGROUND);
            return m_stopping;
        });
    }));

    // THREAD - FOREGROUND MAP
    threads.emplace_back(g_asyncDispatcher.submit_task([&] {
        std::unique_lock lock(fgMapPool->getMutexPreDraw());
        fgMapCond.wait(lock, [this]() -> bool {
            if (m_drawEvents->canDraw(DrawPoolType::MAP))
                m_drawEvents->drawForgroundMap();
            return m_stopping;
        });
    }));
    ```

**Comment by patrykq112** [comment]
this replacement helped, it no longer crashes at the start

**Comment by patrykq112** [comment]
@mehah I found one more bug after this update. When opening a backpack, layout:getNumLines() always returns 0 and the backpacks open at the wrong height.

**Comment by mehah** [comment]
@patrykq112 

try this:
add internalUpdate() at the end of the UIGridLayout::applyStyle() method

like this:

![image](https://github.com/mehah/otclient/assets/2267386/cf77acd1-cef7-412a-8508-d624b802577d)

**Comment by patrykq112** [comment]
it didn't help, still the same

**Comment by mehah** [comment]
Could you give me an example, where are you executing this method so I can test it?

because everything seems normal to me.

![image](https://github.com/mehah/otclient/assets/2267386/dd40ff19-3baf-4345-9051-a72e0589a69f)

**Comment by mehah** [comment]
@patrykq112 
hmm, try this:
add
```c++
    if (m_parentWidget)
        m_parentWidget->onLayoutUpdate();
```
![image](https://github.com/mehah/otclient/assets/2267386/56d76a77-a4e1-4394-9a98-c2b3dcdbe75e)

**Comment by patrykq112** [comment]
> Could you give me an example, where are you executing this method so I can test it?
> 
> because everything seems normal to me.
> 
> ![image](https://private-user-images.githubusercontent.com/2267386/330214414-dd40ff19-3baf-4345-9051-a72e0589a69f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDMzMzAsIm5iZiI6MTcxNTY0MzAzMCwicGF0aCI6Ii8yMjY3Mzg2LzMzMDIxNDQxNC1kZDQwZmYxOS0zYmFmLTQzNDUtOTA1MS1hNzJlMDU4OWE2OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMjMzMDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmMwMDNkMzJjZTkxZDU1ZDhjMjhmZWI1MWU3MjFlOTBlMzZlMjcyZDhmM2M3M2IwZGUwNWI3MTBkZDJlZWU4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nRcpfIjEM3ew-3pOhXScf3lzrjknMDBsfWyS6LK3u7Q)

game_containers/containers.lua

containerWindow:setContentMaximumHeight(cellSize.height * l**ayout:getNumLines()**)

**Comment by patrykq112** [comment]
@mehah 


https://github.com/mehah/otclient/assets/16617982/876ca183-33a3-42ac-afa0-02958f417547

**Comment by patrykq112** [comment]
I found one more bug, the character names shake a lot when walking (it's most noticeable when moving at high speed)

**Comment by mehah** [comment]
> @mehah
> 
>  2024-05-14.13-12-55.mp4

fixed  https://github.com/mehah/otclient/commit/6da664517b4e0ea6a30fa18e919831267da5bff9


> I found one more bug, the character names shake a lot when walking (it's most noticeable when moving at high speed)

I will look into this problem.

**Comment by mehah** [comment]
> I found one more bug, the character names shake a lot when walking (it's most noticeable when moving at high speed)

fixed https://github.com/mehah/otclient/commit/84dca80f61f07bfca1e5014d3a1e0401e671ef0f
