### ISSUE TITLE
text bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#756]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

the character name shaking bug still occours. It is most visible when the fps limit is turned on (e.g. 60)

tested after last commit "fix: foreground map render"

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrykq112** [comment]
https://github.com/mehah/otclient/assets/16617982/d9e1f12a-493e-4765-9950-b4daa632a83e

**Comment by patrykq112** [comment]
@mehah with an extended view, when there are more tiles on the screen, the character name shakes are much larger

https://github.com/mehah/otclient/assets/16617982/4e2729dd-f715-4744-9088-51ea2f0cc40c

**Comment by mehah** [comment]
are you compiling in debug or release?

**Comment by patrykq112** [comment]
> are you compiling in debug or release?

release

**Comment by patrykq112** [comment]
@mehah I found one more bug. If the widget has "text-auto-resize" then when calling the "onTextChange" function it returns the old values "getWidth()", "getHeight()" etc.

I think there may be more problems with this. This did not occur before "perf: more fps and less usage memory"

**Comment by patrykq112** [comment]
the client also often remains in the processes after being turned off

**Comment by mehah** [comment]
@patrykq112 
https://github.com/mehah/otclient/pull/759
Could you test, here I can't reproduce this problem.

**Comment by patrykq112** [comment]
@mehah the character name shaking bug no longer occurs after these fixes

**Comment by mehah** [comment]
and onTextChange @patrykq112 ?

**Comment by patrykq112** [comment]
> and onTextChange @patrykq112 ?

still occurs

**Comment by patrykq112** [comment]
@mehah I found a new bug, it's bright everywhere, the lighting system doesn't work properly

**Comment by mehah** [comment]
> @mehah I found a new bug, it's bright everywhere, the lighting system doesn't work properly

fixed

**Comment by mehah** [comment]
@patrykq112 
I'm not able to reproduce the text problem, I'm using this code to test.

```lua
local widget = g_ui.createWidget('Label')
widget:setTextAutoResize(true)
widget:setWidth(500)
    
addEvent(function()
    widget:setText('fff15')
end)

widget.onTextChange = function(widget)
    print(widget:getWidth())
end
```

**Comment by patrykq112** [comment]
@mehah 

create otui
```
  ScrollablePanel
    id: testPanel
    anchors.left: parent.left
    anchors.top: parent.top
    anchors.bottom: parent.bottom
    width: 185
    vertical-scrollbar: testPanelScrollBar
    UILabel
      id: testLabel
      anchors.left: parent.left
      anchors.right: parent.right
      anchors.top: parent.top
      min-height: 35
      text-vertical-auto-resize: true
      text-align: center
      text-wrap: true
      @onTextChange: function(self, text, oldText) print(self:getHeight()) end
  VerticalScrollBar
    id: testPanelScrollBar
    anchors.top: testPanel.top
    anchors.bottom: testPanel.bottom
    anchors.right: testPanel.right
    step: 4
    pixels-scroll: true
```

and call "setText" from lua, example: `testPanel.testLabel:setText('kfaspokfasopaskfopaskopfaskpofaskopfsakafspokfopaskfopsakopafskopasaspofkasopksaopfkfaspok saopfkaspoaskfopas kpoasfk apok oaspfkasopfkasopksaop kaosp k fsop')`

**Comment by patrykq112** [comment]
@mehah there are many more bugs because the layout is updated in g_dispatcher.deferEvent. Many modules I have created have bugs. For example, there is a bug with anchors - UIAnchorLayout::addAnchor/UIAnchorLayout::removeAnchors/UIAnchorLayout::addWidget call the "update" function which does not work properly there in some cases.

**Comment by patrykq112** [comment]
source before "perf: more fps and less memory usage" commit
![image](https://github.com/mehah/otclient/assets/16617982/4204af94-e204-4ef8-ac9f-3cfe27e72371)


lastest source
![image](https://github.com/mehah/otclient/assets/16617982/56fbbae3-af91-4c10-92b1-002f534e4456)

**Comment by mehah** [comment]
> @mehah there are many more bugs because the layout is updated in g_dispatcher.deferEvent. Many modules I have created have bugs. For example, there is a bug with anchors - UIAnchorLayout::addAnchor/UIAnchorLayout::removeAnchors/UIAnchorLayout::addWidget call the "update" function which does not work properly there in some cases.

I don't understand, do you call layout:update in lua?

If so, just pass true as an argument and it will be updated immediately.

layout: update (true)

If this is the problem, test passing true, please.

**Comment by mehah** [comment]
If it doesn't solve it, I'll roll it back, the gain isn't worth it. :joy:

**Comment by patrykq112** [comment]
> > @mehah there are many more bugs because the layout is updated in g_dispatcher.deferEvent. Many modules I have created have bugs. For example, there is a bug with anchors - UIAnchorLayout::addAnchor/UIAnchorLayout::removeAnchors/UIAnchorLayout::addWidget call the "update" function which does not work properly there in some cases.
> 
> I don't understand, do you call layout:update in lua?
> 
> If so, just pass true as an argument and it will be updated immediately.
> 
> layout: update (true)
> 
> If this is the problem, test passing true, please.

I don't call from lua, otui uses functions that update the layout.

There are many bugs with updating the layout in source.

**Comment by mehah** [comment]
https://github.com/mehah/otclient/commit/a70f6918b2413fd8d3bdf23e43524bf98027d32f
