### ISSUE TITLE
slow client loading 

### ISSUE THREAD

**Issue by Odisey25** [opentibiabr/otclient#757]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

because many times in computers that are not so powerful this kind of occurrence tends to happen that the maps load slower or when they make a sudden change does not update you have to close and re-enter the game. 
![otclag](https://github.com/mehah/otclient/assets/65802862/00063a40-473b-49e5-9677-c779f88c94cc)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrykq112** [comment]
turn off Options -> Graphics -> Async texture loading
