### ISSUE TITLE
Drawing items with flags

### ISSUE THREAD

**Issue by Lording23** [opentibiabr/otclient#76]
I think the bug is related to DrawFlags.
This issue is reproducible without changes to the code in this repository
You can reproduce the bug by throwing any items to any ground. If you throw a gold coin and later a brown mushroom the second one will always go bottom, untill you leave and appear again in the screen this second item will be in top.
I'm using latest commit from 19~ hours ago.
![dsa](https://user-images.githubusercontent.com/53460029/115097089-a09f9380-9ed4-11eb-81c5-55c5f531fd87.png)

**Comment by Klonoa88** [comment]
Weird... I use the latest TFS and the latest sources from this client and I don't have that problem. 
Which server do you use?

[Video](https://dl.dropboxusercontent.com/s/yzue7dafkvb12rb/2zAs0ddqNJ.mp4)

**Comment by Lording23** [comment]
It seems to be only on 7.x. Tested on two servers, OTX and Nostalrius.

**Comment by mehah** [comment]
honestly, i don't know if i'm going to waste time with this, you can rollback the addThing and removeThing methods and all that reference the variables, m_creatures, m_ground, m_topItems, m_bottomItems and m_commonItems in tile.cpp

my focus has always been 10.98+

**Comment by mehah** [comment]
honestly, i don't know if i'm going to waste time with this, you can rollback the addThing and removeThing methods and all that reference the variables, m_creatures, m_ground, m_topItems, m_bottomItems and m_commonItems in tile.cpp

my focus has always been 10.98+, maintaining compatibility with old versions is giving me a lot of headache.

**try using OTHire** @Lording23

**Comment by Lording23** [comment]
Okay let me test it.
-Update-
Same thing happened in OTHire, common items are being drawed in reverse. 
I throw platinum at first and then rod.

![dsds](https://user-images.githubusercontent.com/53460029/115643280-f0150380-a2c8-11eb-8824-af3acc778053.png)

Tried some around here but I had no success at all
            originalStack -= m_ground.size() + m_bottomItems.size() + m_topItems.size() + m_creatures.size();

            if(originalStack > m_commonItems.size()) {
                m_commonItems.push_back(item);
            } else {
                m_commonItems.insert(m_commonItems.begin() + originalStack, item);

Also noticed some lines in edubart that might help?:
    if(drawFlags & Otc::DrawItems) {
        // now common items in reverse order
        for(auto it = m_things.rbegin(); it != m_things.rend(); ++it) {
            const ThingPtr& thing = *it;
            if(thing->isOnTop() || thing->isOnBottom() || thing->isGroundBorder() || thing->isGround() || thing->isCreature())
                break;
            thing->draw(dest - m_drawElevation*scaleFactor, scaleFactor, animate, lightView);
            m_drawElevation += thing->getElevation();
            if(m_drawElevation > Otc::MAX_ELEVATION)
                m_drawElevation = Otc::MAX_ELEVATION;
        }
    }

**Comment by mehah** [comment]
I'll take a look as soon as possible.

**Comment by mehah** [comment]
could you provide me with a 7.x server already compiled so that I can do the tests?

**Comment by Lording23** [comment]
Yes OTHire is precompiled in windows I sent you in OTLand the host login so you can enter to the machine. It's already online with a client inside, ordered it yesterday for testings.

**Comment by mehah** [comment]
can you test?

**Comment by Lording23** [comment]
This fix made it work 100%. Been tested it for a while and no errors/crash.
I will report anything I notice as irregular, maybe at some point you get time. 

2 Small details noticed in the last 2 weeks:

This happens untill you "redirect" or walk. your name and life bar get in the right place
![detail1](https://user-images.githubusercontent.com/53460029/116740010-df3b5080-a9a0-11eb-8dc0-479e2df81b3b.png)

This happen when you spam a hotkey and walk.
![detail2](https://user-images.githubusercontent.com/53460029/116740019-e2ced780-a9a0-11eb-88c4-3ad59a131688.png)

**Comment by mehah** [comment]
I was unable to reproduce this problem.
![image](https://user-images.githubusercontent.com/2267386/116923459-0ad26b00-ac2d-11eb-9a58-cbc71117aad0.png)
