### ISSUE TITLE
TFS 13.10 Login Console Error

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#761]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

TFS 13.10 Login Console Error

https://prnt.sc/l_pDV4QJCUgE

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luanluciano93** [comment]
Can you test now with the latest updates?

**Comment by daniofordon** [comment]
error invalid thing type client id 0 in category 4

> Can you test now with the latest updates?

error invalid thing type client id 0 in category 4

**Comment by Codinablack** [comment]
I can confirm, using TFS master, for protocol 13.10. (once the world ports are set to correct port and I get a character list), can't login.
![otc](https://github.com/mehah/otclient/assets/8696596/c36def3e-bdb7-4c28-ac96-3269e10a78a9)

**Comment by Codinablack** [comment]
Turns out there were only a few adjustments necessary to make this work for 13.10. Here are those adjustments

![image](https://github.com/mehah/otclient/assets/8696596/e4243f01-74c3-49d6-bcd8-b52710a052ea)

**Comment by luanluciano93** [comment]
#787 Can you check if this solves it? Thank You @Codinablack

**Comment by mehah** [comment]
fixed?

**Comment by kokekanon** [comment]
yesterday I tried it , works in release 3.5 .( to make pr of feat: highscore)
no packet error
![image](https://github.com/mehah/otclient/assets/114332266/c6339ac1-97a6-416a-bde9-69d0b48bd181)


![3 57](https://github.com/mehah/otclient/assets/114332266/0b95363b-90f2-495d-8eff-3ceb9db94d50)

but in the main repo there is a packets error when logging in.
```
ERROR: ProtocolGame parse message exception (4934 bytes, 4743 unread, last opcode is 0x03 (3), prev opcode is 0xa1 (161)): unhandled opcode 3
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1310)
```

according to the tfs console, the player logs in, but in the client it does not log in. 
![mainrepo](https://github.com/mehah/otclient/assets/114332266/b84ae371-bded-4ced-acc2-b63564d61eb6)



> 
> error invalid thing type client id 0 in category 4

try with httpPort = 80 in tfs config

**Comment by luanluciano93** [comment]
@kokekanon test: https://github.com/mehah/otclient/wiki/Tutorial-to-Use-OTC-in-TFS-main + https://github.com/mehah/otclient/pull/808

**Comment by kokekanon** [comment]
can login but 

```
ERROR: ProtocolGame parse message exception (5071 bytes, 493 unread, last opcode is 0x25 (37), prev opcode is 0x86 (134)): unhandled opcode 37
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1310)
```

**Comment by kokekanon** [comment]
no work

### the bug can be found here,

```
void ProtocolGame::parseItemClasses(const InputMessagePtr& msg)
```


GameForgeConvergence `https://github.com/mehah/otclient/pull/789/files`

![image](https://github.com/mehah/otclient/assets/114332266/a123c09c-01f0-4f9a-9fe7-102c0ab6bef2)


----------------------------------
-------------------------
----------------------
# note 
I can login with those changes from your pr
I don't know what forge is ( im player 8.6 jaja). check if there is a conflict in 13.32. 
![image](https://github.com/mehah/otclient/assets/114332266/435379fd-81f0-4df1-9837-1536d7bae8ed)

![image](https://github.com/mehah/otclient/assets/114332266/9ab9c7bd-dff8-4e82-9b46-e77dbbddcdd2)

![image](https://github.com/mehah/otclient/assets/114332266/b65773a4-8e21-4424-90cc-2d9ad12e5434)

![image](https://github.com/mehah/otclient/assets/114332266/d8c8ebab-7072-4b93-98d9-b0f2002fd334)

**Comment by luanluciano93** [comment]
@kokekanon test: https://github.com/mehah/otclient/wiki/Tutorial-to-Use-OTC-in-TFS-main + https://github.com/mehah/otclient/pull/808

**Comment by kokekanon** [comment]
# last commits [a71f159](https://github.com/mehah/otclient/pull/808/commits/a71f15935d21b780d47356fb7ee14dd486a5205e) 

now there is a problem with items you can up in inventory
if you have them in your inventory or if they are on the ground.

player named "koke" had one item in the inventory. player "sample" had nothing.

![vvvv](https://github.com/mehah/otclient/assets/114332266/6bdc3bba-d3a0-46f9-8701-f5d774956b96)

```

ERROR: ProtocolGame parse message exception (5156 bytes, 1326 unread, last opcode is 0x00 (0), prev opcode is 0x78 (120)): unhandled opcode 0
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1310)
```

------------------- 

# release 3.5
![fff](https://github.com/mehah/otclient/assets/114332266/1084cafc-0502-4b14-a4b4-3a8a82a991bc)

**Comment by luanluciano93** [comment]
https://github.com/mehah/otclient/wiki/Tutorial-to-Use-OTC-in-TFS-main
