### ISSUE TITLE
light system bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#764]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

this bug has been around for a long time

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
@patrykq112 
test plz
https://github.com/mehah/otclient/pull/765

**Comment by patrykq112** [comment]
@mehah the same bug still occurs

**Comment by mehah** [comment]
@patrykq112 
I can't reproduce this problem, try this here:

replace onCameraMove for
```c++
void MapView::onCameraMove(const Point& /*offset*/)
{
    requestUpdateMapPosInfo();
    if (isFollowingCreature()) {
        updateViewport(m_followingCreature->isWalking() ? m_followingCreature->getDirection() : Otc::InvalidDirection);
    }

    g_drawPool.repaint(DrawPoolType::FOREGROUND_MAP);
    g_drawPool.repaint(DrawPoolType::CREATURE_INFORMATION);
    g_drawPool.repaint(DrawPoolType::LIGHT);
}
```

**Comment by patrykq112** [comment]
@mehah it didn't help, still the same bug

**Comment by mehah** [comment]
@patrykq112 
I need a tip on how you are reproducing this, in my environment, which I use Tibia as a base, it doesn't happen.

**Comment by mehah** [comment]
https://github.com/mehah/otclient/assets/2267386/a033a0a0-0333-42da-b07d-c1f350d7b89a

**Comment by mehah** [comment]
Are you able to simulate this in Tibia? @patrykq112

**Comment by mehah** [comment]
I created a method to return to the old algorithm, uncomment this line and test it.

in lightview.cpp
![image](https://github.com/mehah/otclient/assets/2267386/1f3317e6-3848-4a7f-93b7-a0e5874dc32c)

**Comment by xrddw126** [comment]
I will honestly say that I also have huge problems with light on this client. I have the January version and in addition to the problem above, there are some black shadows that have a noticeable delay when walking

Maybe the problem is that I am using the 8.54 server, but from the January version these problems with light started until I turned it off completely

The problem most often occurs when objects that generate light appear on the map while walking

**Comment by mehah** [comment]
@patrykq112 
What is your PC configuration?

This delay is probably occurring because things are running asynchronously and your CPU can't keep up, later I will redo some things to try to solve this problem.

**Comment by patrykq112** [comment]
> @patrykq112 What is your PC configuration?
> 
> This delay is probably occurring because things are running asynchronously and your CPU can't keep up, later I will redo some things to try to solve this problem.

Laptop, AMD Ryzen 5 4500u, 16 GB ram, windows 11.

try replace "g_game.walk(dire, firstStep)" to "g_game.forceWalk(dir)" in function "smartWalk" in file game_inferface/gameinterface.lua

When I did this, the bug occurs every time I walk

**Comment by mehah** [comment]
@patrykq112 

This doesn't happen here, please test with a clean client, without modifications and see if it happens, because honestly, I don't know if your project is 100% updated according to the project found on this github, I've had a lot of problems with that. people reporting problems that simply didn't update or updated everything wrong and I spent hours trying to figure it out and ended up discovering that the problem didn't exist.

So please record a video with this problem occurring in the most recent client and without any modifications, as I am not responsible for customized projects.

**Comment by patrykq112** [comment]
@mehah 


https://github.com/mehah/otclient/assets/16617982/a8b81ccd-7780-4e12-92c0-bbc96a2dcdee

**Comment by mehah** [comment]
@patrykq112 
ok, I'm going to redo some things to get rid of this problem once and for all.

**Comment by mehah** [comment]
try again @patrykq112 
https://github.com/mehah/otclient/pull/765

**Comment by patrykq112** [comment]
@mehah 

this bug no longer occurs, but shadows appear in random places when walking around the map and there is a visible drop in fps (in some places even from 500 to 200)

**Comment by mehah** [comment]
> @mehah
> 
> this bug no longer occurs, but shadows appear in random places when walking around the map and there is a visible drop in fps (in some places even from 500 to 200)

I'm not finished yet, I just asked you to test to see if you at least fixed the old bug, other bugs may occur, as I'm throwing everything into a separate thread and redoing the logic.

**Comment by patrykq112** [comment]
> > @mehah
> > this bug no longer occurs, but shadows appear in random places when walking around the map and there is a visible drop in fps (in some places even from 500 to 200)
> 
> I'm not finished yet, I just asked you to test to see if you at least fixed the old bug, other bugs may occur, as I'm throwing everything into a separate thread and redoing the logic.

This bug no longer occurs after these changes 😊

**Comment by mehah** [comment]
@patrykq112 
test again :)

**Comment by patrykq112** [comment]
> @patrykq112 test again :)

It's better, there are no more FPS drops, no shadows appear in random places. Lighting does not work on Magic Effects and Missiles.

**Comment by patrykq112** [comment]
@mehah It's better, there are no more FPS drops, no shadows appear in random places.

**Comment by patrykq112** [comment]
@mehah 
![image](https://github.com/mehah/otclient/assets/16617982/7749fb07-2dc8-4231-97a0-ce9d4342097d)

**Comment by patrykq112** [comment]
I added `if (!tile) continue;` after `for (const auto& tile : map.shades) {` , `for (const auto& tile : map.tiles){` and it helped

I noticed that if there are a lot of characters running next to you with lights and they run off the screen, all the lights flash

**Comment by patrykq112** [comment]
@mehah 

https://github.com/mehah/otclient/assets/16617982/4e78781e-e4ae-4c48-a3a6-6bf865bbb3c3

**Comment by patrykq112** [comment]
https://github.com/mehah/otclient/assets/16617982/f8f1b6be-df3a-4b6a-807a-035d835ed3c8

**Comment by mehah** [comment]
@patrykq112 
test again.

**Comment by patrykq112** [comment]
@mehah now it works very well, the light no longer flashes 😊
