### ISSUE TITLE
bug with highlight

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#766]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

https://github.com/mehah/otclient/assets/16617982/ff24e779-1645-4085-ba21-58740bd4813a

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
Are you really sure your client is updated?

**Comment by rodrigopaixaorj** [comment]
https://github.com/mehah/otclient/commit/d0d708cd6ad5af11a1a5d2b71b67b6cca2d27edf

**Comment by patrykq112** [comment]
> Are you really sure your client is updated?



> [d0d708c](https://github.com/mehah/otclient/commit/d0d708cd6ad5af11a1a5d2b71b67b6cca2d27edf)

Yes, I am using the latest source. Changes have been recently introduced to this system.

https://github.com/mehah/otclient/commit/404e2c5b53792c80b80ab375963008eba479df99
