### ISSUE TITLE
Error terminal 13.32

### ISSUE THREAD

**Issue by pedrohfk** [opentibiabr/otclient#773]
### Priority

High

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

When I walk the character around the city it keeps getting stuck.

![image](https://github.com/mehah/otclient/assets/16357255/f8b5a117-4f7c-4cef-b6c4-03e406830730)

![image](https://github.com/mehah/otclient/assets/16357255/0442ddbe-f1cc-4533-82fc-a41581f23381)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by libergod** [comment]
Just to add to this issue, I've been debuging the OTC, found a better message error: 

![image](https://github.com/mehah/otclient/assets/37589902/a040d37c-364b-4c0c-96ad-3a24cb61da72)

Unfortunately, don't know how to fix opcodes but could help in the further analysis.

**Comment by luanluciano93** [comment]
> Just to add to this issue, I've been debuging the OTC, found a better message error:
> 
> ![image](https://private-user-images.githubusercontent.com/37589902/333706747-a040d37c-364b-4c0c-96ad-3a24cb61da72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjI2MTcsIm5iZiI6MTcyMDMyMjMxNywicGF0aCI6Ii8zNzU4OTkwMi8zMzM3MDY3NDctYTA0MGQzN2MtMzY0Yi00YzBjLTk2YWQtM2EyNGNiNjFkYTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDAzMTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MGU5ZDM4ODFmZGZiYmRmYWY2NDAxZDhlZWZlODFhZjRhMDcyN2VjNmRiNTRiOTM5OWRlYzRiYTI4OWU1NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eIZeE6poAx7z011hpHVcbHDqCj065W5QQfgQBEcbgPI)
> 
> Unfortunately, don't know how to fix opcodes but could help in the further analysis.


I will review all market bytes for canary main soon

**Comment by pedrohfk** [comment]
As tested, it stopped giving errors and is ok.
