### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by xrddw126** [opentibiabr/otclient#777]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I noticed that the method:

void DrawPoolManager::addTexturedRect(const Rect& dest, const TexturePtr& texture, const Rect& src, const Color& color, const DrawConductor& condutor) const

For some reason it randomly crashes the client, interestingly this happens not on all but only some processors, but on more powerful ones
[log.txt](https://github.com/mehah/otclient/files/15468292/log.txt)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
there is no getTexture in creatureInformation, is this custom code?

https://github.com/mehah/otclient/blob/fd8799e59115ef0cba65732e50b4c4025064599b/src/client/creature.cpp#L127

**Note: If so, you cannot request getTexture within this method, there may be competition with lua since it is executed asynchronously between UI and Map**

**Comment by xrddw126** [comment]
Yes, I wanted to add additional icons next to the life bars. Ok, thanks. Will try to do as you say

**Comment by mehah** [comment]
@xrddw126
it will not work, I will give another solution.

**Comment by mehah** [comment]
@xrddw126 @patrykq112 

put "/" at the beginning of Path so as not to make a lua call.

like this:
```c++
g_textures.getTexture('images/xyz/item.png');
to
g_textures.getTexture('/images/xyz/item.png');
```

**Comment by mehah** [comment]
I will close this issue as it is not a project problem.

**Comment by patrykq112** [comment]
@mehah For me, crashes occur on a clean project. The client closes randomly, no error or crash report appears

**Comment by mehah** [comment]
> @mehah For me, crashes occur on a clean project. The client closes randomly, no error or crash report appears

Run it directly through Visual Studio so it displays the error when it occurs.

**Comment by patrykq112** [comment]
@mehah 
![image](https://github.com/mehah/otclient/assets/16617982/74c16448-8806-4c05-8b68-da600277dc08)
![image](https://github.com/mehah/otclient/assets/16617982/d8ee3b32-6584-4ea2-8dd3-fe9e6c97fe1c)
![image](https://github.com/mehah/otclient/assets/16617982/df1136ad-4ce3-4924-8208-6c4aba3d5a7e)
![image](https://github.com/mehah/otclient/assets/16617982/7d1e0bd4-3cb2-447c-8727-6b04fa46e51f)

**Comment by patrykq112** [comment]
this bug occurs after "fix: crash with getTexture inside preDraw" commit.

**Comment by mehah** [comment]
@patrykq112 

test plz:  https://github.com/mehah/otclient/pull/782
