### ISSUE TITLE
Bug in function "g_ui.displayUI()"

### ISSUE THREAD

**Issue by alysonjacomin** [opentibiabr/otclient#783]
### Priority

High

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

The "g_ui.displayUI()" function is only working when applied within the INIT or TERMINATE function, when applied in any other function it starts spamming an error

The problem is finding the file path, because following what I did in the example below I managed to solve the problem

Example: the "Open new channel" and "Ignore players" buttons in the game_console module are spamming errors

However, if I change these factors below the error is corrected:
 "g_ui.displayUI('communicationwindow')" to "g_ui.displayUI('/modules/game_console/communicationwindow')"

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I can't reproduce, test with a clean client, without modifications and in the latest revision.

![image](https://github.com/mehah/otclient/assets/2267386/7c35021c-35f7-4647-af6d-64b2f0e89118)
