### ISSUE TITLE
Other Light/Shadow bug (Borders)

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#79]
Found another bug with light and shadows.
Check out the borders on the video below:
[Video](https://dl.dropboxusercontent.com/s/75c0nrqnmx9t3g0/8nFNZqwreD.mp4)

**Comment by mehah** [comment]
is the shadow system or light system?

show me in the original form.

**Comment by Klonoa88** [comment]
> 
> 
> is the shadow system or light system?
> 
> show me in the original form.

original form? I do not know exactly which of them it is, lights or shadows. But it looks strange.

**Comment by mehah** [comment]
original form = systems(light/shadow) disabled

because I see no problem, this floor seems to be below the track, if the floor is very dark and has a shadow system, it will get even darker, apparently it has nothing to do with the light system, the shadows of the light system only reaches the floor above you, impossible to stay below, only if it is the shadow system.

**Comment by mehah** [comment]
or you can export that part of the map so I can see what’s going on.

**Comment by Klonoa88** [comment]
Tried now and it is NOT Floor shadowing. It is the light system
[Video](https://dl.dropboxusercontent.com/s/wlaik86bg94bcvl/UfKevQfcp3.mp4)

**Comment by Klonoa88** [comment]
The dark, black should only be on the tile I walk on? Not on borders? If I remove borders, it will be as it should be :P
[Video](https://dl.dropboxusercontent.com/s/nteqndl9k55qxkn/V0VJv2BaUC.mp4)

**Comment by mehah** [comment]
this is really weird, i need to simulate the same condition here, these spriters are from tibia, can you export this part of the map and send it to me?

**Comment by Klonoa88** [comment]
> 
> 
> this is really weird, i need to simulate the same condition here, these spriters are from tibia, can you export this part of the map and send it to me?

I do not know if it is original sprites from tibia. We are a few working on this project and sprites are not my area haha;) but you can map a bridge under floor 7 and try. it probably does not matter what sprites it is

**Comment by Klonoa88** [comment]
The bridge is mapped like this and is on floor 11
[Image](https://i.imgur.com/ai9N1tV.png)

**Comment by mehah** [comment]
it matters how you defined the sprites in your dat file.

if i can't simulate this problem on my ambient work which is the Tibia, i won't be able to check if it really is a system problem or some definition in your dat file,

the shadow conditions of the light system, you can find it here:
https://github.com/mehah/otclient/blob/557014a26c1ead5954b25499b85b27fc6bd00167/src/client/mapview.cpp#L122

Note: that light in your character is very strange, it seems that it has been altered, it is not a gradient.

**Comment by Klonoa88** [comment]
> Note: that light in your character is very strange, it seems that it has been altered, it is not a gradient.

Strange because I use your sources. The only custom is: Adding more tiles to game window.
Where should I look in the sources to see if it went wrong with my character light?

**Comment by mehah** [comment]
if you can simulate this problem with the tibia spriters and give me the map, i would appreciate it, because that way i can simulate.

> > Note: that light in your character is very strange, it seems that it has been altered, it is not a gradient.
> 
> Strange because I use your sources. The only custom is: Adding more tiles to game window.
> Where should I look in the sources to see if it went wrong with my character light?

https://github.com/mehah/otclient/blob/cache-for-all/src/client/lightview.cpp
and min light is 1:
https://github.com/mehah/otclient/blob/557014a26c1ead5954b25499b85b27fc6bd00167/src/client/creature.cpp#L102

**Comment by Klonoa88** [comment]
> it matters how you defined the sprites in your dat file.

> if i can't simulate this problem on my ambient work which is the Tibia, i won't be able to check if it really is a system problem or some definition in your dat file,

I have checked with him who fixes our sprites and those items should have the same flags as tiles and borders in real tibia..

Edit: These border sprites are the original Tibia..

**Comment by mehah** [comment]
ok, you can recreate this area with the tibia spriters and pass me, something like that, on the same floor and etc ...

**Comment by Klonoa88** [comment]
I will ask our mapper/sprite to do it later because I have no map editor on my computer haha: P but we put the flag Translucent on the borders and now it work better :)
[Video](https://dl.dropboxusercontent.com/s/3fxyhzg14wxxs3n/cqRMsKp8Og.mp4)

**Comment by Klonoa88** [comment]
> light.intensity = std::max<uint8>(light.intensity, 1); 

Aha I had set it to 2 haha: P

**Comment by mehah** [comment]
> I will ask our mapper/sprite to do it later because I have no map editor on my computer haha: P but we put the flag Translucent on the borders and now it work better :)
> [Video](https://dl.dropboxusercontent.com/s/3fxyhzg14wxxs3n/cqRMsKp8Og.mp4)

so there is something wrong with the definition of your dat file, ground border is different from ground.

**Comment by Klonoa88** [comment]
Okay. Will check it out later :)

**Comment by mehah** [comment]
> > light.intensity = std::max(light.intensity, 1);
> 
> Aha I had set it to 2 haha: P

you can keep 1 and increase the brightness, which is .1f to .5f, for example ...

https://github.com/mehah/otclient/blob/557014a26c1ead5954b25499b85b27fc6bd00167/src/client/lightview.cpp#L98

or

`lights.push_back(LightSource{ pos , light.color, radius, 1.f }); `

**Comment by Klonoa88** [comment]
Oki. I'll try :)

**Comment by mehah** [comment]
I will close the problem, since it was a problem of definition in its object
