### ISSUE TITLE
New Layout - Red Fist mode not working

### ISSUE THREAD

**Issue by matheussf** [opentibiabr/otclient#794]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

With the new changes on layout, the red fist mode is not working.

Not sure what is happening, since the code `g_game.setPVPMode(pvpMode)` is being reached with Red Fist enum set as 3 when the red fist mode button is enabled.

I've tried to look on the new layout PR what might be causing this, but there were so many commits and the commit that removes `game_combatcontrols` doesn't add this feature in the same commit, so information is lost between the commit history.

![image](https://github.com/mehah/otclient/assets/16403023/45aa46b4-35cf-4a7d-9c28-82c7d9eb4b2d)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
I tried to fix it, **but** my knowledge only goes up to 8.6. I don't know what PVP Mode is.
in 8.6 is functional
https://github.com/Nottinghster/otclient/pull/42

![image](https://github.com/mehah/otclient/assets/114332266/885fbce6-bb79-456f-a82a-a9130122de37)
I don't know why Nottinghster accepted it and then did revert xd

**Comment by rodrigopaixaorj** [comment]
If someone manage to implement/adapt the old combat controls in new layout, it will fix everything related to it

https://github.com/mehah/otclient/blob/dfcf9db6e4366e82cba2636bb85c51f79985ac3d/modules/game_combatcontrols/combatcontrols.lua

**Comment by rodrigopaixaorj** [comment]
@matheussf Could you take a look at this and fix it ?

**Comment by matheussf** [comment]
> @matheussf Could you take a look at this and fix it ?

I'm working on the analyzers right now, and I feel that would take some time for me to fix it, have so much to learn yet. But I can try after the analyzers

**Comment by rodrigopaixaorj** [comment]
Fixed https://github.com/mehah/otclient/commit/c5c614154eb1197551455791168211023939028a
