### ISSUE TITLE
New layout - Status icons not working

### ISSUE THREAD

**Issue by matheussf** [opentibiabr/otclient#796]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

With the new layout the status in the inventory is not working anymore.

Old Client:
![image](https://github.com/mehah/otclient/assets/16403023/54eb7feb-68e1-4898-a55f-8db50c09e633)

New Client:
![image](https://github.com/mehah/otclient/assets/16403023/5544b8eb-2196-4e5d-887d-03685032772d)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
last commits: [style: add text (DEBUG MODE) in compilation in debug]
it works , this error **isn't** in the main repo

test 8.6 

![image](https://github.com/mehah/otclient/assets/114332266/429131ee-9ef4-4360-8970-f3043de44a0d)

**Comment by matheussf** [comment]
Not sure if the latest changes on protocolgameparses fixed it, but it is working in both repos, mine and this.
(Might be a side effect when I was refactoring.)
