### ISSUE TITLE
Walking into uninvited house tiles makes the outfit flicker

### ISSUE THREAD

**Issue by diath** [opentibiabr/otclient#8]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Walk into a house that you're not invited to

### Expected behaviour
Player snaps back into position

### Actual behaviour
Player briefly disappears before snapping back

**Comment by mehah** [comment]
I tested it here and everything is correct, I don't know if it was something I just fixed before your report, test it with the last review, I'll leave it open in the meantime.
