### ISSUE TITLE
Wrong draw order (Borders)

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#80]
Something is wrong about the order in which grounds and borders are drawn. Sometimes some borders end up below others.
I think this issue is the same, or has to do with this [#76](https://github.com/mehah/otclient/issues/76). 

If I relogg, the order changes. in this case, the gray borders end up below the brown ones. It's the same if I run away and then come back.

I have tried with original OtClient and there does not this problem exist.

Watch the video below:
[Video](https://dl.dropboxusercontent.com/s/g3jp015vlvholbi/GzS8ngC0gH.mp4)

### Environment
10.98 Latest version of TFS and your Latest OTC sources **(cache-for-all)**

**Comment by mehah** [comment]
can you test?

**Comment by Klonoa88** [comment]
I have tried now and borders and tiles are drawn in the right order now :) But the client crashes after a while. 
No errors in Terminal and no crash log :(

**Check out the video below:**
[Video](https://dl.dropboxusercontent.com/s/30kmblh0xzh814q/Brt82CzPha.mp4)

**Comment by mehah** [comment]
> I have tried now and borders and tiles are drawn in the right order now :) But the client crashes after a while.
> No errors in Terminal and no crash log :(
> 
> **Check out the video below:**
> [Video](https://dl.dropboxusercontent.com/s/30kmblh0xzh814q/Brt82CzPha.mp4)

can you test in debug mode?

Compile Debug Mode -> click local windows debugger -> (reproduce the bug) -> (when to crasher) click retry -> (and go to the call stack tab and see where it went wrong.)

I simulated a mistake for you to understand where it is.
![image](https://user-images.githubusercontent.com/2267386/116711242-08f87580-a9a9-11eb-8f15-bf94b813b9fe.png)

**Comment by Klonoa88** [comment]
> Compile Debug Mode -> click local windows debugger -> (reproduce the bug) -> (when to crasher) click retry -> (and go to the call stack tab and see where it went wrong.)

I have been trying for an hour now with Debug (x64). Can't get the crash in this mode. But as soon as I switch to Release (x64) again, it crashes. Hmm?? Idk

**Comment by mehah** [comment]
test now

**Comment by Klonoa88** [comment]
After all the latest commits, everything works perfectly so far. So I think you can close this issue now. Thanks for a great job @mehah. You keep OTClient alive :)

One small thing. 
After this commit [Anti-Aliasing Option / Render Scale System ](https://github.com/mehah/otclient/commit/c0cb8d328ca44482225b6fcf3100337a0d14f0f5) when you deleted [this](https://github.com/mehah/otclient/commit/c0cb8d328ca44482225b6fcf3100337a0d14f0f5#diff-7d3052fc5ceeba10fe7064b52a13554d24b54229f6c3d831358bab727167edfe). 
Outfits is no longer draw smooth in OutfitWindow. They are now more pixelated.

**Comment by mehah** [comment]
well, for me it wasn't pixelated, but anyway, I put it in to force the smoothing
