### ISSUE TITLE
Question FloorShade

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#82]
This is more of an Question than an issue. How can I do to only have [this](https://i.imgur.com/UOsKGnb.png) (floorshade) active under seafloor? I do not want it over the seafloor on the houses and things like [this](https://i.imgur.com/Lsv5qKB.png). Do you have an example of how I can fix this? :)

**Comment by mehah** [comment]
all shadefloor logic you can find from this line:

https://github.com/mehah/otclient/blob/278e6612350b0e7aa515fedfaeff4f3baa565974/src/client/mapview.cpp#L124

![image](https://user-images.githubusercontent.com/2267386/117331042-b9182380-ae6c-11eb-882d-42532e054cda.png)

you can simply make a logic to ignore the shadow from floor 7 to 0, which are floors where daylight falls.

**Comment by Klonoa88** [comment]
I have tried there for a few hours now in different ways but I do not get it to work as I want :(

**Comment by Klonoa88** [comment]
Do you have a magic line in stock that I can put there so it works? haha: P

**Comment by mehah** [comment]
but what do you really want, put shade only on floors 8+?

if it really is, just change this line:
https://github.com/mehah/otclient/blob/278e6612350b0e7aa515fedfaeff4f3baa565974/src/client/mapview.cpp#L125
for this:
`if(nextFloor >= m_floorMin && nextFloor > Otc::SEA_FLOOR) {`

it should work, I haven't tested it. :)

**Comment by Klonoa88** [comment]
Yes I will have shades on floor 8+ only.

No, that did not work as it should hehe ;) Now you can see all the light sources that are under the sea floor. And then some shadow squares appear. Look here :) Look [HERE](https://i.imgur.com/dTaZpVl.jpg)

**Comment by Klonoa88** [comment]
Do you have any other solution?

**Comment by Klonoa88** [comment]
@mehah

**Comment by mehah** [comment]
https://github.com/mehah/otclient/blob/278e6612350b0e7aa515fedfaeff4f3baa565974/src/client/mapview.cpp#L123
to
`if(lightView && z > Otc::SEA_FLOOR) {`

**Comment by Klonoa88** [comment]
No it does not work. Light still comes through floors. But I separated drawing in my own way and use g_map.isCovered() to solve my problem :) So we can close this now.
