### ISSUE TITLE
can write but  messages are not sent canary + mehah client  protocol 11 windows 10 no editions server + client clean

### ISSUE THREAD

**Issue by Feliipe93** [opentibiabr/otclient#822]
### Priority

Low

### Area

- [X] Data
- [X] Source
- [X] Docker
- [X] Other

### What happened?

A bug happened!

im using latest canary ( no editions + mehah otclient no editions im connecting with protocol 11
i write messages but messages are not being sent to the server at all
eberything is clean  client + server

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
1 - Check terminal if there are errors
2 - Check options and see if all message options are checked

**Comment by kokekanon** [comment]
test in main repo protocol 13.32

![132333](https://github.com/user-attachments/assets/60320d4c-32ef-400d-80bd-174f041eec53)
![image](https://github.com/user-attachments/assets/1c6139b1-45d5-4037-95c7-78a608df5beb)

last commits: canary
![image](https://github.com/user-attachments/assets/311e84ef-59e9-4daa-8640-550b759fcedd)
last commits: redemption
![image](https://github.com/user-attachments/assets/197d00ad-6802-4f73-8022-ba9d321be152)




test protocol 11 : 

![12313](https://github.com/user-attachments/assets/494f38b5-10a0-49be-bbab-6293cbc609ca)


try clearing cache

**Comment by rodrigopaixaorj** [comment]
@pasturryx Maybe you're doing something wrong, this issue will be closed, feel free to ask for help in our Discord channel
