### ISSUE TITLE
Error in client_options when attempting to load gameMapPanel

### ISSUE THREAD

**Issue by Znote** [opentibiabr/otclient#83]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Download 1.0.1 [Source code (zip)](https://github.com/mehah/otclient/archive/refs/tags/1.0.1.zip) file and extract it to a folder in your computer
2. Download 1.0.1 [otclient1.0.1x64.zip](https://github.com/mehah/otclient/releases/tag/1.0.1) file and extract it to the same folder.
3. Start otclient.exe and click CTRL + T to see the error in the terminal. 

### Expected behaviour
No error. 

### Actual behaviour
It looks like client_options is trying to use the game_interface module, before game_interface has loaded. Is there a way to prioritize module loading?
![image](https://user-images.githubusercontent.com/1552144/117633707-9775af80-b17e-11eb-8b96-c49922fe6751.png)
https://github.com/mehah/otclient/blob/3d2bdcf207f258ae48351f391ff545ca39c0877e/modules/client_options/options.lua#L223-L231

### Environment
Windows 10, protocol 10.98

### Additional thoughts
Well I'm actually researching why this instance of otclient refuses to save my minimap, the client seems to work fine, but as soon as I logout and login again my minimap gets reset. I figured this might be related to that issue, since this line might mess up map load/save initialization? 

I'm not 100% sure this is what causes the map to not load and save properly, so I omitted this from expected and actual behavior.

**Comment by mehah** [comment]
I am analyzing the problem with the minimap
