### ISSUE TITLE
Login in corpse after death

### ISSUE THREAD

**Issue by leoddias** [opentibiabr/otclient#831]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Sometimes when you die, you relog in your dead corpse.
branch main
![otclient_x64_AgIMa0X7Ov](https://github.com/user-attachments/assets/fb577f65-c84c-4836-a367-0f573b389f03)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
I think it's more of a canary problem, because in tfs (otland) 13.10 I can't reproduce that.

**Comment by luanluciano93** [comment]
- which server base are you using?
- which version of tibia are you using?
- what are the errors in the otc log?

**Comment by leoddias** [comment]
@luanluciano93 

Canary - Main Branch - 13.32
No errors in OTC Log.

**Comment by leoddias** [comment]
@kokekanon could be something with canary+otclient... but.... it dont happens in cipclient.

![client_-_127 0 0 1_JPUmhDmi8s](https://github.com/user-attachments/assets/38a01e95-7e71-4f3b-bfeb-a92e88036ba1)

**Comment by kokekanon** [comment]
as i said the error is in canary not in otclient

delete this if : "otclientV8 > 0" and work

https://github.com/opentibiabr/canary/blob/main/src/server/network/protocol/protocolgame.cpp#L927


https://github.com/user-attachments/assets/22146d42-c82a-4951-8667-cf33ca04d5a5



PR FIX in canary : https://github.com/opentibiabr/canary/pull/2776

**Comment by leoddias** [comment]
@kokekanon 
PR: https://github.com/opentibiabr/canary/pull/2776
Tested and approved in Canary and Client OTC Meha  - Version 13.32 - **main branch**
