### ISSUE TITLE
error parseCreatureSpeed

### ISSUE THREAD

**Issue by kojimhojo** [opentibiabr/otclient#839]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I don't know how to reproduce this, but sometimes it appears
13.32
```
ERROR: ProtocolGame::parseCreatureSpeed: could not get creature with id 268435457
at:
    [C++]: ?parseCreatureSpeed@ProtocolGame@@AEAAXAEBV?$shared_ptr@VInputMessage@@@std@@@Z
```

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luanluciano93** [comment]
the structure of the "change speed" byte packet collection method is correct for version 13.32

The problem must be in another byte packet.

The server sends many bytes at once, and the packets are defined by the first byte, for example, the server sends seventy bytes, the first one is defined by the number 13, and let's assume that it is called in a method that the framework receives the another thirty-nine bytes, there are still forty bytes left, and the 40th will be the byte that will define the next packet, and so on, if any structure goes wrong (receiving less or more bytes) it will give an error. The difficult part is finding which package the error is in without a specific message or action.

**Comment by Wirless** [comment]
did you increase the window size or rendering more tiles on map than you should and maybe not parsing them? or too many floors? if i recall correctly some otc can download all floors as its a function for minimap right that would draw the map in order to draw minimap no?
as far as i see the pointer is not correctly calling or recalling the creature due to maybe lag or loss of packets?

**Comment by kokekanon** [comment]
I guess the problem is on the server side and not on the client side .
in v8 :  
![image](https://github.com/user-attachments/assets/e44fbaf8-80a8-44d9-83c7-d5fe0b4b90ee)

**Comment by mehah** [comment]
As there was no response, I will close this issue.
