### ISSUE TITLE
player:getVocation() function does not return all vocation IDs

### ISSUE THREAD

**Issue by BastardofWinterfell** [opentibiabr/otclient#845]
### Priority

Low

### Area

- [ ] Data
- [x] Source
- [ ] Docker
- [ ] Other

### What happened?

The `player:getVocation()` function currently only returns a number from 1 to 4 corresponding to the four basic [unpromoted vocations](https://tibia.fandom.com/wiki/vocation) in Tibia.

1. Knight
2. Paladin
3. Sorcerer
4. Druid

However, it should also return different numbers (e.g. from **11 to 14**) to differentiate [promoted vocations](https://tibia.fandom.com/wiki/vocation_promotion), which should have different client IDs, from their unpromoted equivalents.

11. Elite Knight
12. Royal Paladin
13. Master Sorcerer
14. Elder Druid

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
https://github.com/mehah/otclient/blob/main/modules/gamelib/player.lua#L175

**Comment by kokekanon** [comment]
changes were incorporated cyclopedia

134c6dc
you can use this function
https://github.com/mehah/otclient/blob/main/modules/gamelib/player.lua#L175
