### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by xrddw126** [opentibiabr/otclient#849]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I completely don't know what the cause of this is, but twice I had such a crash while walking on the map

I tried many times to reproduce it, but to no avail

I add crashlog, maybe it will help something

[crashreport.log](https://github.com/user-attachments/files/16677269/crashreport.log)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
build date: Jul 12 2024

The ideal is to update your client, this crash may have already been fixed.

**Comment by xrddw126** [comment]
I've updated the client with all missing commits and will check, but I have a feeling it's not related to the latest patches

This is some rare bug because it occurred to me 2 times in the last 2 weeks

**Comment by mehah** [comment]
the problem is that the log doesn't show anything relevant for me to reach any conclusion.

**Comment by mehah** [comment]
Update your project to last Rev, has crash fix
