### ISSUE TITLE
On outfit change not checking if outfit is mountable or not

### ISSUE THREAD

**Issue by Feliipe93** [opentibiabr/otclient#85]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. use an outfit and dismount it
2. change your outfit
3. it will get mounted even when it were unmounted also it  insntanty mount outfits that should be unmountable. it wont check a flag.
as example this
`if ((playerOutfit->lookType == xxx) || (playerOutfit->lookType == xxx)) {
   sendCancelMessage(RETURNVALUE_NOTPOSSIBLE);
   return false;
}`
or this
https://github.com/otland/forgottenserver/pull/2035/commits/9b993bfd4d36aea740e02fe96d8f2765c1709e52

the code works but by the client  the outfits get mounted i've also opened a thread in otland
https://otland.net/threads/prevent-automatic-mount-on-outfit-change.276437/#post-2660069

### Expected behaviour

if outfit is checked as un mountablevia server  it will not  instantly mount after outfit change

### Actual behaviour

when you change outfit it get isntatly mounted wether the outfit mountable or not

### Environment

latest mehah otclient

**Comment by mehah** [comment]
here is working normally, but I will update the outfitwindows with what is in ot1264.

https://github.com/opentibiabr/otclient/blob/sengi/modules/game_outfit/outfit.lua

**Comment by mehah** [comment]
ready, it is updated, if you still have the problem, it is your server, I tested it on TFS 10.98 and OTservBR 12.64 and it is working perfectly.

**Comment by Feliipe93** [comment]
deleted it was   a non accurate post

**Comment by Feliipe93** [comment]
updated  issue

Edit : the bug occurs only if you are using an outfit that allow mounts.

 if you are mounted using an outfit that allows you to use mounts and then you change to an outfit that does not allow mounts it will change the outfit but will not un-mount it first.

Using clean files. same as you

@mehah

**Comment by Feliipe93** [comment]
i must add that this does not happens on otcv8 :/

**Comment by mehah** [comment]
the project is to support tibia and not customizations, if the current code is working in tibia, there's no reason for me to analyze and fix something that doesn't happen, because I don't have the same environment as you.

**Comment by mehah** [comment]
another thing, if the client was able to place the mount, it is because the server allowed him to place it, so the main problem is not with the client.

**Comment by mehah** [comment]
you have to understand the basics, any order the client gives and it runs without permission, there is a security issue on the server side.

**Comment by mehah** [comment]
I analyzed the code here, it sends a request to the server asking to change the outfit, if for some eventuality he managed to put X outfit or Y mount, the server that allowed it, then there is some security problem (condition) in your modifications.

**Comment by mehah** [comment]
I didn't really understand what you said, you're saying that when changing the character, he shouldn't wear the mount if he's already dressed before, is that it?

**Comment by Tazer89** [comment]
I think he means that when you change outfit it doesn't check if the outfit is compatible with mount. Exemple: Gamemaster outfit can't mount becouse it looks wierd/broken. @mehah

**Comment by mehah** [comment]
but who has to say whether the mount is compatible or not, is the server and not the client, if the client was able to use X outfit using Y mount, it was because the server allowed it.

**Comment by mehah** [comment]
well, as i didn't get any feedback, i'll be closing.
