### ISSUE TITLE
excessive ram consumption with a lot of AE ThingExternalTexture

### ISSUE THREAD

**Issue by kojimhojo** [opentibiabr/otclient#850]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

test in main repo 08/20/2024

With  +250 AE ThingExternalTexture **RAM 737MB**
![image](https://github.com/user-attachments/assets/7e803373-a2fc-455f-b679-f55447f87bb8)

wihout ThingExternalTexture **only ThingCategoryEffect, ThingCategoryCreature** **RAM 113MB**
![image](https://github.com/user-attachments/assets/af069ed7-2e0e-451b-8aa1-82d7e36ec8b0)

without AE (empy effects.lua) **RAM 111MB**
![image](https://github.com/user-attachments/assets/2b3b01e9-cb79-4da5-930b-a4a88e11b92c)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
@kojimhojo 
test plz

**Comment by kojimhojo** [comment]
![image](https://github.com/user-attachments/assets/63828597-74b9-4c8b-984c-1dc0d960e5b1)
to
![image](https://github.com/user-attachments/assets/a9da65aa-b841-488e-aa95-1fe5d3936e5f)

woooow amazing,
it worked perfectly, awesome job , thanks


684MB to 111MB

**Comment by mehah** [comment]
thx :heartpulse:
