### ISSUE TITLE
Shop and coins dont work

### ISSUE THREAD

**Issue by DigoAlves1480** [opentibiabr/otclient#854]
### Priority

High

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I compiled the project in x86 release mode because the x64 version doesn't run on older UMP architectures, and I noticed that the shop doesn't recognize items or coins. You open the shop and nothing appears. The forge doesn't work either. I'm running on version 13.32. Event shedule dont work, boos and boosted creature cont work. It is not possible to write to communication channels.Managers containers doesn't work correctly. I cant find cyclopedia

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
# store
fix :  https://github.com/mehah/otclient/pull/855
13.32
![image](https://github.com/user-attachments/assets/5f193403-bd2f-49aa-a248-2ba8a6d89a4a)
13.40
![image](https://github.com/user-attachments/assets/a2d7367d-3b43-4b25-a320-cab01b9f41a6)

# Event shedule
about Event shedule , i think i broke that when i modified new layout xd (at that time I didn't know that the information was extracted from login.php) 

but test here

![image](https://github.com/user-attachments/assets/f4838034-1946-4265-80cb-b6920c947eca)

# Managers containers
What is the bug? I only use 8.6, I don't know how it works.

**Comment by DigoAlves1480** [comment]
i just download the latest repository and compile in vs in release x86 mode.
