### ISSUE TITLE
Market bad performance

### ISSUE THREAD

**Issue by MUN1Z** [opentibiabr/otclient#864]
### Priority

Low

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

We have comparing some things between Mehah and Cip client, i have noted a great CPU increase when browsing the market module.

cip (13.40):
https://github.com/user-attachments/assets/a3700425-5ad4-4b95-ab61-9d96d69ad1bd

mehah (Last main commit 30/08/2024):
https://github.com/user-attachments/assets/261e0cd9-0104-466b-8443-2425b8efd498

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
This market is from my grandmother's time, I believe it would be more sensible to rewrite it, even to make the UI closer to Tibia and whoever is going to rewrite it, use HTML/CSS, to abolish OTUI once and for all and it will be beautiful when I implement TypescriptToLua, I've already done some tests here and the implementation is super simple.

**Comment by mehah** [comment]
https://github.com/mehah/otclient/commit/e8fba330c99194fccbc6ab0f08c498a247cf202f
I think that fixed it.
