### ISSUE TITLE
Bot scripts encryption

### ISSUE THREAD

**Issue by Bob13372** [opentibiabr/otclient#867]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

After encrypting client using --encrypt, bot configs created in %AppData% are also encrypted. Now if you upload there your new conifg (unencrypted) with scripts, you will see bot executor errors ingame and bot won't work.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SkullzOTS** [comment]
@Bob13372 try this: https://github.com/mehah/otclient/pull/876

**Comment by SkullzOTS** [comment]
Now you will need to enable GameAllowCustomBotScripts in game_features
