### ISSUE TITLE
CTLR + BACKSPACE onKeyPress problem

### ISSUE THREAD

**Issue by leonves** [opentibiabr/otclient#869]
### Priority

Medium

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

When I press CTRL + backspace in any text editor, it glitches. Does anyone know what it could be? I tried changing the function to do nothing when pressed, but it didn’t work.

https://github.com/user-attachments/assets/5e371091-7031-45d4-9541-7b3cc53f8273

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gesior** [comment]
I've tested this. Pressing CTRL+BACKSPACE adds `7F` (127) ASCII character, which in Notepad++ is printed as special character `DEL`
![image](https://github.com/user-attachments/assets/e28c760a-fd33-4ecc-b74b-0218994d7631)

Fix (removes 1 character, not 1 word, but blocks character 127) in `src/framework/ui/uitextedit.cpp`:

**This will make CTRL+BACKSPACE work as BACKSPACE (todo: make it remove whole word)**
Under:
```cpp
        } else if (keyCode == Fw::KeyA && getProp(PropSelectable)) {
            if (m_text.length() > 0) {
                selectAll();
                return true;
            }
        }
```
Paste:
```cpp
        else if(keyCode == Fw::KeyBackspace && getProp(PropEditable)) { // erase left word
            if (hasSelection() || !m_text.empty()) {
                // todo: remove word, not 1 character
                del(false);
                return true;
            }
        }
```

**This will block adding character `127` to text edit area:**
Under:
```cpp
bool UITextEdit::onKeyText(const std::string_view keyText)
{
```
Paste:
```cpp
    if (keyText.length() == 1 && keyText.front() == 127) {
        return false;
    }
```
