### ISSUE TITLE
buy button gamestore inactive even though you have enough coins in your account

### ISSUE THREAD

**Issue by dgprado-80** [opentibiabr/otclient#873]
### Priority

Low

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

The buy button in gamestore is inactive even though you have enough coins in your account.
only Transferable Coins are working.
![image](https://github.com/user-attachments/assets/591e18b3-a13c-49f9-871e-96be6a4bc25c)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dgprado-80** [comment]
I dont use transferable coins

**Comment by kokekanon** [comment]
but you have 0 points xd
I think the problem is that the module has the wrong icon.

13.40 cipsoft
![image](https://github.com/user-attachments/assets/2f53f3b3-7430-4ac5-ba6f-8dfcafa071e3)

**Comment by dgprado-80** [comment]
![image](https://github.com/user-attachments/assets/4418583c-9cc6-48f3-99f2-92c2057eaab5)
My client cipsoft 1332. I dont use transferable coins.

**Comment by kokekanon** [comment]
:O how do I change that on the server side?

**Comment by dgprado-80** [comment]
Man, I don't remember how I changed. some time ago. hahaha. I'm trying to remember to solve this problem. I'll tell you as soon as I remember.

**Comment by dgprado-80** [comment]
i dont change notthing, i just dont add trasferable coins for players.

**Comment by dgprado-80** [comment]
I just realized that if the character has enough balance in trabsferible coins, he can only buy them for normal coins. The problem appears to be that the price of items is being checked exclusively in transferable coins

**Comment by kokekanon** [comment]
try this https://github.com/mehah/otclient/pull/874

canary\data\modules\scripts\gamestore\gamestore.lua

if you want test : 
![image](https://github.com/user-attachments/assets/a510743a-f810-4e07-86ac-35b348625aa2)

**Comment by dgprado-80** [comment]
eu fiz uma pequena modificação game_store.lua do canary para que a loja trabalhasse apenas com coins normais ru alterei de :
                  if not offer.coinType then
                        offer.coinType = GameStore.CoinType.Transferable

para

                  if not offer.coinType then
                        offer.coinType = GameStore.CoinType.Coin

este trecho ficabem no final do arquivo linha 6723
________________________________
De: kokekanon ***@***.***>
Enviado: quinta-feira, 12 de setembro de 2024 15:49
Para: mehah/otclient ***@***.***>
Cc: dgprado-80 ***@***.***>; Author ***@***.***>
Assunto: Re: [mehah/otclient] buy button gamestore inactive even though you have enough coins in your account (Issue #873)


try this #874<https://github.com/mehah/otclient/pull/874>

**Comment by dgprado-80** [comment]
> :O how do I change that on the server side?

I made a small modification to the canary's game_store.lua so that the store would only work with normal coins and I changed it from:
                  if not offer.coinType then
                        offer.coinType = GameStore.CoinType.Transferable

para

                  if not offer.coinType then
                        offer.coinType = GameStore.CoinType.Coin

This excerpt is at the end of the line file 6723

**Comment by kokekanon** [comment]
test pr

**Comment by dgprado-80** [comment]
> test pr

Yes my Hero, its works. thxx
