### ISSUE TITLE
7.6 Fire-field animations run way too fast

### ISSUE THREAD

**Issue by divinity76** [opentibiabr/otclient#878]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Fire-field and poison-field and orb and coal-basin and animations all run way too fast on 7.6 , or at least on tibiafun.zapto.org.
Observed on 3.5 release.

https://github.com/user-attachments/assets/cede9596-ec4c-4280-9c9c-25f12529a0e9

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
Just change it here: https://github.com/mehah/otclient/blob/main/data/setup.otml#L33

**Comment by divinity76** [comment]
@Nottinghster I guess 75 is the correct speed for some other version of tibia then? 8.6+ perhaps?

**Comment by rodrigopaixaorj** [comment]
> @Nottinghster I guess 75 is the correct speed for some other version of tibia then? 8.6+ perhaps?

Try 500

**Comment by divinity76** [comment]
@Nottinghster yeah that works much better! thanks

But if someone submit a pull request setting it to 500, i guess it will be rejected with "breaks the speed of some other tibia version" ?

**Comment by Nottinghster** [comment]
> @Nottinghster yeah that works much better! thanks
> 
> But if someone submit a pull request setting it to 500, i guess it will be rejected with "breaks the speed of some other tibia version" ?

Yes
