### ISSUE TITLE
Shadow on player

### ISSUE THREAD

**Issue by Mrpox** [opentibiabr/otclient#88]
Set it to 95% ambient light for the most clear way to see it.

![image](https://user-images.githubusercontent.com/72432211/120145186-661f5b00-c1e3-11eb-90f4-2d34fdd75f34.png)

At 0% ambient light, player emits a tiny bit of light and completely dark around.

When ambient light goes above the brightness of the player (around 35%) it begins to be brighter around player and a shadow starts forming on the player.
And when reaching 100% ambient light its gone.

**Comment by Znote** [comment]
![image](https://user-images.githubusercontent.com/1552144/123309775-a09bbf80-d525-11eb-9d56-530124d88f56.png)

Confirmed, using untouched files. 860 things
