### ISSUE TITLE
bug: possible memory leak when multiple UIcreature, UIitem are displayed in UIScrollArea ?

### ISSUE THREAD

**Issue by kokekanon** [opentibiabr/otclient#889]
**the memory increase is exponential in the case of UIcreature , UI item in a UIscrollArea.**

if it is a UIwidget the memory increase is marginal.

.
.
.
.
--------------------------------------------
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

# 1) v8 

**500mb -> 549 mb**

https://github.com/user-attachments/assets/4ea000e9-40ed-4264-b4b2-fa9fb55e12a8

.
.
.
.
--------------------------------------------

.
# 2) redemption

**200mb -> 670 mb**

game_outfit

https://github.com/user-attachments/assets/af659e8a-8bc3-4207-b843-6a5e8d6bde09

**150mb -> 800 mb**

game_store

https://github.com/user-attachments/assets/227a5516-26b5-4778-b641-719b288ac749

**150mb -> 460 mb**

game_cyclopedia

https://github.com/user-attachments/assets/3bbbe888-e00e-498d-ae6a-2da090140e2e

if I add all three and walk around the map for a while it is very easy to get to ~1gb ram in less than 1 minute.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
module for test https://github.com/user-attachments/files/17100970/game_testPR.zip

force test  :

![image](https://github.com/user-attachments/assets/1971f265-d3ef-49a1-893e-929a0ad769c7)





https://github.com/user-attachments/assets/cf76392a-2e40-43d6-b62e-05d2c1d25304

**Comment by mehah** [comment]
I believe this leak may be pointers stuck in lua,

reduce this time:

https://github.com/mehah/otclient/blob/de666d32f4490c948241c60057395851b060ef62/src/framework/core/garbagecollection.cpp#L32

for example 10 seconds, to see if the memory is freed up faster.

and about the memory being at "100mb" then going to "500mb" it is because the assets and texture are lazy loading, in v8 as it is dat/spr, it loads everything 1x to memory.

**Comment by kokekanon** [comment]
You're right, haha. I got scared when I saw 1.5 GB of ram being used.

I also tried with spr 11.00.


|            	| init       	| end        	|
|------------	|------------	|------------	|
| Redemption 11.00 	| 512~520 mb 	| 670~710 mb 	|
| otcv8   11.00 	   	| 513 mb     	| 599 mb     	|
