### ISSUE TITLE
Color of name not updating according to lifebar

### ISSUE THREAD

**Issue by Mrpox** [opentibiabr/otclient#89]
![image](https://user-images.githubusercontent.com/72432211/120174539-7d6f4000-c205-11eb-8765-55f5677d4564.png)

I damaged player down to red health and cast exura sio.
Bar is yellow but name is still red.
This can happens both way, lifebar is red and name is green etc.

Updates after a player or creature walks.

![image](https://user-images.githubusercontent.com/72432211/120174710-af80a200-c205-11eb-81ad-f92086bd6c3c.png)

**Comment by Znote** [comment]
Sounds a bit related to monsters dissapearing from battle window:
https://github.com/mehah/otclient/issues/92

Monsters chasing you will not appear in battle window until you move your character, even though they are clearly in screen.

**Comment by mehah** [comment]
test with the new rendering system.

**Comment by Mrpox** [comment]
Cant replicate this issue anymore.

**Comment by mehah** [comment]
> Cant replicate this issue anymore.

confirm for me @Znote

**Comment by mehah** [comment]
> Cant replicate this issue anymore.

so can i close?

**Comment by Mrpox** [comment]
@mehah Yep, can be closed!
