### ISSUE TITLE
 [BOT] Macro

### ISSUE THREAD

**Issue by bateunatrave** [opentibiabr/otclient#891]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

I'm using the latest version

ERROR: [BOT] Macro:  execution error: /game_bot/functions/map.lua:112: attempt to call field 'findEveryPath' (a nil value)

![image](https://github.com/user-attachments/assets/fbf8e8e2-58cd-43b2-a7ea-da733e42c9d9)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
1) how to reproduce this bug?  
2) clean cache win+r  `%appdata%/otcr/otclient/otclient` 
3) use v4.8

**Comment by bateunatrave** [comment]
I'm on this version, after clearing the cache the red message disappeared, but after configuring some waypoints the error appeared again, but in yellow. 
![image](https://github.com/user-attachments/assets/254f7e71-2adf-4161-8a91-dd38362e7806)


I have this error in the healer function

ERROR: caught a lua call to a bot protected game function, the call was cancelled
stack traceback:
    [builtin#142]: at 0x7ff765dd5b00
    [C]: in function 'say'
    [string "/vBot/HealBot.lua"]:561: in function 'callback'
    /game_bot/functions/main.lua:117: in function 'callback'
    /game_bot/executor.lua:179: in function </game_bot/executor.lua:178>
    [C]: in function 'pcall'
    /game_bot/executor.lua:178: in function </game_bot/executor.lua:172>
    [C]: in function 'pcall'
    /game_bot/bot.lua:462: in function </game_bot/bot.lua:454>
ERROR: caught a lua call to a bot protected game function, the call was cancelled

**Comment by kokekanon** [comment]
according to me it's some custom script.
I see you have several
![image](https://github.com/user-attachments/assets/fe6a59ca-cf49-43fe-873c-18b62534a536)



I can't reproduce this. in clean


why terminal delivers this , when you compiled without bot_protection
ERROR: caught a lua call to a bot-protected game function, the call was cancelled.  xD

**Comment by bateunatrave** [comment]
> according to me it's some custom script. I see you have several ![image](https://private-user-images.githubusercontent.com/114332266/370959671-fe6a59ca-cf49-43fe-873c-18b62534a536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTgyODgsIm5iZiI6MTcyNzMxNzk4OCwicGF0aCI6Ii8xMTQzMzIyNjYvMzcwOTU5NjcxLWZlNmE1OWNhLWNmNDktNDNmZS04NzNjLTE4YjYyNTM0YTUzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwMjMzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODY3NGVlYmRkOTEyZDY3N2Y0YmQwNzg5ZGQ2NmJhYzI3MzhiODM1ZTM0MzI2MTk1ZGU4YmEzNjllZmM3MmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xMOe3xw4No39t-YnhEC7jPDrO004JKHBmF1IrwsKgYA)
> 
> I can't reproduce this. in clean
> 
> why terminal delivers this , when you compiled without bot_protection ERROR: caught a lua call to a bot-protected game function, the call was cancelled. xD

I'm not using custom scripts, just the git version, I compiled with this option OFF and removed the init comment about the bot

option(TOGGLE_BOT_PROTECTION "Use bot protection" OFF)

**Comment by mehah** [comment]
@bateunatrave 
```cmake
option(TOGGLE_BOT_PROTECTION "Use bot protection" OFF)
```

It is for compilations using cmake, if you are using a VC17 project it is in vc17/settings.props.

You simply went to init and removed the bot check and that is why the module was loaded, but the compiled client still has BOT_PROTECTION, you don't need to change anything in init.

```lua
    if not g_game.isEnabledBotProtection() then -- You can't remove that.
        g_modules.ensureModuleLoaded('game_bot')
    end
```
