### ISSUE TITLE
Unable to compile using wiki on windows vcpkg

### ISSUE THREAD

**Issue by themaoci** [opentibiabr/otclient#893]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

#EDITED
1>   Creating library C:\Users\X\Desktop\Tibia\otclient-3.5\vc17\../otclient_x64.lib and object C:\Users\X\Desktop\Tibia\otclient-3.5\vc17\../otclient_x64.exp
1>libprotobuf.lib(descriptor.cc.obj) : error LNK2001: unresolved external symbol __std_mismatch_4
1>openal32.lib(null.cpp.obj) : error LNK2001: unresolved external symbol _Thrd_sleep_for
1>openal32.lib(wave.cpp.obj) : error LNK2001: unresolved external symbol _Thrd_sleep_for
1>C:\Users\X\Desktop\Tibia\otclient-3.5\vc17\..\otclient_x64.exe : fatal error LNK1120: 2 unresolved externals
#EDITED

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by themaoci** [comment]
tried using latest and release 3.5 happends on both

**Comment by mehah** [comment]
I think vcpkg is now stable again, just do a git pull and vcpkg upgrade --no-dry-run
