### ISSUE TITLE
Attack square dissapears

### ISSUE THREAD

**Issue by maddogtannen231** [opentibiabr/otclient#898]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

Red attack square dissapears shortly after attacking a monster - The player still attacks the monster and the red square is visible on battle list, however u are unable to see the red attack square around monster.

https://gyazo.com/3fa4e59aeabaabd43aabfe35c0b04720 

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
how to reproduce it ? 
![image](https://github.com/user-attachments/assets/14afcc3f-f605-4da5-a3e2-0a13228f6a4e)

**Comment by maddogtannen231** [comment]
It just happens right away, atleast from a release that i compiled on  on 26.09.

**Comment by OTArchive** [comment]
> how to reproduce it ? ![image](https://private-user-images.githubusercontent.com/114332266/372949695-14afcc3f-f605-4da5-a3e2-0a13228f6a4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODcxMzYsIm5iZiI6MTcyNzg4NjgzNiwicGF0aCI6Ii8xMTQzMzIyNjYvMzcyOTQ5Njk1LTE0YWZjYzNmLWY2MDUtNGRhNS1hM2UyLTBhMTMyMjhmNmE0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNjMzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzhlYWVmMTViNzQwOTkyODdkNWQ4NDc0NWJlZDMwN2MzY2FkZjBjOWNlMDEwZDRkY2UzNTQzNWNlYmJiYTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.keaXYiCDeqY5wp1q2-20Z-Tk3UqK4x5deqN-FAVz0eQ)

Happens with me when using latest Canary, not sure if it's a client issue or if the wrong packet is being sent.
The square disappears when you are hit by a monster, instead of the black square appearing on it.

**Comment by maddogtannen231** [comment]
Im using tfs 1.42

**Comment by kokekanon** [comment]
yes you are right, I confirm the bug in 13.40

**Comment by maddogtannen231** [comment]
Also im using 10.98 protocol version, but im not sure it matters?

**Comment by AllanHarlen** [comment]
yes you are right, I confirm the bug in 8.54

**Comment by themaoci** [comment]
im not sure how to reproduce it but i had that problem on my server in 1098 not sure how i fixed that tho... (i could suspect its something in lua)
