### ISSUE TITLE
Shield blink doesn't request creature information drawing

### ISSUE THREAD

**Issue by diath** [opentibiabr/otclient#9]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Enable inactive shared party experience mode

### Expected behaviour
Party shields blink

### Actual behaviour
Party shield is invisible until next information redraw

### Suggestion
This can be fixed by requesting draw in `Creature::updateShield` however I'd also suggest that you request that information for other things in `Creature::setIcon`, `Creature::setHealthPercent` and so on rather than in `protocolgameparse.cpp`.

**Comment by mehah** [comment]
fixed thx. I put in protocolparse to avoid unnecessary calls to draw, let's see how the performance behaves.
