### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by kyurejl** [opentibiabr/otclient#9]
Usando otservbr-develop e otclient-develop ao tentar entrar no personagem da esse erro e fica permanentemente tentando entrar no jogo.
 ERROR: ProtocolGame parse message exception (3005 bytes unread, last opcode is 0x00 (0), prev opcode is 0x17(23)): unhandled opcode 0

**Comment by lgrossi** [comment]
Unfortunately, that's not true. I've done clean clone + a clean build in both repositories, develop branch, is normally working.
