### ISSUE TITLE
Dead monsters in battle list

### ISSUE THREAD

**Issue by Znote** [opentibiabr/otclient#90]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
Not entirely sure, my brother reported this after I sent him this otclient, I havent reproduced it locally yet. 

### Expected behaviour
Monsters should be removed from the list

### Actual behaviour
![image](https://user-images.githubusercontent.com/1552144/121074683-7d0e1080-c7d4-11eb-828e-0d1fdc6404e1.png)
```lua
ERROR: protected lua call failed: LUA ERROR:
/game_battle/battle.lua:550: attempt to concatenate local 'sortType' (a nil value)
stack traceback:
[c]: in function '__concat'
    /game_battle/battle.lua:550: in function 'removeCreature'
    /game_battle/battle.lua:802: in function </game_battle/battle.lua:801>
```
Could it be `getSortType()` doesn't always return a string?

### Environment
OTClient 1.0.1, W10, TFS 1.3 [(protocol 8.60)](https://github.com/nekiro/TFS-1.4-Downgrades)

**Comment by Znote** [comment]
Somehow it got sorted out when they downloaded directly from the releases link here on github x)

**Comment by oarsc** [comment]
This issue is already closed, but it happened to me too.
I just fixed it ;)
