### ISSUE TITLE
crash after encryption

### ISSUE THREAD

**Issue by Wirless** [opentibiabr/otclient#901]
### Priority

Low

### Area

- [ ] Data
- [x] Source
- [ ] Docker
- [ ] Other

### What happened?

== application crashed
app name: Rookgaard Independence-PreRelease
app version: 3.x
build compiler: Visual Studio - x64
build date: Oct  3 2024
build type: RelWithDebInfo
build revision: 0.000 (desenv)
crash date: Oct 03 2024 17:56:32
exception: Access violation (0xc0000005)
exception address: 0xd15d422d
  backtrace:
    0: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(memcpy+0x17d) [0x00000000D15D422D]
    1: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(FileStream::cache+0x341) [0x00000000D0FF66E1]
    2: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(ThingTypeManager::loadDat+0x169) [0x00000000D0F18B29]
    3: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(std::_Func_impl_no_alloc<`luabinder::make_mem_func_singleton<bool,SpriteManager,std::basic_string<char,std::char_traits<char>,std::allocator<char> > >'::`2'::<lambda_1>,bool,std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &>::_ÿå]+0x41) [0x00000000D0FE27D1]
    4: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(`luabinder::bind_fun_specializer<bool,std::function<bool __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &)>,std::tuple<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >'::`2'::<lambda_1>::operatoÿå]+0x160) [0x00000000D0F9F580]
    5: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(LuaInterface::luaCppFunctionCallback+0x5c) [0x00000000D1037DFC]
    6: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(lj_BC_FUNCC+0x42) [0x00000000D0E8AD20]
    7: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(lua_pcall+0xaa) [0x00000000D143BFFA]
    8: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(LuaInterface::safeCall+0x6b) [0x00000000D103705B]
    9: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(LuaInterface::signalCall+0x101) [0x00000000D1037291]
    10: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(LuaInterface::callGlobalField<unsigned short>+0x2f9) [0x00000000D0F35D99]
    11: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(Game::setClientVersion+0xb9) [0x00000000D0EBF929]
    12: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(std::_Func_impl_no_alloc<`luabinder::bind_fun_specializer<void,std::function<void __cdecl(unsigned short const &)>,std::tuple<unsigned short> >'::`2'::<lambda_1>,int,LuaInterface *>::_Do_call+0x73) [0x00000000D0FE0C03]
    13: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(LuaInterface::luaCppFunctionCallback+0x5c) [0x00000000D1037DFC]
    14: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(lj_BC_FUNCC+0x42) [0x00000000D0E8AD20]
    15: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(lua_pcall+0xaa) [0x00000000D143BFFA]
    16: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(LuaInterface::safeCall+0x6b) [0x00000000D103705B]
    17: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(LuaInterface::signalCall+0x66) [0x00000000D10371F6]
    18: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(LuaObject::luaCallLuaField<unsigned char,int,int>+0x2ba) [0x00000000D10EA88A]
    19: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(UIWidget::onKeyPress+0x4d) [0x00000000D10DB82D]
    20: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(UIWidget::propagateOnKeyPress+0x12f) [0x00000000D10DC1CF]
    21: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(UIWidget::propagateOnKeyPress+0xf6) [0x00000000D10DC196]
    22: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(UIManager::inputEvent+0xde) [0x00000000D10C3B6E]
    23: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(std::_Func_impl_no_alloc<``GraphicalApplication::init'::`2'::<lambda_2>::operator()<InputEvent const &>'::`5'::<lambda_1>,void>::_Do_call+0x1a) [0x00000000D10123EA]
    24: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(Event::execute+0x24) [0x00000000D0FF5054]
    25: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(Application::poll+0x3c) [0x00000000D0FF2A7C]
    26: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(GraphicalApplication::poll+0x1c) [0x00000000D0FF902C]
    27: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(`GraphicalApplication::run'::`2'::<lambda_2>::operator()+0xad) [0x00000000D0FF8B6D]
    28: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(`BS::thread_pool::submit_task<`GraphicalApplication::run'::`2'::<lambda_2>,void>'::`2'::<lambda_1>::operator()+0x12) [0x00000000D100D1F2]
    29: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(BS::thread_pool::worker+0x267) [0x00000000D0FF1DD7]
    30: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(std::thread::_Invoke<std::tuple<void (__cdecl BS::thread_pool::*)(unsigned int,std::function<void __cdecl(void)> const &),BS::thread_pool *,unsigned int,std::function<void __cdecl(void)> >,0,1,2,3>+0x16) [0x00000000D1012E56]
    31: C:\Users\krz\Desktop\Independence\otclient_gl_x64.exe(thread_start<unsigned int (__cdecl*)(void *),1>+0x5a) [0x00000000D157D5EE]
    32: C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x14) [0x000000001DC27374]
    33: C:\WINDOWS\SYSTEM32\ntdll.dll(RtlUserThreadStart+0x21) [0x000000001E47CC91]

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wirless** [comment]
cant enter game. just encrypted the client and thats what i get when entering acc and password unencrypted works fine

**Comment by Wirless** [comment]
why ban me from discord for asking that question ? hellooopo

**Comment by Wirless** [comment]
Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)Try to ask questions in [discord](https://discord.gg/HZN8yJJSyC)

**Comment by Wirless** [comment]
so much of help to ban someone who has issue.

**Comment by Wirless** [comment]
that will resolve it!

**Comment by kojimhojo** [comment]
the last change I tracker was this one 

https://github.com/mehah/otclient/pull/876 by @SkullzOTS 

additional information: 


steps : 
encrypt
open the client
select versions using .spr and .dat
click on login in entergame windows
crash

![image](https://github.com/user-attachments/assets/93af2970-ef87-4bba-9a79-c15a3d35c926)
Correct encrypt
![image](https://github.com/user-attachments/assets/e64fb960-ac5b-4ed1-bebd-ce17632a95b4)

```cpp
>	otclient_dx_x64.exe!memcpy_repmovs() Line 50	Unknown
 	otclient_dx_x64.exe!FileStream::cache(bool useEnc) Line 89	C++
 	otclient_dx_x64.exe!ThingTypeManager::loadDat(std::string file) Line 87	C++
 	[Inline Frame] otclient_dx_x64.exe!std::invoke(bool(ThingTypeManager::*)(std::string) &) Line 1745	C++
 	[Inline Frame] otclient_dx_x64.exe!std::_Mem_fn<bool (__cdecl ThingTypeManager::*)(std::string)>::operator()(ThingTypeManager * &) Line 578	C++
 	[Inline Frame] otclient_dx_x64.exe!luabinder::make_mem_func_singleton::__l2::<lambda_1>::operator()(std::string) Line 190	C++
 	[Inline Frame] otclient_dx_x64.exe!std::invoke(luabinder::make_mem_func_singleton::__l2::<lambda_1> &) Line 1739	C++
 	otclient_dx_x64.exe!std::_Func_impl_no_alloc<`luabinder::make_mem_func_singleton<bool,ThingTypeManager,std::string>'::`2'::<lambda_1>,bool,std::string const &>::_Do_call(const std::string & <_Args_0>) Line 907	C++
 	[Inline Frame] otclient_dx_x64.exe!std::_Func_class<bool,std::string const &>::operator()(const std::string &) Line 951	C++
 	[Inline Frame] otclient_dx_x64.exe!luabinder::call_fun_and_push_result(const std::function<bool __cdecl(std::string const &)> &) Line 64	C++
 	[Inline Frame] otclient_dx_x64.exe!luabinder::expand_fun_arguments<0,bool>::call(const std::tuple<std::string> &) Line 94	C++
 	[Inline Frame] otclient_dx_x64.exe!luabinder::expand_fun_arguments<1,bool>::call(const std::tuple<std::string> &) Line 85	C++
 	otclient_dx_x64.exe!luabinder::bind_fun_specializer::__l2::<lambda_1>::operator()(LuaInterface * lua) Line 112	C++
 	[Inline Frame] otclient_dx_x64.exe!std::_Func_class<int,LuaInterface *>::operator()(LuaInterface * <_Args_0>) Line 951	C++
 	otclient_dx_x64.exe!LuaInterface::luaCppFunctionCallback(lua_State * __formal) Line 629	C++
 	otclient_dx_x64.exe!lj_BC_FUNCC()	Unknown
 	otclient_dx_x64.exe!lua_pcall(lua_State * L, int nargs, int nresults, int errfunc) Line 1146	C
 	[Inline Frame] otclient_dx_x64.exe!LuaInterface::pcall(int) Line 812	C++
 	otclient_dx_x64.exe!LuaInterface::safeCall(int numArgs, int numRets) Line 434	C++
 	otclient_dx_x64.exe!LuaInterface::signalCall(int numArgs, int numRets) Line 486	C++
 	[Inline Frame] otclient_dx_x64.exe!LuaInterface::luaCallGlobalField(const std::basic_string_view<char,std::char_traits<char>>) Line 492	C++
 	otclient_dx_x64.exe!LuaInterface::callGlobalField<unsigned short>(const std::basic_string_view<char,std::char_traits<char>> global, const std::basic_string_view<char,std::char_traits<char>> field, const unsigned short & <args_0>) Line 507	C++
 	otclient_dx_x64.exe!Game::setClientVersion(const unsigned short version) Line 1670	C++
 	[Inline Frame] otclient_dx_x64.exe!std::_Func_class<void,unsigned short const &>::operator()(const unsigned short &) Line 951	C++
 	[Inline Frame] otclient_dx_x64.exe!luabinder::call_fun_and_push_result(const std::function<void __cdecl(unsigned short const &)> &) Line 74	C++
 	[Inline Frame] otclient_dx_x64.exe!luabinder::expand_fun_arguments<0,void>::call(const std::tuple<unsigned short> &) Line 94	C++
 	[Inline Frame] otclient_dx_x64.exe!luabinder::expand_fun_arguments<1,void>::call(const std::tuple<unsigned short> &) Line 85	C++
 	[Inline Frame] otclient_dx_x64.exe!luabinder::bind_fun_specializer::__l2::<lambda_1>::operator()(LuaInterface * lua) Line 112	C++
 	[Inline Frame] otclient_dx_x64.exe!std::invoke(luabinder::bind_fun_specializer::__l2::<lambda_1> &) Line 1739	C++
 	otclient_dx_x64.exe!std::_Func_impl_no_alloc<`luabinder::bind_fun_specializer<void,std::function<void __cdecl(unsigned short const &)>,std::tuple<unsigned short>>'::`2'::<lambda_1>,int,LuaInterface *>::_Do_call(LuaInterface * && <_Args_0>) Line 909	C++
 	[Inline Frame] otclient_dx_x64.exe!std::_Func_class<int,LuaInterface *>::operator()(LuaInterface * <_Args_0>) Line 951	C++
 	otclient_dx_x64.exe!LuaInterface::luaCppFunctionCallback(lua_State * __formal) Line 629	C++
 	otclient_dx_x64.exe!lj_BC_FUNCC()	Unknown
 	otclient_dx_x64.exe!lua_pcall(lua_State * L, int nargs, int nresults, int errfunc) Line 1146	C
 	[Inline Frame] otclient_dx_x64.exe!LuaInterface::pcall(int) Line 812	C++
 	otclient_dx_x64.exe!LuaInterface::safeCall(int numArgs, int numRets) Line 434	C++
 	otclient_dx_x64.exe!LuaInterface::signalCall(int numArgs, int numRets) Line 468	C++
 	otclient_dx_x64.exe!LuaObject::luaCallLuaField<TPoint<int>>(const std::basic_string_view<char,std::char_traits<char>> field, const TPoint<int> & <args_0>) Line 189	C++
 	[Inline Frame] otclient_dx_x64.exe!LuaObject::callLuaField(const std::basic_string_view<char,std::char_traits<char>>) Line 199	C++
 	otclient_dx_x64.exe!UIWidget::onClick(const TPoint<int> & mousePos) Line 1847	C++
 	otclient_dx_x64.exe!UIManager::updatePressedWidget(const std::shared_ptr<UIWidget> & newPressedWidget, const TPoint<int> & clickedPos, bool fireClicks) Line 185	C++
 	otclient_dx_x64.exe!UIManager::inputEvent(const InputEvent & event) Line 130	C++
 	[Inline Frame] otclient_dx_x64.exe!GraphicalApplication::inputEvent(const InputEvent &) Line 283	C++
 	[Inline Frame] otclient_dx_x64.exe!GraphicalApplication::init::__l2::<lambda_2>::()::__l5::<lambda_1>::operator()() Line 67	C++
 	[Inline Frame] otclient_dx_x64.exe!std::invoke(GraphicalApplication::init::__l2::<lambda_2>::()::__l5::<lambda_1> & _Obj) Line 1729	C++
 	otclient_dx_x64.exe!std::_Func_impl_no_alloc<``GraphicalApplication::init'::`2'::<lambda_2>::operator()<InputEvent const &>'::`5'::<lambda_1>,void>::_Do_call() Line 905	C++
 	[Inline Frame] otclient_dx_x64.exe!std::_Func_class<void>::operator()() Line 951	C++
 	otclient_dx_x64.exe!Event::execute() Line 37	C++
 	[Inline Frame] otclient_dx_x64.exe!EventDispatcher::executeEvents() Line 136	C++
 	[Inline Frame] otclient_dx_x64.exe!EventDispatcher::poll() Line 52	C++
 	otclient_dx_x64.exe!Application::poll() Line 151	C++
 	otclient_dx_x64.exe!GraphicalApplication::poll() Line 236	C++
 	otclient_dx_x64.exe!GraphicalApplication::run::__l2::<lambda_2>::operator()() Line 158	C++
 	otclient_dx_x64.exe!BS::thread_pool::submit_task::__l2::<lambda_1>::operator()() Line 618	C++
 	[Inline Frame] otclient_dx_x64.exe!std::_Func_class<void>::operator()() Line 951	C++
 	otclient_dx_x64.exe!BS::thread_pool::worker(const unsigned int idx, const std::function<void __cdecl(void)> & init_task) Line 937	C++
 	[Inline Frame] otclient_dx_x64.exe!std::invoke(void(BS::thread_pool::*)(unsigned int, const std::function<void __cdecl(void)> &) &&) Line 1745	C++
 	otclient_dx_x64.exe!std::thread::_Invoke<std::tuple<void (__cdecl BS::thread_pool::*)(unsigned int,std::function<void __cdecl(void)> const &),BS::thread_pool *,unsigned int,std::function<void __cdecl(void)>>,0,1,2,3>(void * _RawVals) Line 61	C++
 	otclient_dx_x64.exe!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter) Line 97	C++
 	kernel32.dll!00007ffca49e257d()	Unknown
 	ntdll.dll!00007ffca574af28()	Unknown
```

![image](https://github.com/user-attachments/assets/6e4169f0-9e57-4532-9629-79c41a598117)


![image](https://github.com/user-attachments/assets/9b266542-2a99-486e-aa49-b3a2e00ac083)
![image](https://github.com/user-attachments/assets/63dac44c-d00b-4f34-bf41-75886d7fd3b7)

![image](https://github.com/user-attachments/assets/69c197ac-b566-4876-bc30-6257d0d396d3)
![image](https://github.com/user-attachments/assets/4885d6a4-8720-4467-8d07-38f818d20079)

**Comment by Wirless** [comment]
nevermind any fucking compilation without encryption client is fucked

**Comment by kojimhojo** [comment]
simply undo  pr 876 
and in passing asks with respect

**Comment by SkullzOTS** [comment]
I'll test it soon, when I made this PR there was no problem like that, it could be that some other change is conflicting!

**Comment by SkullzOTS** [comment]
@Wirless try this please: https://github.com/mehah/otclient/pull/910
