### ISSUE TITLE
Error to used update client 

### ISSUE THREAD

**Issue by T3llorista** [opentibiabr/otclient#904]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Ubuntu 24.04 LTS in my log on apache 2.4.58 when i open the client and download the update of client i get this error in apache2 log:
Got error 'PHP message: PHP Warning:  Undefined property: stdClass::$version in /var/www/html/api/updater.php on line 30
![imagen_2024-10-05_022655061](https://github.com/user-attachments/assets/42d19187-49ab-4c5d-8452-4826fd70596b)
Php Version 8.3.6
![imagen_2024-10-05_022940450](https://github.com/user-attachments/assets/b8f00e88-27b2-4f64-a8d1-b21daa187b83)

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
use this updater.php (no v8)
https://github.com/mehah/otclient/blob/main/tools/api/updater.php

and skip warning `"Got error 'PHP message: PHP Warning: Undefined property: stdClass::$version in `/var/www/html/api/updater.php on line 30" in
https://github.com/mehah/otclient/blob/main/modules/updater/updater.lua#L220

change 

version = APP_VERSION,
    to
version = 1,

for test



edit: im test in PHP Version 8.2.0 and work , in http and without cloudflare , windows 11

**Comment by T3llorista** [comment]
![imagen_2024-10-08_211853976](https://github.com/user-attachments/assets/e065503f-5c71-4102-8f74-d74dbf81b9c8)
![imagen_2024-10-08_211940185](https://github.com/user-attachments/assets/f86c9bd8-7053-455d-aaaa-460e1db3a9db)
[error.log](https://github.com/user-attachments/files/17298206/error.log)
