### ISSUE TITLE
market

### ISSUE THREAD

**Issue by bateunatrave** [opentibiabr/otclient#911]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

when you enter the my offers window

ERROR: ProtocolGame parse message exception (341 bytes, 7 unread, last opcode is 0xf9 (249), prev opcode is 0xffffffff (-1)): InputMessage eof reached
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1332)
ERROR: ProtocolGame parse message exception (342 bytes, 7 unread, last opcode is 0xf9 (249), prev opcode is 0x1e (30)): InputMessage eof reached
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1332)
ERROR: ProtocolGame parse message exception (341 bytes, 7 unread, last opcode is 0xf9 (249), prev opcode is 0xffffffff (-1)): InputMessage eof reached
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1332)
ERROR: ProtocolGame parse message exception (341 bytes, 7 unread, last opcode is 0xf9 (249), prev opcode is 0xffffffff (-1)): InputMessage eof reached
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1332)
ERROR: ProtocolGame parse message exception (398 bytes, 0 unread, last opcode is 0xf9 (249), prev opcode is 0xffffffff (-1)): InputMessage eof reached
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1332)
ERROR: ProtocolGame parse message exception (398 bytes, 0 unread, last opcode is 0xf9 (249), prev opcode is 0xffffffff (-1)): InputMessage eof reached
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1332)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
try
https://github.com/mehah/otclient/blob/main/src/client/protocolgameparse.cpp#L4990


`const uint32_t sellOfferCount = msg->getU32();`
L4990 
to
L4997
![image](https://github.com/user-attachments/assets/7c51e08e-0deb-4c3b-9430-885d6ddbac1a)


```diff
    const uint32_t buyOfferCount = msg->getU32();
-  const uint32_t sellOfferCount = msg->getU32();


    std::vector<MarketOffer> offers;


    for (uint32_t i = 0; i < buyOfferCount; ++i) {
        offers.push_back(readMarketOffer(msg, Otc::MARKETACTION_BUY, var));
    }

+ const uint32_t sellOfferCount = msg->getU32();
    for (uint32_t i = 0; i < sellOfferCount; ++i) {
        offers.push_back(readMarketOffer(msg, Otc::MARKETACTION_SELL, var));
    }
```

**Comment by bateunatrave** [comment]
@kokekanon 
taking advantage,
I noticed that it can only be with me, but when the player tries to sell an item with a tier, the item is not removed from the player

**Comment by kokekanon** [comment]
did you try in the main or in the pr?

**Comment by Codemaufeito** [comment]
> main

main

**Comment by kokekanon** [comment]
test pr if you want to use actions, to make it faster : 
https://github.com/mehah/otclient/actions/runs/11244701579

![image](https://github.com/user-attachments/assets/92964b3b-e5a4-43ee-821f-2b8ebaa0da29)
+modules/game_market/market.lua of pr

**Comment by bateunatrave** [comment]
> test pr if you want to use actions, to make it faster : https://github.com/mehah/otclient/actions/runs/11244701579
> 
> ![image](https://private-user-images.githubusercontent.com/114332266/374746154-92964b3b-e5a4-43ee-821f-2b8ebaa0da29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MDY1OTcsIm5iZiI6MTcyODUwNjI5NywicGF0aCI6Ii8xMTQzMzIyNjYvMzc0NzQ2MTU0LTkyOTY0YjNiLWU1YTQtNDNlZS04MjFmLTJiOGViYWEwZGEyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQyMDM4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmQ4OTZmN2I0N2M3YTlkZTdiZjc0YWZmNGFkMDY3OGY0M2ZhMDczM2I3MDVkMThmZGNhZjRlM2RjYzQzYTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SBaLzhyPme74GVQ1xeGVMgJBa0-MQM_QFtkw1O6VWbI) +modules/game_market/market.lua of pr


the 0xf9 error issue seems to have fixed
just this doubt about the tier that remained open

**Comment by kokekanon** [comment]
Can you take a picture, show the problem (graphically)? I have never used market in my life

**Comment by Codemaufeito** [comment]
put tier on an item
put the item up for sale
(at least with me) the item is not removed from the character and the item's tier changes when it enters the market
