### ISSUE TITLE
vBot 4.8 freezing

### ISSUE THREAD

**Issue by bateunatrave** [opentibiabr/otclient#913]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

UI.Separator()
followName = "autofollow"
if not storage[followName] then storage[followName] = { player = 'name'} end
local toFollowPos = {}

UI.Separator()
UI.Label("Auto Follow")

followTE = UI.TextEdit(storage[followName].player or "name", function(widget, newText)
    storage[followName].player = newText
end)

followChange = macro(200, "Follow Change", function() end)

followMacro = macro(300, "Follow", function()--era 50
    local target = getCreatureByName(storage[followName].player)
    if target then
        local tpos = target:getPosition()
        toFollowPos[tpos.z] = tpos
    end
    if player:isWalking() then
        return
    end
    local p = toFollowPos[posz()]
    if not p then
        return
    end
if autoWalk(p, 20, { ignoreNonPathable = true, precision = 1 }) then
        delay(250)
    end
end)

UI.Separator()
onPlayerPositionChange(function(newPos, oldPos)
  if followChange:isOff() then return end
  if (g_game.isFollowing()) then
    tfollow = g_game.getFollowingCreature()

    if tfollow then
      if tfollow:getName() ~= storage[followName].player then
        followTE:setText(tfollow:getName())
        storage[followName].player = tfollow:getName()
      end
    end
  end
end)

onCreaturePositionChange(function(creature, newPos, oldPos)
    if creature:getName() == storage[followName].player and newPos then
        toFollowPos[newPos.z] = newPos
    end
end)

I was testing the ingame script editor option
and I noticed that for example in this auto follow script

when the player enters some portals the client freezes without logging or crashes

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
you are in the main repo ? i test and there is no client freeze

default , vbot 1.3 , `last commits : fix: spacing for align bottom vertical layouts `
if you are using the main repo  you probably have other custom bot scripts ¿ that cause freeze?

| Cliente 	|  check|
|----------	|--------	|
| Redemption vbot 4.8     	|  X  	|  
| V8 vbot 4.8| X		| 
|  redemption vbot 1.3| ✅  	|  
|  v8 vbot 1.3| ✅  	|  



https://github.com/user-attachments/assets/1b300675-8cf5-41bc-9f9c-3974442a7281


that code has something that does not work with the v4.8 version. considering that the same code does not work in v8 .
the code is simply not compatible with v4.8 only 1.3. 

create or search for another code . compatible with v4.8

 the issues should be closed, it is not the client's problem.

**Comment by Codemaufeito** [comment]
Now I understand, I was always using vbot 4.8, I thought it would be the updated version, so the correct version to use is cavebot_1.3
actually using it doesn't freeze.

**Comment by bateunatrave** [comment]
ok
