### ISSUE TITLE
Monsters dont appear in battle window if you dont move your character

### ISSUE THREAD

**Issue by Znote** [opentibiabr/otclient#92]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Get a monster to chase you
2. Walk so the monster goes out of screen, but not too far so the monster stops chasing you.
3. Stand still while monster re-enters your screen. 

### Expected behaviour

Monster should re-appear in battle list

### Actual behaviour

Monster not found in battle list (Pay attention to Cyclops when he dissapear and re-enter screen). 
![battlewindowbug2](https://user-images.githubusercontent.com/1552144/123310672-9ded9a00-d526-11eb-97a9-164fe00613c7.gif)

### Environment
Clean files, compiled latest commit on May 29, 2021, Windows 10 (a bit after 1.0.1 tag, issue can be reproduced in 1.0.1 release), TFS 1.3

**Comment by mehah** [comment]
test with the last revision

**Comment by Znote** [comment]
> test with the last revision

I struggle a bit with visual studio, could you tag a release, or/and add a workflow that auto compiles latest commit?

**Comment by mehah** [comment]
later I do it,
follow the release link: https://github.com/mehah/otclient/releases/tag/1.1b

**Comment by oarsc** [comment]
My last commit should have fixed this problem. Can you check it?

**Comment by mehah** [comment]
new release: https://github.com/mehah/otclient/releases/tag/1.1.1b

**Comment by Znote** [comment]
> new release: https://github.com/mehah/otclient/releases/tag/1.1.1b

Tested with this, bug fixed! :)
