### ISSUE TITLE
Double party shield

### ISSUE THREAD

**Issue by Znote** [opentibiabr/otclient#93]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Create a party
2. Move abit around then stand still
3. Wait a sec or two and see if shield overlaps itself

### Expected behaviour

One shield, not two layered on top of each other. 

### Actual behaviour

![image](https://user-images.githubusercontent.com/1552144/123323615-0b54f700-d536-11eb-986e-cba15044d8da.png)

### Environment
1.0.1, W10, TFS 1.3

**Comment by mehah** [comment]
test with the new rendering system.

**Comment by Znote** [comment]
> test with the new rendering system.

Tested on 1.1.1b, fixed!
