### ISSUE TITLE
character stuck

### ISSUE THREAD

**Issue by bateunatrave** [opentibiabr/otclient#934]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

![image](https://github.com/user-attachments/assets/a0c4200e-556a-4660-a4bd-68863b281126)
`ProtocolGame parse message exception (14169 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xc0 (192), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (2296 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1785 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1003 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (953 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1085 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (834 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (851 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1274 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1459 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1119 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (66 bytes, 45 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (965 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1073 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (834 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (954 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1280 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (692 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1254 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1074 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1280 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1667 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1337 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1137 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (81 bytes, 60 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1338 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1032 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1064 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (995 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (80 bytes, 59 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (963 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (2051 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1974 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1386 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1162 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1285 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1587 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1339 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (962 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1162 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1351 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (75 bytes, 54 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (82 bytes, 61 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (75 bytes, 54 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (945 bytes, 54 unread, last opcode is 0xaa (170), prev opcode is 0x83 (131), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1414 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1610 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1414 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1132 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (859 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (143 bytes, 122 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1157 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (968 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1482 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (66 bytes, 45 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (89 bytes, 68 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1289 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1130 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1123 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1322 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (81 bytes, 60 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1149 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1288 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1140 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (82 bytes, 61 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1595 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1769 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (97 bytes, 76 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1345 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1354 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1443 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (352 bytes, 331 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1216 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1083 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1409 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1162 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1490 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (980 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (963 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1282 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (969 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (64 bytes, 43 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1207 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (978 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1752 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1846 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (980 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (517 bytes, 496 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1035 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (830 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (696 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (70 bytes, 49 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (74 bytes, 53 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (987 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1403 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (969 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1313 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (868 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1414 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1288 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1069 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (842 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (632 bytes, 323 unread, last opcode is 0xaa (170), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (88 bytes, 67 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1283 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (221 bytes, 55 unread, last opcode is 0xaa (170), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1443 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (968 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1162 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (963 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (800 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1420 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1690 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1956 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1283 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1942 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1780 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (866 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (679 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1026 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1535 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1564 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1243 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1218 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (962 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (854 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1294 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (962 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (878 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1135 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1000 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1481 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (1680 bytes, 0 unread, last opcode is 0x9f (159), prev opcode is 0xa0 (160), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (67 bytes, 46 unread, last opcode is 0xaa (170), prev opcode is 0xffffffff (-1), proto: 1332): InputMessage eof reached
ProtocolGame parse message exception (11313 bytes, 1 unread, last opcode is 0x9f (159), prev opcode is 0xc0 (192), proto: 1332): InputMessage eof reached
`

After a few hours I noticed that this bug occurs, the character attacks mobs that are already dead, and bugs start to appear on the map.

However, if the character logs out or exits through a portal, everything returns to normal.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
protocol incompatibility, since you didn't offer more details, I will close this issue.
