### ISSUE TITLE
npc trade 

### ISSUE THREAD

**Issue by bateunatrave** [opentibiabr/otclient#939]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

When the NPC has many items in the trade, there is an accumulation of items and a large drop in FPS.

![image](https://github.com/user-attachments/assets/7bb9f1b9-08d0-4a5f-852a-bfb8b8452acc)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
What is your version and protocol?

this npc how many items does it sell/buy ?

error terminal ?

**Comment by bateunatrave** [comment]
> canary ? [opentibiabr/canary#2837](https://github.com/opentibiabr/canary/pull/2837)
> 
> What is your version and protocol?
> 
> this npc how many items does it sell/buy ?
> 
> error terminal ?

version 13x
the npc has more than 100 items
if the 'show all' option is unchecked
the bug marked with a circle is correct because only the items that the character has for sale appear

**Comment by kokekanon** [comment]
I confirm bug, to repoduce it in 11.00 or 13.40 


/goto The Lootmonger

hi
trade


release 3.5 same
![image](https://github.com/user-attachments/assets/9e943ae9-43cb-4c6e-a524-1e94bd5b96ed)


**after 769 widgets in the grid the error occurs** 
```
       if key == 768 then
            break
        end
```

**Comment by kokekanon** [comment]
>"accumulation of items and a large drop in FPS."

(I fixed the visual bug, not the performance bug.)
test you performance 
https://github.com/mehah/otclient/pull/940

my pc is not the best one to measure that.
![image](https://github.com/user-attachments/assets/2332c3d0-6c6c-453c-b343-e2264e3ae5a8)
