### ISSUE TITLE
OTClient doesnt save/load minimap file.

### ISSUE THREAD

**Issue by trzzu** [opentibiabr/otclient#94]
MINIMAP BUG

### Actual behaviour
Client doesnt save/load minimap file.

### Environment
TFS 1.3 8.6 / OTClient 1.0

**Comment by mehah** [comment]
here it is saving perfectly, make sure you are using the latest version or are using two clients at the same time.

**Comment by Znote** [comment]
Try updating to latest version, I also had this issue, but it was fixed in version 1.0.1. 

I tested on 1.1.1b, and it works there as well. (for me). 
But I had a few friends who kept having the same issue, going to see if they still has it. It could be a permission error?

**Comment by mehah** [comment]
> Try updating to latest version, I also had this issue, but it was fixed in version 1.0.1.
> 
> I tested on 1.1.1b, and it works there as well. (for me).
> But I had a few friends who kept having the same issue, going to see if they still has it. It could be a permission error?

I don't know, can you ask them to retest?

**Comment by mehah** [comment]
well, as i didn't get any feedback, i'll be closing.
