### ISSUE TITLE
Client not checking if server has elevation/height

### ISSUE THREAD

**Issue by ForgottenOldschool** [opentibiabr/otclient#95]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Add parcel height block to server side
2. enable it
2. try to walk over two or more stacked item with height/elevation like ex: parcels 
4. client don't get it so player will try to walk over the parcel anyway  , so like the server doesn't allow it creates the sensation of jumping

### Expected behaviour

 the player  shouldn't make pre-walk he should just stand still and wil recieve a message "sorry this is not possible"
### Environment
using latest mehah otclient

tested with otcv8 with an added code in modules/walking.lua which is this, 
```
 nextWalkDir = nil
  removeEvent(autoWalkEvent)
  autoWalkEvent = nil
  local preWalked = false
  local playerTile = player:getTile()--agregado 7.4 block parcel
   if toTile and toTile:isWalkable() then
    if not player:isServerWalking() and not ignoredCanWalk then
        if (playerTile and (toTile:getElevation() - playerTile:getElevation() <= 1) or (playerTile:getElevation() > 3)) then
            player:preWalk(dir)
            preWalked = true
        end
    end--agregado 7.4 block parcel
```
the code added  works, disabling the jumping when someone tries to walk over the stack parcel with the heigh stack block feature enable using arrow keys, the problem  is that there is no code to check that when a player tries to walk with  game mouse over the parcel. so with that method player is still " jumping".

here you can see the video ( testing in otcv8)
https://www.youtube.com/watch?v=Mc3hTbBV3ig&ab_channel=felipeandres

**Comment by mehah** [comment]
my focus is not keeping compatibility with tibia oldschool, i don't have time, i need the help of the community for that.

**Comment by mehah** [comment]
tries to apply the same logic, but in the creature's onwalk (creature, oldPosition, position) event

something like that:

```lua
connect(LocalPlayer, {
		onWalk = function(player, oldPosition, position)
			 nextWalkDir = nil
			  removeEvent(autoWalkEvent)
			  autoWalkEvent = nil
			  local preWalked = false
			  local playerTile = player:getTile()--agregado 7.4 block parcel
			   if toTile and toTile:isWalkable() then
				if not player:isServerWalking() and not ignoredCanWalk then
					if (playerTile and (toTile:getElevation() - playerTile:getElevation() <= 1) or (playerTile:getElevation() > 3)) then
						player:preWalk(dir)
						preWalked = true
					end
				end--agregado 7.4 block parcel		
		end
})
```

**Comment by mehah** [comment]
well, as i didn't get any feedback, i'll be closing.
