### ISSUE TITLE
Cyclopedia + Skill Window 

### ISSUE THREAD

**Issue by vllsystems** [opentibiabr/otclient#952]
### Priority

Low

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Quando os itens estão equipados:

![image](https://github.com/user-attachments/assets/963fd436-df26-4a16-b27d-0692ba6ad6a0)

Quando estão desequipados:

![image](https://github.com/user-attachments/assets/c578aba1-2089-4fbf-b74b-3755f56efdba)

==========================================
Desculpem, não sei abrir PR, mas:

- Skill Window.
-- Critical Hit deveria ser em porcentagem né?

Logo, skills.lua linha 22:
        if id == "skillId7" or id == "skillId8" or id == "skillId9" or id == "skillId11" or id == "skillId13" or id == "skillId14" or id == "skillId15" or id == "skillId16" then

-- Os skills abaixo de mana leech chance, deveriam sumir ao desequipar os itens? (desculpem, não sei como funciona no global)

==========================================
Ao abrir o Cyclopedia -> Combat Stats:

![image](https://github.com/user-attachments/assets/712b6149-842a-403b-a358-d135526b2d4f)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
give me the id or name of  equipped items, to reproduce it.

**Comment by vllsystems** [comment]
at canary base, any equip with tier 10, or the other skills atributes.

**Comment by vllsystems** [comment]
quando não há nenhum item equipado.
![image](https://github.com/user-attachments/assets/82edff2f-bf2a-4f8b-9418-8f7f2e98b0d5)

Ao equipar os itens, ele não atualiza em tempo real.

O erro em Lua é com equipamento ou sem.

Parece estar relacionado ao Perfectshot.

**Comment by vllsystems** [comment]
alguns valores arredondam para baixo:

![image](https://github.com/user-attachments/assets/836192c2-3a70-48b9-a211-406b7963af04)


18:28 You see golden legs (Arm:9).
It can only be wielded properly by knights and paladins.
Classification: 2 Tier: 10 (2.35% Transcendence).
It weighs 56.00 oz.
Client ID: 3364
Position: In your inventory.

18:29 You see a demon armor (Arm:16).
Imbuements: (Empty Slot, Empty Slot).
Classification: 2 Tier: 10 (7.51% Ruse).
It weighs 80.00 oz.
Client ID: 3388
Position: In your inventory.

18:29 You see a demon helmet (Arm:10).
Imbuements: (Empty Slot, Empty Slot).
Classification: 2 Tier: 10 (24.05% Momentum).
It weighs 29.50 oz.
You hear an evil whispering from inside
Client ID: 3387
Position: In your inventory.

**Comment by kokekanon** [comment]
I have no error. you have updated canary and otc with their respective main repo ?
![image](https://github.com/user-attachments/assets/b54c1d2c-3d2b-45d7-9112-51bec6a2fc49)


![image](https://github.com/user-attachments/assets/17689352-4b7c-4d28-bb6d-7ab73e5e2d20)
![image](https://github.com/user-attachments/assets/ad84956e-2a27-4a67-b978-f49a1b0c1250)
