### ISSUE TITLE
canary 13.40 console error parseSetOutfit

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/otclient#955]
### Priority

Medium

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Error in the console after changing the appearance in otclient

![console error](https://github.com/user-attachments/assets/ab675f4c-c362-4b84-80f4-559516cb3984)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
how to reproduce it ?


![image](https://github.com/user-attachments/assets/6c7e75b6-5463-49ec-bf1f-c640d28fbb84)

**Comment by daniofordon** [comment]
fix. close
