### ISSUE TITLE
[TFS] Monster icons issue

### ISSUE THREAD

**Issue by ArturKnopik** [opentibiabr/otclient#971]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Left - Cipsoft client
Right - OTC
Creatures with icons breaks client
![image](https://github.com/user-attachments/assets/2a8a1273-304e-4b08-9a58-cd144ab0b93c)

ERROR: ProtocolGame parse message exception (180 bytes, 92 unread, last opcode is 0x66 (102), prev opcode is 0x6d (109)): ProtocolGame::getThing: invalid thing id
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1310) 

Reproduce:
setup otc using this tutorial:
https://github.com/mehah/otclient/wiki/Tutorial-to-Use-OTC-in-TFS-main
Use TFS master with this fix - https://github.com/otland/forgottenserver/pull/4845
use this map
[world.zip](https://github.com/user-attachments/files/17827551/world.zip)
use this script 
```LUA

local spawn = GlobalEvent("spawnStartup")
function spawn.onStartup()
		local m = Game.createMonster("Demon", {x = 119, y = 115, z = 7}, true, true)
		m:setSpecialIcon(5,0)
		m:setIcon(CREATURE_ICON_PIGEON,0)
		m:setIcon(CREATURE_ICON_QUESTION,1)
end
spawn:register()
```
walk here (god: **/town 1**)
![image](https://github.com/user-attachments/assets/a0a0dc22-db74-4b54-b4d9-2abde94b199b)
try walks around

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
https://github.com/mehah/otclient/pull/972
b6cb2d1
