### ISSUE TITLE
[TFS] Npc breaks map drawing

### ISSUE THREAD

**Issue by ArturKnopik** [opentibiabr/otclient#974]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Broken map map drawing when npc appears/walks
Left: Cipsoft (expected)
Right: OTC (actual)
![image](https://github.com/user-attachments/assets/c3eb325b-5bb4-4a16-bebb-5ea4e846d588)

![image](https://github.com/user-attachments/assets/b3275c70-7e18-4729-940c-6096a97d4002)
[packet.log](https://github.com/user-attachments/files/17835734/packet.log)

Reproduction:
Setup TFS (master) with this map and npc: 
 * fix for TFS + OTC: https://github.com/otland/forgottenserver/pull/4845
 * Map: [world.zip](https://github.com/user-attachments/files/17835749/world.zip)
 * Npcs: [npc.zip](https://github.com/user-attachments/files/17835754/npc.zip)
 
Go to {x = 116, y = 123, z = 7} positon
Start walking

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
https://github.com/user-attachments/assets/222b7340-86ab-4bcf-a333-c98382695738

Are you sure you have **only** this feature disabled ? 

g_game.enableFeature(GameSequencedPackets)

([wiki ](https://github.com/mehah/otclient/wiki/Tutorial-to-Use-OTC-in-TFS-main) is wrong)



I think you followed the wiki and disabled GameThingClock , and these items cause your problem

![image](https://github.com/user-attachments/assets/bcb221dd-35d3-40ef-ac9f-ffdc9d0bd7ad)


Me last commits tfs : fix: Add UTF-8 support for Unicode compatibility 2 
two months ago  xd

**Comment by ArturKnopik** [comment]
Yes, i follows wiki setup.

**Comment by kokekanon** [comment]
just disable :
GameSequencedPackets

keep enable. for test 

GameThingClock y GameThingCounter


that has tfs here
`Update to game protocol 12.91 tfs # 4568`

**Comment by ArturKnopik** [comment]
It's working, probably TFS chapter in Wiki require some update.

**Comment by kokekanon** [comment]
@majestyotbr @Nottinghster @luanluciano93

**Comment by kokekanon** [comment]
the wiki was updated
https://github.com/mehah/otclient/wiki/Tutorial-to-Use-OTC-in-TFS-main
