### ISSUE TITLE
[WIKI] Ubuntu 24.04 compilation instruction

### ISSUE THREAD

**Issue by gesior** [opentibiabr/otclient#982]
### Priority

Enhancement

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What is missing?

I'm working on Docker build (it does not work now). I tried to compile OTC on Ubuntu 24.04 and in official instruction are some steps that are not needed on Ubuntu 24.04 (replace `g++` and `cmake` with newest version):
https://github.com/mehah/otclient/wiki/Compiling-on-Ubuntu-24.04

All commands I had to run to compile on Ubuntu 24.04:
linux (when I finish work on Docker, I will test if all these packages are required):
```
sudo apt update && sudo apt dist-upgrade -y
sudo apt install git cmake build-essential autoconf libtool ca-certificates curl zip unzip tar pkg-config ninja-build libglew-dev libx11-dev ccache linux-headers-$(uname -r) -y
```
vcpkg:
```
cd ~
git clone https://github.com/microsoft/vcpkg
cd vcpkg/
./bootstrap-vcpkg.sh
```
Download client files:
```
cd ~
git clone --depth 1 https://github.com/mehah/otclient.git
```
Compile:
```
cd otclient/
mkdir build && cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake .. --preset linux-release
cmake --build linux-release
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eemarwell** [comment]
I've builded using Dockerfile and it worked properly.

**Comment by gesior** [comment]
> I've builded using Dockerfile and it worked properly.

I've found out why it failed on my PC on step:
```docker
RUN vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ') \
	&& echo "vcpkg commit ID: $vcpkgCommitId" \
	&& git clone https://github.com/Microsoft/vcpkg.git \
	&& cd vcpkg \
	&& git checkout $vcpkgCommitId \
	&& ./bootstrap-vcpkg.sh
```
with error:
```
0.378 vcpkg commit ID: c82f74667287d3dc386bce81e44964370c91a289
0.387 Cloning into 'vcpkg'...
7.840 error: pathspec 'c82f74667287d3dc386bce81e44964370c91a289?' did not match any file(s) known to git
```
It's because I've clone OTC repo on Windows with auto-replace LF -> CRLF, which somehow made function `$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ')` add new-line character to commit hash variable, which git shows in error as `?` at end of commit hash.

---

I will work on other Dockerfile issue: Windows compilation files are not excluded in `.dockerignore`, which makes docker copy up to 17 GB (` transferring context: 16.75GB `) of 'context' into docker container.
