### ISSUE TITLE
Android compiling

### ISSUE THREAD

**Issue by tomasz1337** [opentibiabr/otclient#988]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Can't compile in android studio
![image](https://github.com/user-attachments/assets/077bffa7-4293-48f7-b092-7766220e4239)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SkullzOTS** [comment]
fixed! https://github.com/mehah/otclient/pull/1007
