### ISSUE TITLE
Black flashes

### ISSUE THREAD

**Issue by Mrpox** [opentibiabr/otclient#99]
Every ~35frames the GameMapPanel goes black for one frame when topmenu is removed.
This wasnt the case in previous versions.
Im assuming it has something to do with the new rendering features and GameMapPanel being a larger size due to not being anchored to topmenu.bottom but parent.top instead.

Hard to make a gif that will show the issue well.
But can be replicated by adding:
topMenu:setHeight(0) inside function init()  in the file topmenu.lua

**Comment by mehah** [comment]
I'm analyzing the problem, meanwhile, use setHeight(1)
