### ISSUE TITLE
add language change in client

### ISSUE THREAD

**Issue by Wirless** [opentibiabr/otclient#997]
### Priority

Missing Content

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

ability to change the language because many people lose their mind by missclicking on spanish thanks mehah great idea getting NON technical people to open %AppData% ;((((((

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
??
that was fix here
https://github.com/mehah/otclient/pull/983

**Comment by Wirless** [comment]
i just removed useless game_locales from features since nobody ever uses it anyways and its not even UI friendly looks more fk*d than the whole ot community.
